### ISSUE TITLE
using without sessions (node on server)

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [XeroAPI/xero-node#113]
Hi,
Thanks for this library. I have a client rendered app and a node backend, and I've gotten to a point where I can follow the example app to the point of getting a session authenticated.

However, I'm using firebase cloud functions and working from realtime database triggers, and so don't have anything the equivalent of an express session.

My question is can I call these helper methods and pass them the oauth token each time as an additional parameter, rather than assuming an authenticated session?

This may be documented somewhere, but as of yet I haven't been able to find it so i thought I'd ask.

Thanks

**Comment by philals** [comment]
Hi @SamMatthewsIsACommonName.

I'm not 100% on the specifics of Firebase. Is the client running the SDK in their browser?

**Comment by SamMatthewsIsACommonName** [comment]
Hi @philals , no it is running on node on a vm instance basically. The client end is a single page application so hence no req / res pattern like an express app, or sessions. Basically we push some data up to our realtime database and it triggers these node processes. So on that basis, the authentication token is available to the process (the client never actually receives this).
I've got the authentication part working using node-oauth library which I see parts of this repo borrow heavily from. May I ask what the crucial differences you needed to make were from that lib? As I understand it's not really maintained anymore, and possibly there is an issue with content type json headers which I'm about to explore now.

**Comment by philals** [comment]
Hi @SamMatthewsIsACommonName 

Sorry. I'm not sure what changes were required to be made from that library. This is a fork from TimNZ's original code, which was made a few years ago. So TimNz might have an idea, or @jordanwalsh23 (who has since left Xero) who forked it and updated this repo.

I would imagine that the node-oauth was copied in, hopefully with minimal changes. At a guess any changes would have been to support Private applications.

This would be similar to the schema code. Ideally we would probably pull both those chunks of code and use a maintained package.

**Comment by SamMatthewsIsACommonName** [comment]
OK I see thanks. Yes it seems there are even more maintained forks of node-oauth now but most are quite new so I assume picking one that seems like it will continue to be maintained as a dependency could be handy.
So the schema code I take it is what transforms the json to the xml needed?
This may be a bit too much of an ask but I feel if you were able to as you say take those back to being dependencies then the actual xero aspect would be a lot more lightweight and flexible, so for example adding the ability for ouath parameters to be passed to the functions wouldn't be such a huge undertaking (or maybe for example pass either the session or the token data, for a more universal solution), and would enable this to become a real node client designed to run independently on a node server rather than an express style 'node app', as I know these node apps are very popular but I really think independent node server processes are increasing in popularity with containers, cloud functions etc.

**Comment by philals** [comment]
Hi @SamMatthewsIsACommonName 

I'm going to close this issue. Please note that we have have taken your feed back on board. Please open a new issue if you have any more.
