### ISSUE TITLE
Invalid Private Key PEM Swallows Error Rather than Returning the Error

### ISSUE THREAD

**Issue by securityvoid** [XeroAPI/xero-node#116]
I imagine this is true for any of the hashing in _createSignature, but specifically line 224-227 of lib/oauth/oauth.js will completely swallow the error thrown back from Crypto, rather than returning an error:

```
} else if (this._signatureMethod == "RSA-SHA1") {
        key = this._privateKey || "";
        hash = crypto.createSign("RSA-SHA1").update(signatureBase).sign(key, 'base64');
```
Specifically Crypto is expecting the RSA Key to be surrounded with:
```
-----BEGIN RSA PRIVATE KEY-----
-----END RSA PRIVATE KEY-----
```
This is relatively clear if you get the message from Crypto:
`error:0906D06C:PEM routines:PEM_read_bio:no start line`

As it is now though, you get no output and nothing happens. This isn't too helpful. 

Reproduction Steps:
1) Set your privateKey to a value that does not have the RSA Start Line Headers.
2) Attempt to call a Xero function (e.g. I called core.contacts.getContacts).

NOTE: Nothing happens and no error is returned to explain why.

Full stack of the error that is lost (Line numbers might be slightly off since I added some debugging to find this. The original line number listed above should be the offending code:

```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Sign.sign (crypto.js:282:26)
    at exports.OAuth._createSignature (\node_modules\xero-node\lib\oauth\oauth.js:228:70)
    at exports.OAuth._getSignature (\node_modules\xero-node\lib\oauth\oauth.js:105:17)
    at exports.OAuth._prepareParameters (\node_modules\xero-node\lib\oauth\oauth.js:319:20)
    at exports.OAuth._performSecureRequest (\node_modules\xero-node\lib\oauth\oauth.js:329:34)
    at exports.OAuth.get (\node_modules\xero-node\lib\oauth\oauth.js:509:17)
    at getResource (\node_modules\xero-node\lib\application.js:313:25)
    at \node_modules\xero-node\lib\application.js:275:25
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by abirtley** [comment]
Thank you @securityvoid for pointing this out - you helped me diagnose the silent failure I was experiencing. To clarify for others who stumble upon this, the silent fail can be cause by any sort of error in your key, not just a lack of BEGIN and END tags.

**Comment by philals** [comment]
https://github.com/XeroAPI/xero-node/pull/169 should fix this. With tests. @SidneyAllen

**Comment by philals** [comment]
Hi closing as latest version fixes this issue. Thanks
