### ISSUE TITLE
What is the proper way to use createdByMyApp for Invoices

### ISSUE THREAD

**Issue by securityvoid** [XeroAPI/xero-node#117]
The Xero API documentation lists "[createdByMyApp](https://developer.xero.com/documentation/api/invoices)" as an optional parameter.

However, I can't seem to figure out the proper syntax for using it. The following throws an error:
```
        xero.core.invoices.getInvoices({
            where: 'Status="DRAFT" AND createdByMyApp=true',
        })
```
The error:
```
{ ErrorNumber: 16,
     Type: 'QueryParseException',
     Message: 'No property or field \'createdByMyApp\' exists in type \'Invoice\'' } }
(node:20984) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: GET call failed with: 400
```

While the following doesn't do anything:
```
        xero.core.invoices.getInvoices({
            where: 'Status="DRAFT"',
            createdByMyApp: true
        })
```

**Comment by philals** [comment]
Hi @securityvoid 

Give this ago. It worked for me:

```
xeroClient.core.invoices.getInvoices({
  params: {
    createdByMyApp: true,
  }
})
  .then(function(invoices) {
    invoices.forEach(function(invoice) {
      console.log('GOT BACK: ', invoice.InvoiceID); 
    });
  });
```

**Comment by securityvoid** [comment]
@philals You can close this. I didn't test the above, but I moved over to using the REST API directly. Its not hard to make REST calls in node, and it is MUCH better documented. I was spending way too much time trying to reverse this code to determine what I needed to do to use it than the benefit it provided.

I'm currently using a hybrid of this library and direct REST calls, but I will be changing everything over to direct REST calls.

**Comment by philals** [comment]
Cheers. @securityvoid Yeah, I think this lib is doing too much. And has too much spaghetti code. I find it hard to reason about. 

Ideally I would like to make it much much thinner, and do heaps less.

Are you using a Private app or a Public/Partner app?

**Comment by securityvoid** [comment]
This is for a Private App. Primarily I wanted to be able to call the Xero API from Microsoft Flow, which supports OAuth 2.0 but not OAuth1.0a. I ended up writing an Azure Function which is an OAuth1.0 wrapper for Xero. The Azure Function is protected by basic auth.

The most annoying part was updating the Swagger files that were out there to do what I wanted to do; but that wasn't that horrible.

Xero should really think about just publishing the Swagger files and keeping those up-to-date and stop trying to maintain all these libraries. Swagger / OpenAPI is pretty much covered by any and every programming language now and IMHO is better than a library. Everything can call REST. Put a definition to that REST and its even easier.

**Comment by philals** [comment]
@securityvoid Thanks for the info on how you're using things.

Yes, we are exploring OpenAPI/Swagger. I can't make any commitments though.
