### ISSUE TITLE
SentToContact not a Full Boolean its True or Unset

### ISSUE THREAD

**Issue by securityvoid** [XeroAPI/xero-node#118]
I don't know if this is best here, or if there is another way to give feedback for documentation to be updated. This is really for the API in general, and not specifically the node-js implementation, but it does impact things here.

[The API Docs state that SentToContact is a Boolean.](SentToContact)

This is half-true. It is set to "True" if the Invoice/Payable has been sent to the contact. It is not set at all if it hasn't been set.

As a result the following will not give you the expected results:
```
xero.core.invoices.getInvoices(
        {
            where: 'Type="ACCREC" AND SentToContact=false'
        }
```

And you instead need:

```
xero.core.invoices.getInvoices(
        {
            where: 'Type="ACCREC" AND SentToContact!=true'
        }
```

At a bare minimum it would be good if there were some examples in the sample app that showed how to do this so it could be looked up. Right now its not covered.

**Comment by philals** [comment]
Thanks for the issue. I'm talking to the Accounting API PO about this.

**Comment by philals** [comment]
Thanks again for this.

It is talked about in the documentation here : https://developer.xero.com/documentation/api/requests-and-responses#get-modified

See Example 3 under "Retrieving a filtered set of resources using the “where”". It is an optional field, so SentToContact!=true would be the same as SentToContact!=null.

There are lots of where cases so, unfortunately, we cannot cover them all with examples.

I have passed this feedback onto the accounting API product owner.
