### ISSUE TITLE
BankTransactions function 'newBankTransactions' is not consistent

### ISSUE THREAD

**Issue by jordanwalsh23** [XeroAPI/xero-node#12]
The function provided by the BankTransactions helper `newBankTransactions` creates a map of BankTransaction objects and the `save()` function needs to be called on each.

For efficiency, this should instead provide a `saveAll()` function that allows multiple BankTransactions to be saved in a single API call.

**Comment by jordanwalsh23** [comment]
#84

**Comment by jordanwalsh23** [comment]
Looks like this change has been merged.  Awaiting the next release to NPM prior to closing.

**Comment by philals** [comment]
Hi. 

I have merged the pull requests and deployed as v2.7.0 on NPM. 

Thanks for the issue.
