### ISSUE TITLE
When calling newBankTransactions

### ISSUE THREAD

**Issue by tallday** [XeroAPI/xero-node#121]
When calling  xeroClient.core.bankTransactions.newBankTransactions(bankTransactions) I am receiving the following error TypeError: xeroClient.core.bankTransactions.newBankTransactions is not a function

**Comment by philals** [comment]
Hi @tallday. Have you checked the source code of this module to make sure the function is there?

**Comment by tallday** [comment]
It doesnt look like the function is there to me. Thats why im confused as the documentation provides the example. @philals

**Comment by jordanwalsh23** [comment]
Hi @tallday, if you check the tests files it's often more helpful (and potentially more correct) than the documentation:

```
  it('create multiple banktransactions', done => {
    const banktransactions = [];

    for (let i = 0; i < 2; i += 1) {
      banktransactions.push(
        currentApp.core.bankTransactions.newBankTransaction({
          Type: 'SPEND',
          Contact: {
            Name: 'Johnny McGibbons',
          },
          LineItems: [
            {
              Description: 'Annual Bank Account Fee',
              UnitAmount: 0.01,
              AccountCode: expenseAccountCode,
            },
          ],
          BankAccount: {
            AccountID: bankAccountId,
          },
        })
      );
    }

    currentApp.core.bankTransactions
      .saveBankTransactions(banktransactions)
      .then(response => {
        expect(response.entities).to.have.length.greaterThan(0);
        response.entities.forEach(bankTransaction => {
          expect(bankTransaction.BankTransactionID).to.not.equal('');
          expect(bankTransaction.BankTransactionID).to.not.equal(undefined);
        });
        done();
      })
      .catch(err => {
        console.error(util.inspect(err, null, null));
        done(wrapError(err));
      });
  });
```

In this case the function is actually `saveBankTransactions()` and it takes an array of banktransaction objects that were created from the `newBankTransaction()` constructor.

Hope that helps.

**Comment by tallday** [comment]
Thanks very much. This has help me a lot @jordanwalsh23.
I have since determined that I was actually wanting to create bank statements not transactions. Which then I discovered this https://xero.uservoice.com/forums/5528-xero-api/suggestions/340274-import-bank-statement-lines-via-the-api

**Comment by philals** [comment]
Thanks for the help @jordanwalsh23
