### ISSUE TITLE
How to void unallocated Credit Note

### ISSUE THREAD

**Issue by tinovyatkin** [XeroAPI/xero-node#125]
I'm getting Xero internal error while trying to Void unallocated credit note (that's possible via web). Tried POST to /CreditNotes/{creditNoteId} with { Status: 'VOIDED' } or { Status: 'DELETED' } in both cases got validation error as response with Xero internal error as text...
Is I'm doing something wrong or API?

**Comment by philals** [comment]
Hi @tinovyatkin are you able to post some example code I can run?

**Comment by tinovyatkin** [comment]
Hmm... It will be ids from my Xero base. Not sure how to share that. Can you post an example how to void an unallocated credit note?

**Comment by tinovyatkin** [comment]
It will be logical to allow DELETE call to /CreditNotes/{creditNoteId} but it's not working neither

**Comment by SidneyAllen** [comment]
Hi @tinovyatkin 

I've run the following code and successfully set Status= VOIDED of a CreditNote that has the Status of AUTHORISED.

var CreditNoteID = '7adXXXXXXXXXXXXXXXX2cda';

var data = {
    CreditNoteID: CreditNoteID,
    Status: 'VOIDED'
};

var creditnote = xeroClient.core.creditNotes.newCreditNote(data,null);
creditnote.save()
  .then(function(ret) {
      // Do something 
  })

I've also run similar code to set status=DELETED for a DRAFT CreditNote
