### ISSUE TITLE
Compile package to es5.

### ISSUE THREAD

**Issue by AlexVoitenko** [XeroAPI/xero-node#131]
Hi there!
I was trying to integrate xero to Meteor app which is using old Node version (v4.8.4) and  got an errors because of modern syntax like this:
https://github.com/XeroAPI/xero-node/blob/master/lib/entities/accounting/organisation.js#L49.

Does it possible to compile lates version of package to es5?

**Comment by philals** [comment]
Hi. Thanks for the issue. 

At this stage I'm not keen to add any compile before it gets pushed to NPM.

You welcome to set something up with an online CI tool (like CircleCI). That will publish to NPM under an other name. xero-node-es5? Please post back with a new issue if you go down this path.

If there is enough demand for this version then we will do the same to the main NPM package.

Thanks

**Comment by philals** [comment]
Hi @AlexVoitenko just had a talk with the team.

We're thinking that adding bable and going down to ES5 might be a good idea. This will hopefully allow us to catch any code issues, and give us more confidence in refracting. 

If you're keen please send a PR, please do.

Initially we will compile locally and push that to NPM. Then I'll set it up in CI to do this automatically on new version tags to master.

**Comment by philals** [comment]
@AlexVoitenko 

I have set up Babel and we're talking about our compile strategy. 

Node 4 is in "Maintenance LTS" so we're thinking of only targeting current "Active LTS" which is Node 6, and moving along with that cycle (https://github.com/nodejs/Release).

Is this still an issue for you?

**Comment by philals** [comment]
Hi @AlexVoitenko any thoughts on https://github.com/XeroAPI/xero-node/pull/154 ?
