### ISSUE TITLE
 Download PDF of invoce 

### ISSUE THREAD

**Issue by dweep119** [XeroAPI/xero-node#132]
Hello
I need to **generate pdf version of invoice** via **NodeJS Api**.
I also follow the [API previewer](https://app.xero.com/Preview/invoices) in that I set Accept Type and it give me pdf of particular
InvoiceID. 

But I want to set in my function,How can i set the headers field in my function.
I also follow this [link](https://github.com/XeroAPI/xero-node/blob/master/docs/Invoices.md) for making function.

_**My Code like this,**_

**Router Call:-**

```
router.get('/invoice/id/:id/pdf',async (req, res) => {
var id = req.params.id;
console.log("Invoice ID",id);
arrinvoicename = await xerofun.getListInvoiceByIdPDF(id);
res.render('invoicedetail', {
invoicebyid: arrinvoicename
})
})
```

**XeroFunction:-**

```
exports.getListInvoiceByIdPDF = async function(id)
{
var myInvoiceID = id;
let invoice = await xeroClient.core.invoices.getInvoice(myInvoiceID)
invoice._application.oa._headers['Accept'] = 'application/pdf';
return invoice; 
}
```
But it is not working for me.
Please do needful.
Thanks.

**Comment by philals** [comment]
Hi @dweep119 I tried a while ago to get this working. I could not get it to work. So I'm thinking of removing the function.

See here for a discussion on PDFs #119

Let me know if you can get that PR to return an invoice.

**Comment by philals** [comment]
Hi @dweep119 I'm going to close this as it's really similar to https://github.com/XeroAPI/xero-node/issues/120
