### ISSUE TITLE
How to check oauth token expired?

### ISSUE THREAD

**Issue by khmelevskii** [XeroAPI/xero-node#133]
I want to check my token after
```
const xeroClient = new xero.PublicApplication(xeroConfig);
```

I didn't find `checkExpiry` method or anything else.

Thanks.

**Comment by philals** [comment]
Hi @khmelevskii 

I see you are using a Public app. Can you store the time that it was created? Once you're past 30 mins it'll be expired. 

The alternative would be to make a call and see if it's rejected.

**Comment by philals** [comment]
Hope this helps. More info can be found on https://developer.xero.com/documentation/getting-started/api-application-types
