### ISSUE TITLE
"this._super is not a function"

### ISSUE THREAD

**Issue by pwichmann** [XeroAPI/xero-node#134]
What could cause this error that I get after creating a contact (and before creating an invoice)?
The contact gets created. But then everything crashes.

```
[omitted]/node_modules/xero-node/lib/entities/accounting/contact.js:109
    return this._super(options);
                ^
TypeError: this._super is not a function
```

The contact itself does not appear to have any problems:
```HasValidationErrors: false```

**Comment by jordanwalsh23** [comment]
Hey @pwichmann. Can you please post your code that is causing this issue?

The _toObject function should probably be removed from the Contact entity as I don't believe it's required, that said, I'd still be keen to see the code that is causing this issue.

**Comment by pwichmann** [comment]
I just closed the issue because I cannot confidently say that I am not the error cause.

**Comment by pwichmann** [comment]
Yep, as usual: the biggest problem sits in front of the computer. I made a mistake and did not format the API call correctly.
