### ISSUE TITLE
How to call streamInvoice() function??

### ISSUE THREAD

**Issue by dweep119** [XeroAPI/xero-node#135]
Hello

Can you provide me example of **_streamInvoice() function_**?
[Here](https://github.com/XeroAPI/xero-node/blob/master/docs/Invoices.md) you can provide a function regarding it, but does not provide example.
Can please provide a Example of it?

Thanks.

**Comment by philals** [comment]
Hi @dweep119 I tried a while ago to get this working. I could not get it to work. So I'm thinking of removing the function.

See here for a discussion on PDFs https://github.com/XeroAPI/xero-node/pull/119

Let me know if you can get that PR to return an invoice.

**Comment by dweep119** [comment]
Hey @philals 
I am also try as you say for downloading invoice as a pdf but it is not working.
Here it is my code,

**_Router Call:-_**

```
router.get('/invoice/id/:id/pdf',async (req, res) => {
  var id = req.params.id;
  arrinvoicename = await xerofun.getListInvoiceByIdPDF(id);
 return arrinvoicename
})
```

**_XeroFunction:-_**

```
exports.getListInvoiceByIdPDF = async function(id)
{
   var invoiceId = id;
   let invoice = await xeroClient.core.invoices.getInvoice(invoiceId, null, null, "application/pdf");
   console.log('invoice', invoice)  // undefined
    return invoice;
}
```

**Comment by philals** [comment]
Hi Please see docs added here: https://github.com/XeroAPI/xero-node/pull/156

Will close. Please reopen a new issue is you have any problems. Thanks
