### ISSUE TITLE
Reference field is missing from CreditNoteSchema

### ISSUE THREAD

**Issue by sziebertAu** [XeroAPI/xero-node#141]
Reference field value sent with core.creditNotes.newCreditNote() is not registering.
I noticed that the Reference field is missing from CreditNoteSchema in /lib/entities/accounting/creditnote.js.

If I replace it manually, it works.

**Comment by philals** [comment]
Thanks @sziebertAu 

Are you able to send a PR with your fix?

Let me know if you need a hand.
