### ISSUE TITLE
Missing 'OrganisationID' from Organisation.toJSON() 

### ISSUE THREAD

**Issue by neeon-li** [XeroAPI/xero-node#152]
The 'OrganisationID' seem missing in Organisation object.

I saw `expect(ret.OrganisationID).to.be.a('string');` is located at 
`/test/core/organisation_tests.js`.
But it seems missing `OrganisationID: { type: String },` in `/lib/entities/accounting/organisation.js`.

Ever I added it back, it still not shows the OrganisationID after .toJSON().
Am I missing some part to modify ?

**Comment by philals** [comment]
Hi @neeon-li 

Do you mind posting a code example that illustrates this issue? 

Thanks

**Comment by SidneyAllen** [comment]
Hi @neeon-li 

Even though you only have 1 Organisation, the object is returned as an Array.  The code below displays the Orgnisation Name, CountryCode and OrganisationID in the console.

xeroClient.core.organisations.getOrganisations()
  .then(function(data) {
    data.forEach(function(entry) {
      console.log(entry.Name);
      console.log(entry.CountryCode);
      console.log(entry.OrganisationID);
    });
  })
    .catch(function(err) {
      // Do Something
  })

**Comment by neeon-li** [comment]
@philals Sorry for late response.

Thx @SidneyAllen for showing the example of getOrganisations().

I was using the code as follow:
```
  xeroClient.core.organisations
    .getOrganisation()
    .then(organisation => {
      console.log(organisation.Name);
      console.log(organisation.OrganisationID);
    })
    .catch(error => {
      console.log(error);
    });
```

I am successful to get the OrganisationID right now.
I may accidentally meet some kind of typo or error to make the OrganisationID gone.
But at least it works for me right now with version 2.15.0.

Thx guys.

**Comment by neeon-li** [comment]
I have success to reproduce the problem this time.

The problem happens after used `organisation.toJSON()` to get Json object.
Try the following codes:
```
  xeroClient.core.organisations
    .getOrganisations()
    .then(data => {
      data.forEach(entry => {
        console.log(entry.Name);
        console.log(entry.CountryCode);
        console.log(entry.OrganisationID);

        const entryObj = entry.toJSON();
        console.log(entryObj.Name);
        console.log(entryObj.CountryCode);
        console.log(entryObj.OrganisationID);
      });
    })
    .catch(error => {
      // Do Something
      logger.error('[%s] ', error);
    });
```

The OrganisationID will show as `undefined`.
Is this a bug ?

**Comment by philals** [comment]
Thanks for the issue. I have merged and released PR.
