### ISSUE TITLE
Invoice as pdf returns blank pdf

### ISSUE THREAD

**Issue by ChrisGrigg** [XeroAPI/xero-node#160]
I'm having trouble with xero-node npm lib when I try to get an invoice as a PDF. I have taken the example from the npm page https://www.npmjs.com/package/xero-node with the following code:

    xeroClient.core.invoices.getInvoice(req.body.invoiceID, null, null, null, null, "application/pdf")
        .then((data) => {
           console.log(`data ${JSON.stringify(data)}`);
           fs.writeFile(data.FileName, data.PdfContentRaw, 'binary', function(){
           // Do something with the file
           });
        });`

When I do this the file returned is just a blank 1 page pdf.

**Comment by gimenete** [comment]
Same here. I'm trying to export as PDF this invoice from the demo organisation https://go.xero.com/AccountsReceivable/View.aspx?InvoiceID=3f887d04-cbd9-4853-b594-bc1ab207558c

This is the code and I get a blank page:

```javascript
    return xeroClient.core.invoices
      .getInvoice('3f887d04-cbd9-4853-b594-bc1ab207558c', null, null, null, null, 'application/pdf')
      .then(function(data) {
        fs.writeFile(data.FileName, data.PdfContentRaw, 'binary', function() {
          // Do something with the file
        });
      });
```

**Comment by ChrisGrigg** [comment]
Any timelines on when this will be fixed? I need this feature ASAP. Thanks

**Comment by whitemarble** [comment]
Same here, what we got from "data.PdfContentRaw" is the PDF raw data, not the binary file. Seems we need to get it converted. Anyone knows how to do this?

**Comment by philals** [comment]
Hi @ChrisGrigg  Sorry we have not had time to look into this so no ETA. PRs welcome.

**Comment by jordanwalsh23** [comment]
I recall when writing the library that I had issues with saving attachments
to files when using fs.writeFIle and instead I was able to successfully
write using fs.writeFileSync.

I'm not sure if this contributes to the fix, but while the lovely folk at
Xero are investigating further I suggest you give it a shot

**Comment by ChrisGrigg** [comment]
Thanks @philals and @jordanwalsh23 unfortunately fs.writeFileSync does not work it has the same result. I would like to do a PR but don't currently have time.

**Comment by gimenete** [comment]
I found a workaround @ChrisGrigg 

```javascript
const stream = fs.createWriteStream(path.join(__dirname, 'invoice.pdf'));
stream.on('close', () => {
  console.log('PDF is ready!');
});
xeroClient.core.invoices.streamInvoice('3f887d04-cbd9-4853-b594-bc1ab207558c', 'pdf', stream);
```

**Comment by roger-balie** [comment]
Good day

I've also been having issues with generating PDFs. 
It worked sometimes and I needed to generate 40+ invoices one after another and attach them to an email.

I am using: 
`
const sgMail = require('@sendgrid/mail');
const streams = require('memory-streams');
var writeStream = new streams.WritableStream();
xeroClient.core.invoices.streamInvoice(xeroInvoiceId, 'pdf', writeStream)
    .then(function() {
        const msg = {
            to: 'recipient@something.com',
            from: 'sender@something.com',
            subject: 'Xero Invoice',
            html: 'Dear Recipient<br/><br/> Please find attached your latest invoice.<br/><br/>Kind regards,<br/>The Sender',
            attachments: [
                {
                    filename: 'Invoice.pdf',
                    contentType: 'application/pdf',
                    content: writeStream.toBuffer().toString("base64")
                }
            ]
        };
        sgMail.send(msg);
    })
    .catch(function(err) {
        console.log('error: ' + err);
    });
`
To resolve my issue, I had to replace the "pipe" function in "lib/oauth/oauth.js".

From line 413:
`
var dataLen = 0; 
request.on('response', function(response) {
    if (options.stream) {
        // .pipe doesn't work most of the time
        //response.pipe(options.stream);
        data = [];
        response.on('data', function(chunk) {
            data.push(chunk);
            dataLen += chunk.length;
        });
    } else {
        response.setEncoding('utf8');
        response.on('data', function(chunk) {
            data += chunk;
        });
    }
    response.on('end', function() {
        if (options.stream) {
            var buf = new Buffer(dataLen);

            for (var i=0, len = data.length, pos = 0; i < len; i++) { 
                data[i].copy(buf, pos); 
                pos += data[i].length; 
            }
            
            options.stream.write(buf);
        }
        passBackControl(response);
    });
    response.on('close', function() {
        if (allowEarlyClose) {
            passBackControl(response);
        }
    });
});
`
Now my invoices stream 100% of the time.

Hope this helps someone.

**Comment by whitemarble** [comment]
I tried @gimenete 's solution, xeroClient.core.invoices.streamInvoice() works! Thank you
When I use the Xero standard invoice template it works, however when I use the customized invoice template it won't get any response, I'm not sure it is a Xero API or xero-node problem.

When using xeroClient.core.invoices.getInvoice(req.body.invoiceID, null, null, null, null, "application/pdf") both standard invoice template and customized template can get response, but still gets blank file.

**Comment by philals** [comment]
Hi folks. Closing this issue as it mainly relates to the old version. Please feel free to open another one and reference to this. Thanks
