### ISSUE TITLE
Dont PUT, always POST

### ISSUE THREAD

**Issue by Kasi-mir** [XeroAPI/xero-node#167]
For example in customers, it would be worth it to get rid of the ContactID validation as you can update items without having contactID in place. So never is there need to PUT, but would be rather useful to always POST.

For example external systems could use the ContactNumber to update the account without needing the ContactID and this seems to be a valid way to query the Xero contacts.

The same logic could be removed from everywhere, I see no gain in PUT instead of POST.

Input please.

**Comment by philals** [comment]
Thanks @Kasi-mir . I'll have a chat to the accounting API PO when they are next in, to see if I can get more info on thus,

**Comment by philals** [comment]
Hi @Kasi-mir 

Thanks for the question. Yes it looks like you could do this.

I take this into account when thinking about the next version of the SDK.

I do think it's good to keep the PUT & POSTS separate so in the API logs you can see if the intention was a create or update.

I'll close this issue for now - feel free to raise another if something comes up.
