### ISSUE TITLE
TrackingCategorySchema issue and way to convert Journals to Json.

### ISSUE THREAD

**Issue by jin-chong** [XeroAPI/xero-node#170]
Hi,
I'm using ver 2.17.
I got the Journals from https://api.xero.com/api.xro/2.0/journals.
By express js, when I try to send back Journals as Json to client, I found some issues like below:
  1. When I call express's 'res.json(Journals);', it only serializes some parts of properties.
  2. 'JSON.stringify(Journals)' has same issue.
  3. 'JSON.stringify( Journals.map( (j)=> j.toObject() )' throws exception such as ' no _super' at joural.js:46
  4. finally I did like below:
  JSON.stringify( Journals.map( (j)=>j._schemaToObject({all: true}) )
  It looks OK but it misses some properties at TrackingCategories ( property of JournalLine).  Even if the object has 'Option' and 'TrackingOptionID' but it fails to serialize these to JSON.
  I found TrackingCategorySchema (trackingcategory.js: 5) does not have the definition of these properties.
  I could make it work once I add these properties into TrackingCategorySchema.
  I feel like TrackingCategorySchema should look like TrackingOptionsSchema at shared.js: 83

Can you have a look if TrackingCategorySchema definition is correct?
And what is the best way to convert the array of Schema objects to Json or normal object?

Thanks,
Jin

**Comment by philals** [comment]
Hi @jin-chong 

Are you able to use the latest version V3?

We have rewritten the module from the ground up.

https://github.com/XeroAPI/xero-node/issues/183

**Comment by philals** [comment]
Hi folks. Closing this issue as it mainly relates to the old version. Please feel free to open another one and reference to this. Thanks
