### ISSUE TITLE
Account.CurrencyCode not serialized correctly. Directive is wrong

### ISSUE THREAD

**Issue by addertheblack** [XeroAPI/xero-node#171]
I would like to create a bank Account with currency "CAD". This is a foreign currency, my default is USD. When I create an Account data structure using 

const newAccount = xeroClient.core.accounts.newAccount(accountToAdd);

with a CurrencyCode it's not sent the xero when I newAccount.save()

The problem looks to be in 

File: ./lib/entity_helpers/accounting/accounts.js ./lib/entities/accounting/account.js

Line 13:

CurrencyCode: { type: String, toObject: 'never' },

should be something like

CurrencyCode: { type: String, toObject: 'hasValue' },

**Comment by philals** [comment]
Hi @addertheblack . Your code looks like it will probably work. Do you mind sending a PR? Try adding a test with it as well.

Thanks for the input.

**Comment by philals** [comment]
Thanks for the issue. I have merged and released PR.
