### ISSUE TITLE
'Uncaught Error: Cannot find module'

### ISSUE THREAD

**Issue by damienrobson** [XeroAPI/xero-node#174]
Hi.

I'm trying to get this package working and I'm hitting the following error when trying to instantiate a new client via `new Xero.PublicApplication(config)`:

`Uncaught Error: Cannot find module './entity_helpers/accounting/organisations'`

Any ideas?

**Comment by philals** [comment]
Hi

I have tried t replicate. See below. This is on a fresh repo.

Are you able to create a gist or empty repo that demonstrates the issue?

Thanks.

![image](https://user-images.githubusercontent.com/8849355/36274134-a7788ab8-12eb-11e8-8162-61522154ca9a.png)

**Comment by damienrobson** [comment]
[Gist](https://gist.github.com/damienrobson/92789a7dbf76925476508a4b898c6885)

I'm using Meteor and React if that makes any difference. The code in the Gist is ran from a button click.

**Comment by philals** [comment]
Hi @damienrobson 

I imagine this has something more to do with your package.json.

Are you able to upload a full repo with a package,json. 

A simple app - one that just makes an API call.

**Comment by damienrobson** [comment]
Thanks, @philals - the problem was mine. I was running on the client, not the server. Sorry!
