### ISSUE TITLE
refreshAccessToken not functioning

### ISSUE THREAD

**Issue by sudharsh-duo** [XeroAPI/xero-node#175]
Error - oauth_problem=token_rejected&oauth_problem_advice=Token 5BD4O5UNAVIYTKQ686PY5IB9DWQI8K does not match an expected REQUEST token

Code as bellow - 

app.get('/xero/refreshToken', function(req, res) {
    getToken(req.query.domain).then(function(xeroCon){

       //Receive saved token 
        var token={"oauth_token":xeroCon.token,"oauth_token_secret":xeroCon.token_secret};
        var options={"accessToken":xeroCon.token,"accessSecret":xeroCon.token_secret};
        req.session.token=token;

        authorizedOperation(req, res, '/xero/refreshToken', function(xeroClient) {
            // Refresh token 
            xeroClient.refreshAccessToken(function (xCli){
                console.log(xCli);
            },options );

        })
    }).catch(function(err){
        res.send({"status": false, "error": err}) ;
    });
});

**Comment by philals** [comment]
Hi is #176  and this the same issue?

**Comment by sudharsh-duo** [comment]
Hi @philals,
Token not refresh automatically, that's why I try to refresh the token explicitly, so it's two different issues right. If it easy to track by combine those two ticket, please combine it. 
Thanks

**Comment by philals** [comment]
What App Type are you using? Private, Public or Partner? See: https://developer.xero.com/myapps for what type it is.

**Comment by rjaus** [comment]
I attempted this with the Partner App (explicit refresh) and received the "Token does not match" error.

**Comment by sudharsh-duo** [comment]
Hi @philals,
I'm also using partner App.

**Comment by philals** [comment]
Just updating. I have run all the token_tests on a Partner app. All green.

Not much more to report just yet.

**Comment by philals** [comment]
Hi @sudharsh-duo 

Are you able to review the token_tests.

I have added a few extra tests here: https://github.com/XeroAPI/xero-node/commit/54fe24655747458e5613f23653c0a962b1337f42 to make sure of a few things.

These tests use refreshAccessToken() and are not throwing an issue for me.

**Comment by philals** [comment]
@sudharsh-duo  So I have done a bit of digging and seems things are work. Just not working with the sample app,

Are you basing your examples off the xero-node-sample app?

This uses the browsers session storage to store oauth_token and and oauth_token_secret. This is because it has no persistent datastore.

One thing that it does not store is the sessionHandle. Even if it did, there are no methods that I can see to set the internal this.options.sessionHandle on the XeroClient you have initialized. 

So the green tests are correct as far as I can see. Please double check that you are persisting your sessionHandle.

I have hacked up a quick proof here to show that refreshAccessToken is working: https://github.com/philals/xero-node-sample-app/tree/f/sudharsh-duo

Please add your PartnerApp config and you have to go to these endpoints, in this order, to get it running:

1. Load up http://localhost:3100/
2. Click on List Organisations http://localhost:3100/organisations. This will make you Auth the app against your Org and list the Orgs details
3. Click on BrandingThemes. http://localhost:3100/brandingthemes. Here I have hacked around. It will explicitly refreshAcessToken (and fire off the event Jordan mentioned above).

This hacked together version keeps all options in memory and are shared between requests (even multiple users), So we cannot put it up on Heroku etc. It's just to show that refreshAcessToken works.

Let me know if this makes sense.

**Comment by sudharsh-duo** [comment]
@philals ,
I checked with your source code. (https://github.com/philals/xero-node-sample-app/tree/f/sudharsh-duo). It's just refresh the token regardless the session. I need to refresh the token for particular session. It's for back end process such as when the time of invoice creation I need to push the invoice data to Xero, there is no browser interaction. I jsut store the token during the initial integration by the user, there after I need to refresh the token when the token expire. so I forcefully load the saved token to session to call Xero API. It's working perfectly until token expiration. I hope you understood my use case. @rjaus also with me, you can get more clarification from him.

**Comment by philals** [comment]
Hi @sudharsh-duo 

Have you set up a listener for the `xeroTokenUpdate` event? This should alert you to the `accessToken`, `accessSecret` and new `sessionHandle`. Store these in a DB.

When it's time to push data to Xero. Reinitialize the SDK with these options(see below).

It you manually want to refresh to token before doing this sync you can call `xeroClient.refreshAccessToken()`.

At the moment, I'm struggling on figuring out how to reinitialize the SDK object with the `sessionHandle` etc that was stored in the DB.

**Comment by philals** [comment]
@sudharsh-duo. Please see here for an example https://github.com/philals/xero-node-sample-app/tree/f/sudharsh-duo. Please follow the same instructions as above. If you use VSCode then you can stop at the debugger statements.

Here I am: 
1. Subscribing to `xeroTokenUpdate`
2. On a tokenUpdate (store the result in a DB for later), using the new data to recreate the SDK object and make a call to the Users endpoint.

Although my example has browsers interaction (you have to go to /brandingthemes). I only do this for demo purposes. You can fire off the same events without a browser.

**Comment by sudharsh-duo** [comment]
@philals ,
Yes, I set up a listener for the xeroTokenUpdate event and I can receive updated token, so how do I map that token to user, Is there any link to received data  in xeroTokenUpdate event and the user. currently I store token and token secret for the user. On the request from the user I just load the saved token and token secret to the session for the user.

**Comment by philals** [comment]
@sudharsh-duo Cool. I think we're on the same page now.

Good question. 

I'm not too sure how to match a refreshed Token to a User when your in the `xeroTokenUpdate` event context. The SDK really needs to pass into that event the old sessionHandle or something.

Do you have any ideas?

Let me think about that one.

**Comment by philals** [comment]
What about this:

When you create the event handler, have a variable outside that is the Users name/id.

![image](https://user-images.githubusercontent.com/8849355/36704982-bdd2b3bc-1bc7-11e8-9972-76cf3f66c8d9.png)

**Comment by sudharsh-duo** [comment]
@philals ,
Cool, It's a good way if the token get update automatically. But when we need to update the token explicitly it's better to pass old token to refreshAccessToken() method.

**Comment by philals** [comment]
Cheers.

Hopefully I have helped. I'll document a few things as it's a bit sparse in this area.

Will close issue for now.

Best of luck.

**Comment by sudharsh-duo** [comment]
@philals ,
Please give the solution to update the token explicitly with reference such as passing old token to  refreshAccessToken() method as well.

**Comment by philals** [comment]
@sudharsh-duo 

I have. Please check the branch in the repo mentioned above.

**Comment by philals** [comment]
Also see here: https://github.com/XeroAPI/xero-node/blob/master/docs/PartnerSetup.md

**Comment by sudharsh-duo** [comment]
@philals,  Ok great, so which version of xero-node will I use in my project.

**Comment by philals** [comment]
Hi @sudharsh-duo Use the latest one.

**Comment by sudharsh-duo** [comment]
Thank you for our support @philals.

**Comment by adamreisnz** [comment]
> Also see here: https://github.com/XeroAPI/xero-node/blob/master/docs/PartnerSetup.md

Has this page moved somewhere else?

**Comment by philals** [comment]
Hi @adamreisnz, this conversation related to the v2 version of xero-node.

We have moved all v2 related docs/code to a branch called `v2`

https://github.com/XeroAPI/xero-node/blob/v2/docs/PartnerSetup.md

Since this discussion we have released a new version, which is better.

Hope this helps.

**Comment by adamreisnz** [comment]
@philals yes thanks, I've been upgrading to v3 this afternoon and piecing the puzzle together. 
It's a nicer API (still damned shame that Xero doesn't upgrade to oAuth v2 though), but I did find a few more changes from v2 to v3 that haven't been documented in the readme migration from v2 notice.

Some examples are that you no longer use `new Xero.PublicApplication` but `new Xero.AccountingAPIClient`, access token is no longer passed with options but as a second param, the oAuth related methods are in their own namespace now, some changes from `z` to `s`, etc.

Would be good to have the full list of changes somewhere to make migration a bit easier. If I have missed this and this has been documented somewhere I apologise, but then I wasn't able to find it.

**Comment by philals** [comment]
Thanks for the info @adamreisnz. 

Don't worry OAuth2 is coming... That was some of the motivation in some of the API decisions we made.

We might have missed some specifics in the migration guide. Unfortunately it was not easy to document all changes - as we wrote the new module from scratch. 

Hopefully you have found a way. I have added a few of your notes to the migration guide.

**Comment by adamreisnz** [comment]
Yep most of it was pretty easy to deduce from the example in the readme, all up and running now including refresh tokens, thanks 👍
