### ISSUE TITLE
Token not get refresh automatically, when the token expired.

### ISSUE THREAD

**Issue by sudharsh-duo** [XeroAPI/xero-node#176]
I'm loading the saved token to Xero client, but when the token get expire, it's not automatically refresh the token.

My code as bellow  :

//Loading saved token
var token={"oauth_token":xeroCon.token,"oauth_token_secret":xeroCon.token_secret};
req.session.token=token;
authorizedOperation(req, res, '/xero/getContacts', function(xeroClient)

config.accessToken = req.session.token.oauth_token;
config.accessSecret = req.session.token.oauth_token_secret;

//Load token to client 
xeroClient = new xero.PartnerApplication(config);

  eventReceiver.on('xeroTokenUpdate', function(data) {
                //Token not receiving here, when the token expire.
                console.log("Received xero token refresh: ", data);
            });

**Comment by rjaus** [comment]
This is how the Xero Sample App handle token refresh: https://github.com/XeroAPI/xero-node-sample-app/blob/master/index.js#L124

I'm testing this now to see if it actually succeeds with the refresh (after 30 minutes).

**Comment by jordanwalsh23** [comment]
The `eventReceiver` object must be obtained from the `xeroClient.eventEmitter` object.  It creates it internally and makes it available for use externally e.g.

```
xeroClient = new xero.PartnerApplication(config);

let eventReceiver = xeroClient.eventEmitter;

eventReceiver.on('xeroTokenUpdate', function(data) {
   //Token will now be received here as it's using the correct eventReceiver object.
   console.log("Received xero token refresh: ", data);
});
```

**Comment by rjaus** [comment]
Hey @jordanwalsh23 that appears to be how it's being used in this case: https://github.com/XeroAPI/xero-node-sample-app/blob/master/index.js#L122

Yet, that still fails.  But it seems to be due to the underlying refreshAccessToken function failing. #175

**Comment by jordanwalsh23** [comment]
There's a test for partner apps in the library that tests the refresh
through an event emitter.

I think it actually refreshes the token immediately after creating the
partner app in the test.

Is that test failing? If so, something in the API must have changed as I
don't believe that part of the library has changed recently.

**Comment by jordanwalsh23** [comment]
Run token_tests.js with a partner application in the testing config.  It is currently testing the eventEmitter stuff through a spy function.

**Comment by philals** [comment]
Hi @sudharsh-duo . Sorry I'm quite tied up (mid-sprint) at the moment. Will look into this after.

Can you try an older version? Say 2.10.1?

**Comment by sudharsh-duo** [comment]
Hi @philals,
Ok, I'll try with version 2.10.1

**Comment by sudharsh-duo** [comment]
Hi @philals,
I tested with mentioned version (2.10.1), same issue there.

**Comment by philals** [comment]
Closing as I believe this issue is related to https://github.com/XeroAPI/xero-node/issues/175. Please see my latest comment as I think I have resolved it.
