### ISSUE TITLE
Error updating payments to DELETED with example code

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#178]
I'm trying to update payments of an invoice, settings their statuses to DELETED. I'm not 100% sure if this is an issue of the xero-node library, but it might worth to take a look at it.

Given the following example code from the docs, I modified payment.Status from AUTHORISED to DELETED
```
var somePaymentID = '75520d2e-e19d-4f36-b19b-e3b9000b2daa';

xeroClient.core.payments.getPayment(somePaymentID)
   .then(function(payment) {
      //We've got the payment so now let's change the name
      payment.Status = 'DELETED';

      payment.save()
         .then(function(response) {
            var thisPayment = response.entities[0];
            console.log(thisPayment.Status); //'DELETED' ?
         })
   });
```
Xero api returns ValidationError:

`Message: 'Only Status accepted for updates.'`

Edit: I've figured out how to do it without xero-node, but still not sure if the library provides a way to handle this.

```
POST /Payments/<PaymentID>
with Body: '<Payments><Payment><Status>DELETED</Status></Payment></Payments>'  
```

**Comment by philals** [comment]
Hi @sandorvasas 

Looks like (https://developer.xero.com/documentation/api/payments#POST) when you want to reverse a payment you can only post in the ```status``` key on the Payments object.

Try a new payments object with no other keys except status.

**Comment by philals** [comment]
Hopefully I answered your question. Feel free to open a new issue if it did not help.

**Comment by adamreisnz** [comment]
How does the new API handle this? Could you please post a complete example on how to mark a payment as deleted? I'm confused whether I have to get the payment first, or instantiate an empty payment object, which seems convoluted. I'd expect to be able to just pass in a payment ID and updated data to the `client.payments.update()` method, but according to the docs, the function [appears to expect an array of payments](https://xeroapi.github.io/xero-node/v3/classes/accountingapiclient.html#payments). A simple example would be much appreciated.

**Comment by adamreisnz** [comment]
Figured it out based on another example in one of the issues:

```js
await this.client.payments.update({
  PaymentID: id,
  Status: 'DELETED',
});
```

**Comment by philals** [comment]
Thanks @adamreisnz 

Do you mind pointing out/PR where the documentation could have been better for this?

**Comment by adamreisnz** [comment]
Yes, as per the link included in my previous comment.
This appears to be (mostly) dynamically generated documentation based on function signatures etc.

However it's a bit unclear on how to do common use cases, like updating status of a payment to deleted. Some code examples around these common calls would be good to have in the documentation.
