### ISSUE TITLE
Error not returned

### ISSUE THREAD

**Issue by ajouve** [XeroAPI/xero-node#179]
https://github.com/XeroAPI/xero-node/blob/f6106f7d4be5290a7d2b7465f5cb70a5c959dff9/lib/application.js#L292

There is an issue there is there is no `err.data`

I had the following one

```
Error: No key provided to sign
    at Sign.sign (crypto.js:307:11)
```

**Comment by philals** [comment]
Hi.

I'm not 100% what you're pointing out. 

But.. could might be related to this? https://github.com/XeroAPI/xero-node/issues/116

I had a PR which I could resurrect, which added a check to make sure your privateKey was valid.

**Comment by ajouve** [comment]
I just forgot to add the .pem file content in the config.
and my promise or callback was never called because there is no the `data` key in the `err` variable.
So the callback or reject is not called

**Comment by philals** [comment]
Thanks will try to get that PR going again to prevent this
