### ISSUE TITLE
Unhandled Promise Rejection error

### ISSUE THREAD

**Issue by MaxGuitet** [XeroAPI/xero-node#180]
Hello all,

We have recently become a Partner app with Xero and we would like to use this nice package to integrate.
We are using Meteor 1.6 and the xero-node 2.19.0. The issue we are facing is that some methods trigger an `Unhandled Promise Rejection error` which we cannot catch.

To better explain the problem, I've created a simple example repo based on the meteor example app: https://github.com/MaxGuitet/xero-node-meteor

If you run the app, you will see that the `xeroClient.core.organisations.getOrganisation()` works fine (it seems to be the only one) but `xeroClient.core.clients.getClients()` triggers the error.

I have tried to find out where the issue is raised in the module but couldn't find it. The `get` method in `application.js` seems to work fine. You will see that the [`console.log`](https://github.com/MaxGuitet/xero-node-meteor/blob/master/imports/api/xero/server/xero.js#L89) is being called with the results, but immediately after the server error is raised which prevent the rest of the code from being executed.

Here is the stacktrace I have

```
=> App running at: http://localhost:3000/
W20180305-12:57:13.522(0)? (STDERR) (node:5686) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Maximum call stack size exceeded
W20180305-12:57:13.620(0)? (STDERR) (node:5686) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Let me know if I can be of any help.

**Comment by philals** [comment]
Hi @MaxGuitet 

Sorry are you able to post a repo with out all the meteor stuff?

You have given me a good idea though. Soon, I'll whip up a template repo that people can use to report issues.

**Comment by philals** [comment]
Hold fire...

**Comment by philals** [comment]
ARe you able to replicate using a Private app? Try this: https://github.com/philals/xero-node-example-console-app

Please fork and replicate your issue. 

If it's only with Public/Partner apps then we can figure something out.

**Comment by MaxGuitet** [comment]
I tried with the `xero-node-sample-app` and it does work there. Hence why I added the Meteor demo app. The file of interest for you are located in [`/imports/api/xero/server`](https://github.com/MaxGuitet/xero-node-meteor/tree/master/imports/api/xero/server). 

I will try with the Private app you posted in the meantime.

Thanks for your help.

**Comment by MaxGuitet** [comment]
Just had a go at your test app but I cannot create a private App, probably because I only have access to the Demo Company (I'm just a dev).

**Comment by philals** [comment]
You should be able to connect a Private app to that Demo Company.

Can you still replicate against the Demo Company?

**Comment by MaxGuitet** [comment]
Sorry, I was being stupid, the name probably existed already.

Just tried and it works fine with you sample private app.

**Comment by MaxGuitet** [comment]
Hi,
I just cloned your console app, set my credentials and ran it and it output the total number, no error raised.
I didn't change anything to the sample app code apart from the credentials.

**Comment by MaxGuitet** [comment]
Hi,
I did a bit more investigation and in the end it looks like the problem is not coming from xero-node but from meteor itself. Here are the findings in case someone else faces the same problem.

Unlike in the example app, you cannot return to the client the full object that you retrieve from xero-node. The part I don't understand is that the error is thrown on the server, not the client. To give an example, the following method will work:
```js
const xeroMethod = new ValidatedMethod({
  ...
  async run(doc) {
    const result = await xeroClient.core.contacts.getContact('id');
    console.log(result) // => outputs the results correctly
    return 'OK'
});
```
but not this one:
```js
const xeroMethod = new ValidatedMethod({
  ...
  async run(doc) {
    const result = await xeroClient.core.contacts.getContact('id');
    console.log(result) // => outputs the results correctly
    return result; // => throws an Unhandled Promise rejection error
});
```
To get it to work, you need to extract the actual object from the Xero Object (without constructor, schema and so), e.g.:
```js
const xeroMethod = new ValidatedMethod({
  ...
  async run(doc) {
    const result = await xeroClient.core.contacts.getContact('id');
    console.log(result) // => outputs the results correctly
    return result.toJSON(); // => returns the contact object to the client
});
```

When you think about it, it makes sense that we cannot return server objects to the client, but what puzzles me is the error being thrown on server.

This issue can be closed now I think, thanks @philals for your help :slightly_smiling_face:
