### ISSUE TITLE
Add 'headers' property to errors returned from API calls

### ISSUE THREAD

**Issue by danielmoi** [XeroAPI/xero-node#184]
Hello all,

Wondering if there was any plans in your roadmap to return the error response headers from Xero API calls?

Per the docs at https://developer.xero.com/documentation/auth-and-limits/xero-api-limits:
> You will also receive an X-Rate-Limit-Problem HTTP header with the value of Daily or Minute to indicate which rate limit you have hit.

If there are no immediate plans to implement this, I can work on a fork and submit a PR.

Thanks!

**Comment by philals** [comment]
Hi @danielmoi 

Have you seen this? https://github.com/XeroAPI/xero-node/issues/183

We're working on a new version. We just had a chat, we think it would be a good idea to add headers to the HttpError exception.

Wanna give it a crack?

We're keen to get outside eyes on the new version.

**Comment by danielmoi** [comment]
Hi @philals 
That looks really interesting!
Ok, I will have a look and get back to you if I manage to hook it up 👍🏼

**Comment by philals** [comment]
Wicked. Let me know if you need a hand.

**Comment by philals** [comment]
FYI @danielmoi . We have added this to the new version. 

Please check it out - we're keen for feedback

**Comment by danielmoi** [comment]
Hi @philals 
Thanks for that!
Would you be able to point to where the Xero error response headers are being passed on?
I can't seem to locate that code path in https://github.com/XeroAPI/xero-node/blob/2ef24317cd2d3ce0b63a57eb6da106f8d1fecbce/lib/application.js

**Comment by philals** [comment]
Hi @danielmoi 

It's in the new version. Version 3.

See here for some details: https://github.com/XeroAPI/xero-node/issues/183

I'll update this issue with the latest version which will include the headers and publish it in the next few mins.

**Comment by philals** [comment]
@danielmoi I have just released the latest version of the new one

**Comment by danielmoi** [comment]
Hey @philals 
Awesome, I can see it here 
https://github.com/XeroAPI/xero-node/blob/v3/src/internals/OAuth1HttpClient.ts#L220
Looks great, excited about v3!

**Comment by philals** [comment]
Thanks

@danielmoi Please feel free to start using it now.
