### ISSUE TITLE
inversion POST / PUT

### ISSUE THREAD

**Issue by ajouve** [XeroAPI/xero-node#185]
https://github.com/XeroAPI/xero-node/blob/7a21323e6a8da3490e4af7cec6a295aa64973b1f/lib/entities/accounting/contact.js#L122

Not an expert but you should do a put request on an existing id and a post to create a new one https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6

**Comment by philals** [comment]
Hi @ajouve 

Yup this is an issue with the Xero API. PUT and POST are swapped.

See the "HTTP POST and PUT" section of this page. This is a historical issue that would have been a major breaking change to swap around.

The newer APIs like Payroll etc are to spec on this.

Hope this helps.
