### ISSUE TITLE
Request: Add support for GET OnlineInvoiceUrl

### ISSUE THREAD

**Issue by DaveCLowe** [XeroAPI/xero-node#186]
Would be great to build in support to get the online invoice URL as per : https://developer.xero.com/documentation/api/invoices

Retrieving the online invoice url:
To integrate your application with Xero's online invoicing, you can retrieve the online invoice url for sales (ACCREC) invoices. Note: you cannot retrieve an online invoice url for DRAFT invoices.

GET https://api.xero.com/api.xro/2.0/Invoices/9b9ba9e5-e907-4b4e-8210-54d82b0aa479/OnlineInvoice
{
  "OnlineInvoices": {
    "OnlineInvoice": { 
      "OnlineInvoiceUrl": "https://in.xero.com/iztKMjyAEJT7MVnmruxgCdIJUDStfRgmtdQSIW13" 
    }
  }
}

Thanks!

**Comment by philals** [comment]
Hi @DaveCLowe 

We have build this into the new version of the SDK. We're in the later stages of dev.

Wanna give it a spin? We're after feed back.

Details here: https://github.com/XeroAPI/xero-node/issues/183

We might soon have a OAuth interface change coming in the next 24 hours, other than that the API is stable.

Let me know what you think.

**Comment by DaveCLowe** [comment]
Sure, sounds great thanks!

Re the above req, I thought I could add this to invoice.js - but I was wrong..
  getOnlinePaymentURL: function(options) {
      return this.application.get(`Invoices/${this.InvoiceID}/OnlineInvoice`,
      options);
  },

**Comment by philals** [comment]
@dupski Please update here once you have completed that API change.

**Comment by philals** [comment]
@DaveCLowe API is updated and can now be considered stable. 

More docs incoming - but hopefully the examples in the repo are a good enough place to start

**Comment by DaveCLowe** [comment]
Works a treat in v3. Thanks a lot guys 👍 
  return await xero.invoices.onlineInvoice.get({InvoiceID: InvoiceID});
