### ISSUE TITLE
Does this package include OAuth process?

### ISSUE THREAD

**Issue by xuan9230** [XeroAPI/xero-node#19]
Hi, I just started integration with Xero in my node app, wondering does this package include OAuth process?

**Comment by jordanwalsh23** [comment]
Yes it does. Please read the getting started guide in the docs to learn how to authenticate. Closing as Issues should be reserved for actual bugs or features. Thx

**Comment by xuan9230** [comment]
Hi, thanks for the reply. I've gone through the guide, tried both the sample app and built my own app, but getting the same error:

```
{ oauth_problem: 'token_rejected',
     oauth_problem_advice: 'Token has not been provided' }
```

It's a public app registered, and should be able to see the demo company.

**Comment by jordanwalsh23** [comment]
Either your config file has not been set up correctly, or your application can't access your config file.

I suggest you sign up for a runscope account, check the docs to configure a runscope bucket ID and add it to your config.  You can then debug the calls through there.

If you're still having issues, please contact api@xero.com and the fine people there will help you out.

- Jordan
