### ISSUE TITLE
Creating blank PDF on Xero Attachement

### ISSUE THREAD

**Issue by ashishsrivastavaicreon** [XeroAPI/xero-node#190]
I am using following code. It creates a attachment on Xero invoice But when I tried to download. it was blank

var data = {
	FileName: transaction_id+'.pdf',
	MimeType: "application/pdf"
};

var filePath = './invoice/'+transaction_id+'.pdf';
var fileReadStream = fs.createReadStream(filePath);
var attachmentObj = xeroClient.core.attachments.newAttachment(data);

//Retrieve some entity to add the attachment to (e.g. Invoices)
xeroClient.core.invoices.getInvoice(json.Response.Invoices.Invoice.InvoiceID)
    .then(function(invoice){
        attachmentObj.save("Invoices/" + invoice.InvoiceID, fileReadStream, true)
          .then(function(attachments){
              //Attachment has been created 
              var myAttachment = attachments.entities[0];
          })
    });

**Comment by philals** [comment]
Hi @ashishsrivastavaicreon 

We'll move the conversation here.

Hi Ashish

What version of xero-node are you using?

We have been working on a new version which has way better support for what you are trying to do.

Can you give it a spin?

If it does not work - we'll fix it. We have less appetite for fixing the old version.

https://github.com/XeroAPI/xero-node/issues/183

**Comment by DaveCLowe** [comment]
Hi Ashish,

Sounds to me like your invoice is going through in Draft status - which means Xero will no longer let you grab the PDF (in a recent change...) Wish they did (or I knew where to look) a changelog.

Test it out by viewing your "PDF" in a text editor. It might say something like:
<ApiException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ErrorNumber>10</ErrorNumber>
  <Type>ValidationException</Type>
  <Message>A validation exception occurred</Message>
  <Elements>
    <DataContractBase xsi:type="OnlineInvoice">
      <ValidationErrors>
        <ValidationError>
          <Message>Online invoices can only be created for invoices that have been authorised.</Message>
        </ValidationError>
      </ValidationErrors>
    </DataContractBase>
  </Elements>
</ApiException>

**Comment by ashishsrivastavaicreon** [comment]
I am using  "xero-node": "^2.20.0",

![image](https://user-images.githubusercontent.com/38007229/38235761-db391a0c-373f-11e8-9b10-20707c1e4a37.png)

Please see the screenshot my invoice is not in Draft status

**Comment by ashishsrivastavaicreon** [comment]
Hi @philals ,

I upgraded to v3. its working fine on v3
