### ISSUE TITLE
Invoice.LineItems is not working in v3

### ISSUE THREAD

**Issue by neeon-li** [XeroAPI/xero-node#200]
I am using `v3.0.2`.
The Invoice.LineItems is always returning an empty array to me.
But I checked the invoice in Xero, and sure there is some LineItem in each invoice.

```
const XeroClient = require('xero-node').AccountingAPIClient;
const config = require('./config.json');

(async () => {
  const xero = new XeroClient(config);
  const result = await xero.invoices.get();
  for (const invoice of result.Invoices) {
    console.log(invoice);
    if (invoice.LineItems) {
      for (const LineItem of invoice.LineItems) {
        console.log(LineItem);
      }
    }
  }
}
```

**Comment by philals** [comment]
Thanks for including running code in your issue, make things way easier!

I'll have a look at this when I have a moment.

**Comment by gslisrael** [comment]
See https://developer.xero.com/documentation/api/invoices:

> When you retrieve multiple invoices, only a summary of the contact is returned and no line details are returned - this is to keep the response more compact.
The line item details will be returned when you retrieve an individual invoice, either by specifying Invoice ID or Invoice Number or by using the optional paging parameter

Try xero.invoices.get({InvoiceNumber: SOME_VALID_INVOICE_NUMBER}); and you should see them.

**Comment by philals** [comment]
Thanks again for your contribution @gslisrael 

@neeon-li Does the suggestion work?

Thanks

**Comment by neeon-li** [comment]
Thx @gslisrael, I really miss that point.

With this limitation, then I got into another problem.
Based on the API Limits:
```
Minute Limit: 60 calls in a rolling 60 second window
```
I will need to wait a long time until complete my report with >1k Invoices.

**Comment by MJMortimer** [comment]
@neeon-li the invoices endpoint supports paging, which will allow you to retrieve 100 invoices at time with line items included.

Something like this:
`xero.invoices.get({page: 1});`
Would get you the page 1 of all invoices including full line item details. 
Continue looping through incrementing page numbers until you receive an empty invoices array.

**Comment by neeon-li** [comment]
@MJMortimer Great ! Thank for this trick.
I really forget about it.
It works.
At least, this helps me to get ~6k invoices per minute.

**Comment by gslisrael** [comment]
Yes. @MJMortimer's solution is better than mine. I missed that in the API spec.

**Comment by philals** [comment]
Thanks @MJMortimer and @gslisrael
