### ISSUE TITLE
How can I create Invoice with my InvoiceID?

### ISSUE THREAD

**Issue by landrail8** [XeroAPI/xero-node#204]
All Invoices has created in our specific database with ID like `6a09f20a-8de6-11e1-b3e1-001617ec3f2a`. 

If I send JSON with my `ID = a0925a79-43ef-11e8-8156-da7279fdb1da`  I see this answer
`Invoices:
   [ { Type: 'ACCREC',
       InvoiceID: 'a0925a79-43ef-11e8-8156-da7279fdb1da',
       Payments: [],
       CreditNotes: [],
       Prepayments: [],
       Overpayments: [],
       **HasErrors: true**,
       IsDiscounted: false,
       Contact: [Object],
       DueDateString: '2018-04-19T07:28:05',
       DueDate: '/Date(1524122885000+0000)/',
       Status: 'AUTHORISED',
       LineItems: [Array],
       StatusAttributeString: 'ERROR',
       ValidationErrors: [Array] } ] }`

If I send JSON without my ID - I see good answer and the new Invoice added in XERO (with ID === `93508865-daca-41eb-acd7-fc5322a118bf`).

How can I create Invoice with my InvoiceID?

**Comment by philals** [comment]
Hi @landrail8 

Can you please show the value to ValidationErrors on the first call?

I don't think you can create an Invoice and specify an Id for it to have. I'm betting that your first call is failing (have a look at the `ValidationErrors` object on the response).

Please check the Invoice docs here: https://developer.xero.com/documentation/api/invoices

You can only do things listed in those docs.

**Comment by MJMortimer** [comment]
Yeah spot on @philals, you can't choose the InvoiceID when creating the invoice, it will only be generated for you on successful creation.

**Comment by landrail8** [comment]
@philals ValidationErrors is empty
 @MJMortimer ok, I'll work in this paradigm
many thanks

**Comment by philals** [comment]
Thanks for the question @landrail8 

Let us know if there anything else.
