### ISSUE TITLE
Is there a way to access History and Notes?

### ISSUE THREAD

**Issue by brucem1976** [XeroAPI/xero-node#205]
I am looking to use xero-node to get history and notes for specific entries: https://developer.xero.com/documentation/api/history-and-notes

Is there any way to do this?

**Comment by philals** [comment]
Hi @brucem1976 this endpoint was released recently. 

If you need it today - I recommend using the generic endpoint method (https://github.com/XeroAPI/xero-node/blob/c7aa9b48579d258d8447de72a65cf5186c365ffa/src/__integration_tests__/generic-endpoint.integration.tests.ts).

If you're keen you could implement the endpoint and send a PR. Happy to help with any pointers.

**Comment by brucem1976** [comment]
Thanks -  I don't know TypeScript, but am keen to help if I can, I'll check it out

**Comment by brucem1976** [comment]
@philals I'm sure I'm doing something silly - I've cloned the folder, and set up the integration tests with my Xero keys etc, but when I run npm test, I get rate limiting issues over and over:
`XeroError: Minute rate limit exceeded (please wait before retrying the xero api)
`
Anything I'm not setting up correctly that could cause this?

**Comment by brucem1976** [comment]
@philals thanks - GMT+2 (Cape Town, South Africa) - do you put 1 org in 1private-config, and the other in private-config?

I'm making good headway - how do I send the changed files to you for review? (sorry, supernoob!)

**Comment by philals** [comment]
Yes, one App for each config.

Nice - from here you will have to fork the repo, push your new code, and send a PR.

I quickly flicked though Youtube, and think this video hopefully will help: https://www.youtube.com/watch?v=_NrSWLQsDL4

Hope this helps.
Let me know how you get on.

**Comment by brucem1976** [comment]
@philals - thanks. I've just done the PR - very new for me, would love some constructive and honest feedback!

**Comment by philals** [comment]
Wicked! Thanks for that. Looking good from a quick glance. I'll try process it ASAP.

Thanks for the contribution.

**Comment by brucem1976** [comment]
Great. So npm test still fails - I see the tests assume you have certain documents in your Org, and fail if they don't exists (mine fails on overpayments and prepayments for this reason) - then there are some partner and callback tests that fail, and then after a while all the tests still start failing on rate limiting, even with 2 Private Apps?

**Comment by philals** [comment]
Weird. I think they might be a bit too specific - and require a NZ Demo Org. 

I'll pull down your branch and run em.

**Comment by philals** [comment]
Gulp... I think your extra tests have put us over the rate limit... 

Let's see what we can do about that. I might have to add have a third app,

**Comment by philals** [comment]
Nice work @brucem1976 

I merged and released your changed last night (NZ).

Thanks for the contribution.

Also have raised https://github.com/XeroAPI/xero-node/issues/207 about the rate limit issue.

**Comment by brucem1976** [comment]
Great, do you think it needs to be noted somewhere that the end to end
tests fail on some non-NZ demo companies?

**Comment by philals** [comment]
Hi @brucem1976 

I'm not 100% sure of the exact circumstances that they fail under.

It might just be ANY demo org they will pass for.

This is something that will need to be investigated.

**Comment by brucem1976** [comment]
@philals in the case of my demo org, they failed because:
 - I hadn't set up a partner app
 - There were no prepayments present
 - There were no overpayments present

`FAIL  src\__integration_tests__\partner-example-callbackUrl.tests.ts
  ● Partner Example Tests with callbackUrl › encountered a declaration exception
    Cannot find module '../xero-login.json' from 'integration.helpers.ts'`

`FAIL  src\__integration_tests__\practice.tests.ts
  ● Practice API Tests › encountered a declaration exception
    Cannot find module '../partner-config.json' from 'integration.helpers.ts'`

`FAIL  src\__integration_tests__\overpayments.integration.tests.ts
  ● /overpayments › get all
    expect(object)[.not].toHaveProperty(path)
    Expected object to be an object. Received:
      undefined: undefined`

`FAIL  src\__integration_tests__\prepayments.integration.tests.ts (6.611s)
  ● /prepayments › get all
    expect(received).toBeGreaterThan(expected)
    Expected value to be greater than:
      0
    Received:
      0`

**Comment by philals** [comment]
Thanks for the research.

I have added these notes to the readme.
