### ISSUE TITLE
Missing OAuth request

### ISSUE THREAD

**Issue by adamreisnz** [XeroAPI/xero-node#211]
Could you tell me under what circumstances one would receive a `Missing OAuth request` error when using this library?

I tried to search Xero's documentation but couldn't find anything meaningful, so I suspect it may be thrown by this package instead.

**Comment by philals** [comment]
Hi @adamreisnz 

I just did a quick search of the code and can't see this error.

Are you able to reproduce it in an empty repo?

**Comment by adamreisnz** [comment]
It's possible the error is being returned from Xero itself, but I don't understand why it would happen. I had all oAuth data in place, and if it wasn't the Xero node client must've thrown an error as well no?

**Comment by philals** [comment]
Hi,

Can you please give the code you are using to replicate this issue.

You're welcome to fork this repo: https://github.com/philals/xero-node-example-console-app

Or copy and past the examples in the README or this repo: https://github.com/XeroAPI/xero-node-samples

**Comment by adamreisnz** [comment]
I've found the culprit, turns out it was a part of our own app, sorry for the noise! 🤦‍♂️

**Comment by philals** [comment]
No worries. Have a nice day.

**Comment by adamreisnz** [comment]
Thanks you too!
