### ISSUE TITLE
PUT call failed with: 401 and exception without oauth_problem, oauth_problem_advice

### ISSUE THREAD

**Issue by gabrieljo** [XeroAPI/xero-node#214]
Hi there, 

I have issues with PUT call failed with: 401 error without oauth_problem and advice.
Can not guess what is the problem. I checked API config (consumer key, consumerSecret, privateKeyPath, userAgent). it is ok. is there any way to figure it out. 

I use :
 "xero-node": "^2.6.0",
"express": "^4.15.3",

the error:
Error: PUT call failed with: 401 and exception: ""
/app/node_modules/xero-node/lib/application.js:160:42
passBackControl (/app/node_modules/xero-node/lib/oauth/oauth.js:405:25)
IncomingMessage.<anonymous> (/app/node_modules/xero-node/lib/oauth/oauth.js:421:17)
emitNone (events.js:91:20)
IncomingMessage.emit (events.js:185:7)
endReadableNT (_stream_readable.js:974:12)
_combinedTickCallback (internal/process/next_tick.js:80:11)
process._tickCallback (internal/process/next_tick.js:104:9)

thanks

**Comment by philals** [comment]
Hi

I have created an issue template which should help us. Please follow these instructions: 

Hi, before posting an issue please try to replicate your bug in an empty repo and push it up to be available publicly.

Here are some repos that you can fork and attempt to replicate the issue:

- https://philals/xero-node-example-console-app
- Copy and paste the examples in the README or this repo

This will help us to diagnose your issue.

Any bugs/issues with the API are best directed to: https://developer.xero.com/community

Thanks

**Comment by philals** [comment]
Hi @gabrieljo I notice that you're using v2.

Do you mind upgrading to the latest version?

**Comment by gabrieljo** [comment]
Thanks guys,

I solved this problem it is little wired the solution is I just rebuild "Xero App" then the problem has been gone. 

I close this thanks again.

cheers
