### ISSUE TITLE
Support for Projects API

### ISSUE THREAD

**Issue by jamespwilson** [XeroAPI/xero-node#215]
Xero now supports Projects and the api (beta) documentation is found here https://developer.xero.com/documentation/projects/overview-projects

Thanks

**Comment by philals** [comment]
Thanks @jamespwilson 

I have marked this as a feature request. Feel free to send a PR (even one endpoint to start someone off). Let us know if you need any design help.

**Comment by SerKnight** [comment]
FYI Projects API support is available for this repo in our currently supported Authorization flow OAuth2.0 : https://github.com/XeroAPI/xero-node/blob/master/src/gen/api/projectApi.ts

Will have some guides coming out soon on the migration strategy from OAuth1.0a-2.0 as well!
