### ISSUE TITLE
Request:invoices.update example in documentation or example repo

### ISSUE THREAD

**Issue by schinns** [XeroAPI/xero-node#219]
Hello! I have just started using the xero-node wrapper, and the [documentation](https://xeroapi.github.io/xero-node/v3/classes/accountingapiclient.html#invoices) and [example repo](https://github.com/XeroAPI/xero-node-sample-app/blob/master/index.js) have been quite helpful. I have been able to successfully retrieve an invoice, create and invoice, but I am having trouble with updating an invoice. 

I wish that the documentation or the example repo had a example for `invoices.update`.

I only need to update the `AmountPaid` and `Status` of an existing invoice. Here is what I have:
```
             var result = await xero.invoices.get({InvoiceID: xeroInvoiceID});
              await xero.invoices.update({
                Type: 'ACCREC',
                InvoiceNumber: result.Invoices[0].InvoiceNumber,
                Contact: result.Invoices[0].Contact,
                InvoiceID: xeroInvoiceID,
                Status: 'PAID',
                AmountPaid: result.Invoices[0].AmountDue,
                LineItems: result.Invoices[0].LineItems
              });

```
I have confirmed that my get call is sucessful. But for some reason my update call doesn't seem to be working. I am not getting any error logged either. ¯\_(ツ)_/¯ 
I don't know exactly which properties are required (besides InvoiceID of course) in an update call. 
It would be so helpful if there was an example of `invoices.update`. Thank you!

**Comment by philals** [comment]
Hi @schinns Good idea. 

I'll add one soon (or let's get you up and running and then PR it).

As for your issue. Have you checked the API docs here: https://developer.xero.com/documentation/api/invoices

The SDK is only capable of what the API can do. Give that a go. 

There is also the API previewer for quick checks: https://app.xero.com

**Comment by philals** [comment]
Looks like we have no examples in here either: https://github.com/XeroAPI/xero-node/blob/755d5e0775afda749b089aa849490b1c5370ba6f/src/__integration_tests__/invoices.integration.tests.ts

Let's add one.

**Comment by schinns** [comment]
Hey @philals ! Thanks for your reply! Yes, the API docs is very nice, it's helped me understand how to use the SDK much better. I understand to update an invoice I should use a `POST` request and provide the InvoiceID. I have also tried using `invoices.create` and pass the InvoiceID in as one of the parameter, but to no avail. 

And yes! The invoices integration test file has been very helpful to look at as well, it would be even more helpful if it covered `invoices.update` as well. 

I have been trying to figure out how to update an invoice for a couple days now, I will give it another whirl soon. 

Thanks again for your help.

**Comment by philals** [comment]
Hi just closing to clear things up. Feel free to open a new one. Thanks.
