### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: XeroError: permission_denied 

### ISSUE THREAD

**Issue by Lincoln23** [XeroAPI/xero-node#220]
I am currently trying to authenticate with Xero, I am using Node.js and I am currently following the example provided (https://www.npmjs.com/package/xero-node) for a public application. I am getting issues with permissions currently
Here is config.json;
`{
  "appType": "public",
  "consumerKey": "key",
  "consumerSecret": "secret",
  "callbackUrl": null
}`

and main.js

```
const XeroClient = require('xero-node').AccountingAPIClient;
const config = require('./config.json');

(async () => {

  let xero = new XeroClient(config);

  // Create request token and get an authorisation URL
  const requestToken = await xero.oauth1Client.getRequestToken();
  console.log('Received Request Token:', requestToken);

  authUrl = xero.oauth1Client.buildAuthoriseUrl(requestToken);
  console.log('Authorisation URL:', authUrl);

  // Send the user to the Authorisation URL to authorize the connection

  // Once the user has authorised your app, swap Request token for Access token
  const oauth_verifier = **number**;
  const savedRequestToken = {
    oauth_token: requestToken.oauth_token,
    oauth_token_secret: requestToken.oauth_token_secret
  };
  console.log("This is where the error occurs");
  const accessToken = await xero.oauth1Client.swapRequestTokenforAccessToken(savedRequestToken, oauth_verifier);
  console.log('Received Access Token:', accessToken);

  // You should now store the access token securely for the user.

  // You can make API calls straight away
  const result = await xero.accounts.get();
  console.log('result:', result);

})(); 
```

However, I get the error of 

> UnhandledPromiseRejectionWarning: Error: XeroError: permission_denied (The consumer was denied access to this resource.)

Where am I going wrong?

Also is there a way to get the oauth_verifier number without having to go to the Authorisation URL and copy and paste the value into the variable oauth_verifer?

Thanks

**Comment by philals** [comment]
Hi, Thanks for making code that I can copy down.

Will check into this soon - in the mean time: The only way to get the verifier is via the copy/paste or use a callback URL on your server.

**Comment by Lincoln23** [comment]
@philals Thanks for quick response, I have solved that issue. However I have encountered another issue, do the oauth_token and oauth_token_secret only valid for one request? Since every time I rerun my server, it requires me to generate a new key

**Comment by Lincoln23** [comment]
@philals thanks for the help I have solved the issue
