### ISSUE TITLE
purchaseOrder update - V2

### ISSUE THREAD

**Issue by shierro** [XeroAPI/xero-node#222]
Hi folks, thanks for creating this awesome library!

On the sample script to update a purchase order on this link https://xeroapi.github.io/xero-node/v2/Purchase-Orders.html

```javascript
var purchaseOrderID = '39580864-26a9-40fd-840a-da4c61564476';

//Get the draft purchase order, update it, and save it.
currentApp.core.purchaseOrders.getPurchaseOrder(purchaseOrderID)
    .then(function(purchaseOrder) {

        purchaseOrder.Reference = 'Updated';

        purchaseOrder.save()
            .then(function(savedPurchaseOrder) {
                console.log(savedPurchaseOrder.entities[0].Reference); //'Updated'
            });
```

it seems that the library needs to do 2 API calls in order to update a PO?
On the [API documentation](https://developer.xero.com/documentation/api/purchase-orders#post)

it seems to me that we should be able to update a PO using 1 API call. 
This is a bit of an issue on our side because
1. There is no mechanism to bulk create POs
2. API rate limit is 5k & we have more than 5k POs

Am i missing something here or is there a way to update a PO using 1 API call only using this library?

Sorry to bother and thanks!

**Comment by philals** [comment]
Hi @shierro 

Yes that's correct. One is to get the PO and the other call is to update it.

This was a bit of a limitation of V2, and one of the reasons why we create V3. We did not believe that the libraries interface was as intuitive as it could have been.

Are you able to upgrade to V3?

**Comment by shierro** [comment]
Hey @philals thanks for the quick reply.

Ok I understand and it's good to know that this is addressed already in V3. We'll switch to V3 in the near future.
