### ISSUE TITLE
Invoice uploadAttachment returning 401 XeroError: signature_invalid (node-xero v3)

### ISSUE THREAD

**Issue by alastairayliffe** [XeroAPI/xero-node#225]
Hi,

I'm trying up upload an invoice to Xero, then save an attachment against this invoice.

I've dropped in a function below which is called at the point of obtaining the access token from Xero (lasting 30 mins). I've just dropped in a test invoice (const newInvoice), and then try to save a test attachment against it (const newAttachment).

I'm creating a XeroClient successfully using the config and access token and am able to post an invoice to Xero (invoices.create(newInvoice)). The invoice ID from Xero's response is added to an attachment object (const newAttachment) and then sent via invoices.attachments.uploadAttachment to Xero.

Xero comes back with a 401 error suggesting the signature is not valid -

"Error: XeroError: signature_invalid (Failed to validate signature)"

I had a look at the header info of this error (back from Xero) and signature in this response is set to expire exactly 1 hr before the current call and 1.5 hrs before current signature should expire (based on the standard 30 min expiry time). I'm unsure if this is relevant.

I'm most likely setting up the invoices.attachments.upload incorrectly. Apologies if this is the wrong forum to raise this.

Any help greatly appreciated! Love the integration!

Thanks,

`const XeroClient = require('xero-node').AccountingAPIClient;

const config = require('./config.json');

const xeroPostInvoices = (accessToken) => {
    const xero2 = new XeroClient(config, accessToken);
    let newInvoice = {
        Type: "ACCPAY",
        Contact: {
            Name: "test"
        },
        Date: '2018-06-20',
        DueDate: '2018-06-20',
        LineAmountTypes: "Inclusive",
        InvoiceNumber: 'test-01',
        LineItems: [{
            Description: 'test',
            Quantity: 1,
            UnitAmount: 1,
            AccountCode: 401,
        }],
    }

    xero2.invoices.create(newInvoice)
        .then(invoice => {
            const invoiceID = invoice.Invoices[0].InvoiceID;
            let newAttachment = {
                entityId: invoiceID,
                fileName: "test.pdf",
                includeOnline: true,
                pathToUpload: '/Users/alastairayliffe/Desktop/test.pdf',
                MimeType: "application/pdf"
            }
            return xero2.invoices.attachments.uploadAttachment(newAttachment)
        })
        .then(attachments => {
            //Attachment has been created
            console.log(myAttachment)
            return myAttachment = attachments.entities[0];
        })
        .catch(err => {
            console.log(err)
            return err
        })`

This is the full error message - 

`oauth_problem=signature_invalid&oauth_problem_advice=Failed%20to%20validate%20signature" headers:{cache-control:"max-age=0, no-cache, no-store”, connection:"close”, content-length:"87”, content-type:"text/html; charset=utf-8”, date:"Fri, 20 Jul 2018 10:16:25 GMT”, expires:"Fri, 20 Jul 2018 10:16:25 GMT”, pragma:"no-cache”,
strict-transport-security:"max-age=31536000”, www-authenticate:"OAuth Realm="10.144.114.235””, x-client-tls-ver:"tls1.2”, statusCode:401 message:"XeroError: signature_invalid (Failed to validate signature)" stack:"Error: XeroError: signature_invalid (Failed to validate signature)↵    at new XeroError (/Users/alastairayliffe/workspace/heyprestofinal/node_modules/xero-node/lib/XeroError.js:30:24)↵    at /Users/alastairayliffe/workspace/heyprestofinal/node_modules/xero-node/lib/internals/OAuth1HttpClient.js:259:36↵    at passBackControl (/Users/alastairayliffe/workspace/heyprestofinal/node_modules/oauth/lib/oauth.js:397:13)↵    at IncomingMessage.<anonymous> (/Users/alastairayliffe/workspace/heyprestofinal/node_modules/oauth/lib/oauth.js:409:9)↵    at emitNone (events.js:111:20)↵    at IncomingMessage.emit (events.js:208:7)↵    at endReadableNT (_stream_readable.js:1055:12)↵    at _combinedTickCallback (internal/process/next_tick.js:138:11)↵    at process._tickDomainCallback (internal/process/next_tick.js:218:9`

**Comment by philals** [comment]
Hi @alastairayliffe 

I have just ran the tests from my machine and they are passing. 

![image](https://user-images.githubusercontent.com/8849355/43033201-1f8c39f2-8d1a-11e8-88be-fa70353c1d1d.png)

Are you able to upload a empty repo that I can clone and replace with my keys? Please have the config inline (so basically just a index.js and package,json).

I'll clone it down and have a look. Thanks

**Comment by alastairayliffe** [comment]
hi @philals,

I'd really appreciate you taking a look!

I've replicated your demo on the node-xero-v2 library (updating for v3) using handlebars etc (see below) -

https://github.com/alastairayliffe/xero-node-v3-attachment-example

Config is included in the index file as requested (I've taken out my access codes).

This app successfully pushes an invoice to xero (which is great!), but then appears to fail with signature issues on uploading the attachment... It looks like Xero thinks the signature has expired (when it's just been created). If it's not something I've done wrong, I'm thinking it might something to do with the region of Xero the upload is using for the attachment, maybe Europe.. (Europe is 1hr in front the UK - where I'm based).

Thanks again for your help. Let me know if you'd prefer in another format.

Alastair

**Comment by alastairayliffe** [comment]
Hi @philals,

I've got the attachment upload to work now now... In all honesty, not sure how... I'll have a look at the differences tomorrow (my brain is fried tonight).

Was just letting you know to avoid wasting any more of your time!

Thanks again for this library. It's awesome.

**Comment by philals** [comment]
Hi @alastairayliffe I'll close this issue to clean things up. 👍 

Really keen for you to note your findings in the documentation. 

Thanks

**Comment by alastairayliffe** [comment]
Hi Phil, apologies about the delay. happy to do so.

What would be the best way to contribute? I can update the repository to
become a 'working app xero integration app'?... Or should is there a better
way?

Thanks,

**Comment by theteapot** [comment]
I came across this after encountering the same issue, turns out in my case not specifying the "mimeType" property in the uploadAttachment method was returning this error code.

**Comment by philals** [comment]
Thanks @theteapot.

I just checked. Looks like mimeType is required https://github.com/XeroAPI/xero-node/blob/00ea2a7d484701cc2475f6563907f6a923e9c376/src/AccountingAPI-models.ts#L5

So this confirms your statement.

Thanks for posting here for the next person.

**Comment by GfxKai** [comment]
I got this error because the `fileName` property contained a sneaky forward slash in one case. Seems obvious now but if you've ended up here and are scratching your head, remember to sanitise this parameter if you're dealing with dynamically named attachments!
