### ISSUE TITLE
Ability to create multiple Invoices in one API call

### ISSUE THREAD

**Issue by c-f-allen** [XeroAPI/xero-node#227]
Hi,

I've recently started using xero-node v3 having previously used v2 in another project.

In v2 it was possible to format/generate multiple invoices and then send them as a batch. As far as I can see, this functionality is not available using v3 standard functions (client.invoices.create()).

Am I missing something? Is there a way to pass an array to invoices.create()? 

I've also attempted using the oauth1Client to make a generic call to achieve this but am consistently receiving 401 signature_invalid (Failed to validate signature) and it looks like oauth1Client.post is expecting an object for its body parameter anyways.

I've attempted the calls GET '/api.xro/2.0/Organisations' and POST '/api.xro/2.0/Invoices' and both give the same 401 response but are fine when using the standard functions 'client.organisations.get()' and 'client.invoices.create()'. Is there any authentication or extra params I need to pass into the generic oauth1Client.get() and oauth1Client.post() to sort the signature?

Any help getting this sorted would be really appreciated. Thanks.

**Comment by c-f-allen** [comment]
Not sure if this is relevant to the 401 signature invalid issue but the www-authenticate header is different for the standard function call vs the generic oauth1Client call:

Standard function client.invoices.create(): 
'www-authenticate': 'OAuth Realm="api.xero.com"'
'xero-cell': 'favorit'

Generic function POST '/api.xro/2.0/Invoices':
'www-authenticate': 'OAuth Realm="10.144.138.98"'
NO xero-cell header.

**Comment by philals** [comment]
Hi @c-f-allen sounds like you might not have things set up correctly.

Can you post an empty repo showing what you are doing, I'll clone it down and have a look?

Have you seen the examples in the ReadeME?

**Comment by philals** [comment]
Here are the tests around creating multiple invoices: https://github.com/XeroAPI/xero-node/blob/master/src/__integration_tests__/invoices.integration.tests.ts#L32

**Comment by c-f-allen** [comment]
Hi @philals thanks for linking that test file. 

You're right, I was passing in my invoices as an array rather than an object with the Invoices property.

I've matched it to the structure from the tests and its working fine now.

Can't believe I missed it! 

Thanks for your reply and help.
