### ISSUE TITLE
(xero-node v2) Unable to download receipt attachments 404 error

### ISSUE THREAD

**Issue by mervintankw** [XeroAPI/xero-node#231]
Hi there.

The company I worked for is using xero-node v2 SDK to consume Xero's API. 

The problem here is with the downloading of receipt attachments. Previously with the same code we are able to download receipt attachments, but since 20 Aug 2018, downloading of receipt attachments returned with Error 404.

The following is the code that we have been using for a couple of months. Since 20 Aug 2018, the requests always end up with the error "createUpdateAttachment: caught error during data writing".

`//Create a local writestream
                    var wstream = fs.createWriteStream(tempFile, { encoding: 'binary' });

                    //Data has been written successfully
                    wstream.on('finish', function() {
                        fs.readFile(tempFile, function (err, fsData) {
                            // trigger upload to S3 function
                            uploadToS3(req, {
                                s3Path: s3Path,
                                contentType: data.mime_type,
                                buffer: fsData
                            }, function (status, url) {
                                data.url = '/' + data.url;
                                fs.unlink(tempFile, function(err) {});
                                callback();
                            });
                        });
                    });

                    wstream.on('error', function(err) {
                        logErr(req, 'createUpdateAttachment: download data writing failed', [err]);
                        wstream.close();
                    });

                    attachment.getContent(wstream)
                    .catch(function(err) {
                        logErr(req, 'createUpdateAttachment: caught error during data writing', [err]);
                    });`

Just wondering if anyone here is aware of this issue?

Update:
The following is the error I got from our elastic beanstalk log.

`{ Error: GET call failed with: 404
at self.oa.get.stream (/var/app/current/node_modules/xero-node/lib/application.js:455:36)
at passBackControl (/var/app/current/node_modules/xero-node/lib/oauth/oauth.js:405:25)
at IncomingMessage.<anonymous> (/var/app/current/node_modules/xero-node/lib/oauth/oauth.js:421:17)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9) statusCode: 404 }`

**Comment by philals** [comment]
Thanks. 

Just clarifying. Was this working on 19th of Aug?

**Comment by mervintankw** [comment]
@philals yes it was working on 19 Aug.

**Comment by mervintankw** [comment]
In case anyone else is facing this issue, the Attachment.Url from Xero's attachment API is not working at the moment, so you will have to reformat the Attachment.Url in order to be able to download the attachment.

Incorrect Attachment.Url:
https://api-accounting.ringum.xero.com/1.0/Invoices/[invoice_id]/Attachments/[file_name]
 
Correct Attachment.Url (should be):
https://api.xero.com/api.xro/2.0/invoices/[invoice_id]/attachments/[file_name]
Note: correct Attachment.Url format referenced from https://developer.xero.com/documentation/api/attachments#GET.
