### ISSUE TITLE
oauth_problem=consumer_key_unknown&oauth_problem_advice=Unknown Consumer (Realm: , Key: )

### ISSUE THREAD

**Issue by achabill** [XeroAPI/xero-node#235]
I have the following setup

```
const XeroClient = require('xero-node').AccountingAPIClient;
const xeroConfig = {
    "appType": "public",
    "consumerKey": "VW**************************BY",
    "consumerSecret": "QQ**************************JE",
    "callbackUrl": "https://{no-domain-currently-set}"
}
```

Then for request token

```
let xero = new XeroClient(xeroConfig);
// Create request token and get an authorisation URL
xero.oauth1Client.getRequestToken().then(requestToken => {
    console.log('Received Request Token:', requestToken);
     ...
}
```

I get error: `oauth_problem=consumer_key_unknown&oauth_problem_advice=Unknown Consumer (Realm: , Key: )`

My keys are correct and I'm calling this from ReactJS.

**Comment by philals** [comment]
Hi @achabill 

If you're using a callbackUrl please make sure it's set as a callback domain for your App in https://developer.xero.com/myapps

With out all manner of hackery, unfortunately, you cannot call the API from a Users browser. At the moment, as we only support OAuth1.0a, you will need a backend. 

OAuth 2.0 is coming which will enable that.

Hope this helps.

**Comment by achabill** [comment]
Thanks @philals
