### ISSUE TITLE
Enhancement: Allow upload of attachment from existing stream

### ISSUE THREAD

**Issue by x2764tech** [XeroAPI/xero-node#236]
I have a little helper script that gets unreconciled bank transactions (from the bank statement report), and uses some rules to match emails in my inbox, gets the PDF attachments and uploads them as new invoice attachments. It saves me around 1/2 day of effort every month (as a one-man-band, this is quite a saving).

As I don't really want to save the pdf files to disk, is there anyway to enable the saving of attachments from an existing stream? I currently create a stream from a byte array like this:

```javascript
/// buffer is byte array from message
const stream = require('stream');
const bufferStream = new stream.PassThrough();
bufferStream.end(buffer);
```

**Comment by philals** [comment]
Hi @x2764tech Looks like @Titannet has you covered

https://github.com/XeroAPI/xero-node/pull/258
