### ISSUE TITLE
Feature Request: Allow for the creation of Notes on supported types

### ISSUE THREAD

**Issue by robbishop** [XeroAPI/xero-node#237]
I find the ability to add Notes to Xero documents very useful, especially when using the API and I need to reference the origin of the data, such as a row in a spreadsheet. There already is support for getting Notes via the [history endpoint](https://developer.xero.com/documentation/api/history-and-notes) on most document types so could we have create too please.

**Comment by iamam34** [comment]
This feature was released in v3.1.0 bf753fdfa16189
```JS
const response = await xero.invoices.history.create({
	InvoiceID: invoiceId,
	HistoryNote: {
		Details: 'Hello from robbishop'
	}
});
```
