### ISSUE TITLE
Credit note allocation's 'AppliedAmount' property is wrong

### ISSUE THREAD

**Issue by daniel-van-niekerk** [XeroAPI/xero-node#239]
The credit note's allocation object expected a property called 'AppliedAmount'. In the Xero Api docs it is also listed as 'AppliedAmount' but their example uses 'Amount' instead. Using 'AppliedAmount' causes a validation error about amount being 0. Using the 'Amount' property works.

This code does not work:
`await xero.creditNotes.allocations.create({AppliedAmount: amount, Invoice: invoice}, {CreditNoteID: creditNoteId});`

This code works:
`await xero.creditNotes.allocations.create(<any>{Amount: amount, Invoice: invoice}, {CreditNoteID: creditNoteId});`

**Comment by philals** [comment]
Thanks @daniel-van-niekerk. Good catch.

I have published the change.

PS The property is different between JSON and XML.
