### ISSUE TITLE
Invoice line item with Code & Description on Web UI does not show Code when queried via API.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [XeroAPI/xero-node#243]
If an invoice line item has only the following entered in then Xero API seems to treat it as a description only line item and does not include the ItemCode despite it being set in the Web UI.
  Code, Description, Blank Qty, Blank Unit Price

I added an Item to a draft invoice with a code and description and blank for everything else.
When querying the draft invoice via the API I see the ItemCode is not set.

Setting a qty of 1 and a Unit Price of 0 seemed to resolve this.

As the API gives me back different data to what I am seeing on screen in the web browser on Xero.
Is this the sort of thing that should be posted to the developer community?
https://developer.xero.com/community

Or is it only specific to xero-node, have not tried any other API libraries/access but I should think that they all get the same data back.

**Comment by philals** [comment]
Hi @LiamKarlMitchell 

Thanks for the issue. It's known issue in the API (not Node specific). A fix is in the backlog but not a priority in the near future.

Best to workaround by providing a quantity for now.

Thanks

**Comment by LiamKarlMitchell** [comment]
Will do thanks.
