### ISSUE TITLE
userAgent property not read from config

### ISSUE THREAD

**Issue by nyangate** [XeroAPI/xero-node#244]
When I check the User Agent on under "My Apps" history I get 

NodeJS-XeroAPIClient.3.0.13.TIHKWFI8HCTGC7JRXJ7KRKHM3E5KGZ

 yet am specifying the userAgent parameter on the config file:

`{`
  "appType": "public",
  "consumerKey": "...",
  "consumerSecret": "...",
  "callbackUrl": ".....",
  "userAgent": "Bambapos (PUBLIC) Xero Integration"
`}`

I noticed the sample app does not include the `userAgent,`. How can I set this?
My aim is to register my app as a partner application which requires a user-agent to be specified.
Kindly assist.

**Comment by philals** [comment]
Hi @nyangate 

Looks like we missed this requirement. 

Please continue with your application, also leave that bit of config in there. I'll get a fix when I have a spare moment - so you should get the update for free in the next release.

Please point your friendly developer evangelist to this issue it they notice the lack of App Name.

**Comment by jwbaldry** [comment]
I'm in the process of testing this and about to submit a PR to read the userAgent from the config file and pass through to the oauthConfig object.  It came up as part of our Xero app certification requirements.

**Comment by philals** [comment]
Hi.

Thanks again for letting us know of this issue.

I have pushed a new release with builds off #245 by adding a test and setting the agent correctly.

Thanks again.

**Comment by nyangate** [comment]
Thank you for the quick assistance.
