### ISSUE TITLE
Unhandled error - token_rejected

### ISSUE THREAD

**Issue by radvansky-tomas** [XeroAPI/xero-node#248]
Correct behaviour:
reject promise should be triggered with corresponding xero error

Code to replicate:

```
return new Promise(function(resolve, reject) {
    let xero = new XeroClient(environment.xeroConfig);
    xero.oauth1Client
      .swapRequestTokenforAccessToken(data.requestToken, data.code)
      .then(function(accessToken) {
        console.log("authXero", accessToken);
        resolve(accessToken);
      })
      .catch(function(err) {
        reject(err);
      });
  });
```

```
Unhandled error { Error: XeroError: token_rejected (Token EBUGVZOXAMTKEJZAU4G1WC39HPXJJG does not match an expected REQUEST token)
    at XeroError.Error (native)
    at new XeroError (/user_code/node_modules/xero-node/lib/XeroError.js:30:24)
    at /user_code/node_modules/xero-node/lib/internals/OAuth1HttpClient.js:93:57
    at /user_code/node_modules/xero-node/node_modules/oauth/lib/oauth.js:465:22
    at passBackControl (/user_code/node_modules/xero-node/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/user_code/node_modules/xero-node/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
  statusCode: 401,
  data: 'oauth_problem=token_rejected&oauth_problem_advice=Token%20EBUGVZOXAMTKEJZAU4G1WC39HPXJJG%20does%20not%20match%20an%20expected%20REQUEST%20token',
  headers: null }
```

**Comment by RettBehrens** [comment]
A quick note on why we’re closing this issue:

With the release of version 4.x of the Xero-Node SDK in December of 2019, we delivered a complete overhaul of the SDK. 

We moved from writing our SDKs by hand to generating our SDKs using our [Xero-OpenAPI](https://github.com/XeroAPI/Xero-OpenAPI) specs. By utilizing Xero-OpenAPI specs to generate code we’ve improved the developer experience of maintaining the SDK and improved the accessibility for our developer community to contribute via pull requests to the Xero-OpenAPI specs. 

We also built our new SDKs to use the industry standard OAuth2 in preparation for our March 2021 deprecation of OAuth1. For more details, see our [blog post on our decision to move to OAuth2](https://devblog.xero.com/an-update-on-why-we-are-saying-goodbye-oauth-1-0a-hello-oauth-2-0-6a839230908f). 

Version 3.x using Oauth1 and version 4.x using OAuth2 do not share any code as we now generate our SDKS. Going forward we’re focusing on building, maintaining and improving our generated SDKs but you are welcome to fork the [‘oauth1’ branch](https://github.com/XeroAPI/xero-node/tree/oauth1) and apply changes if you wish to implement something for your integration.
