### ISSUE TITLE
savePDF should reject if folder does not exists

### ISSUE THREAD

**Issue by ajouve** [XeroAPI/xero-node#250]
Hi there,

I am using the method `xero.invoices.savePDF`, if the `savePath` does not exists I have `Error: ENOENT: no such file or directory, open` it should be return by a promise reject

**Comment by philals** [comment]
Hi @ajouve Mind sending a PR for this?

**Comment by sapinder** [comment]
Is there a way to get the pdf as arraybuffer? Actually my requirement is to provide a pdf to web client without saving this on my node server?

**Comment by ajouve** [comment]
@sapinder 👍 Would be great

**Comment by iamam34** [comment]
closing as duplicate of #261
