### ISSUE TITLE
Incorrect response type for onlineInvoice

### ISSUE THREAD

**Issue by cobermeier-affinipay** [XeroAPI/xero-node#256]
In AccountingApiClient.d.ts, onlineInvoice (line 245) is stated as:

`        onlineInvoice: {
            get: (args?: {
                InvoiceID: string;
            }) => Promise<string>;
        };
`

The return type upon call is not a string but looks to conform to the other *Response objects and API expectation:

`{
  "Id": "<removed>",
  "Status": "OK",
  "ProviderName": "<removed>",
  "DateTimeUTC": "/Date(1554415691762)/",
  "OnlineInvoices": [
    {
      "OnlineInvoiceUrl": "<removed>"
    }
  ]
}`

**Comment by philals** [comment]
Thanks for noticing. 

I think online invoices was a new endpoint even we wrote this. 

Mind sending a PR with your changes? I'll review against the docs. 

Thanks for your input
