### ISSUE TITLE
Multiple where filters

### ISSUE THREAD

**Issue by huzz456** [XeroAPI/xero-node#260]
Hi

What is the proper syntax for getting a bank transaction with multiple 'where' filters? The way I have it only recognises the last 'where' filter but not the first one. I've tried several different approaches and combinations with no luck, feel like I'm missing something obvious?! (The 'If-Modified-Since' works fine)

```
const result = await xero.bankTransactions.get({"If-Modified-Since" : '2018-05-12T00:00:00', Where : 'Reference == "Sunday - Spend"', Where : 'Status == "DELETED"'});
console.log(result.BankTransactions);
```

**Comment by iamam34** [comment]
Looks like you've figured it out. For anyone else with a similar issue: you can pass multiple conditions in the Where clause like `Where : 'Reference == "Sunday - Spend" && Status == "DELETED"'`. More examples at https://developer.xero.com/documentation/api/requests-and-responses.
