### ISSUE TITLE
Pagination option

### ISSUE THREAD

**Issue by yogeshwar607** [XeroAPI/xero-node#270]
For invoice.get , only page is available as option , any reference for limit & skip for pagination part

as of now only {page:1} is available in option

**Comment by stansv** [comment]
```
Paging invoices (recommended)
To utilise paging, append a page parameter to the URL e.g. ?page=1. If there are 100 records in the response you will need to check if there is any more data by fetching the next page e.g ?page=2 and continuing this process until no more results are returned. 

By using paging all the line item details for each invoice are returned which may avoid the need to retrieve each individual invoice.
```

(TL/DR: there's no dedicated limit option, it's always 100 if you pass page and no upper limit otherwise)

https://developer.xero.com/documentation/api/invoices

**Comment by MrNavneetChauhan** [comment]
how to get all items, in similar way, I have tried to put page query, but it return same data even on different page numbers.
