### ISSUE TITLE
Is there any documenation on AgedReceivablesByContact for xero-node?

### ISSUE THREAD

**Issue by leotheloser** [XeroAPI/xero-node#271]
I'm using the xero-node library and attempting to get Aged Receivables By Contact. I cannot find any documentation on doing so as it appears that there is only one accepted argument: ReportID. Unless I am missing something.

```
xero.reports.get({
  ReportID: "AgedReceiveablesByContact",
  ContactID: "contactid" // <- something like this would be great
})
```

Thanks

**Comment by alexcollier** [comment]
The SDK has the following which you are using. this method clearly shows that reports takes arguments.  
_this.reports = {
            get: function (args) { return __awaiter(_this, void 0, void 0, function () {
                var endpoint, reportId;
                return __generator(this, function (_a) {
                    endpoint = 'reports';
                    if (args) {
                        reportId = args.ReportID;
                        delete args.ReportID; // remove from querystring
                        endpoint = endpoint + '/' + reportId + utils_1.generateQueryString(args);
                    }
                    return [2 /*return*/, this.oauth1Client.get(endpoint)];
                });
            }); }

so if you use as per the documentation https://developer.xero.com/documentation/api/reports#AgedReceivablesByContact
let = {
           ReportID : overriding_ReportID,
           contactID : overriding_contactID,
}
xero.reports.get(options);

I believe it might be the fact you are parsing in "ContactID" rather then "contactID"

**Comment by leotheloser** [comment]
Thanks @alexcollier I'll test it now, I was sure I was following this correctly. Thanks.

**Comment by leotheloser** [comment]
> The SDK has the following which you are using. this method clearly shows that reports takes arguments.
> _this.reports = {
> get: function (args) { return __awaiter(_this, void 0, void 0, function () {
> var endpoint, reportId;
> return __generator(this, function (_a) {
> endpoint = 'reports';
> if (args) {
> reportId = args.ReportID;
> delete args.ReportID; // remove from querystring
> endpoint = endpoint + '/' + reportId + utils_1.generateQueryString(args);
> }
> return [2 /_return_/, this.oauth1Client.get(endpoint)];
> });
> }); }
> 
> so if you use as per the documentation https://developer.xero.com/documentation/api/reports#AgedReceivablesByContact
> let = {
> ReportID : your_ReportID,
> contactID : your_contactID
> }
> xero.reports.get(options);
> 
> I believe it might be the fact you are passing in "ContactID" rather then "contactID"

Yeap thanks!
