### ISSUE TITLE
OAuth 2.0 (Beta)

### ISSUE THREAD

**Issue by ClintDavis** [XeroAPI/xero-node#280]
The OAuth2.0 beta is now available to developers building new integrations. Our implementation supports the standard authorization code grant type and you can find the details of how it works:

https://developer.xero.com/documentation/oauth2/auth-flow

**Comment by jamesrusso** [comment]
Looking forward to support for this in xero-node.

**Comment by SidneyAllen** [comment]
We are working on updating xero-node to support OAuth 2.0. 

Appreciate your patience as this isn't a small update but a complete rewrite of "xero-node" and other SDKs.  We have moved to auto-generate the models and Xero client using OpenAPI spec 3.0. This along with moving from oAuth 1.0a to 2.0 will result in a major update to this library.

We will update this thread when a beta version is ready for release.

**Comment by ezetaraborelli** [comment]
Hi there!

First of all, thank you for your work on this library!! I'm really glad to know that an update with oAuth2.0 is on its way! Do you have an ETA? I'm looking forward to ditching the oAuth1.0 apps ASAP :)

**Comment by SidneyAllen** [comment]
Hi @ezetaraborelli  @ClintDavis @jamesrusso 

Thanks for your patience - we have an alpha release of the xero-node SDK.
https://www.npmjs.com/package/xero-node/v/4.0.0-alpha.3

I want to set expectations around version 4.x.  All SDKs created and supported by Xero going forward will be built off our OpenAPI specs.  We see a lot of benefits to having more consistent support for multiple languages with this approach, but I want to acknowledge that this is a breaking change as methods, models (and of course authentication) has changed is small are large ways.

It's still early days, so appreciate your feedback, support and understanding as we make this transition.

**Comment by thehappycoder** [comment]
```

October 2019Hello OAuth 2.0, goodbye OAuth 1.0a | October 2019Hello OAuth 2.0, goodbye OAuth 1.0a | October 2019 | Hello OAuth 2.0, goodbye OAuth 1.0a
-- | -- | -- | --
October 2019Hello OAuth 2.0, goodbye OAuth 1.0a | October 2019 | Hello OAuth 2.0, goodbye OAuth 1.0a
October 2019
Hello OAuth 2.0, goodbye OAuth 1.0a
```

**Comment by thehappycoder** [comment]
@SidneyAllen I think it's too short notice. How can you expect us to migrate to OAuth 2.0 if this node library is still in Alpha? I think developers should still have an option to create OAuth 1.0a app registrations until this node library v4 is stable.

**Comment by SidneyAllen** [comment]
Hi @thehappycoder 

We will continue to enhance our SDKs over the next few weeks and will be ready for developers to use in anger by end of November. We welcome your continued feedback as we progress! 😄

**Comment by ezetaraborelli** [comment]
Hi @SidneyAllen! 

Is the node SDK ready to be used on prod now? I've just finished other tasks I had, so I'd like to tackle this upgrade now

**Comment by SidneyAllen** [comment]
We've removed the alpha/beta label, please see version 4.x for OAuth 2.0 support.

Any feedback - please submit an issue so we can track evaluate them.
