### ISSUE TITLE
ContactNumber has been removed from AccountingAPI-models.ts

### ISSUE THREAD

**Issue by tvajda** [XeroAPI/xero-node#283]
The ContactNumber API field disappeared in the latest release as it was removed by a merge commit https://github.com/XeroAPI/xero-node/commit/3035ce1a0814e4bb079941cf4a97eec1db3e9fd1

**Comment by iamam34** [comment]
Good catch, many apologies for the faulty merge! Fixed in https://github.com/XeroAPI/xero-node/commit/35a0a790e74d5f05772af47f9e2585a179a7ec5e, I'll try to do another release this week.

**Comment by iamam34** [comment]
Fixed in v3.1.1. Thanks again!

**Comment by tvajda** [comment]
No problem, thanks for the fix
