### ISSUE TITLE
General 500 server error when creating invoice with invalid ContactID GUID

### ISSUE THREAD

**Issue by PaulKlein** [XeroAPI/xero-node#285]
**SDK you're using (please complete the following information):**
 - Version 3.1.1

**Describe the bug**
If I try to create an invoice with an invalid GUID for the contact, I get back a general 500 error instead of a validation error explaining what the problem is.

**To Reproduce**
Use the following code:
```
try {
        const result = await xero.invoices.create({
            Invoices: [
                {
                    "Type": "ACCREC",
                    "Contact": {
                        "ContactID": "SOME-INVALID-DATA"
                    },
                    "LineItems": [
                        {
                            "Quantity": 1,
                            "LineAmount": 10,
                            "Description": "Line Item"
                        }],
                }
            ]
        });
        console.log(JSON.stringify(result));
    } catch (e) {
        console.log(e);
    }
```

Running this code throws an error containing a general 500 error:

```
XeroError: statusCode=500 data=<ApiException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ErrorNumber>500</ErrorNumber>
  <Type>UnknownErrorException</Type>
  <Message>An error occurred in Xero. Please contact api@xero.com. Also check the API Status page https://status.developer.xero.com/ for current service status.</Message>
</ApiException>
```

If I change the ContactID GUID to a valid ID, the invoice is created successfully.

**Expected behavior**
In the API Previewer, an invalid GUID is reported as a specific failure, which I expected to see in the library as well.

API Previewer result:
```
<ApiException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ErrorNumber>14</ErrorNumber>
  <Type>PostDataInvalidException</Type>
  <Message>Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).</Message>
</ApiException>
```

Thanks for any help here.

**Comment by walmon** [comment]
Exactly what happened to me. No details at all. Thankfully I searched for the generic error on this repo and found this issue.

**Comment by SerKnight** [comment]
Thanks for the update ya'll. I believe this is an API level inconsistency in the GUID validation. I will validate and report direct back to API team. Closing for now as its not an SDK level issue but helpful to have for others who might encounter it before it gets prioritized to be fixed.
