### ISSUE TITLE
Can't make post request on oauth2

### ISSUE THREAD

**Issue by jakeleventhal** [XeroAPI/xero-node#286]
**SDK you're using (please complete the following information):**
I'm using OAuth 2 so I'm not actually using the client but am having trouble creating an invoice using the request library (as is done in the examples provided)

**Describe the bug**
The API says "No data has been processed for this endpoint. This endpoint is expecting Invoice data to be specified int he request body"

**To Reproduce**
Run the following code (with valid tenant id, invoice form, and accesstoken:
```javascript
export const sendXeroInvoice = async (accessToken, tenantId) => {
  const invoiceRequestsOptions = {
    auth: {
      bearer: accessToken
    },
    form: [invoice],
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'xero-tenant-id': tenantId
    },
    url: 'https://api.xero.com/api.xro/2.0/Invoices'
  };

  await request.put(invoiceRequestsOptions, (err, res, body) => {
    console.log('body', JSON.stringify(body));
  });
};
```

**Expected behavior**
Xero Invoice is successfully posted

**Comment by SidneyAllen** [comment]
Hi @jakeleventhal 

Thanks for your question.  This question isn't specific the xero-node sdk so I'd consider it off topic for github issues.

Looking at the error, it mentions expecting invoice data to be passed in the body.  I'd refer you to the API documentation for en example fo the properties you should pass in the body when creating an invoice.

https://developer.xero.com/documentation/api/invoices#post

For more questions about using rolling your own OAuth 2.0 solutions without the xero-node sdk, I'd recommend Stackoverflow as a great place to find skilled Node developers who can assist.

Thanks!
