### ISSUE TITLE
typedoc is specified as dependency

### ISSUE THREAD

**Issue by trsdln** [XeroAPI/xero-node#289]
This causes package manager to install obsolete dependencies while installing `xero-node`. Not sure this is intended behavior. Would be nice to move it `devDependencies`. Thanks in advance.

**Comment by SerKnight** [comment]
ref: https://github.com/XeroAPI/xero-node/issues/319

typedoc no longer in dependencies

{
    "name": "xero-node",
    "version": "2.0.0",
    "description": "Xero NodeJS OAuth 2.0 client for xero-node",
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "author": "Xero Platform Team",
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "git://github.com/XeroAPI/xero-node.git"
    },
    "scripts": {
        "build": "tsc",
        "test": "jest"
    },
    "devDependencies": {
        "@types/jest": "^24.0.23",
        "@types/node": "^12.12.5",
        "@types/request": "^2.48.3",
        "jest": "^24.9.0",
        "open": "^6.4.0",
        "prompt": "^1.0.0",
        "ts-jest": "^24.1.0",
        "typescript": "^3.7.2"
    },
    "dependencies": {
        "openid-client": "^3.8.3",
        "request": "^2.88.0"
    }
}
