### ISSUE TITLE
Line Items Tracking not updates

### ISSUE THREAD

**Issue by ddtch** [XeroAPI/xero-node#293]
Hi, I'm trying to update Line Items tracking options in my invoice. And everything seems ok, but tracking info doesn't updates. 

I'm using `node-xero` to do that. So I do next

```
// invoice listItems

...
"LineItems": [
        {
          "ItemCode": "HB01",
          "Description": "Product name",
          "UnitAmount": 3139.00,
          "TaxType": "TAX008",
          "TaxAmount": 298.00,
          "LineAmount": 3139.00,
          "AccountCode": "200",
          "Tracking": [
            {
              "Name": "Location (State)",
              "Option": "California",
              "TrackingCategoryID": "id",
              "TrackingOptionID": "7gf"
            }
          ],
          "Quantity": 1.0000,
          "LineItemID": "f7a",
          "ValidationErrors": []
        },
        {
          "Description": "Shipping Charge",
          "UnitAmount": 245.00,
          "TaxType": "NONE",
          "TaxAmount": 0.00,
          "LineAmount": 245.00,
          "AccountCode": "220",
          "Tracking": [],
          "Quantity": 1.0000,
          "LineItemID": "ee0",
          "ValidationErrors": []
        }
      ],
... 

```

after I receive invoice I'm truing to update it.

```
const updateLocations = async (invoice, countryCode) => {
  const trackObject = {
    "Name": "Location (State)",
    "Option": "Texas", // for example lets just hard code this state name
  };
  const items = invoice.LineItems.map((el, idx) => {
    el.Tracking = [trackObject];
    return el;
  });

  const dataToSend = {
    "Type": invoice.Type,
    "Contact": {
      "ContactID": invoice.Contact.ContactID,
    },
    "LineItems": items,
  };

   await xero.invoices.update(dataToSend)
     .then(resp => {
       console.log('Updated Successfully')
     })
     .catch(err => {
       console.log('Update error');
       console.error(err);
     });
};
```
after executing I see Updated Successfully message but when looking this invoice in dashboard I see that changes doesn't applied. Any ideas?

**Comment by RettBehrens** [comment]
A quick note on why we’re closing this issue:

With the release of version 4.x of the Xero-Node SDK in December of 2019, we delivered a complete overhaul of the SDK. 

We moved from writing our SDKs by hand to generating our SDKs using our [Xero-OpenAPI](https://github.com/XeroAPI/Xero-OpenAPI) specs. By utilizing Xero-OpenAPI specs to generate code we’ve improved the developer experience of maintaining the SDK and improved the accessibility for our developer community to contribute via pull requests to the Xero-OpenAPI specs. 

We also built our new SDKs to use the industry standard OAuth2 in preparation for our March 2021 deprecation of OAuth1. For more details, see our [blog post on our decision to move to OAuth2](https://devblog.xero.com/an-update-on-why-we-are-saying-goodbye-oauth-1-0a-hello-oauth-2-0-6a839230908f). 

Version 3.x using Oauth1 and version 4.x using OAuth2 do not share any code as we now generate our SDKS. Going forward we’re focusing on building, maintaining and improving our generated SDKs but you are welcome to fork the [‘oauth1’ branch](https://github.com/XeroAPI/xero-node/tree/oauth1) and apply changes if you wish to implement something for your integration.
