### ISSUE TITLE
Projects API support in 4.x

### ISSUE THREAD

**Issue by thehappycoder** [XeroAPI/xero-node#300]
We must have it yesterday :)

Any ETA?

**Comment by SidneyAllen** [comment]
Hi @thehappycoder 

No ETA, but we has started working on the OpenAPI spec for projects API endpoints.  All new SDKs are built of our OAS.

Will post an update once we are further along.

**Comment by SidneyAllen** [comment]
@SerKnight - the OAS for Projects and is ready for you :-)

**Comment by SerKnight** [comment]
Hi @thehappycoder - Projects API support is now in xero-node package - please refer to the sample app to get up to speed quickly on the new endpoints: https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L2041
