### ISSUE TITLE
Incorrect query paramaters for Reports/TrialBalance

### ISSUE THREAD

**Issue by tanjacky** [XeroAPI/xero-node#301]
**Version**
 - Version 3.0.21
**Describe the bug**
[AccountingAPIClient.reports.get()](https://github.com/XeroAPI/xero-node/blob/v3.0.21/src/AccountingAPIClient.ts#L927) is documented with incorrect date parameters.
`
get: async (args?: { ReportID: string, toDate?: string, fromDate?: string, where?: string }): Promise<ReportsResponse>
`
API does not respect `toDate` and `fromDate`, but does respect `date`.

**To Reproduce**
Tried the following
```
const AccountingAPIClient = require('xero-node').AccountingAPIClient
const { Reports } = await AccountingAPIClient.reports.get({
  ReportID: 'TrialBalance',
  toDate: '2018-12-01'
  fromDate: '2018-12-15',
})
```
and received (snipped of response JSON):
```
...
    ReportTitles:
     [ 'Trial Balance',
       'My Demo Company',
       'As at 3 December 2019' ], // this is todays date
...
```

But when I do the following:
```
const AccountingAPIClient = require('xero-node').AccountingAPIClient
const { Reports } = await AccountingAPIClient.reports.get({
  ReportID: 'TrialBalance',
  date: '2018-12-31'
})
```
I get:
```
...
    ReportTitles:
     [ 'Trial Balance',
       'My Demo Company',
       'As at 31 December 2018' ],
...
```

**Expected behavior**
`AccountingAPIClient.reports.get()` should use be documented with `date` instead of `toDate` and `fromDate`.

**Comment by SerKnight** [comment]
^4.5.2 supports this report with correct docs. Thank you for reporting. 

API Documentation
> https://xeroapi.github.io/xero-node/v4/accounting/index.html#api-Accounting-getReportTrialBalance

Sample Code
> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L2027
