### ISSUE TITLE
setAccessTokenFromRedirectUri with state throws error

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#304]
I'm calling `setAccessTokenFromRedirectUri` with a state parameter added.

I tracked down that the function ( see the comments I added )
```js
async setAccessTokenFromRedirectUri(url) {
        const urlObject = new URL(url);
        let params = {};
        for (const [key, value] of urlObject.searchParams) {
            params[key] = value;
        }

       /* NOTICE THERE IS NO THIRD PARAMETER, SEE BELOW! */
        this.tokenSet = await this.openIdClient.callback(this.config.redirectUris[0], params);


        this.setAccessTokenForAllApis();
        await this.fetchConnectedTenantIds();
    }
```

It calls the openId client's callback fn, which starts as:

```js
 async callback(
    redirectUri,
    parameters,
    checks = {},    /* NOTICE THE THIRD PARAMETER IS {} AND NOT SET ABOVE */
    { exchangeBody, clientAssertionPayload } = {},
  ) {
    const params = pickCb(parameters);

    if (this.default_max_age && !checks.max_age) {
      checks.max_age = this.default_max_age;
    }
   
     /* NOTICE THAT IF STATE IS SET, THIS WILL FAIL */
    if (params.state && !checks.state) {
      throw new TypeError('checks.state argument is missing');
    }

    if (!params.state && checks.state) {
      throw new RPError({
        message: 'state missing from the response',
        checks,
        params,
      });
    }

```

and of course I get this when including a state param:

> checks.state argument is missing

Please fix ASAP, we're in the middle of migrating to OAuth2 and this is a blocker issue.

Or shall I just cut the `state=xxx` part off the URL, will that work?

**Comment by SerKnight** [comment]
Thanks for logging this issue. Can you elaborate with the params you are sending when you receive the state error? Have you manually added any state params?

We’ve got an example auth that shows a successful oauth2 Authentication flow. Ping back if that makes it more clear, or will check back here early next week when back in office.

https://github.com/XeroAPI/xero-node-oauth2-app

**Comment by ttruong15** [comment]
I am also having the same issue.  As soon as i pass in the state params for the buildConsentUrl() to redirect to be authenticated.  Once the callback comeback i am calling the setAccessTokenFromRedirectUri() and got this error.

**Comment by SerKnight** [comment]
> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L152

Will try to walk through what sample app does to auth, maybe with full stack trace etc we can track down why you are receiving a state error..

So ensuring you both have added your dev urls to your whitelisted callbacks in your myapps dashboard?
![Screen Shot 2019-12-17 at 4 25 26 PM](https://user-images.githubusercontent.com/2935387/71042749-dc142d00-20e9-11ea-8084-d6bd0fa26b5d.png)

Assuming that piece is all good & you have your credentials set - once you hit callback route, this is how to get & read the access token (using typescript but if you drop the `XeroJwt` & `XeroAccessToken` should work all the same)

```javascript
import jwtDecode from 'jwt-decode';
...

router.get("/callback", async (req: Request, res: Response) => {
   try {
        const url = process.env.REDIRECT_URI + req.originalUrl;
        await xero.setAccessTokenFromRedirectUri(url);
        const accessToken = await xero.readTokenSet();

        const decodedIdToken: XeroJwt = jwtDecode(accessToken.id_token);

        req.session.decodedIdToken = decodedIdToken

        const decodedAccessToken: XeroAccessToken = jwtDecode(accessToken.access_token)
        req.session.decodedAccessToken = decodedAccessToken
        req.session.accessToken = accessToken;

        req.session.allTenants = xero.tenantIds
        req.session.activeTenant = xero.tenantIds[0]

        res.render...
      }  catch (e) {
         // log / output error
      }
 });
```

**Comment by SerKnight** [comment]
Also had another community member reach out with a related issue. Wanted to note that the consent url does not actually need any explicit params passed to it.. 

```javascript
await xero.buildConsentUrl()
```

It will generate based on your Xero configs client id / secret / and redirect uris: https://github.com/XeroAPI/xero-node/blob/83f95e54328c3f4bb79c545155153454e07f1933/src/xeroClient.ts#L29

**Comment by ttruong15** [comment]
I need the state field pass to the url so here's what i did:
`
let consentUrl = await xero.buildConsentUrl()
res.redirect(consentUrl + "&state=sample-string-val"
`
on the callback endpoint
`
await xero.setAccessTokenFromRedirectUri(url);
const token = await xero.readTokenSet()
`
Here's the error thrown:
TypeError: checks.state argument is missing
    at Client.callback (node_modules/openid-client/lib/client.js:413:13)
    at XeroClient.setAccessTokenFromRedirectUri (node_modules/xero-node/dist/XeroClient.js:35:49)

If i dont provide the state parameter everything works fine.  So i know i got everything setup correctly.

**Comment by rhajizadeh** [comment]
I ran into the same problem
I had to remove the state parameter from the url before passing it to  ``setAccessTokenFromRedirectUri`` function.
Having state parameter is extremely beneficial please add it to the library.

**Comment by SerKnight** [comment]
Re-visiting this. If someone can send me a simple replication of this issue I can address! You can fork: https://github.com/SerKnight/xero-node-basic-app to show me. The url that should be passed  is just the REDIRECT_URI + the `req.originalUrl`

If you clone the sample app you can log the `const url` to see the format of what is being passed.

```javascript
const url = process.env.REDIRECT_URI + req.originalUrl;
await xero.setAccessTokenFromRedirectUri(url);
```

**Comment by ericdude4** [comment]
@SerKnight I have recreated this issue in a fork https://github.com/ericdude4/xero-node-basic-app

I have commented out the workaround on `index.js:50`

The `xero.buildConsentUrl` function and `IXeroClientConfig` should support the `state` parameter.

**Comment by SerKnight** [comment]
@ericdude4 + others, thank you.. I dug into the weeds of openid-client, and  the callback requires additional params to check that the initial values sent in are what comes back.

```markdown
state: <string> When provided the authorization response's state parameter will be checked to be the this expected one. Use of this check is required if you sent a state parameter into an authorization request.
```
> https://github.com/panva/node-openid-client/blob/master/docs/README.md#clientcallbackredirecturi-parameters-checks-extras

--------

I've got this as a PR to review before we go master but fixed a few issues in the most recent release 4.0.7
> https://www.npmjs.com/package/xero-node
Replace your package.json with:
```
 "xero-node": "^4.0.7"
```

Thanks for your patience all! Let me know if this resolves each of your issues.
* https://github.com/XeroAPI/xero-node/issues/317
* https://github.com/XeroAPI/xero-node/issues/304

**Comment by ericdude4** [comment]
@SerKnight Everything is working now. Thank you.
