### ISSUE TITLE
How to list all tenants? Not just tenantIds, but with names

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#305]
Title says it all. I haven't been able to find any function to do it. I want to provide users a list of their tenants so they can select which organization they want to link our app to.

**Comment by SerKnight** [comment]
Yes this is something on our mind. You can get the tenant name through the GET org call:

> https://developer.xero.com/documentation/api/organisation

Hope to get this functionality added soon, but at least will have it shown in the sample app how to achieve soon

**Comment by SerKnight** [comment]
Hey @sandorvasas - I've raised this feature request with the API Team. I will update here when I get a response. It would be ideal to have the Org Name in the initial /connections response: 
```
connections = {
  id: 'cf500f43-5d4f-4b4d-8f73-d9a862a0ba42',
  tenantId: 'xxxxxxx-472c-4671-81b7-f2ea44547da0',
  tenantType: 'ORGANISATION',
  createdDateUtc: '2019-12-06T21:35:33.0943390',
  updatedDateUtc: '2019-12-06T21:35:33.0963710'
},{
  id: 'a602f926-087c-42dc-a11f-46490dfc15cb',
  tenantId: 'xxxxxxx-8d09-448e-9402-6df79d6fc8be',
  tenantType: 'ORGANISATION',
  createdDateUtc: '2019-12-06T21:45:16.0510690',
  updatedDateUtc: '2019-12-06T21:45:16.0537880'
},
```
However how its currently setup is to return the org name and other details after a single GET to the /organisations endpoint `https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L1013` so will need to loop on that in the interim.
![Screen Shot 2020-01-22 at 9 41 23 AM](https://user-images.githubusercontent.com/2935387/72914318-bd621100-3cfb-11ea-9f3c-46db2ec172b6.png)

Update you here when I have more details
