### ISSUE TITLE
Cannot updateContacts() with ContactPersons.

### ISSUE THREAD

**Issue by philliplakis** [XeroAPI/xero-node#306]
**SDK you're using (please complete the following information):**
 - Version 4.0.4

**Describe the bug**
I am unable to add `ContactPersons` to contact.

**Expected behavior**
I expect to be able to add `ContactPerson` to a contact just like V3. 

**Screenshots**
n/a

**To Reproduce**
I have an Array of Contact persons like below:
```JS
[
  { 
    "FirstName": "Name",  
    "LastName": "String",
    "EmailAddress": "me@company.com", 
    "IncludeInEmails": "true" 
  },
  { 
    ....
  }
]

```

In V3 i was able to update with:
```JS
 await xero.contacts.update({
        ContactID: xeroID,
        Name: "name",
        ContactPersons: owners, 
        EmailAddress: "billing@company.com"
      });
```

With V4 i am unable to do this:
```JS
    
    const contacts = {
        contacts: [
          {
            Name: name,
            ContactPersons: owners, // Array. 
            EmailAddress: "billing@company.com"
          }
        ]
      };
      console.log("owners: " + JSON.stringify(contacts, null, 2));
      await xero.accountingApi.updateContact(
        tenantId,
        xeroID,
        contacts
      );
```

In V4 each time the error is :
```
{ 
  ErrorNumber: 17,  
  Type: 'NoDataProcessedException', 
  Message:  'No data has been processed for this endpoint. This endpoint is expecting Contact data to 
  be specifed in the request body.' ,
  body: Contacts { contacts: undefined } 
} 
```
**Additional context**
Can we get some documentation on V4? 
It seems the transition from V3 to V4 apart from Authentication is vastly different.

**Comment by SerKnight** [comment]
Thank you for all the details. Will be digging in ASAP. Authorization should have been the only update. I will reproduce and get back to you next week. Thanks for patience.

**Comment by philliplakis** [comment]
Hi,

Is there any update to get this fixed?

Thanks
Phillip

**Comment by SidneyAllen** [comment]
Hi @philliplakis 

Just checked these two examples.  

// As JSON Object
const contact2: Contact = { name: "Contact Sid Bar 2" + Helper.getRandomNumber(10000), firstName: "Foo", lastName: "Bar", emailAddress: "foo.bar@example.com", contactPersons:[{firstName: "Joe", lastName: "Johnson" }] };
const contactCreateResponse = await xero.accountingApi.createContact(req.session.activeTenant, contact2);


// More verbose setting each attribute and pushing into Array
// Define our ContactPersons Array
const contactPersons: ContactPerson[] = [];

// Define a ContactPerson and Push to Array
const person1: ContactPerson = new ContactPerson();
person1.firstName = "Joe";
person1.lastName = "Johnson";
contactPersons.push(person1);

// Define a ContactPerson and Push to Array
const person2: ContactPerson = new ContactPerson();
person2.firstName = "Jane";
person2.lastName = "Johnson";
contactPersons.push(person2);

const contact: Contact = new Contact();
contact.name = "Some Customer";
contact.firstName = "123";
contact.lastName = "foobar";
contact.emailAddress = "foo@bar.com"
contact.contactPersons = contactPersons;

const contactCreateResponse = await xero.accountingApi.createContact(req.session.activeTenant, contact);

**Comment by philliplakis** [comment]
Hi @SidneyAllen ,

You closed the issue without addressing the title or description of the issue. This issue is still happening in `4.1.4` , i am using `UPDATE` not `CREATE` .... `xero.accountingApi.updateContact()`

Again il put some examples:
**V3 Working**
```
 await xero.contacts.update({
        ContactID: "d6a384fb-f46f-41a3-8ac7-b7bc9e0b5efa",
        Name: "name",
        ContactPersons: [
        {
          FirstName: "me",
          LastName: "you"
        },
        {
          FirstName: "here",
          LastName: "there"
        }
      ], 
        EmailAddress: "billing@me.com"
      });
```

**V4.0.1 - 4.1.4** NOT Working
```
 const contacts = {
      Name: "Melrose Parking",
      ContactPersons: [
        {
          FirstName: "me",
          LastName: "you"
        },
        {
          FirstName: "here",
          LastName: "there"
        }
      ],
      EmailAddress: "billing@mp.com"
    };

    await xero.accountingApi.updateContact(
      xero.tenantIds[0],
      "d6a384fb-f46f-41a3-8ac7-b7bc9e0b5efa",
      contacts
    );
```
**V4 Responce Body:**
```
body":{"ErrorNumber":17,"Type":"NoDataProcessedException","Message":"No data has been processed for this endpoint. This endpoint is expecting Contact data to be specifed in the request body."}
```

**Comment by philliplakis** [comment]
sdsd

**Comment by SerKnight** [comment]
Thank you for the example to reproduce @philliplakis - I will hey to this winter his week and report back.

**Comment by SidneyAllen** [comment]
@philliplakis have you tried changing the casing?  

My example has ....

contactPersons:
  [
    {
      firstName: "Joe", 
      lastName: "Johnson" } 
  ] 
};

while your is 

 ContactPersons: [
        {
          FirstName: "me",
          LastName: "you"
        },
        {
          FirstName: "here",
          LastName: "there"
        }
      ],

**Comment by philliplakis** [comment]
@SidneyAllen there is a common message from the xero team that the only change from v3 to v4 is authentication. Is this the case or not?
In any case regardless it still is not working for `updateContact` i get the same error.

**Below is the entire API call:**
```JS
app.get("/updateContact", async (req, res) => {
  try {
    await checkConfig();
    await connectDb();
  } catch (e) {
    console.log("CheckConfig() failed");
    return res.status(400).json({ e });
  }

  try {
    const accessToken = await query.XeroToken();

    await xero.setTokenSet(accessToken[0].token);

    await xero.refreshToken();

    const refreshedAccessToken = await xero.readTokenSet();

    await query.XeroToken(refreshedAccessToken, xero.tenantIds[0]);

    const contacts = {
      Name: "Melrose Parking",
      ContactPersons: [
        {
          firstName: "me",
          lastName: "you"
        },
        {
          firstName: "here",
          lastName: "there"
        }
      ],
      EmailAddress: "billing@you.com"
    };

    await xero.accountingApi.updateContact(
      xero.tenantIds[0],
      "d6a384fb-f46f-41a3-8ac7-b7bc9e0b5efa",
      contacts
    );

    res.send(createContact);
  } catch (e) {
    console.log(e);
    res.status(500).send(e);
  }
});
```

**Comment by SidneyAllen** [comment]
@philliplakis 

Can you share any specifics about where you were told the only change between v3 and v4 was authentication?  That would be inaccurate as xero-node v4 and all Xero OAuth 2.0 SDKs are being generated from our OpenAPI specs and therefore share none of the code from any OAuth 1.0a SDKs (in this case xero-node v3).  


@RettBehrens on the team has tested the following code around updating Contacts in different scenerios.

Just tested with 4.1.4

This code updates a contact that previously had no contact person:
`app.get('/contact', async (req: Request, res: Response) => {
try {
const contact: Contact = {
name: "FooBar",
firstName: "Foo",
lastName: "Bar",
emailAddress: "foo.bar@example.com",
};
const newContacts: Contacts = new Contacts();
newContacts.contacts = [contact];
const contactCreateResponse = await xero.accountingApi.createContacts(req.session.activeTenant, newContacts);
console.log(contactCreateResponse.body.contacts[0]);

const person: ContactPerson = {
firstName: 'Joe',
lastName: 'Schmo'
};

const updateContact: Contact = {
name: contact.name,
firstName: contact.firstName,
lastName: contact.lastName,
emailAddress: contact.emailAddress,
contactPersons: [person]
};

const updateContacts: Contacts = new Contacts();
updateContacts.contacts = [updateContact];

const contactUpdateReponse = await xero.accountingApi.updateContact(req.session.activeTenant, contactCreateResponse.body.contacts[0].contactID, updateContacts);
console.log(contactUpdateReponse.body.contacts[0]);
} catch (err) {
console.log(err);
}
});`

This code overwrites the existing contact person when updating:
`app.get('/contact', async (req: Request, res: Response) => {
try {
const contact: Contact = {
name: "FooBar",
firstName: "Foo",
lastName: "Bar",
emailAddress: "foo.bar@example.com",
contactPersons: [
{
firstName: 'Bazz',
lastName: 'Buzz'
}
]
};
const newContacts: Contacts = new Contacts();
newContacts.contacts = [contact];
const contactCreateResponse = await xero.accountingApi.createContacts(req.session.activeTenant, newContacts);
console.log(contactCreateResponse.body.contacts[0]);

const person: ContactPerson = {
firstName: 'Joe',
lastName: 'Schmo'
};

const updateContact: Contact = {
name: contact.name,
firstName: contact.firstName,
lastName: contact.lastName,
emailAddress: contact.emailAddress,
contactPersons: [person]
};

const updateContacts: Contacts = new Contacts();
updateContacts.contacts = [updateContact];

const contactUpdateReponse = await xero.accountingApi.updateContact(req.session.activeTenant, contactCreateResponse.body.contacts[0].contactID, updateContacts);
console.log(contactUpdateReponse.body.contacts[0]);
} catch (err) {
console.log(err);
}
});`

And this code updates the contactPersons with an additional contact person
`app.get('/contact', async (req: Request, res: Response) => {
try {
const contact: Contact = {
name: "FooBar",
firstName: "Foo",
lastName: "Bar",
emailAddress: "foo.bar@example.com",
contactPersons: [
{
firstName: 'Bazz',
lastName: 'Buzz'
}
]
};
const newContacts: Contacts = new Contacts();
newContacts.contacts = [contact];
const contactCreateResponse = await xero.accountingApi.createContacts(req.session.activeTenant, newContacts);
console.log(contactCreateResponse.body.contacts[0]);

const person: ContactPerson = {
firstName: 'Joe',
lastName: 'Schmo'
};

const updateContact: Contact = {
name: contact.name,
firstName: contact.firstName,
lastName: contact.lastName,
emailAddress: contact.emailAddress,
contactPersons: [person, contactCreateResponse.body.contacts[0].contactPersons[0]]
};

const updateContacts: Contacts = new Contacts();
updateContacts.contacts = [updateContact];

const contactUpdateReponse = await xero.accountingApi.updateContact(req.session.activeTenant, contactCreateResponse.body.contacts[0].contactID, updateContacts);
console.log(contactUpdateReponse.body.contacts[0]);
} catch (err) {
console.log(err);
}
});```

**Comment by SidneyAllen** [comment]
This code overwrites the existing contact person when updating:

```
app.get('/contact', async (req: Request, res: Response) => {
try {
const contact: Contact = {
name: "FooBar",
firstName: "Foo",
lastName: "Bar",
emailAddress: "foo.bar@example.com",
contactPersons: [
{
firstName: 'Bazz',
lastName: 'Buzz'
}
]
};
const newContacts: Contacts = new Contacts();
newContacts.contacts = [contact];
const contactCreateResponse = await xero.accountingApi.createContacts(req.session.activeTenant, newContacts);
console.log(contactCreateResponse.body.contacts[0]);

const person: ContactPerson = {
firstName: 'Joe',
lastName: 'Schmo'
};

const updateContact: Contact = {
name: contact.name,
firstName: contact.firstName,
lastName: contact.lastName,
emailAddress: contact.emailAddress,
contactPersons: [person]
};

const updateContacts: Contacts = new Contacts();
updateContacts.contacts = [updateContact];

const contactUpdateReponse = await xero.accountingApi.updateContact(req.session.activeTenant, contactCreateResponse.body.contacts[0].contactID, updateContacts);
console.log(contactUpdateReponse.body.contacts[0]);
} catch (err) {
console.log(err);
}
});
```

**Comment by SidneyAllen** [comment]
And this code updates the contactPersons with an additional contact person

```
app.get('/contact', async (req: Request, res: Response) => {
try {
const contact: Contact = {
name: "FooBar",
firstName: "Foo",
lastName: "Bar",
emailAddress: "foo.bar@example.com",
contactPersons: [
{
firstName: 'Bazz',
lastName: 'Buzz'
}
]
};
const newContacts: Contacts = new Contacts();
newContacts.contacts = [contact];
const contactCreateResponse = await xero.accountingApi.createContacts(req.session.activeTenant, newContacts);
console.log(contactCreateResponse.body.contacts[0]);

const person: ContactPerson = {
firstName: 'Joe',
lastName: 'Schmo'
};

const updateContact: Contact = {
name: contact.name,
firstName: contact.firstName,
lastName: contact.lastName,
emailAddress: contact.emailAddress,
contactPersons: [person, contactCreateResponse.body.contacts[0].contactPersons[0]]
};

const updateContacts: Contacts = new Contacts();
updateContacts.contacts = [updateContact];

const contactUpdateReponse = await xero.accountingApi.updateContact(req.session.activeTenant, contactCreateResponse.body.contacts[0].contactID, updateContacts);
console.log(contactUpdateReponse.body.contacts[0]);
} catch (err) {
console.log(err);
}
});
```
