### ISSUE TITLE
Failed API call leads to refreshToken() not working.

### ISSUE THREAD

**Issue by philliplakis** [XeroAPI/xero-node#307]
**SDK you're using (please complete the following information):**
 - Version 4.0.4

**Describe the bug**
If a failed API call is made specifically to contacts API for me, I can not refresh my token again.

**To Reproduce**
1. Get token
2. Refresh as many time as you like.
3. Make API call to contacts that fails. #306 
4. Refresh token now will not work.

**Expected behavior**
I expect a token to be refreshable even after a failed API call.

**Screenshots**
N/A

**Additional context**
If an attempt is made after a failed API call i get the following output:
```
TypeError: Cannot read property 'refresh' of undefined at XeroClient.refreshToken
```

**Comment by hanselke** [comment]
i'm getting the same error.

**Comment by philliplakis** [comment]
> i'm getting the same error.

Us too, still awaiting a response from the dev team, Hoping to get this fixed soon...

**Comment by SerKnight** [comment]
Duplicate to  #299  so closing and starting to gather specifics in that issue.

Phillip I recorded a video of your #3 https://drive.google.com/open?id=19VfjsCIKLda6sWM6hwZyatTFTkp0RU1V&authuser=0 )

I think I am missing something in the steps to reproduce.. Lets move it to 299 and can get it sorted asap there.
