### ISSUE TITLE
getInvoiceAsPdf returns 404

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#308]
- Version 4.04

The following code returns 404. InvoiceID, xeroTenantId and access token are correct, they work with other Xero endpoints.

```js
const xa = await XeroAccount.findById(xeroAccountId)
await xero.setTokenSet(xa.getXeroAccessTokenSet())

const apiResponse = await xero.accountingApi.getInvoiceAsPdf(xa.xeroTenantId, invoiceId, 'application/pdf')
return apiResponse.body.toString('base64')
```

Response:
```json
"response": {
        "statusCode": 404,
        "body": {
            "type": "Buffer",
            "data": []
        },
....etc, etc....
```

**Comment by tglennan** [comment]
I have submitted a pull request #316 which appears to fix this issue for me. It appears the wrong API endpoint was being used.

**Comment by SidneyAllen** [comment]
@tglennan - thanks for the PR.  We now generate much of our SDK code from our OpenAPI specs.  I'll need to work on a solution at the code template level to address this quirk in our API.  I won't close this PR until I've got a fix in place but we won't be able to merge this as it will be overwritten the next time we re-generate the SDK code.

**Comment by faizalshap** [comment]
Note - you also need to add a header - Accept:'application/pdf' otherwise it won't return actual pdf but json as buffer @SidneyAllen . Please add this. Currently we are editing node modules for this

**Comment by SerKnight** [comment]
Hi @faizalshap - here is an example usage for downloading the invoice as PDF where you won't have to hack your node_modules ;)

https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L908
```javascript
const getAsPdf = await xero.accountingApi.getInvoiceAsPdf(
  req.session.activeTenant,
  totalInvoices.body.invoices[0].invoiceID,
  'application/pdf',
  {  headers: { accept: 'application/pdf' } }
)
```

It will require passing the headers as you said. In a larger release we will be looking to simplify how function params & header options are passed but this should un-block you for now.

Thanks for raising this issue!
