### ISSUE TITLE
Long-term, permanent access token?

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#309]
- Version 4.0.4
How to give users long-term access? We have multiple teams of users to which one or more Xero accounts can be linked via the OAuth2 auth flow. We want them to authorize our app only once and from then on be able to use their Xero account with our app. I understand that offline_access scope can be requested and an access token can be regained every 30 mins with the refresh token, but that method seems quite unreliable to me. If we add this as a CRON job, and we have an outage where the CRON won't run, we'd lose all accesses, and all of our users would need to reauthorize our app.

**Comment by mbyrne00** [comment]
Does the refresh token actually expire or just the access token? Is there _really_ a requirement to refresh every 30 mins or could you just refresh when you need your backend process to do something if the access token is expired?

oAuth 2 flow seems to support this but depends on how xero have setup expiry etc.

**Comment by SerKnight** [comment]
Hey Sandorvasas - just spoke a little about improved documentation efforts in mbyrnes previous issue, but yet the refresh token is actually quite reliable to maintain ongoing access to your customers organization.

I will be adding examples/documentation for this in the repos soon, but know that there are functions for how to renew a token if it becomes expired.

https://github.com/XeroAPI/xero-node/blob/83f95e54328c3f4bb79c545155153454e07f1933/src/xeroClient.ts#L73

I'd recommend coding into a retry cycle that will ensure a token is valid.. Here is a [generic example](https://www.oauth.com/oauth2-servers/making-authenticated-requests/refreshing-an-access-token/) of how this process will go. 

I will update these issues once I can get that example added to the sample app!

**Comment by mbyrne00** [comment]
Thanks @SerKnight. Can you please clarify whether the refresh token we are initially given will continue to be usable for multiple refreshes? Or do we need to get an updated refresh token after we issue a refresh.

The link to the generic example was what I was reading and it says that depends on the implementation.

**Comment by SerKnight** [comment]
@mbyrne00 

> What is the expiration for a refresh token?
**Refresh tokens expire once they’re used or after 30 days. If you don’t refresh your access token within 30 days the user will need to reauthorize your app.**

> What do I do if I can't refresh an access token?
**If you can’t refresh your access token you’ll need to send the user through the authorization flow again to get a code that can be exchanged for a new access and refresh token.**


https://developer.xero.com/documentation/oauth2/auth-flow

**Comment by mbyrne00** [comment]
Thanks @SerKnight - would be handy to document the 30 day expiry on access token and the fact they can't be re-used (you need to use the refresh token returned when you do a refresh) since I couldn't see that anywhere.

So, just to clarify if you refresh within 30 days and get another refresh token returned then you can continue refreshing indefinitely as long as the user hasn't revoked app access, right?

**Comment by SerKnight** [comment]
Yes sir! You got it.. yeah since these Oauth2 SDKS are so new, we still have tons of work to do to document the API better in each one. And also make clear some convenience methods on how to do things like list all authorized org names, and toke refresh strategies.

Thanks for your engagement - much appreciated :)

**Comment by mbyrne00** [comment]
Perfect, thanks again. This will serve as the doco for us for now.
