### ISSUE TITLE
What is the recommended auth approach for server to server apps?

### ISSUE THREAD

**Issue by jason-dark** [XeroAPI/xero-node#310]
**SDK you're using (please complete the following information):**
 - Version 4.0.4

**Is your feature request related to a problem? Please describe.**
It's a problem. I am building a private business app which creates contacts in Xero when they are created in our CRM. I remember the Xero Node sdk used to support .ppk auth for this purpose. This doesn't seem to be supported any more and I'm not sure what the recommended approach for server to server auth flow is now.

**Describe the solution you'd like**
Documentation on the recommended way to do server to server auth flow.

**Describe alternatives you've considered**
None.

**Additional context**
This used to be supported but appears to have been deprecated.

**Comment by SerKnight** [comment]
Hi Jason - I've copied in a response from or dev FAQ - https://developer.xero.com/faq/all/oauth-non-secret.. But as a general answer, know that now that OAuth 2.0 is launched the API team is working on a [PKCE](https://oauth.net/2/pkce/) solution for Oauth2.. I can also ensure that there will be enough time for our folks using OAuth1 for Mobile/Desktop apps to migrate over once we have launched PKCE and have a migration plan.

# Will OAuth 2.0 support desktop/mobile/single-page apps that can’t keep a client secret confidential?
> At the moment, we require that your app can keep a client secret confidential. We are currently evaluating the PKCE extension to better support SPAs and mobile apps.

Feel free to write into api@xero.com with additional questions and can expand on our answer!
