### ISSUE TITLE
The accounting API is missing the BankStatement report endpoint

### ISSUE THREAD

**Issue by lsenjov** [XeroAPI/xero-node#313]
- Version 4.0.4

There is no getReportBankStatement in the accounting API, but it appears here in your [Swagger Docs](https://github.com/XeroAPI/Xero-OpenAPI/blob/master/spec/swagger%20v2/accounting2.json#L4565)

Any idea on when this will get implemented? We're relying on this

**Comment by SerKnight** [comment]
Hey @lsenjov - this is fixed in `4.1.1`

We have an example usage in the sample app. Thanks for reporting this issue! Much appreciated.
> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L1210
```
  const fromDate = "2019-01-01";
  const toDate = "2019-12-31";
  const apiResponse = await xero.accountingApi.getReportBankSummary(req.session.activeTenant, fromDate, toDate);
  console.log(apiResponse.body.reports[0].reportTitles[2]);
```

**Comment by SerKnight** [comment]
Sorry @lsenjov  - Actually this endpoint has been deprecated. I will update this story if I learn more. I mis read the function name.

**Comment by SidneyAllen** [comment]
@lsenjov a bit more details around this.  We have plans to deprecate this report in the future and don't wish to promote it.  For this reason, it's been omitted from our documentation and SDKs.  If you do roll your own code to connect to this report be aware of it's current status and that any replacement report may not have all the same data.

**Comment by mbyrne00** [comment]
@SidneyAllen and @SerKnight - just following up on this. We have had code that has needed to get `openingBalance` and `closingBalance` for a `bankAccountID` between two dates. The attached screen shows this 
![image](https://user-images.githubusercontent.com/5687982/100058161-f10e4a00-2e7c-11eb-984b-4c095f3f361d.png)

`BankSummary` returns this information for all accounts which is fine as we could filter in memory, however we need to get the _bank statement_ closing balance and not the _xero balance_. Please point us to how we can do this in a supported, non-deprecated API through node.

**Comment by SidneyAllen** [comment]
@mbyrne00 - I don't have any new updates on the planned deprecation for this endpoint.  As I mentioned in the comment above, you can roll your own code to interact with this endpoint, but we are choosing to no longer include it in our documentation our SDKs to reduce further adoption.  We will give advance notice when we move forward with deprecation and won't be able to guarantee an alternate endpoint will return the same data.
