### ISSUE TITLE
Unable to create invoice in xero-node v4

### ISSUE THREAD

**Issue by neiroc** [XeroAPI/xero-node#315]
I'm trying to create an invoice through xero-node v4 using the account api function createInvoice ( xeroTenantID, invoice) passing the right parameters but i'm getting this errror:

> No data has been processed for this endpoint. This endpoint is expecting Invoice data to be specifed in the request body

For some reason the body request is undefined. It works good with other functions like getOrganisation(). Do you have any info about this problem??

Using Xero API v3 and writing the POST or PUT request manually works well

**Comment by RichardWatkins1** [comment]
@SidneyAllen is there any update on this?

**Comment by SerKnight** [comment]
Hey @RichardWatkins1 // @neiroc 

So using: "xero-node": "^4.0.6" in the `https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L753` project - was able to create / get / update the invoice. If you can post more about your code we can see how your API call params are shaped - are you familiar with Typescript?

I'm thinking there is likely some missing params from the invoice creation or the invoice param object is not types/shaped correctly.. the API/SDK is expecting the following:

```typescript
import { Invoice, ...otherModels..., XeroClient } from "xero-node";

const invoiceParams: Invoice = {
  type: Invoice.TypeEnum.ACCREC,
  contact: {
    contactID: contactID
  },
  expectedPaymentDate: "2020-01-06T00:00:00",
  ...
}
```

**Comment by simonireilly** [comment]
@SerKnight, @RichardWatkins1 and are working on this together.

We are upgrading from the old client, v3, where we would previously send along a plain javascript object. We were doing as below with the v4.0.6 client. 

```
invoice = (order) => {
  return {
    Type: 'ACCREC',
    Contact: Contact(order.customer),
    LineItems: buildLineItems(order),
    Status: 'AUTHORISED',
    Date: order.placed_at,
    DueDate: order.placed_at,
    InvoiceNumber: order.reference,
    Reference: order.reference,
    SentToContact: true,
    LineAmountTypes: 'Inclusive'
  }
}
const createInvoiceResponse = await xeroClient.accountingApi.createInvoice(xeroTenant, invoice)
```

My understanding is that we should now create an Invoice using the Constructor somehow?

Thanks for the response :+1:

**Comment by SerKnight** [comment]
Ahh - actually that should be mostly okay.. The constructor (in typescript, just called a `Type`) `invoiceParams: Invoice = {` is just going to help you to ensure your parameters are correctly spelled and expected..

I can't be 100% but I actually remember seeing an issue similar when I was passing the whole Contact Object like you are doing here `Contact: Contact(order.customer)` - and in this v4 the API might only be expecting the 
```
...
  contact: {
    contactID: contactID
  }
...
```

So v3 -> v4 will be breaking changes but once you import the type it should be relatively easy to migrate. The sample app should show you how to accomplish each formatting. There are a couple of gotchas i'm working to document better, so thanks for calling this out..

https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L709

I'll close this ticket but please update once you are able to give it a shot - plz re-open if still facing issues.

**Comment by simonireilly** [comment]
Thanks for the tips, I have modified my code as follows:

```js
invoice = (order) => {
  return {
    Type: 'ACCREC',
    Contact: { contactID: '1234' },
    LineItems: buildLineItems(order),
    Status: 'AUTHORISED',
    Date: order.placed_at,
    DueDate: order.placed_at,
    InvoiceNumber: order.reference,
    Reference: order.reference,
    SentToContact: true,
    LineAmountTypes: 'Inclusive'
  }
}
const createInvoiceResponse = await xeroClient.accountingApi.createInvoice(xeroTenant, invoice)
```

```js
{
  invoice: {
    Type: 'ACCREC',
    Contact: {
      contactID: '11234'
    },
    LineItems: [
      [Object],
      [Object],
      [Object]
    ],
    Status: 'AUTHORISED',
    Date: '2019-10-02T13:42:00.000Z',
    DueDate: '2019-10-02T13:42:00.000Z',
    InvoiceNumber: '7e60149f-223b-4cd9-a5ba-27cb85973611',
    Reference: '7e60149f-223b-4cd9-a5ba-27cb85973611',
    SentToContact: true,
    LineAmountTypes: 'Inclusive'
  }
}
```

I still receive the same error message:

```json
{
  "request": {},
  "response": {
    "statusCode": 400,
    "body": {
      "ErrorNumber": 17,
      "Type": "NoDataProcessedException",
      "Message": "No data has been processed for this endpoint.This endpoint is expecting Invoice data to be specifed in the request body"
    }
  }
}
```

The error seems correct, there is no body being passed into the client.

Happy for this issue to be closed once there is a demonstrated workaround/solution.

**Comment by SerKnight** [comment]
@simonireilly

Couple questions:

1) can you `console.log(invoiceParams)` or the exact params that are being sent to the API.. Is that second Object above exactly the second parameter?

2) Is `xeroTenant` just referring to the `active_org_id` - should be a uuid.

--

Highly recommend cloning and spinning up the sample app.. You can log out the parameters and make sure your application's formatting is matched. 


```
const createdInvoice = await xero.accountingApi.createInvoice(req.session.activeTenant, invoiceParams)

```
```
req.session.activeTenant =  554e93d8-xxxx-xxxx-xxxx-f2ea44547da0
...
invoiceParams =  {
  type: 'ACCREC',
  contact: { contactID: '0f576e2e-1dd0-496a-a909-305a8a48e3d9' },
  expectedPaymentDate: '2009-10-20T00:00:00',
  invoiceNumber: 'XERO:1378',
  reference: 'REF:3875',
  brandingThemeID: '91b6efb2-34fc-48db-9425-fa1d681e540d',
  url: 'https://deeplink-to-your-site.com',
  currencyCode: 'USD',
  status: 'SUBMITTED',
  lineAmountTypes: 'Inclusive',
  subTotal: 87.11,
  totalTax: 10.89,
  total: 98,
  date: '2009-05-27T00:00:00',
  dueDate: '2009-06-06T00:00:00',
  lineItems: [
    {
      description: 'Consulting services',
      taxType: 'NONE',
      quantity: 20,
      unitAmount: 100,
      accountCode: '500'
    },
    {
      description: 'Mega Consulting services',
      taxType: 'NONE',
      quantity: 10,
      unitAmount: 500,
      accountCode: '500'
    }
  ]
}
```

**Comment by SerKnight** [comment]
> Happy for this issue to be closed once there is a demonstrated workaround/solution.
https://github.com/XeroAPI/xero-node-oauth2-app

**Comment by simonireilly** [comment]
I will clone the app and dig into this a little deeper.

Thanks again for your responses, I'll pop a comment back on after I have checked out the clone :+1:

**Comment by SerKnight** [comment]
Closing for cleanup - but followup if theres any news on a gotcha/solution we may have missed in the docs.

**Comment by jim-alexander** [comment]
Any news on this? getting the same error

**Comment by SerKnight** [comment]
Hi @jim-alexander since this issue was closed due to different people having diff problems and they were resolved I'd recommend opening a new issue that contains all the data required to debug what is going on for your situation.

> https://github.com/XeroAPI/xero-node/issues/new?assignees=&labels=bug+reported+%28%3F%29&template=bug_report.md&title=
