### ISSUE TITLE
Construtor should create openIdClient

### ISSUE THREAD

**Issue by simonireilly** [XeroAPI/xero-node#317]
**SDK you're using (please complete the following information):**
 - Version [e.g. 4.0.6]

**Is your feature request related to a problem? Please describe.**
When creating a new client with the v4 constructor we don't get immediate access to the `openIdClient` until we call `buildConsentUrl()`.

This is not much fun when we are refreshing tokens e.g. in AWS lambda where we need to do something like:

```
const freshenClient = async (refreshToken) => {
  // Do this because the constructor does not create an instance of the client
  await xero.buildConsentUrl()
  await xero.setTokenSet(refreshToken)
  await xero.refreshToken()
  return null
}

freshenClient({ refresh_token: String(process.env.refresh_token), access_token: null })
```

**Describe the solution you'd like**

I would propose that the constructor can also create `this.openIdClient` in `/xero-node/dist/XeroClient.js` so the client can be used without having to round trip into another method and promise chain.

**Describe alternatives you've considered**

The workaround is presented above.

**Additional context**

This is useful for a distributed system that seeks to cache refresher tokens and re-refresh the client after the container the client is operating in has been (e.g. lambda) has been removed from memory.

**Comment by SerKnight** [comment]
This was addressed & fixed in the PR for 4.0.7
> https://github.com/XeroAPI/xero-node/issues/304#issuecomment-575225660
