### ISSUE TITLE
Running the Test Suite, Building the Project, and Contributing

### ISSUE THREAD

**Issue by simonireilly** [XeroAPI/xero-node#318]
Sorry for posting here but I am really struggling to get the community page to boot:

![image](https://user-images.githubusercontent.com/30017294/71694216-675a1780-2da6-11ea-9ef2-f1c4ef85fa26.png)

Version 79.0.3945.88 (Official Build) (64-bit)

**SDK you're using (please complete the following information):**
 - Version [e.g. 4.0.6]

**Describe the bug**

When running the test suite I encounter the following:

```
## From Contributing.md

mvn test


WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.153 s
[INFO] Finished at: 2020-01-02T21:10:58Z
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/simon/code/node/xero-node). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```

When building the project the following is encountered:

```
yarn build ./src/index.ts

tsc ./src/index.ts
src/gen/api/accountingApi.ts:110:9 - error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.

110     set useQuerystring(value: boolean) {
            ~~~~~~~~~~~~~~

src/gen/api/accountingApi.ts:114:9 - error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.

114     set basePath(basePath: string) {
            ~~~~~~~~

src/gen/api/accountingApi.ts:118:9 - error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.

118     get basePath() {
            ~~~~~~~~

src/gen/api/accountingApi.ts:130:9 - error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.

130     set accessToken(token: string) {
            ~~~~~~~~~~~

src/index.ts:6:15 - error TS2307: Cannot find module './XeroClient'.

6 export * from './XeroClient';
```

- It appears in a lot of places there is a capital `XeroClient` but this file doesn't exist, it is a lower case.
- I'm not really sure how the CI/CD runs, so I can't look at that and see what I am missing?
- It seems like there is a missing type script config file, I don't know I don't use typescript

Fixing some of these issues locally I can boot the test suite, but then it opens a webpage that responds with a 500. I believe this is because `src/__integration_tests__/config.ts` is hard coded with invalid credentials.

I'm really keen to contribute to this as it forms an integral part of my organizations integration platform.

## Solution

Would really like a steer on how all this is suposed to work out of the box for contributing.

.

**Comment by SerKnight** [comment]
Hi @simonireilly - Sorry can you elaborate a bit.. "I am really struggling to get the community page to boot:" I'm a bit confused by that first statement.

We moved to a new strategy to auto generate all our SDKs from an open api yml based configuration you can see here ( https://github.com/XeroAPI/Xero-OpenAPI )

Our goal is to also have better documentation around receiving contributions from the community, while also maintaining standardization across the SDK ecosystem. I empathize with you on this & ensure you we are putting the resources to improve the developer experience greatly this year!

**Comment by simonireilly** [comment]
Sorry @SerKnight, I didn't make that clear.
The community site had crashed when I was attempting to add the above post there.

Ah, that all makes sense and sounds fantastic, best of luck with the continued transition :+1:

**Comment by SerKnight** [comment]
Hi Simon - FYI theres been a large release to simplify the client ( non-generated code )

Contribution should be much more clear. This update will be a breaking changes ( sorry not 100% following Semver quite yet ) but should increase the usability a lot.

We welcome all your feedback as you continue to use this package!

---
Large release/improvement (4.4.0) to the xero-node SDK..  Based off community feedback & our teams personal usage:
* Simpler client fn() naming conventions
* Added /disconnect helper
* Added updateTenants() helper to fetch and serialize all connected org names + other org data
* Added client tests & GitHub actions CI/runner :testing: :pikaomg:
* Massive Readme re-vamp for usage + Updated sample app with refresh/disconnect ex.
