### ISSUE TITLE
Have typedoc as devDependencies

### ISSUE THREAD

**Issue by crespowang** [XeroAPI/xero-node#319]
**SDK you're using (please complete the following information):**
 - Version [3.1.2]

**Is your feature request related to a problem? Please describe.**
Can **typedoc** be devDependencies?

**Describe the solution you'd like**
We use xero-node in AWS lambda environment, which is sensitive to package size, because **typedoc** requires **typescript**(50MB) as dependencies it go over the limit.

**Comment by SerKnight** [comment]
Thank you @crespowang - good improvement. Will shoot to get this in the next release/

**Comment by crespowang** [comment]
@SerKnight is there a timeline it will be fixed?  Thanks!

**Comment by SerKnight** [comment]
We will try to get this out by next week. If that does not work please fork and solve for interim & I will notify once a package is released.

**Comment by SerKnight** [comment]
Typedoc is no longer in the package.json as a dependency. Most recent npm vsn is `4.0.7`

```
{
    "name": "xero-node",
    "version": "2.0.0",
    "description": "Xero NodeJS OAuth 2.0 client for xero-node",
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "author": "Xero Platform Team",
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "git://github.com/XeroAPI/xero-node.git"
    },
    "scripts": {
        "build": "tsc",
        "test": "jest"
    },
    "devDependencies": {
        "@types/jest": "^24.0.23",
        "@types/node": "^12.12.5",
        "@types/request": "^2.48.3",
        "jest": "^24.9.0",
        "open": "^6.4.0",
        "prompt": "^1.0.0",
        "ts-jest": "^24.1.0",
        "typescript": "^3.7.2"
    },
    "dependencies": {
        "openid-client": "^3.8.3",
        "request": "^2.88.0"
    }
}

```
