### ISSUE TITLE
Receiving error 401, "AuthorizationUnsuccessful" on calls to the Accounting API

### ISSUE THREAD

**Issue by iggytheiguana** [XeroAPI/xero-node#320]
I have implemented the OAuth 2.0 flow in NodeJS and the entire OAuth flow seems to work fine for the entire login->authorization process. I request offline scope and then store the refresh and access tokens for an later batch job to run against the reports API.

I am noticing that for some Xero accounts I am receiving an error 401 "AuthorizationUnsuccessful" when I make any calls to the API using an access token like a call to https://api.xero.com/api.xro/2.0/Reports/ProfitAndLoss

Note
- I am including the Xero-tenant-id in the headers, the Xero-tenant-id I pass is a tenant-id that is returned to me when I make a call to the /connections API using the same access token.
- I use the refresh token to generate a new access token prior to making the call to the api.

Do you have any clues as to what might be happening here? The token appears to be valid and I am able to refresh it just before making these calls. This is only happening on some of the Xero accounts I am working with, others that use the same logic work fine.

**Comment by SerKnight** [comment]
Hi Iggy - That logic seems correct. If you can trace back to the specific time and the App Id/Name - If you email api@xero.com we can dig into the logs and help you figure out what the parameters were. Hard to tell from just this.

It's also possible you didn't include the correct scope for that call.. Offline access is required for refresh, but you also need to encompass the permissions spread across the api:
> https://developer.xero.com/documentation/oauth2/scopes

Closing for now as Its not crystal clear this is an SDK issue, but if you can followup to the api@xero.com email and you can log all necessary details.. (scopes, decoded JWT, etc.) and  are still encountering this, please re-open.
