### ISSUE TITLE
How to use  xero.accountingApi.emailInvoice

### ISSUE THREAD

**Issue by blairjo** [XeroAPI/xero-node#321]
Hi,

I'm migrating to V4 and need to use the emailInvoice function, but I'm not sure what the "requestEmpty" param is? I've looked in the sample app and there's no reference to this, but I understand you've got a lot of work on migrating all these APIs so docs are a bit behind. 

Can you point me in the right direction please?

Thanks

**Comment by blairjo** [comment]
update on this: I tried passing in a dummy RequestEmpty object, with a test value for the status, but the call request() fails. The problem seems to be the xero-node code is not passing json=true in the options like it does with say createInvoice but it is passing a JSON RequestEmpty object. You then get an error in request.setContentLength because it is expecting any JSON objects to have been converted to a string.

**Comment by SerKnight** [comment]
Fix released in 4.1.1 - thanks for logging this as an issue!

Added sample usage in the sample app: https://github.com/XeroAPI/xero-node-oauth2-app/pull/17

![Screen Shot 2020-01-22 at 5 18 31 PM](https://user-images.githubusercontent.com/2935387/72946939-b3610200-3d3d-11ea-826b-13f0e75ef952.png)
