### ISSUE TITLE
Allow option to prevent serialization of raw Xero data

### ISSUE THREAD

**Issue by blairjo** [XeroAPI/xero-node#322]
**SDK you're using (please complete the following information):**
 - Version [4.0.6]

**Is your feature request related to a problem? Please describe.**
We store some data from Xero in our local database. In the new version 4 of the library, all objects coming back from Xero are being serialized according to the object's attributeTypeMap, which means that field ids are being changed to lowercase, e.g Name becomes name. This seems like a huge breaking change - none of the data coming back from Xero now matches what we hold in our database.

**Describe the solution you'd like**
Is it possible to have a flag that bypasses the serialize / deserialize functions, and simply leaves the data alone as it came from Xero?

**Describe alternatives you've considered**
I guess I could maybe manually call the serialize method for each item returned, or write my own transformer code.

**Comment by SidneyAllen** [comment]
@blairjo thank you for the feedback - this is a use case we haven't built for but can look at in the future.  It may take some time as our near term focus is on fixing issues and getting full API coverage in our SDKs. 

If this is a total blocker for you, have you considered just rolling your own oauth 2 solution - this will remove the dependency on the SDK for now and help you progress.

We wrote up a blog post on the topic
https://devblog.xero.com/xero-oauth-2-api-whats-new-node-example-94715fc8ff19

**Comment by blairjo** [comment]
@SidneyAllen Thanks for getting back to me. As a workaround for now, I have just overridden the values in the attributeTypeMap for each object so that the properties remain capitalised.
