### ISSUE TITLE
Contact.updatedDateUTC is always invalid

### ISSUE THREAD

**Issue by leviwheatcroft** [XeroAPI/xero-node#323]
**SDK you're using (please complete the following information):**
 - 4.0.6

**Describe the bug**
Calls to `xero.accountingApi.getContacts()` return Contacts with `updatedDateUTC` as and invalid Date object, so `contact.updatedDateUTC.toString()` returns "Invalid Date".

**To Reproduce**
call `xero.accountingApi.getContacts()`

**Expected behavior**
`updatedDateUTC` should be valid date objects.

**Screenshots**
N/A

**Additional context**
The raw json response is a string like `\/Date(1488391422280+0000)\/`

It looks like [this line](https://github.com/XeroAPI/xero-node/blob/master/src/gen/model/accounting/models.ts#L512) calls `Object.deserializer` with the raw string, and 'Date' as the type.

So then [this line](https://github.com/XeroAPI/xero-node/blob/master/src/gen/model/accounting/models.ts#L499) just returns `new Date()` with the raw string.

Also related, not sure whether this should be a separate issue the `Invoice` structure `date` and `dueDate` properties are returned as a raw string. This was the case in 3.x, but now in 4.x this behaviour differs from `updatedDateUTC` which may be unexpected. Additionally, 3.x provided `Invoice.DateString` and `Invoice.DueDateString`, which don't appear to be provided by 4.x, they're still listed in the [API Reference](https://developer.xero.com/documentation/api/invoices)

That said, I must have misunderstood something because if the above were true then no dates would work in any structures and I'm sure someone would have noticed by now.

**Comment by SerKnight** [comment]
Thanks for this feedback - implemented fix in 4.1.1
> https://github.com/XeroAPI/xero-node/releases/tag/4.1.1

Changelog explains why but this is the fix fyi: https://github.com/XeroAPI/xero-node/blob/master/src/gen/model/accounting/models.ts#L500

Screenshot of fix in the sample app
![Screen Shot 2020-01-22 at 5 26 15 PM](https://user-images.githubusercontent.com/2935387/72946840-5e24f080-3d3d-11ea-91ec-6258e8c5131a.png)
> https://github.com/XeroAPI/xero-node-oauth2-app

**Comment by STEVEOO6** [comment]
I'm receiving the same invalid format /Date(1588723200000+0000)/ for an invoices UpdatedDateUTC property when creating an invoice via xero.accountingApi.createInvoices().
