### ISSUE TITLE
undefined properties being returned during deserialization

### ISSUE THREAD

**Issue by blairjo** [XeroAPI/xero-node#325]
**SDK you're using (please complete the following information):**
 - Version [4.0.6]

**Describe the bug**
When data is being deserialized on the way back in from Xero, the code iterates all possible values in the mapping list, and tries to set each field in the attributeTypeMap list, regardless as to whether there is any data for that field. This results in lots of "undefined" property values. 

This causes us a headache because we are writing this data into a firebase database, which does not allow undefined properties. I can write code to clean the data prior to inserting, but there a risk of something getting missed.  This is another breaking change from v3 where it looks like a call to JSON.parse() in the OAuth1HttpClient was filtering out the undefined values.

**To Reproduce**
Call any API that returns data, where not every field is populated in Xero

**Expected behavior**
It would be better if the deserializer only attempts to populate fields that have a value, as per v3.

**Comment by RettBehrens** [comment]
Hey @blairjo I've tested this out and it seems to remove undefined property values consistently:

`JSON.parse(JSON.stringify(response.body))`

Perhaps that will work for your use case? 

Alternatively, if you wish to preserve the keys, you can use a replacer like so:

`JSON.parse(JSON.stringify(response.body, (key, value) => value === undefined ? null : value))`

Unfortunately, from what I know about firebase, you cannot store an object with keys with null or undefined property values. You can, however, store a stringified object with keys with null property values and parse it after retrieval.

If these possible solutions don't work for your use case, the issue may need to be resolved outside of the SDK as it has to do with firebase specifically.

**Comment by blairjo** [comment]
Hi,

Yes, that is the workaround I have implemented, but it would be better if I
didn't need a workaround and Xero-node only serialized properties with a
value, as per version 3. I shouldn't have to use this workaround every time
I call an api method - the Xero node library should be consistent with what
the actual Xero api returns.

Thanks

John
