### ISSUE TITLE
fetching tenant ids

### ISSUE THREAD

**Issue by rhajizadeh** [XeroAPI/xero-node#326]
**SDK you're using :**
 - Version 4.0.2

**Is your feature request related to a problem?.**
Users may have multiple Xero tenant ids that authorised a system to access. Xero-node uses ```fetchConnectedTenantIds``` to refresh the list of connected tenant ids. However, this function is defined as a private one in the typings making it inaccessible from a typescript project. 

**Describe the solution you'd like**
Please make ```fetchConnectedTenantIds``` public in the typings of the package, so we can fetch the tenant ids if we need to.

**Comment by SerKnight** [comment]
Made that function public, but also note that the client has access to `.tenantIds` 

```
const xero = new XeroClient({
        clientId: client_id,
        clientSecret: client_secret,
        redirectUris: [redirectUrl],
        scopes: scopes.split(" "),
      });

=> xero.tenantIds
```

We show how this can work in the sample app by letting you change with tenant you are working with through a dropdown where you can choose through all the tenantId's

> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L98

Thanks for the feedback!
