### ISSUE TITLE
getQuotes api not working.

### ISSUE THREAD

**Issue by hanselke** [XeroAPI/xero-node#328]
**SDK you're using (please complete the following information):**
 - Version 4.0.6

**Describe the bug**
getQuotes method returns undefined

**To Reproduce**
await xero.accountingApi.getQuotes(tenantId)

it returns

response.body: 'oauth_problem=consumer_key_unknown&oauth_problem_advice=Consumer%20key%20was%20not%20recognised'

body:  Quotes { quotes: undefined, '': undefined },

**Expected behavior**
should return with body.quotes object.

my accessToken is valid as i can use it to do await xero.accountingApi.getItems(tenantId)

**Screenshots**

**Additional context**

**Comment by SidneyAllen** [comment]
@hanselke - support for the Quotes API support is new - we'll need to look into this and get back to you with a working example of how to use.
