### ISSUE TITLE
Unable to pass query string parameters (fromDate/toDate) to the getReportBankSummary method

### ISSUE THREAD

**Issue by marcschregardus** [XeroAPI/xero-node#330]
There doesn't appear to be any way to pass the `fromDate` and `toDate` to the Xero Client Accounting API method `getReportBankSummary()`.

I have tried passing as header parameters, but without any success.

Is there a way of exposing the URL to allow the addition of these query string params, or can they be added to the method signature.

**Comment by marcschregardus** [comment]
The associated Xero Support Case # is CX0009427335

**Comment by wobinb** [comment]
The issue appears to originate from the OpenAPI spec that we use to generate the various SDKs (including this one). I've proposed a change to the spec here: https://github.com/XeroAPI/Xero-OpenAPI/pull/113

Once that has been done, the change will filter down to the SDK

**Comment by SidneyAllen** [comment]
@marcschregardus - issue addressed in xero-node 4.1.0

Example added to xero-node-oauth-app 
https://github.com/XeroAPI/xero-node-oauth2-app/pull/16

**Comment by marcschregardus** [comment]
Thanks for updating this - however, when I upgraded the client to use the new API, a number of other items within our code failed (specifically, the `buildConsentUrl()` method is now failing).
