### ISSUE TITLE
Absent types on @4.1.1 version

### ISSUE THREAD

**Issue by ifree92** [XeroAPI/xero-node#336]
xero-node@4.1.1 hasn't types after module has been installed.

I see this line in package.json
```json
{
  "types": "dist/index.d.ts",
  "version": "4.1.1"
}
```

However, dist folder containts only javascript files without types. I think just wrong pushing module on npm.
Just FYI

(For now I'm using previous 4.1.0 version)

**Comment by SerKnight** [comment]
Thank you @ifree92  - you are all set in 4.1.2

Just did a big round of maintenance but moving to more scheduled release cycles. Appreciate your issue.

> https://github.com/XeroAPI/xero-node/commit/6c40fa5e26d3d1322e1e25b82602d94f0cbfa8f2
