### ISSUE TITLE
.getJournals and .getContacts give 401's

### ISSUE THREAD

**Issue by brucem1976** [XeroAPI/xero-node#344]
**SDK you're using (please complete the following information):**
 - 4.1.2

**Describe the bug**
All other endpoints return results, but these two give 401s with exactly the same code path - I've reconnected the same org with Adviser rights a few times, and then connected a second org also with Adviser rights - in all cases - all endpoints worked and only these 2 give 401s

Also - the OAuth1 version of xero-node fetches both Contacts and Journals on the same Org perfectly.

**To Reproduce**
1. Use .getJournals or .getContacts 

**Expected behavior**
The authentication is working perfectly, all the other endpoints before and after these 2 calls work, and these fail right in the middle. Expected to get a page of Contacts and a page of Journals

**Additional context**
URL that it generates for Journals:
`GET /api.xro/2.0/Journals HTTP/1.1\r\nxero-tenant-id: <hidden>\r\nIf-Modified-Since: 1970-01-01T00:00:00.000Z\r\nAuthorization: Bearer <hidden>\r\nhost: api.xero.com\r\naccept: application/json\r\nConnection: close\r\n\r\n',`

**Comment by SerKnight** [comment]
@brucem1976 please update to 4.1.4 - 4.1.3 was patched with a bug fix related to serialization that will fix your described issue.

Thank you for reporting.

**Comment by brucem1976** [comment]
@SerKnight I just updated and tested again (ensured 4.1.4 was definitely installed) and I got exactly the same issue

**Comment by SerKnight** [comment]
Reopened for now.

Are you sure you delete your whole `node_modules` directory or the installed xero-node version and npm install again? I will try to re-create as well but explicitly fixed that issue in 4.1.4

**Comment by brucem1976** [comment]
Hi @SerKnight - thanks. Yes, deleted xero-node in node_modules completely, this is from the currently installed one after npm install:
```
"_from": "xero-node@4.1.4",
  "_id": "xero-node@4.1.4",
  "_inBundle": false,
  "_integrity": "sha512-YstW3k4ps4htinqadbszThpxr70dxFpv/DiT+oBxVwgtHSdR4VjtCwv3PtK5XH7AjEWcak3u4KJ/YCici++D4A==",
  "_location": "/xero-node",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "xero-node@4.1.4",
    "name": "xero-node",
    "escapedName": "xero-node",
    "rawSpec": "4.1.4",
    "saveSpec": null,
    "fetchSpec": "4.1.4"
  },
```

If you can let me know what the issue was pre-4.1.4, how it would have caused problems with getContacts() and getJournals() specifically, I will do some testing and see what I can find from my side too..

**Comment by SerKnight** [comment]
There was a bug fix in how params were serialized for places we passed multiple strings ( https://github.com/XeroAPI/xero-node/commit/4ede28eff1a4dd23c6438384fbfa8b09d7c466ad ) 

For example:
`?Statuses=DRAFT,PAID`
was being passed to Xero like:
`?Statuses[0]=DRAFT&Statuses[1]=PAID`
..

I' trying to replicate the issue with 4.1.4 - but not able to. If you can please replicate using the [sample app](https://github.com/XeroAPI/xero-node-oauth2-app) or the [basic node starter](https://github.com/SerKnight/xero-node-basic-app) I will ensure I dig in asap. 

`const allContacts = await xero.accountingApi.getContacts(req.session.activeTenant)`

# Contacts
> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L553
<img width="1382" alt="Screen Shot 2020-02-04 at 10 48 44 AM" src="https://user-images.githubusercontent.com/2935387/73771655-f9ee2d80-473b-11ea-995e-dfbd328a636f.png">

# Journals
> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L1069
<img width="599" alt="Screen Shot 2020-02-04 at 10 49 53 AM" src="https://user-images.githubusercontent.com/2935387/73771715-18542900-473c-11ea-80a0-95d18968c43f.png">


Also - If wanted to create a ticket by emailing api@xero.com - we can lookup your exact logs and find out exactly why you are getting 401 unauthorized.

**Comment by brucem1976** [comment]
@SerKnight thanks for this suggestion - the sample app connects and fetches contacts and journals fine, so it must be something to do with my initialization at runtime. Is it okay if I post the sequence of commands I use here, or is there a better place to interact on this?

**Comment by brucem1976** [comment]
@SerKnight well this is embarrassing.... I hadn't requested scopes _accounting.contacts_ and _accounting.journals.read_ - amazing how things start working when you actually have permission....

**Comment by SerKnight** [comment]
No worries @brucem1976  - we are working on better error messages for that 500 authentication page. Glad you got it sorted.
