### ISSUE TITLE
Not using express-session messes scopes!

### ISSUE THREAD

**Issue by philliplakis** [XeroAPI/xero-node#345]
**SDK you're using (please complete the following information):**
 - Version  4.1.4

**Describe the bug**
If you remove the express-session and its config, messes last scope in array! 

**To Reproduce**
1. Go to `https://github.com/SerKnight/xero-node-basic-app` and download, install deps and run.
2. add `console.log(xero.config.scopes)`
3. see output :
```JSON
[
"openid",
"profile",
"email",
"accounting.transactions",
"accounting.settings",
"accounting.contacts",
"offline_access"
]
```
4. Remove [this line](https://github.com/SerKnight/xero-node-basic-app/blob/master/index.js#L4) and [these lines](https://github.com/SerKnight/xero-node-basic-app/blob/master/index.js#L23#L28).
5. Re run app.
6. see output :
```JSON
[
"openid",
"profile",
"email",
"accounting.transactions",
"accounting.settings",
"accounting.contacts/toffline_access"]
```

**Expected behavior**
Not break the scopes, I do not need to use a session i would like the option to remove express-session

**Comment by RettBehrens** [comment]
hey @philliplakis, I followed your steps to reproduce but I was unable to reproduce the behavior described. I've pushed the branch I tested with here: https://github.com/SerKnight/xero-node-basic-app/blob/scopes-issue-345/index.js

Could you please try running that to determine whether or not you still experience the issue? If you still experience the issue, could you provide a screen recording?

Thanks
