### ISSUE TITLE
xero.buildConsentUrl() causes TypeError: Cannot read property 'authorizationUrl' of undefined

### ISSUE THREAD

**Issue by hanselke** [XeroAPI/xero-node#346]
**SDK you're using (please complete the following information):**
 - Version 4.1.4

**Describe the bug**
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'authorizationUrl' of undefined
at XeroClient.<anonymous> (/Users/hanselke/Dev/nextactionmeteor/node_modules/xero-node/dist/XeroClient.js:47:43)
at Generator.next (<anonymous>)
at new Promise (<anonymous>)
at __awaiter (/Users/hanselke/Dev/nextactionmeteor/node_modules/xero-node/dist/XeroClient.js:4:12)
at XeroClient.buildConsentUrl (/Users/hanselke/Dev/nextactionmeteor/node_modules/xero-node/dist/XeroClient.js:46:16)

**To Reproduce**
follow the standard setup instructions and get to buildConsentUrl

**Expected behavior**
It should work as it did before.

**Additional context**
Taking a look at the code, this.openIdClient is not defined.

It allows me to start moving forward if i run xero.buildClient() before running buildConsentUrl...

However it started to give me a nbf error on the callback running  xero.setAccessTokenFromRedirectUri(url).

Fixing the nbf error by adding a sleep before calling  xero.setAccessTokenFromRedirectUri(url); gives me yet another error

`
TypeError: Cannot read property 'callbackParams' of undefined
at XeroClient.<anonymous> (/Users/hanselke/Dev/nextactionmeteor/node_modules/xero-node/dist/XeroClient.js:56:46)
at Generator.next (<anonymous>)
at /Users/hanselke/Dev/nextactionmeteor/node_modules/xero-node/dist/XeroClient.js:8:71
at new Promise (<anonymous>)
at __awaiter (/Users/hanselke/Dev/nextactionmeteor/node_modules/xero-node/dist/XeroClient.js:4:12)
at XeroClient.setAccessTokenFromRedirectUri (/Users/hanselke/Dev/nextactionmeteor/node_modules/xero-node/dist/XeroClient.js:55:16)`

**Comment by SerKnight** [comment]
Thank you Hanselke - will update here asap with a patch.

**Comment by ordapadstar** [comment]
We are seeing the same issue, currently blocking our delivering the OAuth2 migration of our Xero integration. Is there a workaround?

**Comment by sebamza17** [comment]
+1

**Comment by SerKnight** [comment]
Hi all - Working on this now - its happening intermittently for me as well. Update asap.

**Comment by mschaeffner** [comment]
The problem is that the constructor of `XeroClient` calls the function `buildClient`. `buildClient` is an async function. But in the constructor there is no "await" when calling this function, because await is not allowed in a constructor. 

https://github.com/XeroAPI/xero-node/blob/6afd4131c1df4f74f689e5e23e884bac91d04af7/src/xeroClient.ts#L19

A quick workaround would be the following:
```
const xero = new xero_node.XeroClient(xeroConfig)
await xero.buildClient()
const consentUrl = await xero.buildConsentUrl()
```

**Comment by AlexanderButyaev** [comment]
Why don't you want to just remove this.buildClient() call from the constructor and make users explicitly call it in the code (like @mschaeffner proposed)?

**Comment by SerKnight** [comment]
Hi all - a large client refactor has been released.. The docs now reflect the proper authentication process:
```js
const port = process.env.PORT || 3000

const xero = new XeroClient({
  clientId: 'YOUR_CLIENT_ID',
  clientSecret: 'YOUR_CLIENT_SECRET',
  redirectUris: [`http://localhost:${port}/callback`],
  scopes: 'openid profile email accounting.transactions offline_access'.split(" ")
});

await xero.initialize();

let consentUrl = await xero.buildConsentUrl();

res.redirect(consentUrl);
```

Keep us posted on any issues / feedback is appreciated and all community suggestions will be considered.

https://github.com/XeroAPI/xero-node#making-offline_access-calls

--

Additional context in my closure of:
https://github.com/XeroAPI/xero-node/issues/358

**Comment by chilts-reconcilely** [comment]
Hi @SerKnight,

Thanks for the update. I'll report that I've upgraded my test app from v4.2.0 to v4.4.2 and I've managed to get it working again.

I had the workaround to `await xero.buildClient()` after the constructor, so just swapped that out for `await xero.initialize()` and it works fine.

The only other things I had to contend with (whilst looking at the differences in the CHANGELOG.md) were swapping `xero.setAccessTokenFromRedirectUri()` to `xero.apiCallback()` but also populating the tenants with `xero.updateTenants()`.

Hopefully this is useful to any stumbling here. All seems fine at the moment. Thanks again.

**Comment by AlexanderButyaev** [comment]
Hi @SerKnight,

Just updated to v4.4.4. I followed steps @chilts-reconcilely described but still wasn't able to run... Even after step by step debugging and executing code from readme - I get 403 AuthenticationUnsuccessful and Forbidden All the time. Checked scopes, keys, code - all how it's supposed to be...

**Comment by SerKnight** [comment]
Thanks for the update @AlexanderButyaev - 

I've tried to outline this in the docs - if there is an improvement in our docs that you think can be made I'd be happy to implement.
https://github.com/XeroAPI/xero-node#basics

**Comment by SerKnight** [comment]
So yes - the disconnect function actually wants the 'disconnect' object's ID. A "Connection" obj is essentially a mapping of the tenant connection and is ultimately part of how the tokens are generated - Might be worth us adding another comment there.

> https://github.com/XeroAPI/xero-node#basics

^^ disconnect
