### ISSUE TITLE
BatchPaymentDetails not being populated for a Contact

### ISSUE THREAD

**Issue by marcschregardus** [XeroAPI/xero-node#347]
When collecting a `Contact` using the Node API (or http request directly - https://api.xero.com/api.xro/2.0/Contacts) the `BatchPaymentDetails` node is not being populated.

When the API viewer is used, this object is correctly populated on the `Contact`.

The documentation only displays the `BankAccountDetails` (which is what I'm using for a work around for the moment - but this doesn't give me the bank account name). It doesn't mention the `BatchPaymentDetails` object. Is this no longer supported in the new API? (in which case, how can I obtain the Bank Account Name?)

**Comment by RettBehrens** [comment]
Hi @marcschregardus I just used the api previewer and the xero-node sdk to get an individual contact from the Demo Company and got BatchPayments on both responses. I lifted the contactID from the url while viewing Bayside Club in the Demo Company. You can see Bayside Club -> BatchPayments -> BankAccountName is "Madeup Town Bank".

From the sdk:
`const contact = await xero.accountingApi.getContact(req.session.activeTenant, '82d67717-1d2e-4f44-be65-f73a68df8a9f');`

`{
  "contacts": [
    {
      "contactID": "82d67717-1d2e-4f44-be65-f73a68df8a9f",
      "contactStatus": "ACTIVE",
      "name": "Bayside Club",
      "firstName": "Bob",
      "lastName": "Partridge",
      "emailAddress": "bob.partridge@bayclub.co",
      "skypeUserName": "bayside577",
      "contactPersons": [],
      "bankAccountDetails": "101-555-101 00123-12345",
      "taxNumber": "EIN 55-123456",
      "accountsReceivableTaxType": "INPUT",
      "accountsPayableTaxType": "OUTPUT",
      "addresses": [
        {
          "addressType": "POBOX",
          "addressLine1": "P O Box 3354",
          "addressLine2": "South Mailing Centre",
          "city": "Oaktown",
          "region": "NY",
          "postalCode": "12345",
          "country": "USA",
          "attentionTo": "Club Secretary"
        },
        {
          "addressType": "STREET",
          "addressLine1": "79 Madison Ave, Fl 2",
          "addressLine2": "",
          "addressLine3": "",
          "addressLine4": "",
          "city": "New York",
          "region": "NY",
          "postalCode": "10016",
          "country": "USA",
          "attentionTo": "Club Secretary"
        }
      ],
      "phones": [
        {
          "phoneType": "DDI",
          "phoneNumber": "5554418",
          "phoneAreaCode": "202",
          "phoneCountryCode": ""
        },
        {
          "phoneType": "DEFAULT",
          "phoneNumber": "5554455",
          "phoneAreaCode": "102",
          "phoneCountryCode": ""
        },
        {
          "phoneType": "FAX",
          "phoneNumber": "5555566",
          "phoneAreaCode": "102",
          "phoneCountryCode": ""
        },
        {
          "phoneType": "MOBILE",
          "phoneNumber": "5554455",
          "phoneAreaCode": "101",
          "phoneCountryCode": ""
        }
      ],
      "isSupplier": true,
      "isCustomer": true,
      "updatedDateUTC": "2020-02-05T18:25:12.823Z",
      "contactGroups": [],
      "batchPayments": {
        "bankAccountNumber": "101-555-101 00123-12345",
        "bankAccountName": "Madeup Town Bank",
        "details": "OIT-US",
        "code": "",
        "reference": ""
      },
      "balances": {
        "accountsReceivable": {
          "outstanding": -16,
          "overdue": 0
        },
        "accountsPayable": {
          "outstanding": 130,
          "overdue": 130
        }
      },
      "attachments": [],
      "hasAttachments": false,
      "hasValidationErrors": false
    }
  ]
}`

From the previewer:
`<Response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Id>b70caf7e-4a6a-4c34-8e38-c7123f5ec8a7</Id>
  <Status>OK</Status>
  <ProviderName>Xero API Previewer</ProviderName>
  <DateTimeUTC>2020-02-28T15:21:48.0367494Z</DateTimeUTC>
  <Contacts>
    <Contact>
      <ContactID>82d67717-1d2e-4f44-be65-f73a68df8a9f</ContactID>
      <ContactStatus>ACTIVE</ContactStatus>
      <Name>Bayside Club</Name>
      <FirstName>Bob</FirstName>
      <LastName>Partridge</LastName>
      <EmailAddress>bob.partridge@bayclub.co</EmailAddress>
      <SkypeUserName>bayside577</SkypeUserName>
      <BankAccountDetails>101-555-101 00123-12345</BankAccountDetails>
      <TaxNumber>EIN 55-123456</TaxNumber>
      <AccountsReceivableTaxType>INPUT</AccountsReceivableTaxType>
      <AccountsPayableTaxType>OUTPUT</AccountsPayableTaxType>
      <Addresses>
        <Address>
          <AddressType>POBOX</AddressType>
          <AddressLine1>P O Box 3354</AddressLine1>
          <AddressLine2>South Mailing Centre</AddressLine2>
          <City>Oaktown</City>
          <Region>NY</Region>
          <PostalCode>12345</PostalCode>
          <Country>USA</Country>
          <AttentionTo>Club Secretary</AttentionTo>
        </Address>
        <Address>
          <AddressType>STREET</AddressType>
          <AddressLine1>79 Madison Ave, Fl 2</AddressLine1>
          <City>New York</City>
          <Region>NY</Region>
          <PostalCode>10016</PostalCode>
          <Country>USA</Country>
          <AttentionTo>Club Secretary</AttentionTo>
        </Address>
      </Addresses>
      <Phones>
        <Phone>
          <PhoneType>DDI</PhoneType>
          <PhoneNumber>5554418</PhoneNumber>
          <PhoneAreaCode>202</PhoneAreaCode>
        </Phone>
        <Phone>
          <PhoneType>DEFAULT</PhoneType>
          <PhoneNumber>5554455</PhoneNumber>
          <PhoneAreaCode>102</PhoneAreaCode>
        </Phone>
        <Phone>
          <PhoneType>FAX</PhoneType>
          <PhoneNumber>5555566</PhoneNumber>
          <PhoneAreaCode>102</PhoneAreaCode>
        </Phone>
        <Phone>
          <PhoneType>MOBILE</PhoneType>
          <PhoneNumber>5554455</PhoneNumber>
          <PhoneAreaCode>101</PhoneAreaCode>
        </Phone>
      </Phones>
      <UpdatedDateUTC>2020-02-05T18:25:12.823</UpdatedDateUTC>
      <IsSupplier>true</IsSupplier>
      <IsCustomer>true</IsCustomer>
      <BatchPayments>
        <BankAccountNumber>101-555-101 00123-12345</BankAccountNumber>
        <BankAccountName>Madeup Town Bank</BankAccountName>
        <Details>OIT-US</Details>
      </BatchPayments>
      <Balances>
        <AccountsReceivable>
          <Outstanding>-16.00</Outstanding>
          <Overdue>0.00</Overdue>
        </AccountsReceivable>
        <AccountsPayable>
          <Outstanding>130.00</Outstanding>
          <Overdue>130.00</Overdue>
        </AccountsPayable>
      </Balances>
      <HasAttachments>false</HasAttachments>
    </Contact>
  </Contacts>
</Response>`

Closing this issue but reopen it if this doesn't solve your problem.
