### ISSUE TITLE
UnhandledPromiseRejectionWarning: RPError: JWT not active yet, now 1580710946, nbf 1580710950

### ISSUE THREAD

**Issue by Zubair-Ashraf** [XeroAPI/xero-node#348]
using version 4.1.4

I just cloned the repo and started the server.
My app connected successfully with xero but after that when navigates to "/callback", it throws an error which says

**"UnhandledPromiseRejectionWarning: RPError: JWT not active yet, now 1580710946, nbf 1580710950"**

I'm unable to make any calls (getting organizations, invoices etc.) after this error due to unavailablity of a **access_token**

Is anyone also facing this issue? Any kind of help will be appreciated.

**Comment by SerKnight** [comment]
Zubair - are you running the https://github.com/XeroAPI/xero-node-oauth2-app Sample App?

When you say you cloned the repo do you mean you have imported the NPM package to a project?

A little more info and I can assist you on this!

**Comment by ZubairAshraf111** [comment]
I and using this repo https://github.com/XeroAPI/xero-node
Now i seen when i run same code on other system that works fine but when i use https://github.com/XeroAPI/xero-node and  https://github.com/XeroAPI/xero-node-oauth2-app both repo on my system so it throw error JWT not active yet


![Error](https://user-images.githubusercontent.com/57169065/73717072-931c4480-473a-11ea-9253-8749fbaa452f.PNG)

**Comment by kylethacker05** [comment]
using version 4.1.5
I am also getting this error, both with my application and the sample app.
![image](https://user-images.githubusercontent.com/25633243/73838742-1e432a80-4860-11ea-8e2e-54c873b355b1.png)

**Comment by SerKnight** [comment]
This seems to be a side effect of mismatched OS time.. Closing but please re-open with more details if it is a continued blocker with the recent release.. Note the release will require some light refactoring to your auth flow & functions.
