### ISSUE TITLE
Account data structure has a member named "_class", not "class"

### ISSUE THREAD

**Issue by brucem1976** [XeroAPI/xero-node#349]
**SDK you're using (please complete the following information):**
 - 4.2.1

**Describe the bug**
All data structure members seem to start with a lowercase letter, but 'class' in Account has an underscore at the start of the name, which seems like a unique exception

**Comment by SerKnight** [comment]
Thanks Bruce - While our core API has a `Class` field on the Account object. However Class is a reserved word in core JS so gets serialized as the `_class` attribute. Better documentation is coming soon!

For reference: http://www.ecma-international.org/ecma-262/5.1/#sec-7.6.1.2
