### ISSUE TITLE
Potential race condition when initialising client

### ISSUE THREAD

**Issue by daffron** [XeroAPI/xero-node#358]
**SDK you're using (please complete the following information):**
 - Version 4.1.5

**Describe the bug**
When trying to use the package, in a realistic way. (Create a client within an endpoint or process) function calls fail due to `this.openIdClient` being `undefined`. I'll include some logs below.

The auth flow, and examples seem to work due to using the global defined client

**To Reproduce**
Create a client using an access token, then try and immediate use it

**Expected behavior**
Client is created, then method called synchronously 

**Screenshots**
```
buildClient()
DIFF -1579475723343
createXeroClientWithLock() - Partner App, Access Token expires in -18281d
createXeroClientWithLock() - Refreshing Access Token
This.openIdClient  - refreshToken() undefined
TypeError: Cannot read property 'refresh' of undefined
    at XeroClient.<anonymous> (/home/daffron/late-chaser/node_modules/xero-node/dist/XeroClient.js:89:53)
    at Generator.next (<anonymous>)
    at /home/daffron/late-chaser/node_modules/xero-node/dist/XeroClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/daffron/late-chaser/node_modules/xero-node/dist/XeroClient.js:4:12)
    at XeroClient.refreshToken (/home/daffron/late-chaser/node_modules/xero-node/dist/XeroClient.js:83:16)
    at createXeroClient (/home/daffron/late-chaser/lib/xero-client.js:49:45)
GET /auth/xero/ping 200 609.353 ms - 27
this.openIdClient - buildClient() Client {
  authorization_signed_response_alg: 'RS256',
  client_id: '7D0075439B1D8D139D1',
  client_secret: 'blah',
 ....
```
Added logs:
```
    buildClient() {
      console.log('buildClient()')
        return __awaiter(this, void 0, void 0, function* () {
            const issuer = yield openid_client_1.Issuer.discover('https://identity.xero.com');
            this.openIdClient = new issuer.Client({
                client_id: this.config.clientId,
                client_secret: this.config.clientSecret,
                redirect_uris: this.config.redirectUris,
            });
            this.openIdClient[openid_client_1.custom.clock_tolerance] = 5;

            console.log('this.openIdClient - buildClient()', this.openIdClient)
        });
    }
...

refreshToken() {
        return __awaiter(this, void 0, void 0, function* () {
            if (!this.tokenSet) {
                throw new Error('tokenSet is not defined');
            }

            console.log('This.openIdClient  - refreshToken()', this.openIdClient)
            this.tokenSet = yield this.openIdClient.refresh(this.tokenSet.refresh_token);
            this.setAccessTokenForAllApis();
            yield this.fetchConnectedTenantIds();
        });
    }
```

**Comment by daffron** [comment]
I'm assuming this works similar to v3, where you initialise the client with the access token,

I see that `await xeroClient.setTokenSet(accessToken)` can now be called, does this mean we should create a single client, and call that for each process we do? Sorry cannot seem to find any docs on this part of the library

**Comment by daffron** [comment]
Tried the work around in `https://github.com/XeroAPI/xero-node/issues/346#issuecomment-583330717` which worked for this too

**Comment by chilts-reconcilely** [comment]
One thing I noticed @daffron is that the `xero.setTokenSet()` should be called with a `tokenSet` rather than just the `accessToken` as you had in your comment. From what I can see, the token set incorporates an `accessToken`.

e.g.

```
tokenSet: {
  id_token: '...',
  access_token: '...',
  expires_at: 1581485xxx,
  token_type: 'Bearer',
  refresh_token: '...',
  session_state: '...'
},
```

This also wasn't clear to me either though I've had some success doing it that way. I agree with you though, the workaround in #346 also works for me.

**Comment by SerKnight** [comment]
Hi all - 

I've tried to address a number of changes in the recent release.

You can expect future changes to be more bite sized - but used this as an opportunity to make a few structural **BREAKING** changes - this included. 

If anyone encounters issues related to this ticket and the new release, or has recommendations on improving the documentation or the sample app ( https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L127 ) don't hesitate to open another issue!
---

Large release/improvement (4.4.0) to the xero-node SDK..  Based off community feedback & our teams personal usage:
* Simpler client fn() naming conventions
* Added /disconnect helper
* Added updateTenants() helper to fetch and serialize all connected org names + other org data
* Added client tests & GitHub actions CI/runner
* Massive Readme re-vamp for usage + Updated sample app with refresh/disconnect
