### ISSUE TITLE
Version 4.1.7 getInvoiceAttachments returning undefined

### ISSUE THREAD

**Issue by clethrill** [XeroAPI/xero-node#359]
- Version 4.1.7

Call to getInvoiceAttachments returns undefined. I can see in response.body the correct JSON result, however body.attachments is undefined.

```
const attachmentResponse = await xero.accountingApi.getInvoiceAttachments(xero.tenantIds[0], invoiceId)
console.log(attachmentResponse)

// attachmentResponse.response.body is the correct JSON object
// attachmentResponse.body.attachments is undefined
```

**Expected behavior**
I would expect attachmentResponse.body.attachments to equal JSON.parse(attachmentResponse.response.body)

**Screenshots**
![Screen Shot 2020-02-11 at 10 41 28 am](https://user-images.githubusercontent.com/1316802/74200449-1ef21b80-4cbb-11ea-982b-be406bf0cbcb.png)

**Comment by SidneyAllen** [comment]
@clethrill - attachmentResponse.body.attachments is an array of attachment objects.

Check the number of objects returned
attachmentResponse.body.attachments.length

Get the attachementId for the first attachment object,
attachmentResponse.body.attachments[0].attachmentID

**Comment by clethrill** [comment]
Checking the length of attachmentResponse.body.attachments throws an error because attachmentResponse.body.attachments is undefined as shown in the screenshot on the bottom line.

**Comment by clethrill** [comment]
xero.accountingApi.createInvoiceAttachmentByFileName also returns undefined instead of an array on success.

```
const results = await xero.accountingApi.createInvoiceAttachmentByFileName(xero.tenantIds[0], invoiceID, attachmentDetails.fileName, true, pdf)
console.log('Response from xero attachment', results.body)
// logs: 'Response from xero attachment Attachments { attachments: undefined }'
```
