### ISSUE TITLE
Link to the docs from this GitHub project

### ISSUE THREAD

**Issue by chilts-reconcilely** [XeroAPI/xero-node#360]
Hiya, this is just a small project request rather than a feature request for code.

Would it be possible to edit the 'Website' in this project to link to https://xeroapi.github.io/xero-node/ - I know I'd find it useful and perhaps other people might too.

Many thanks.

**Comment by SidneyAllen** [comment]
@chilts-reconcilely - we link to the docs from the README under the heading "SDK Reference"

https://github.com/XeroAPI/xero-node#sdk-documentation
