### ISSUE TITLE
3.1.2 - typedoc package still a dependency

### ISSUE THREAD

**Issue by ibox4real** [XeroAPI/xero-node#361]
**SDK you're using (please complete the following information):**
 - Version 3.1.2

**Describe the bug**
Typedoc is still in the dependencies list and adds an extra 58M to node_modules for no reason

**Comment by SerKnight** [comment]
Thanks for pointing out @ibox4real 

Current list of dependencies at time I am closing this issue:

```
 "devDependencies": {
    "@types/jest": "^24.9.1",
    "@types/node": "^12.12.21",
    "@types/request": "^2.48.4",
    "jest": "^24.9.0",
    "open": "^6.4.0",
    "prompt": "^1.0.0",
    "ts-jest": "^24.3.0",
    "typescript": "^3.8.2",
    "nock": "^12.0.1",
    "sinon": "^9.0.0"
  },
  "dependencies": {
    "openid-client": "^3.9.2",
    "request": "^2.88.0"
  }
```

Also we realize request is not the highest supported http lib, and will address that in future releases.
