### ISSUE TITLE
Docs incorrectly show passing `accessToken` to `setTokenSet()`

### ISSUE THREAD

**Issue by chilts-reconcilely** [XeroAPI/xero-node#362]
**SDK you're using (please complete the following information):**

 - Version [e.g. 4.1.7]

**Describe the bug**

The docs show the passing of an `accessToken` to `setTokenSet()` instead of an actual `tokenSet`.

* e.g. https://xeroapi.github.io/xero-node/#api-Accounting-createAccount

**Screenshots**

![2020-02-19-101802_513x357_scrot](https://user-images.githubusercontent.com/43312462/74778906-64d56200-5301-11ea-90e1-5a76cf865678.png)

**Additional context**

One problem with the current docs and all of the current examples (e.g. https://github.com/XeroAPI/xero-node#javascript-example and even https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts) show the usage of using the `new xeroNode.XeroClient({ ... })` as a global instance using only one connected Xero account. It's been really hard to figure out exactly how to use it with multiple connected accounts. We've figured out a few things but also hitting problems such as the following:

* https://github.com/XeroAPI/xero-node/issues/358
* https://github.com/XeroAPI/xero-node/issues/346

And whilst we **think** we have workarounds, it's a little opaque as to how to do things properly. I'm happy to demonstrate this with a small server so you can see the problem but it'd be great to see an example where the `xeroClient` is:

1. created in each HTTP request where required
2. with a workaround similar to what is shown in https://github.com/XeroAPI/xero-node/issues/346#issuecomment-583330717
3. a call to `.setTokenSet()` to set the correct credentials from the HTTP session/database/other storage
4. and two endpoints showing a call to `xeroClient.accountingApi.getOrganisations()` and perhaps https://api.xero.com/connections so we can see how that works too

**Comment by SerKnight** [comment]
Docs have been updated - thank you for the issue:
```javascript
const tokenSet: TokenSet =  {
  id_token: 'xxx',
  access_token: 'yyy',
  expires_at: 1582308862,
  token_type: 'Bearer',
  refresh_token: 'zzz',
  session_state: 'xxx'
}
await xero.setTokenSet(tokenSet);
```

However - your second point is interesting. If you can simplify what you mean with a small server showing the issue It will be easier to understand.

There will be some client refactors coming next week that simplify the client setup, so your workaround will help in informing those changes.

**Comment by RettBehrens** [comment]
when XeroClient is initialized, a call to the connections endpoint is happening under the hood. `xero.tenantIds` is an array of all connected tenants and `xero.tenantIds[0]` is the active tenant

`[
    {
        "id": "c869f3b7-6435-4c7e-8cb2-122721b04a69",
        "tenantId": "45e4708e-d862-4111-ab3a-dd8cd03913e1",
        "tenantType": "ORGANISATION",
        "createdDateUtc": "2020-02-02T19:17:58.1117990",
        "updatedDateUtc": "2020-02-02T19:17:58.1117990"
    },
    {
        "id": "74305bf3-12e0-45e2-8dc8-e3ec73e3b1f9",
        "tenantId": "c3d5e782-2153-4cda-bdb4-cec791ceb90d",
        "tenantType": "ORGANISATION",
        "createdDateUtc": "2020-01-30T01:33:36.2717380",
        "updatedDateUtc": "2020-02-02T19:21:08.5739590"
    }
]`

`[
    '45e4708e-d862-4111-ab3a-dd8cd03913e1',
    'c3d5e782-2153-4cda-bdb4-cec791ceb90d'
  ]`

would it be useful to potentially have a `xero.tenants` that shows the whole connection object?
