### ISSUE TITLE
Initialize xero client based on tokenSet

### ISSUE THREAD

**Issue by leantorres73** [XeroAPI/xero-node#364]
**SDK:**
 - Version 4.1.7

**Description of what I'm trying to do**
I have an API as the library suggests that redirects and gets the tokenSet from the user flow. 
This first part works great, but what I want is to store that token and use it in another place (another microservice or API). For example, I want to have a process that refreshes the token automatically.

I thought that just using this three lines it will work, but it doesn't:

       

        const tokenSet = new TokenSet(tokenFromDatabase);

        await xeroClient.setTokenSet(tokenSet);

        await xeroClient.refreshToken();

I can guess the library also needs the XeroClient initialized before with the buildConsentUrl and setAccessTokenFromRedirectUri.
Please correct me if I'm wrong (Right now that code is throwing `Cannot read property 'refresh' of undefined`. 

**Description of the solution I'd like**
I want to configure the xero client using just the token set if possible. With that I can have on one side, an API that generates the token with manual interaction and renews the token, and on the other side an API that reads from db the token, and make the calls

**Comment by SerKnight** [comment]
Hey @leantorres73 - I'm working to simplify the helper functions in the XeroClient in the next large release. Have some existing issues related to re-factoring the client.

I've update the docs to show that `setTokenSet` actually takes in the whole openid-client token set which is an object with the access_token nested.

Will do some thinking about how to best simplify to fit everyones use case - mid next week will bounce some ideas back to the community.

Here is the fixed docs, expected `tokenSet` that `setTokenSet` accepts.
```javascript
const tokenSet: TokenSet =  {
  id_token: 'xxx',
  access_token: 'yyy',
  expires_at: 1582308862,
  token_type: 'Bearer',
  refresh_token: 'zzz',
  session_state: 'xxx'
}
```

**Comment by SerKnight** [comment]
Can I ask how you are currently storing the token? Are you storing `access_token` and `refresh_token` separately, or are you storing the parsed `tokenSet` ^

**Comment by chilts-reconcilely** [comment]
If it helps, this is what I'll be doing. I'll be storing the parsed `tokenSet` (encrypted, of course), so just calling `.setTokenSet()` seems fine to me.

**Comment by leantorres73** [comment]
Hey guys, I was able to make it work, I need to build client before calling the set token function. I'll be waiting the new release with the simplifications on the helper functions, thanks!

**Comment by SerKnight** [comment]
Hi all - a large client refactor has been released.. Hoping this sweeping change fixes numerous of our communities recent issues. I look forward to getting and code/documentation feedback.

For these offline access calls you will need to create & then `initialize()` the client.. The docs should now actually reflect the proper workflow.

Keep me posted on any issues!

https://github.com/XeroAPI/xero-node#making-offline_access-calls

--

Additional context in my closure of:
https://github.com/XeroAPI/xero-node/issues/358
