### ISSUE TITLE
Return whole connection object instead of just tenantId to utilise the updateDateUTC value to find latest connected tenant

### ISSUE THREAD

**Issue by kylethacker05** [XeroAPI/xero-node#365]
Currently I have modified the package to return the whole connection object instead of just the tenantId from the get tenantIds method so i can sort the connections by the updatedDateUTC field. This would be nice to have standard. The .Net sdk recently implemented this feature.

**Comment by SerKnight** [comment]
Hi @kylethacker05 - thank you for this feature request..

I have included it in the recent release - however there are also other changes that will require some light refactoring.. I hope the improved readme will make this crystal clear, but please inquire if there are other improvements we can make to the docs.

In addition to some changes in how the xeroClient is initialized, please read the section on the `updateTenants` fn which will call out for each of your connected tenants and nest all that data under the xero.tenants getter. It will include the updatedDateUTC as well as the org name.


---

Large release/improvement (4.4.0) to the xero-node SDK..  Based off community feedback & our teams personal usage:
* Simpler client fn() naming conventions
* Added /disconnect helper
* Added updateTenants() helper to fetch and serialize all connected org names + other org data
* Added client tests & GitHub actions CI/runner
* Massive Readme re-vamp for usage + Updated sample app with refresh/disconnect
