### ISSUE TITLE
invalid_grant when trying to refreshToken()

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#370]
Version 4.2.0

Getting invalid_grant with the following code

```
await xero.refreshToken();
const tokenSet = await xero.readTokenSet()

await xero.setTokenSet(tokenSet)
const apiResponse = await xero.accountingApi.getItems(<TENANT_ID>)

```

I'm not sure why. How otherwise to refresh the token?

It works with the normal accessToken (while it's valid for the first 30 mins)

**Comment by sandorvasas** [comment]
Plus, today, I'm also getting invalid grant with this (yesterday was working fine **I think**):
```ts
try {
      await xero.setTokenSet(xa.getXeroAccessTokenSet())
    
      await xero.accountingApi.getOrganisations(xa.xeroTenantId)
    }
    catch (e) {
      if (e.response && e.response.statusCode && e.response.body) {
        if (e.response.body.status == 401 &&
            e.response.body.detail.includes("TokenExpired")) {
    //      await xero.setTokenSet(xa.getXeroAccessTokenSet())
          await xero.refreshToken();
          const tokenSet = await xero.readTokenSet()
          xa.setXeroAccessTokenSet(tokenSet)
          await XeroAccountModel.updateOne({ _id: xa._id }, { xeroAccessToken: xa.xeroAccessToken })
        } else {
          throw e;
        }
      } else {
        throw e;
      }
    }
```
This is based off of your sample app.

Could you at least return more details besides `{error: invalid_grant}` please? Doesn't really say much. Neither do the docs "could be because of a number of reasons". 

What about the March 1st deadline? We're rushing to keep it so users can migrate to Oauth2 but we can't roll it out to prod having these issues.

**Comment by SerKnight** [comment]
Hi @sandorvasas - Don't worry about a March deadline! Oauth1.a will continue to work through the end of 2020. Related to this exact issue. I'm not sure what could have changed.. If you had not updated the package version there were certainly no changes on that NPM package version.

I recommend being explicit on pinning package versions as this repo is continually being improved.. We are doing our best to follow proper Semver standards but as you know there have been some inconsistencies - we have tried to do a sweeping fix for some of these types of issues in 4.4.0 release.

**It will be a breaking change**, but is very well documented. The main changes will be the client  `buildConsentUrl()` or using `initialize()` as well as the `updateTenants()` helper.. I will close this issue as this release addresses a lot of the problems we've seen in the past weeks.

In addition to the readme, the new code is well showcased in the sample app and it should show much more clearly how to set & refresh tokens you receive back from the initial auth flow:
https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L127

---

Large release/improvement (4.4.0) to the xero-node SDK..  Based off community feedback & our teams personal usage:
* Simpler client fn() naming conventions
* Added /disconnect helper
* Added updateTenants() helper to fetch and serialize all connected org names + other org data
* Added client tests & GitHub actions CI/runner
* Massive Readme re-vamp for usage + Updated sample app with refresh/disconnect

**Comment by sandorvasas** [comment]
I have not changed the version, nor reinstalled xero-node. It is _exactly_ the same package. I just started getting invalid_grants when running the cron job to update the refresh tokens. And there is no indication or description why that is happening.

**Comment by SerKnight** [comment]
Do you know when the refresh token was issued? They last for 60 days ( up from 30 days ) so if you are refreshing the tokenSet at least once per 59 days that should be workable. With some additional code and your client info we can look into your logs in more detail if this persists as a problem.. You can email api@xero.com with your sensitive details to start an api support ticket

**Comment by priyatoshojha** [comment]
Hey I am trying to refresh token after 30 minutes but it expires and getting error like **invalid_grant**
I have to reconnect manually then I get again refresh token and it saved in db, but If I want to use same refresh token to connect then is there any other options.?

**Comment by SerKnight** [comment]
@priyatoshojha - checkout the following line in the sample app. This shows how to use the most recent refresh token in the database to create a new client, and then refresh for a new `token_set`, which will include a new access and refresh token to store in DB again


```js
const newTokenSet = await newXeroClient.refreshWithRefreshToken(client_id, client_secret, tokenSet.refresh_token)
```

> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L262

**Comment by shash7** [comment]
@sandorvasas did you get it working?
