### ISSUE TITLE
4.4.2 - Which tenant id did the user select?

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#374]
V 4.4.2
This might not be a bug, but it's quite unclear to me at this point.

I was authorizing the app to a multi-tenanted xero account (e.g. DemoCompany and TrialCompany), got back the access token for TrialCompany, then updateTenants() correctly lists these two. I had autoselected the first tenant in the list, then I was getting AuthenticationUnsuccessful. (But the tokenset is valid.)

Then I realized I'm selecting the wrong organization when trying to getAccounts() to test the connectivity. (DemoCompany instead of TrialCompany).

So my question is: How do we know which organization the user selected during the authorization flow? The redirectUri parameters don't seem to contain that. 

Could you pass the tenant id to the redirectUri, which in turn would be forwarded to the exchange oauth2 function on our server, and possibly put into the tokenSet too? But at least having it in the redirectUri would enough, so we know what org the user had selected.

Edit: I jwt-decoded `tokenSet.id_token` & `tokenSet.access_token`,  but they don't seem to contain any ids that updateTenants() returns: nor `id`, nor `tenantId`.

**Comment by RettBehrens** [comment]
hey @sandorvasas you should be able to see all connected tenants via xeroClient.tenants and the active connected tenant via xeroClient.tenants[0], however, in testing this I'm also experiencing some inconsistencies that I'm digging into now

**Comment by sandorvasas** [comment]
Oh i see. Yeah i am autoselecting the first tenant from the list but yesterday that didnt work anymore

**Comment by sandorvasas** [comment]
any updates on this?

**Comment by RettBehrens** [comment]
There will be a fix in 4.4.3 which should be built and deployed soon. I'll update you when it's published.

`updateTenants()` will sort the connections such xeroClient.tenants[0] will indeed be the active tenant.

**Comment by RettBehrens** [comment]
4.4.3 is out and the fix is included. 
updateTenants() will sort the connections such that xeroClient.tenants[0] will indeed be the active tenant.
