### ISSUE TITLE
TypeError: tokenSet.expired is not a function

### ISSUE THREAD

**Issue by daffron** [XeroAPI/xero-node#377]
**SDK you're using (please complete the following information):**
 - Version 4.4.3

**Describe the bug**
When calling the the `expired()` function on tokenSet, which was retrieved from `readTokenSet()`, the not a function type error occurs. This was previously working, and is still in the docs.

**To Reproduce**
```
    const tokenSet = await xeroClient.readTokenSet()
  
    if (tokenSet.expired()) {
    ...
```

**Expected behavior**
Function is defined

**Screenshots**

**Additional context**

**Comment by RettBehrens** [comment]
hey @daffron I'm unable to reproduce this issue. I've tested it using this starter [repo](https://github.com/XeroAPI/xero-node-oauth2-ts-starter) checking `tokenSet.expired()` under the call to the organisations endpoint.

If this was previously working for you and now isn't, I'm guessing you updated the version and that a breaking change outlined [here](https://github.com/XeroAPI/xero-node/releases/tag/4.4.1) is the culprit.

If the issue persists, please reopen this issue with more details.
