### ISSUE TITLE
Custom base api url

### ISSUE THREAD

**Issue by xFLy3r** [XeroAPI/xero-node#380]
Hi guys. Is there an option to configure the base API url? (i.e like api.xero.com, identity.xero.com, etc).

**Comment by SerKnight** [comment]
Not Hey @xFLy3r - not currently. The default base path is generated in the Xero-OpenAPI spec for each portion of our API. As we add more functionality ( payroll, assets, files ) they will all have their own base path.

Can you elaborate on your need for this?

Xero Node:
https://github.com/XeroAPI/xero-node/blob/master/src/gen/api/accountingApi.ts#L68

Open API Spec: https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/xero_accounting.yaml#L12

**Comment by xFLy3r** [comment]
Thanks for reply. I wanted it to be configurable to use it in integration tests within docker.

**Comment by SerKnight** [comment]
Ah - good to know. Will be adding some more robust tests in the coming weeks. If you want to document with a bit more detail, we can potentially see how that works into the project.

Certainly don't want to make it harder to test!
