### ISSUE TITLE
updateTenants() requires accounting.settings.read scope

### ISSUE THREAD

**Issue by timdiacon** [XeroAPI/xero-node#384]
The updateTenants() method requires the accounting.settings.read scope otherwise it fails with an auth error. Would be good to mention this in the documentation

**Comment by RettBehrens** [comment]
hey @timdiacon thanks for catching this! I'll update the documentation today

**Comment by jasperkennis** [comment]
On the readme, under https://github.com/XeroAPI/xero-node#accounting-api, this method is used but the required scope is not specified. If the scope is still required, it is not clear from the example.
