### ISSUE TITLE
dueDate and date are not formatted correctly

### ISSUE THREAD

**Issue by leantorres73** [XeroAPI/xero-node#385]
**SDK you're using (please complete the following information):**
 - Version 4.4.2

**Describe the bug**
dueDate and date are displayed in different format than expected. The documentation of the invoice is:
`/**
    * Date invoice is due – YYYY-MM-DD
    */
`

but the real response is:

` "dueDate": "/Date(1585612800000+0000)/",
`

**To Reproduce**
1. Use the `getInvoices` method from `accountingApi`

**Expected behavior**
It should display YYYY-MM-DD format, or at least update the documentation.

Screenshot:
![image](https://user-images.githubusercontent.com/12806363/76861052-bd354c00-683a-11ea-928e-40f4acdffaae.png)

**Comment by SerKnight** [comment]
Fixed in 4.4.7 (https://github.com/XeroAPI/xero-node/releases/tag/4.4.7) release! Thank you for documenting the issue so well.

![Screen Shot 2020-03-25 at 6 09 44 PM](https://user-images.githubusercontent.com/2935387/77597284-f2d5d700-6ec3-11ea-8b26-ba6a3a718a2d.png)
