### ISSUE TITLE
Inconsistency between README file and buildConsentUrl function

### ISSUE THREAD

**Issue by mschaeffner** [XeroAPI/xero-node#388]
**SDK you're using (please complete the following information):**
 - Version [e.g. 4.4.5]

**Describe the bug**

The function `XeroClient.buildConsentUrl` calls `initialize` in its first line.
https://github.com/XeroAPI/xero-node/blob/6d0f717f24b6f9a2a23397a914c3d8b25834c030/src/XeroClient.ts#L79

But in the `README` file, it says one should get the consent url in the following way:
```
const xero = new XeroClient(config);
await xero.initialize();
let consentUrl = await xero.buildConsentUrl();
```

That would mean the `initialize` function is called 2 times.

To fix this,
either remove `await xero.initialize()` from the REDME file,
or remove `await this.initialize()` from `XeroClient.buildConsentUrl`.

**Comment by SerKnight** [comment]
Hey @mschaeffner - thanks for calling this out.

Updated the docs to explain that while initialize() is required to be called, the build consent url fn() currently handles that for you and you don't need to explicitly call that fn() if you are sending a customer through the auth flow for the first time.

```
// `buildConsentUrl()` calls `await xero.initialize()`
let consentUrl = await xero.buildConsentUrl();
```
