### ISSUE TITLE
Did not handle errors when creating invoices unsuccessfully.

### ISSUE THREAD

**Issue by vovanluc-githup** [XeroAPI/xero-node#391]
**SDK you're using (please complete the following information):**
 - Version [e.g. 3.x.x]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RettBehrens** [comment]
hey @vovanluc-githup please provide more information by filling out the issue template and we'll dig in, thanks!

**Comment by SerKnight** [comment]
@vovanluc-githup - once you provide all the information required to reproduce we can re-open this issue! 

I will mention though, we highly recommend upgrading your application code to utilize the newer OAuth2.0 functionality to interact with the Xero API.

**Comment by vovanluc-githup** [comment]
Hi,
I will describe an example:
I had lineItems like this:

[ { description:
     'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    quantity: 39600,
    unitAmount: 214.001007,
    lineAmount: 214 },
  { description:
     '149 Rochor Road # 04-05 Fu Lu Shou Complex Singapore 188425 Tel: ( 65 ) 63344302 Fax: ( 65 ) 63344669GST REG NO M4-0002697-1',
    quantity: null,
    unitAmount: [],
    lineAmount: 561980136 },
  { description: [],
    quantity: null,
    unitAmount: null,
    lineAmount: 191671 },
  { description: [],
    quantity: null,
    unitAmount: null,
    lineAmount: 412019 } ]

After that i use xero-node :^4.4.5 to create new invoice but i did not receive anything that retrun from xero-node sdk. I knew issue is "The line total does not match the expected line total ". But Xero-node did not handle exception for this case.
