### ISSUE TITLE
Allow Xero Client to be used without openid scope

### ISSUE THREAD

**Issue by pslootweg** [XeroAPI/xero-node#396]
**SDK you're using (please complete the following information):**
 - Version 4.4.3

**Is your feature request related to a problem? Please describe.**

The resource api calls only need an access token, and it is hugely frustrating that I can't use the client to handle refresh unless I include openid scope.

**Describe the solution you'd like**

I would like the client *not* to automatically add openid scope(s)

**Describe alternatives you've considered**

Workaround is to code around refresh without using the client.

**Additional context**

N/A

**Comment by SerKnight** [comment]
Hi @pslootweg - just released a fix for this issue. We appreciate your feedback.. Any more insights into your usage of this package is well received. if you would like to elaborate on your use case of this package here I will check back.

https://github.com/XeroAPI/xero-node/releases/tag/4.5.1
