### ISSUE TITLE
Documentation/No Documentation for ArchiveContactsById

### ISSUE THREAD

**Issue by MylesWardell** [XeroAPI/xero-node#397]
## Issue
Their currently is no documentation of how to `ArchiveContactsById()`, is this still possible? If not how does one delete the user from the contact pool.

The closest I could find was `deleteContactGroupContact()`. But I have never added a contact to a contact group, I create users using the generalised `createContacts()` function.

**Comment by RettBehrens** [comment]
hey @MylesWardell here's an example of how to archive a contact by id, using `updateContact()`.

```
const contactsGetResponse = await xero.accountingApi.getContacts(req.session.activeTenant.tenantId);
const contactId = contactsGetResponse.body.contacts[0].contactID;
const archiveContact: Contact = { contactStatus: Contact.ContactStatusEnum.ARCHIVED };
const contacts: Contacts = { contacts: [archiveContact] };
const archiveContactResponse = await xero.accountingApi.updateContact(req.session.activeTenant.tenantId, contactId, contacts);
```

**Comment by MylesWardell** [comment]
Thank you!
