### ISSUE TITLE
Create invoice with lineitem without account code

### ISSUE THREAD

**Issue by pslootweg** [XeroAPI/xero-node#398]
**SDK you're using (please complete the following information):**
 - Version 3.1.0 vs 4.4.3

**Describe the bug**
In 3.1.0 I can create an invoice with `lineitems` that do not have `accountcode` populated. 
With 4.4.3 it fails unless I populate with a valid  `accountcode`.
Are any other `LineItem` fields also changed behaviour? (It seems I also have to provide qty and price etc.)

**To Reproduce**
Create an invoice with just a valid `itemcode`:

```
      {
        "itemcode": "Terms & Conditions"
      }  
```

**Expected behavior**
Invoice is created.

**Comment by RettBehrens** [comment]
@pslootweg You should try setting the Invoice Status to DRAFT - this allows the creation of an invoice without an account code on the line item.

**Comment by pslootweg** [comment]
May bad, during some refactoring I used a different status.

But this *could* benefit from some better documentation.

**Comment by SidneyAllen** [comment]
@pslootweg  - you can find full documentation of Xero's API here.

https://developer.xero.com/documentation/api/invoices#new-invoice

<img width="986" alt="Screen Shot 2020-04-01 at 10 34 12 AM" src="https://user-images.githubusercontent.com/595967/78168222-69af2a80-7404-11ea-96f5-e0053027c8ff.png">
