### ISSUE TITLE
Issue with Contacts schema

### ISSUE THREAD

**Issue by bcsan** [XeroAPI/xero-node#40]
I've lost some reasonable time on this.

On: lib/entities/accounting/contact.js
At: var ContactSchema = new Entity.SchemaObject

A lot of fields does not contain the 'toObject' property. I was trying to create a contact with EmailAddress and I could not until I've added the "toObject: 'hasValue'" to it. Looks like all fields requires this property.

**Comment by jordanwalsh23** [comment]
Thanks for the input.  Sorry that you've wasted time on an issue.  The SDK is still in alpha so you can expect there to be issues like this!

Any chance you could fork/PR the code?

**Comment by jordanwalsh23** [comment]
Resolved in PR #44

**Comment by jordanwalsh23** [comment]
xero-node@2.1.8
