### ISSUE TITLE
Download Prepayment as PDF [Like Invoice and CreditNote]

### ISSUE THREAD

**Issue by faizalshap** [XeroAPI/xero-node#401]
**SDK you're using (please complete the following information):**
 - Version 4.4.7

**Is your feature request related to a problem? Please describe.**
I am not able to download Prepayment as PDF like Invoice and CreditNotes

**Describe the solution you'd like**
I would like a method or workaround to download Prepayment as PDF. 

**Describe alternatives you've considered**
I tried using prepaymentID with downloadInvoiceAsPdf and downloadCreditNoteAsPdf but it returns 404 and not working.

WorkAround - Add this method in node_modules :
```
/**
     *
     * @summary Allows you to retrieve invoices or purchase bills as PDF files
     * @param xeroTenantId Xero identifier for Tenant
     * @param prepaymentID Unique identifier for an Invoice
     */
    getPrepaymentAsPdf(xeroTenantId, prepaymentID, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const localVarPath = this.basePath + '/Prepayments/{PrepaymentID}'
              .replace('{' + 'PrepaymentID' + '}', encodeURIComponent(String(prepaymentID)));
            let localVarQueryParameters = {};
            let localVarHeaderParams = Object.assign({}, this.defaultHeaders);
            let localVarFormParams = {};
            // verify required parameter 'xeroTenantId' is not null or undefined
            if (xeroTenantId === null || xeroTenantId === undefined) {
                throw new Error('Required parameter xeroTenantId was null or undefined when calling getPrepaymentAsPdf.');
            }
            // verify required parameter 'prepaymentID' is not null or undefined
            if (prepaymentID === null || prepaymentID === undefined) {
                throw new Error('Required parameter prepaymentID was null or undefined when calling getPrepaymentAsPdf.');
            }
            localVarHeaderParams['xero-tenant-id'] = models_1.ObjectSerializer.serialize(xeroTenantId, "string");
            Object.assign(localVarHeaderParams, options.headers);
            let localVarUseFormData = false;
            let localVarRequestOptions = {
                method: 'GET',
                qs: localVarQueryParameters,
                headers: localVarHeaderParams,
                uri: localVarPath,
                useQuerystring: this._useQuerystring,
                encoding: null,
            };
            let authenticationPromise = Promise.resolve();
            authenticationPromise = authenticationPromise.then(() => this.authentications.OAuth2.applyToRequest(localVarRequestOptions));
            authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
            return authenticationPromise.then(() => {
                if (Object.keys(localVarFormParams).length) {
                    if (localVarUseFormData) {
                        localVarRequestOptions.formData = localVarFormParams;
                    }
                    else {
                        localVarRequestOptions.form = localVarFormParams;
                    }
                }
                return new Promise((resolve, reject) => {
                    localVarRequest(localVarRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        }
                        else {
                            body = models_1.ObjectSerializer.deserialize(body, "Buffer");
                            if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                                resolve({ response: response, body: body });
                            }
                            else {
                                reject({ response: response, body: body });
                            }
                        }
                    });
                });
            });
        });
    }
```
Sorry i tried but its not formatting properly :(
**Additional context**
N/A

**Comment by SidneyAllen** [comment]
@faizalshap - Thanks for your question.

Prepayments are a form of BankTransaction.  According to our documentation We support PDF download for Invoices, Quotes and PurchaseOrders.  I've found that CreditNotes can also be downloaded as a PDF.  CreditNotes are very similar to Invoices so that makes sense.

I've messaged our API Team to see if other endpoints support PDF downloads.  So, your question hinges on the API supporting this functionality not necessarily the SDK.

**Comment by faizalshap** [comment]
@SidneyAllen yes, it does support and i am already using it by the code that is mentioned.

**Comment by faizalshap** [comment]
Hi @SidneyAllen 
Since past few days i am not able to download prepayment and also saw that there have been some changes in openAPI but this issue is not yet closed.
Can you please tell me when this will be released.
Thanks :)

**Comment by SidneyAllen** [comment]
@faizalshap - watch for the next xero-node build which will be based off 2.1.1 of our OpenAPI specs https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.1.1

@SerKnight might be able to update the timing of the next xero-node release

**Comment by SerKnight** [comment]
@faizalshap - I will update this thread on next release. We will also confirm functionality and add that as a sample route in the https://github.com/XeroAPI/xero-node-oauth2-app project. Thanks for notifying of the issue.

**Comment by SerKnight** [comment]
Hi @faizalshap - apologies on the delay - can you confirm that the PDFs you are downloading with that function are viewable?

**Comment by SidneyAllen** [comment]
@faizalshap - I've added getPrePaymentAsPdf to our OpenAPI spec modeled on getCreditNoteAsPdf, but it does not work.

I've looking on our API logs and confirmed that the prepayments endpoint does not return a PDF, but returns an XML response.  This would be consistent with our documentation that this functionality is not supported by Prepayment endpoint.

If you wish to request this feature, you can do so on our uservoice.
https://xero.uservoice.com/forums/5528-xero-accounting-api

**Comment by faizalshap** [comment]
Hi @SidneyAllen i can confirm that the pdfs as viewable.
