### ISSUE TITLE
500 Internal Server Error when calling updateOrCreateQuotes

### ISSUE THREAD

**Issue by AndrewWrightNZ** [XeroAPI/xero-node#402]
**SDK you're using (please complete the following information):**
 - Version 4.4.9

**Describe the bug**

Receiving 'statusCode: 500, statusMessage: 'Internal Server Error' when calling xero.accountingApi.updateOrCreateQuotes using the code from the xero-node-oauth2-app.

The code I'm using is:

`const useContact: Contact = { contactID: contactCreateResponse.body.contacts[0].contactID };

						// CREATE QUOTES
				        const quote: Quote = {
				          date: '2020-02-05',
				          quoteNumber: "QuoteNum:" + userSuffix,
				          contact: useContact,
				          lineItems: [
				            {
				              description: "Consulting services",
				              taxType: "NONE",
				              quantity: 20,
				              unitAmount: 100.00,
				              accountCode: "500"
				            }
				          ]
				        }
				        const quotes: Quotes = {
				          quotes: [
				            quote
				          ]
				        }
				        try{
				       		const createQuotes = await xero.accountingApi.updateOrCreateQuotes(xeroTenantId, quotes, true)
				       	} catch(e){
				       		console.log('quote error', e)
				       	}`

**To Reproduce**

1. Running the code above
2. The Catch block isn't called, instead a timeout-like 500 error message is returned 

**Expected behavior**

Return success or a non 500 error message 

**Additional context**

Please let me know if more details are needed.

**Comment by SerKnight** [comment]
Hey @AndrewWrightNZ - I'm having a hard time replicating this. Probably the best option is to email `api@xero.com` with the client id or app name. They can then checkout your api logs and see what is going on behind the scenes.. There is a chance its a race condition with the ContactID not persisting in the database yet? Might be worth a try. Let me know.

**Comment by SerKnight** [comment]
Can you log out your two params before the function is called? 
=>`xeroTenantId` & `quotes`
Likely something is not formatted correctly.

**Comment by AndrewWrightNZ** [comment]
Hey @SerKnight thanks for getting back to me. I emailed api@xero.com about this last week who couldn't see what the issue was and asked me to post here.

I've updated the code to post directly to the Xero API which is working so I'll go with that. This may have been due to my code being formatted incorrectly like you say so this can be closed if you're happy to do that.

**Comment by SerKnight** [comment]
"To post directly to the xero api" do you mean you are doing a request straight to the API w/out the sdk?

**Comment by AndrewWrightNZ** [comment]
Yes that's correct

**Comment by SerKnight** [comment]
Ah I see - ok, well If you can log out all the exact params that were going into the SDK call I can dig in so you hopefully don't have to do a workaround.

**Comment by AndrewWrightNZ** [comment]
Thanks @SerKnight. I've run this again using the SDK and have received helpful error messages back. There were formatting issues which I've now resolved so this is now working nicely for me.

Thank you for looking into this.

**Comment by SerKnight** [comment]
No problemo! Glad you got it sorted.
