### ISSUE TITLE
setAccessToken sets token globally

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#406]
Are you sure it is a good practice to set the access token globally for the xero client?
E.g.
```
xero.setAccessToken(TOKENSET)
await xero.getInvoices(...)
```
what if at that same moment, on a high-load server, another http request wants to do the same operation but with another token? Can't this lead to race-conditions? If the wrong token is submitted to the openid-server, it starts throwing invalid_grants and breaks the connection forever (until manual reconnect).

Wouldn't it be safer to do `xero.getInvoices(TOKENSET, .....otherparams)` and attach the tokenset immediately to the openid request? 

And perhaps if you can, don't break the connection permanently when using an outdated refresh token, just throw 'outdated refreshtoken', because this makes life hell for developers.

**Comment by STEVEOO6** [comment]
I wondered the same thing. Thanks for posting this issue.

One approach I would use is to create a new XeroClient() instance on every request (that requires any xero interaction), as this guarantees that no auth data (e.g. the tokenSet) is shared between users/requests.

**Comment by SerKnight** [comment]
Thanks for sharing your use cases. Valuable to improve this project! 

If you can elaborate on your usage we can get a better grasp on mitigating potential risk. I'm not sure I fully understand the code scenario that you are saying could be a risk.

I understand this could be an issue if you were using a single client to run bulk scripts for all your Xero connections in a single thread.. But I imagine you would want to separate those processes into a unique job / thread per user/xero combination?

--
However in this situation, you should probably be re-initializing the client each time you are writing data for a new user/tenant combination. If one user has multiple orgs/tenants that they have authorized to read/write from you can  keep the same client instance and simply switch the first function parameter (`xero-tenant-id`)..
---

Even if you did structure your code so you had a race condition where an instance of the client had the wrong tokenSet the api call will fail as the `xero-tenant-id` will not be authorized to be read from or write to that org based on an incorrect `access_token`..

---
Re-structuring the repo to pass in both a valid `access_token` as well as `xero-tenant-id` for every call is possible.. However we would lose a decent bit of convenience/ease of use in doing things like: refresh(), updateTenants().

Closing the issue but let's continue the conversation!
