### ISSUE TITLE
Bumping minor version results in: .refreshTokenUsingTokenSet is not a function

### ISSUE THREAD

**Issue by lwagf** [XeroAPI/xero-node#408]
**SDK you're using (please complete the following information):**
 - 4.5.1

**Describe the bug**
I previously ran npm i with the save flag which stored `^4.4.3` in my package.json. Later when deployed onto a live environment version 4.5.1 was pulled which seems to have broken/removed the refreshTokenUsingTokenSet method on XeroClient. 

**To Reproduce**
1. Install version 4.4.3. Calling .refreshTokenUsingTokenSet on an instance of XeroClient works perfect
2. Upgrade to 4.5.1. This call now errors

**Expected behavior**
.refreshTokenUsingTokenSet should still work.

**Screenshots**
![Screenshot from 2020-04-21 10-43-11](https://user-images.githubusercontent.com/20410434/79851228-ef4b4800-83bc-11ea-8459-ea88763863c5.png)

**Additional context**
If this method was intentionally removed, I would argue strongly against doing this in a minor version bump

**Comment by george-hm** [comment]
I've experienced similar issues due to renaming of methods/properties in minor versions bumps

I don't like this :(

**Comment by SerKnight** [comment]
Hi @george-hm and @lwagf

It was my understanding that function was not very helpful for the community, while the normal `refreshToken()` was what was actually being used for normal token refresh.

That functioned was refactored/renamed to enable a refresh of the token without invoking the openid-client dependency, where you can now pass your client id/secret, and refresh token - to receive back a new, valid tokenSet: `refreshWithRefreshToken(clientId, clientSecret, refreshToken)`

Here is the commit for that change. It is also reflected in the documentation.
https://github.com/XeroAPI/xero-node/commit/12141f667a6cd7b740c518c3aa6cde9618865943#diff-3c6fef3dbecbe95f5d215adb43c6252aL125

All that being said - this was an oversight in the [semantic versioning](https://semver.org/) and for that I apologies! Doing our best to continually make improvements whilst maintaining stability. Not making that a major version was a mistake.
