### ISSUE TITLE
Simple example of OAuth not working

### ISSUE THREAD

**Issue by TaylorDale** [XeroAPI/xero-node#410]
```
import { XeroClient } from 'xero-node';
import { TokenSet } from 'openid-client';
import express from 'express';
require('dotenv').config();

const xero = new XeroClient({
    clientId: (process.env.XERO_CLIENT_ID || ''),
    clientSecret: (process.env.XERO_CLIENT_SECRET || ''),
    redirectUris: [`http://localhost/`],
    scopes: (process.env.XERO_SCOPES || '').split(' ') // offline_access workflowmax
});

const app = express();
const port = 80;

app.get('/auth', async (req, res) => {
    res.redirect(await xero.buildConsentUrl());
});

app.get('/', async (req, res) => {
    const url = req.url;
    const tokenSet: TokenSet = await xero.apiCallback(url);

    res.json({ result: tokenSet });
});

app.listen(port, () => console.log(`Xero Auth listening at http://localhost:${port}`));
```

When I visit localhost/auth, I get redirected and grant permissions. When the code is sent back to localhost/ I get the following error:
` UnhandledPromiseRejectionWarning: TypeError: id_token not present in TokenSet
    at Client.validateIdToken (.\node_modules\openid-client\lib\client.js:697:15)`

Upon inspection of the idToken object in openid-client's client.js file I can see that it is fully populated with a seemingly valid access and refresh token, but no element id_token exists which causes the exception. I've reviewed the code and can't seem to see anything obvious going wrong?

Cheers

**Comment by SerKnight** [comment]
Hi @TaylorDale  - At first glance it seems like you will need the 'openid' scope as well. That is what will enable you to receive back an `id_token` - Since the WFM api was only recently rolled out to OAuth2.0 there is a chance that is not properly documented.

Give that a shot and lmk how you get on. If that is the issue I will determine where we can best add that to our documentation.

**Comment by SerKnight** [comment]
I'm curious why the open-id-client has the id_token required and is running `validateIdToken` under the hood. I will verify this, as theres no obvious reason this should be required on our end. 

Is there a reason you are not including the `openid` scope in your scopes access?

cc: 
> https://github.com/panva/node-openid-client/issues/107

**Comment by SerKnight** [comment]
Okay so verified that currently this sdk requires the `openid` scope to be added. You don't have to also request `profile email` scopes but that info will be returned encoded in the `id_token`.

This should not be a requirement and ideally you would be able to authenticate without that but not currently the case. I will close the issue as with the information provided it looks like you were simply looking to get it working.. 

However if there is other community support, or you have an explicit need to not include the `openid` scope and return back that `id_token` please re-open this issue with the details and we will get that work scoped out.

https://developer.xero.com/documentation/oauth2/scopes#openid

**Comment by TaylorDale** [comment]
@SerKnight that seems to have fixed it for me as well, thanks for that. There is no particular reason I wasn't including openid just wasn't aware it was required. I see on the main page that this lib does not support WFM but I was hoping that I could leverage it to get the access and refresh token which I can now do

Much appreciated.
