### ISSUE TITLE
All typescript interfaces are partial, some are weirdly cased

### ISSUE THREAD

**Issue by gjuchault** [XeroAPI/xero-node#414]
**SDK you're using (please complete the following information):**
 - Version: 4.5.1

**Describe the bug**
All the interfaces are Partials. Example on `Organisation` (Accounting API). You can also see that some of them are weirdly cased (`aPIKey`, `organisationID`, etc.)
![image](https://user-images.githubusercontent.com/678848/81047910-a6ff5000-8ebb-11ea-8672-d048f9bc318b.png)

**Expected behavior**
```
export declare class Organisation {
	organisationId: string;
	apiKey: string;
	name: string;
	// …
}
```

**Comment by SerKnight** [comment]
Hi @gjuchault - Appreciate you flagging this.

This is a small side effect of the naming conventions in our OpenAPISpec.

The typescript/node generators camel case the types, which are inferred from the spec. While its not the prettiest/conventional it is expected and does represent the API: https://developer.xero.com/documentation/api/organisation

```
OrganisationID:
APIKey:
```

> https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/xero_accounting.yaml#L20408

**Comment by gjuchault** [comment]
@SerKnight But why all the fields are optional then?

**Comment by SerKnight** [comment]
A lot of the base model types will show all fields as optional. However if you look at specific function definitions - those will be explicit about what fields are required/optional.

If you have a specific issue where you are having troubles interpreting the types shoot it here and I can get you sorted!

-------

The Required params for `getInvoices` in the spec
> https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/xero_accounting.yaml#L6367

The Required params for `getInvoices` in the xero-node code
> https://github.com/XeroAPI/xero-node/blob/master/src/gen/api/accountingApi.ts#L7929
