### ISSUE TITLE
scope is INVALID for the methods suggested in readme

### ISSUE THREAD

**Issue by BenjaminCrozier** [XeroAPI/xero-node#416]
you need a scope that includes `accounting.contacts accounting.transactions accounting.settings`
to call `updatedTenants` on a xero client obj. 

if you run the readme code as is, you will get an "invalid grant" error.

**Comment by SerKnight** [comment]
Hi @BenjaminCrozier - Thank you. I will update the docs. Will put into the next release I am doing now.

However you should only need the `accounting.settings` for that call to work as it just calls the /organisation endpoint.

> https://developer.xero.com/documentation/oauth2/scopes
