### ISSUE TITLE
Cant disconnect from xero using xero.disconnect

### ISSUE THREAD

**Issue by kempsteven** [XeroAPI/xero-node#417]
Im using AdonisJs as my Node Framework, the xeroclient config works perfectly, I can extract details that I need.

I just cant disconnect, as I saw in your [sample app](https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L268) we just have to call xero.disconnect, yet i am receiving an error `xero.disconnect is not a function`
```
const xeroNode = require('xero-node')

const xero = new xeroNode.XeroClient({
  clientId: Config.get('xero.client_id'),
  clientSecret: Config.get('xero.client_secret'),
  redirectUris: [Config.get('xero.redirectUri')],
  scopes: Config.get('xero.scopes').split(" ")
})

async disconnect ({ response, session }) {
   ...
   await xero.disconnect(xero.tenantIds[0])
   ...
}
```
![error](https://user-images.githubusercontent.com/51051704/82186503-8d2f2580-991d-11ea-921a-c35d5c156d90.png)

**Comment by SerKnight** [comment]
Hey - I answered this on S/O but will also put it back in here. Ultimately need a bit more information to see why the object's not initialized properly. Can you log out what `xero` is in that context?

------------


Only thing that looks incorrect at first glance is the parameter you are passing to the function. That should actually be the connection object's ID not the tenantId itself: `await xero.disconnect(xero.tenants[0].id)`
 
But other than that can you elaborate the package version you are using? I've just mimicked everything about how you are importing and setting up client, so it's unclear why the disconnect function is not available. Please ensure you are using the most recent version 4.6.0 - the following just worked for me after I successfully got my access token back from the /callback flow.

Setup:

    const xeroNode = require('xero-node')

    const xero = new xeroNode.XeroClient({
    	clientId: client_id,
    	clientSecret: client_secret,
    	redirectUris: [redirectUrl],
    	scopes: scopes.split(' '),
    });

/connect

    const consentUrl: = await xero.buildConsentUrl();

/callback

    const tokenSet = await xero.apiCallback(returning_url);
    await xero.updateTenants();

/disconnect

    const connection = xero.tenants[0]
    	
    await xero.disconnect(connection.id)


If you can post/log some more info can get this sorted for you!

**Comment by SerKnight** [comment]
Actually - It looks like you are calling `disconnect()` on your own app structures XeroController.js file. The disconnect fn() will need to be called on the instantiation of the XeroClient itself.. Seems like you've got an extra layer wrapped on the client.

Re-open if you can verify that wasn't the fix!

**Comment by kempsteven** [comment]
I realised that i was using the version 4.0.*, maybe in that version the disconnect function weren't still available, after i updated it to the latest version, it now works perfectly, anyways Thanks!

**Comment by SerKnight** [comment]
Great to hear. Yeah that was added in https://github.com/XeroAPI/xero-node/releases/tag/4.4.1

🥳
