### ISSUE TITLE
Is it possible to inherit xero's functions?

### ISSUE THREAD

**Issue by kempsteven** [XeroAPI/xero-node#418]
So I have created a class, i want to add custom functions to make things reusable.

```
const xeroNode = require('xero-node')

const xero = new xeroNode.XeroClient({
  clientId: Config.get('xero.client_id'),
  clientSecret: Config.get('xero.client_secret'),
  redirectUris: [Config.get('xero.redirectUri')],
  scopes: Config.get('xero.scopes').split(" ")
})

class Xero {
  constructor(obj){
    Object.assign(this, obj)
  }

  customFn() { ... }
}

module.exports = new Xero(xero)
```

when I import this class I can use the ```Xero.accountingApi```, but I cant use other functions like ``` Xero.buildConsentUrl()``` or ```Xero.apiCallback(url)``` it says that its undefined. on the screenshot attached those undefined functions are nowhere to be found, when i consoled ```new Xero(xero)```

![export](https://user-images.githubusercontent.com/51051704/82407717-80850b80-9a9c-11ea-90eb-7a7371b3bb69.png)

**Comment by SerKnight** [comment]
So not sure why this is not working for you. Here is a very barebones example of importing the package and wrapping `xeroClient` functions.. 🤔 

There might be something around logging out all the functions if they are not explicit exports if you just log an object like that that I don't understand..?

But this example seems to work fine.. If you are still stuck or want to share more code samples can do my best to help you through it.

### index.js
```javascript
const xeroNode = require('xero-node')

const client_id = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
const client_secret = 'xx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
const redirectUri = 'http://localhost:5000/callback'
const scopes = 'openid email profile offline_access accounting.transactions accounting.contacts accounting.attachments'

const xero = new xeroNode.XeroClient({
  clientId: client_id,
  clientSecret: client_secret,
  redirectUris: [redirectUri],
  scopes: scopes.split(" ")
});

class Xero {
  constructor(obj){
    Object.assign(this, obj)
  }
  
  async myCustomConsentUrl(){
    console.log(await xero.buildConsentUrl())
  }
}

const myClass = new Xero()
myClass.myCustomConsentUrl()
```
### Terminal
```bash
node index.js 
```
=> `https://login.xero.com/identity/connect/authorize?client_id=xxxxxxxx&scope=openid%20email%20profile%20offline_access%20accounting.transactions%20accounting.contacts%20accounting.attachments&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fcallback`
