### ISSUE TITLE
Cant create new Items

### ISSUE THREAD

**Issue by kempsteven** [XeroAPI/xero-node#419]
Version 4.6.0

Im just trying to create new items, just copied the syntax on your [sample app](https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L1267), but i cant seem to create new Items, I dont see exactly whats the error, thanks for the help in advance!

Take note that I am using a trial xero account, not sure if thats the case tho.

**Here is a simplified ver. of my code:**
```
const Config = use('Config')
const xeroNode = require('xero-node')
const xero = new xeroNode.XeroClient({
  clientId: Config.get('xero.client_id'),
  clientSecret: Config.get('xero.client_secret'),
  redirectUris: [Config.get('xero.redirectUri')],
  scopes: Config.get('xero.scopes').split(" ")
})

try {
    const item1 = {
      code: "Foo" + '123',
      name: "Bar",
      purchaseDetails: {
        unitPrice: 375.5000,
        taxType: "NONE",
        accountCode: "500"
      },
      salesDetails: {
        unitPrice: 520.9900,
        taxType: "NONE",
        accountCode: "400",
      }
    }

    const newItems = new xeroNode.Items()
    newItems.items = [item1]

    const itemCreateResponse = await xero.accountingApi.createItems(xero.tenants[0].tenantId, newItems)
  } catch (error) {
    console.log(error.response.toJSON())
  }
```
**Here is the error that consoled (error.response.toJSON()):**
![export (1)](https://user-images.githubusercontent.com/51051704/82422563-2fcddc80-9ab5-11ea-89ce-eecc3c211dcf.png)

**Here is the body of the response (error.response.toJSON().body):**
![hhhhhhhhhhhhhhhh](https://user-images.githubusercontent.com/51051704/82422666-51c75f00-9ab5-11ea-9208-9fe2f4fa7160.png)

**Here is validation error (error.response.toJSON().body.ValidationErrors):**
```
[ { Message: 'The PurchasesAccountId account is invalid.' } ]
```

**Comment by kempsteven** [comment]
```
const item1 = {
      code: "Foo" + '123',
      name: "Bar",
      purchaseDetails: {
        unitPrice: 375.5000,
        taxType: "NONE",
        accountCode: "500"
      },
      salesDetails: {
        unitPrice: 520.9900,
        taxType: "NONE",
        accountCode: "400",
      }
  }

```
so its not a xero-node issue, the `item1.purchaseDetails.accountCode` should be available on your list of [chart of accounts](https://go.xero.com/GeneralLedger/ChartOfAccounts.aspx)

**Comment by Eteroa123** [comment]
@kempsteven  - hey ive had the same issue. What do you mean by having `item1.purchaseDetails.accountCode` avaliable in my list of chart of accounts ???
