### ISSUE TITLE
Token Set Expiration Date is not valid

### ISSUE THREAD

**Issue by kempsteven** [XeroAPI/xero-node#420]
- Version 4.6.0

After I generated the tokenset using `xero.apiCallback(url)`, the token set is good but the expiration date is wierd its in year 1970

**To Reproduce**
```
// Route: /xero
...
const consentUrl = await Xero.buildConsentUrl()
response.redirect(consentUrl)
...

// Route: /callback
const tokenSet = await Xero.apiCallback(url)
await Xero.updateTenants()

// after generating token set, I console the tokenSet here I get the invalid expiration date
// sample expiration date: 1590549754
// when I used new Date: new Date(1590549754) = Mon Jan 19 1970 17:49:09 GMT+0800 (Hong Kong Standard Time)
// I consoled new Date(): 2020-05-27T02:52:35.007Z or Wed May 27 2020 10:52:35 GMT+0800 (Hong Kong Standard Time)
```

Because of this, I cant check if the token is going to expire, so that I could refresh it

**Comment by SerKnight** [comment]
Hi @kempsteven 

Xero's tokenSets store expiration in epoch time which is stored in seconds. Javascript native date functions expect milliseconds.. so if you have an epoch timestamp, convert it to a javascript timestamp by multiplying by 1000.

I created a helper in the sample app that shows how to display the expiration in readable format: https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L129

Hope this helps clarify!

> ref: https://www.epochconvert.com/programming/javascript

**Comment by SerKnight** [comment]
I added a few more examples to the sample app to make sure this is crystal clear:

### input:
```
const tokenSet = await xero.readTokenSet();

console.log('token expires in: ', tokenSet.expires_in / 60, ' minutes')
console.log('tokenSet.expires_at ',tokenSet.expires_at)
console.log('token expires at: ', new Date(tokenSet.expires_at * 1000).toLocaleString())

const now = new Date().getTime()
if (tokenSet.expires_in > now) {
  console.log('token is currently expired: ', tokenSet)
} else {
  console.log('tokenSet is not expired!')
}
```

### Output:
```
token expires in:  29.933333333333334  minutes
tokenSet.expires_at  1590618202
token expires at:  5/27/2020, 4:23:22 PM
tokenSet is not expired!
```

I will update xero-node's main docs as well.

**Comment by kempsteven** [comment]
Thanks @SerKnight!
