### ISSUE TITLE
Wrong openid-client types

### ISSUE THREAD

**Issue by gjuchault** [XeroAPI/xero-node#421]
**SDK you're using (please complete the following information):**
 - Version: 4.5.1

**Describe the bug**
`xero-node` is overriding openid-client's types. So if you use `xero-node` and `openid-client` simultaneously, you get definitions from `xero-node`.

This is causing an issue because in the last types versions (https://github.com/panva/node-openid-client/blob/master/types/index.d.ts), some functions are added that your copy is missing (`requestResource` most notably).

You may argue that you have a version in your package.json, but it's in `"^3.9.2"`, which means if I install `openid-client` aside of `xero-node` for other usage and get the latest version, I get a type conflict.

Either fix `openid-client` version so yarn/node installs the two packages versions or (better) do not copy types like this and leverage typescript's native usage

**Comment by SerKnight** [comment]
Hey @gjuchault - can you elaborate on which types are stepping on each other. I can dig in and ensure version/types compatibility but it would certainly be easier to know which `openid-client` version's and what types are being over-written. I've not come across this one before! Thanks for reporting.

**Comment by gjuchault** [comment]
@SerKnight Hi, For example https://github.com/panva/node-openid-client/tree/master/docs#clientrequestresourceresourceurl-accesstoken-options is missing

**Comment by SerKnight** [comment]
Hi @gjuchault  - sorry for the delay. I had a few working sessions trying to recreate this but it is still a bit unclear to me how to reproduce.

As you can see in the `xeroClient.ts` we do import openid-client:
> https://github.com/XeroAPI/xero-node/blob/master/src/XeroClient.ts#L1

We use those types for just a couple things, like defining the type of the incoming `tokenSet`
> https://github.com/XeroAPI/xero-node/blob/master/src/XeroClient.ts#L59

Are you saying the pinned openid-client version we are using in xero-node does not have some of the newer types you would expect in the most recent releases of openid-client?

Also you mentioned an older version of openid-client is causing this issue? If this is still blocking you, can you elaborate a bit clearer on how to reproduce?

**Comment by gjuchault** [comment]
@SerKnight Hello. Sorry for the delay too. We've been again experiencing issues with this.

As soon as we have an un-sync between our `openid-client` version and yours, we have the issue.
A simple way to reproduce:

1- Create a fresh repository.
2- Install the two libraries (`openid-client@4.2.2` and `xero-node@4.9.1`).

At this moment, if you create a Client to xero and try to overrides its HttpOptions properties for example, you will have an issue with type conflicts.

Basically, by doing a `declare module` in `https://github.com/XeroAPI/xero-node/blob/master/src/untyped.ts`, this overrides the type definition for all typescript project leveraging your library.

Some of the fixes:
- Do not copy the types from `openid-client` anyway: you shouldn't need it: the types are provided by the library itself. I don't get the need of copy pasting them
- If ever you decide to do that, please do not embed this file (`untyped.d.ts`) in the npm package (by using a `.npmignore`): a `declare module` is a global type definition. It impacts projects using your library.
