### ISSUE TITLE
getQuoteAsPdf does not set the headers required to get a PDF response

### ISSUE THREAD

**Issue by edwardsph** [XeroAPI/xero-node#422]
- Version 4.6.0

getQuoteAsPdf returns the JSON representation of the quote in a Buffer rather than returning the PDF. The workaround is to add an additional parameter to the call: `{headers: {Accept: 'application/pdf'}`.

There are a number of concerns here:
 - The API documentation doesn't mention this parameter: https://xeroapi.github.io/xero-node/v4/accounting/index.html#api-Accounting-getQuoteAsPdf
 - The API previewer doesn't even support the Quotes API so testing is harder
 - This particular function is not included in examples here: https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts. Other examples like getInvoiceAsPdf do show the solution but unfortunately I started with Quotes so had to work out the issue myself
 - Surely the header must be set by default otherwise why call the function getQuoteAsPdf 
 - I think the same problem applies to the other *AsPdf calls 

Workaround: `xero.accountingApi.getQuoteAsPdf(activeTenantId, quoteId, {headers: {Accept: 'application/pdf'}})`

**Comment by SerKnight** [comment]
Hey @edwardsph - yes I thought i'd done a sweep to get all those PDF functions corrected. Apologies you had a struggle fest by starting with that one..

I'll make sure everything is in order along with the sample app example asap.

**Comment by RettBehrens** [comment]
Hey @edwardsph we're looking at adding this to the generated docs but for now we're updating the sample app so that it matches the other 'asPDF' examples

**Comment by ioripalm** [comment]
$quoteID = "0b9955d9-5380-496a-896f-1331231456";
try {
    $pdfStream = $apiInstance->getQuoteAsPdf($xeroTenantId, $quoteID);
    if ($pdfStream instanceof \Psr\Http\Message\StreamInterface) {
        echo 1;
        $content = $pdfStream->getContents();
    } elseif (is_object($pdfStream) && method_exists($pdfStream, 'fread')) {
        echo 2;\
        $content = '';
        while (!$pdfStream->eof()) {
            $content .= $pdfStream->fgets();
        }
    } else {\
        echo 3;
        $content = $pdfStream;
    }
    file_put_contents('quote.pdf', $content);
    echo "PDF saved：quote.pdf";

} catch (Exception $e) {
    echo 'Exception when calling AccountingApi->getQuoteAsPdf: ', $e->getMessage(), PHP_EOL;
}
