### ISSUE TITLE
createBankTransactionHistoryRecord gives 400 error with valid id

### ISSUE THREAD

**Issue by faizalshap** [XeroAPI/xero-node#431]
**SDK you're using (please complete the following information):**
 - Version ^4.5.2

**Describe the bug**
I tried to create a history record using `createBankTransactionHistoryRecord` but it gives error that `The document with the supplied id was not found for this endpoint.` 
Status Code - 400
ErrorNumber - 10
I have verified that the BankTransactionId is valid and calling getBankTransactionsHistory works fine with the same BankTransactionId.

**To Reproduce**
1. Create Bank Transaction.
2. Try to create history record using createBankTransactionHistoryRecord.

**Expected behavior**
History Record should be created.

Here is the code if that helps - 
`const history = new HistoryRecords();`
` history.historyRecords = [{details: 'paid'}];`
`console.log(await xero.accountingApi.getBankTransactionsHistory(process.env.tenantId, transaction.referenceId)); //works`

`await xero.accountingApi.createBankTransactionHistoryRecord(process.env.tenantId, transaction.referenceId, history);// doesn't`

**Comment by SidneyAllen** [comment]
@faizalshap  - This is a known issue with the API not supporting create history record for several endpoints.

I've raised this with the API team and it has been assessed and I expect a fix in the next 30 to 60 days.

I'll leave this issue open so I can notify you once it has been resolved.

**Comment by SidneyAllen** [comment]
@faizalshap 

I check with the API team and this issue won't be prioritized at this time. The team's roadmap is full. We'll be removing any unsupported endpoints from the documentation and updating our OpenAPI specs to remove these methods since the functionality was not implemented.

I'll be closing this issue as it's not something we can solve via the SDK.

**Comment by SidneyAllen** [comment]
@faizalshap 

Good new our API has turned around a fix for creating History records on unsupported endpoints.

We have merged the change into our OpenAPI specs version 2.2.9 and should appear in the next build of the xero-node SDK
