### ISSUE TITLE
Remove the docs folder from the npm package

### ISSUE THREAD

**Issue by cairnsj** [XeroAPI/xero-node#434]
Version 4.7.4

The npm package is a bloated 20MB.

The docs folder should be removed from the final package as it is:
- unnecessary
- over 15MB in size alone

Thanks

**Comment by SerKnight** [comment]
Totally agreed. Will get this prioritized for the next release along with some package size benchmarks.

**Comment by RettBehrens** [comment]
@cairnsj This has been addressed in 4.7.5 and we're no longer including the docs in the package, only the repo. This has substantially reduced size 👍
