### ISSUE TITLE
Field name changed from CamelCase to camelCase

### ISSUE THREAD

**Issue by pslootweg** [XeroAPI/xero-node#436]
**SDK you're using (please complete the following information):**
 - Version 4.4.3

**Describe the bug**
https://developer.xero.com/documentation/api/contacts

Docs describe responses (e.g.) Contact/Address as

"Addresses": [
        {
          "AddressType": "POBOX",
          "AddressLine1": "P O Box 123",
          "City": "Wellington",
          "PostalCode": "6011",
          "AttentionTo": "Andrea"
        }
      ],

whereas I get

"addresses": [
            {
                "addressType": "STREET",
                "addressLine1": "PO BOX 123",
                "city": "Wellington",
                "postalCode": "6011",
                "attentionTo": "Andrea"
            },

**To Reproduce**
Just fetch any contact.

**Expected behavior**
Returned data doesn't match SDK documentation
**Additional context**
Changed since version 3.1.0

export interface Address {
    AddressType?: string;
    AddressLine1?: string;
    AddressLine2?: string;
    AddressLine3?: string;
    AddressLine4?: string;
    City?: string;
    Region?: string;
    PostalCode?: string;
    Country?: string;
    AttentionTo?: string;
}

and now:

export declare class Address {
    /**
    * define the type of address
    */
    'addressType'?: Address.AddressTypeEnum;
    /**
    * max length = 500
    */
    'addressLine1'?: string;
    /**
    * max length = 500
    */
    'addressLine2'?: string;
    /**
    * max length = 500
    */
    'addressLine3'?: string;
    /**
    * max length = 500
    */
    'addressLine4'?: string;
    /**
    * max length = 255
    */
    'city'?: string;
    /**
    * max length = 255
    */
    'region'?: string;
    /**
    * max length = 50
    */
    'postalCode'?: string;
    /**
    * max length = 50, [A-Z], [a-z] only
    */
    'country'?: string;
    /**
    * max length = 255
    */
    'attentionTo'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}

**Comment by RettBehrens** [comment]
This was a breaking change between 3.x and 4.x that chose camelCase over PascalCase

**Comment by pslootweg** [comment]
So why is the *current* documentation wrong?!

**Comment by pslootweg** [comment]
> This was a breaking change between 3.x and 4.x that chose camelCase over PascalCase

So why is the current documentation wrong?!

https://developer.xero.com/documentation/api/contacts

**Comment by RettBehrens** [comment]
I apologize for any confusion. What you're linking to is the api docs. Here is the [v4 sdk docs](https://xeroapi.github.io/xero-node/v4/accounting/index.html#api-Accounting-createContacts). In addition, the [model](https://github.com/XeroAPI/xero-node/blob/master/src/gen/model/accounting/contact.ts) provides name and casing. Hope this helps!

**Comment by pslootweg** [comment]
Thank you for clarification.
