### ISSUE TITLE
Cannot download as PDF

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#437]
v4.7.4

```
      const apiResponse = await xero.accountingApi.getInvoiceAsPdf(xeroAccount.xeroTenantId, invoiceId, {
        headers: {
          "Content-Type": 'application/pdf'
        }
      })
      console.log("apiResponse: ", apiResponse.body)
      console.log("PDF, apiResponse", JSON.stringify(apiResponse.body, null, 4))
      fs.writeFileSync(process.cwd() + '/pdf.pdf', apiResponse.body)
      console.log("apiResponse decoded: ", apiResponse.body.toString())
```

last log line, "apiResponse decoded" prints the invoice as json. The pdf file contents are also invoice json. It seems the API returns the invoice instead of its PDF.

**Comment by SerKnight** [comment]
Hi Sandorvasas - Is the goal to download that file to the user's machine? We've got that setup in the sample app. i will include below.

Regarding the proper "node" way to download and display in browser, i'd have to explore a bit more on best practice. If you can elaborate on the feature/use case can possibly be of more help. You might need to st the response headers, and response content type as well (shown in sample app)

I just double checked and that is working in sample app for file downloading invoices as PDF:
https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L1158
<img width="1429" alt="Screen Shot 2020-07-15 at 12 05 43 PM" src="https://user-images.githubusercontent.com/2935387/87579884-e2748280-c693-11ea-840b-76a818255dab.png">


Please re-open if you can validate this solution won't work for your use case with a bit more context!

**Comment by sandorvasas** [comment]
Thanks. Changing the Content-Type header to Accept made it work.
