### ISSUE TITLE
Migrate from Request library to GOT

### ISSUE THREAD

**Issue by 99ACA** [XeroAPI/xero-node#442]
**SDK you're using (please complete the following information):**
 - Version [e.g. 3.x.x]

**Describe the bug**
xero-node dependence on  request which request@2.88.2 which  dependence  har-validator@5.1.5
request - only in maintenance mode - https://github.com/request/request/issues/3142 is using package that no longer exist 
 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SerKnight** [comment]
Hi @99ACA - yes we have it on the backlog to replace the `request` library. Its a fairly large change so we are still evaluating the best option for replacement https://github.com/request/request/issues/3143 

Any community support or discussions regarding a specific library they think best appreciated. Will be updating this thread when the work has been scoped and/or started.

**Comment by SerKnight** [comment]
FYI we will likely be migrating to the https://github.com/sindresorhus/got repository for this repo's HTTP library.

**Comment by SerKnight** [comment]
This migration is still a priority for this project, however we are still on a stable version of request and have additional work in the next quarter for this repo.

Main blocker is that the majority of our templates are still patched from the OS project openapi-generator and introducing this change would introduce more risk then we are comfortable with until their are other template generator resources avail for typescript.

https://github.com/OpenAPITools/openapi-generator/issues/5334

Will revisit in future.
