### ISSUE TITLE
Empty tenant list

### ISSUE THREAD

**Issue by clonq** [XeroAPI/xero-node#445]
1. Created trial account
2. Created an organization
3. The following code returns an empty list of tenants

const xero = new XeroClient();
const refreshedTokenSet = await xero.refreshWithRefreshToken(client_id, client_secret, tokenSet.refresh_token);
await xero.setTokenSet(refreshedTokenSet);
console.log(xero.tenants) // -> []

How do I create a tenant?

**Comment by SerKnight** [comment]
Hi @clonq - to get the currently connected tenant data populated on the `xero-node` client you need to ensure your token has the `accounting.settings` scope, and then you need to call `const tenants = await xero.updateTenants()`

https://github.com/XeroAPI/xero-node#step-3-convenience-step

**Comment by clonq** [comment]
Thank you @SerKnight. I've changed my code to:

```
const xero = new XeroClient({
  clientId: '...',
  clientSecret: '...',
  scopes: 'openid profile email accounting.settings offline_access'.split(" ")
});
const refreshedTokenSet = await xero.refreshWithRefreshToken(client_id, client_secret, tokenSet.refresh_token);
await xero.setTokenSet(refreshedTokenSet);
console.log(xero.tenants) // -> []
```
and the list of tenants is still empty.

Do I need to manually add a tenant in the dashboard maybe? I haven't found a way to do that though.

**Comment by RettBehrens** [comment]
Hi @clonq just double checking since your initial steps to recreate go from creating an org to trying to get a refreshed tokenset - have you successfully gone through the initial auth flow to obtain an initial tokenset?

**Comment by clonq** [comment]
@RettBehrens - i've been using xoauth to generate the initial token set as described [here](https://developer.xero.com/documentation/api-guides/machine-2-machine)

**Comment by RettBehrens** [comment]
@clonq are you calling `updateTenants` after `setTokenSet` but before `console.log(xero.tenants)`?

**Comment by clonq** [comment]
@RettBehrens yes, I've updated the code in my previous comment

**Comment by RettBehrens** [comment]
hmm, @clonq what were the requested scopes when you generated the initial tokenset?

**Comment by clonq** [comment]
@RettBehrens - xoauth "default" ones: openid and offline_access

**Comment by RettBehrens** [comment]
@clonq you won't be able to get the tenants list unless the token generated during the auth flow included the necessary scopes. The token can only be used for the user authorized purposes. The xoauth cli has a step to add additional scopes and that's where you want to add all the necessary scopes

**Comment by clonq** [comment]
@RettBehrens after recreating the tokens with accounting.settings added to the scope, I'm able to see the tenants. Thank you!
