### ISSUE TITLE
Typescript compilation errors

### ISSUE THREAD

**Issue by clethrill** [XeroAPI/xero-node#447]
SDK you're using:

    Version 4.5.1

Describe the bug:

When I compile code with the xero-node sdk warnings come up from the compilation, see below for compilation messages

To Reproduce

Compile some code with the xero-node module

Expected behavior
No errors to appear

/redacted/node_modules/xero-node/dist/gen/api/accountingApi.d.ts (76,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/accountingApi.d.ts (77,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/accountingApi.d.ts (78,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/accountingApi.d.ts (81,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/assetApi.d.ts (33,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/assetApi.d.ts (34,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/assetApi.d.ts (35,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/assetApi.d.ts (38,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/projectApi.d.ts (38,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/projectApi.d.ts (39,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/projectApi.d.ts (40,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/gen/api/projectApi.d.ts (43,9): An accessor cannot be declared in an ambient context.
/redacted/node_modules/xero-node/dist/XeroClient.d.ts (56,9): An accessor cannot be declared in an ambient context.

**Comment by SerKnight** [comment]
Hi @clethrill - I am unable to reproduce this. 

Can you post exact steps to reproduce and other system variables?
* typescript version or package.lock
* your `tsconfig.json`

Once we get that data back we can re-open this issue.

**Comment by clethrill** [comment]
[package-lock.json](https://gist.github.com/clethrill/9e0429f08b704215ed0bc536e0e47c15)
[tsconfig.json](https://gist.github.com/clethrill/b98649ce107e228c8631339e8e2aa630)

We use serverless to deploy to AWS, when using the serverless-offline package to run our API locally the above errors are produced.

I'll get back with more reproduction steps later when I have time but it should be

1. run `npx serverless`
2. run `npm i -D serverless-offline`
3. run `npm i xero-node` 
4. set up a lambda function to import xero-node
5. run `serverless offline`
