### ISSUE TITLE
Allow configure openid-client timeout for Client

### ISSUE THREAD

**Issue by samuraitruong** [XeroAPI/xero-node#448]
**SDK you're using (please complete the following information):**
 - Version [ 4.6.0]

**Is your feature request related to a problem? Please describe.**
when xero API slow we got below error
```"Timeout awaiting 'request' for 2500ms"```

**Describe the solution you'd like**
- Allow pass timeout in the constructor of XeroClient

**Describe alternatives you've considered**
- Increase default 2500 to 1000ms

**Additional context**
NA

The similar issue already discussed here - https://github.com/XeroAPI/xero-node/issues/390

**Comment by samuraitruong** [comment]
I implemented it here - https://github.com/XeroAPI/xero-node/pull/449 but not test it yet because the slowness it not happening anymore.

**Comment by sandorvasas** [comment]
Definitely needed. We just got disconnected from everything, quite possibly because of timeouts

**Comment by sandorvasas** [comment]
We are experiencing "AggregateError: Timeout" again. I did set the openid timeout using `sed` (overwritten the file contents), but it times out after 10 seconds! All of our client accounts are disconnected (10+). It's a little frustrating! And I mean very frustrating.

**Comment by SerKnight** [comment]
Thank you for the code sample @samuraitruong  - I am validating and adding a test for to allow that config.

Working to release this now.

@sandorvasas - can you elaborate on how your client accounts were disconnected? I am assuming you are storing your `token_sets` ( containing the `access_token`./ `refresh_token` ) in your datastore.

Curious how an API timeout could effect your tokens/connections? Can you elaborate?

----------
Also worth noting there was an incident a few days ago that might have been the culprit on this: https://status.developer.xero.com/

**Comment by sandorvasas** [comment]
I see there was another thread opened about refresh tokens expiring after 30 minutes. I can verify it. That is why we have our CRON running every 10 mins, so in case of failures, it can try renewing 2 more times, but each 3 timed out last time and then we couldn't renew anymore. 

[https://github.com/XeroAPI/xero-node/issues/435](url)

**Comment by SerKnight** [comment]
Implemented in `4.8.1` release

https://github.com/XeroAPI/xero-node/releases/tag/4.8.1
