### ISSUE TITLE
PurchaseOrder returns empty array

### ISSUE THREAD

**Issue by moazam996** [XeroAPI/xero-node#450]
**SDK you're using (please complete the following information):**
 - Version 4.7.6 latest

**Describe the bug**
i have call the function var results=await xero.accountingApi.getPurchaseOrders(xeroTenantId, null, null, data.dateFrom, data.dateTo, null, null);
but it returns empty purchaseorder array. but when i hit through https://app.xero.com/Preview/purchaseorders i got my purchaseorders.

**To Reproduce**
its urgent

**Expected behavior**
it will return same as https://app.xero.com/Preview/purchaseorders

**Screenshots**
![image](https://user-images.githubusercontent.com/68375149/91582830-cdb12d00-e969-11ea-9cdb-8a3e45276e54.png)
![image](https://user-images.githubusercontent.com/68375149/91582941-f76a5400-e969-11ea-858f-4a3d0c0ce170.png)

**Additional context**
my xero-tenant-id and all other credentials are correct i have double check it.

**Comment by RettBehrens** [comment]
It looks like you're not specifying a date range in the previewer but you are for the call that's returning an empty array - have you double checked your date range and confirmed there are POs within the specified date range?

**Comment by moazam996** [comment]
> It looks like you're not specifying a date range in the previewer but you are for the call that's returning an empty array - have you double checked your date range and confirmed there are POs within the specified date range?

yes i have checked with out date and with date both returning empty array. :-(

**Comment by moazam996** [comment]
can any one help me about mentioned problem it's urgent. Thanks in Advance.

**Comment by moazam996** [comment]
> It looks like you're not specifying a date range in the previewer but you are for the call that's returning an empty array - have you double checked your date range and confirmed there are POs within the specified date range?

Can you please have a look and solve this issue?

**Comment by SerKnight** [comment]
@moazam996 - I have tried to replicate this issue and cannot. Please provide your code samples and variables that are returning you an empty array.

However If you need to post sensitive data I'd recommend just starting a case with `api@xero.com` by emailing them your client id, org id, and problem.

I was able to validate the `getPurchaseOrders` is working as expected. Please re-open the issue if you are able to post in exact steps to re-create.

const getPurchaseOrdersResponse = await xero.accountingApi.getPurchaseOrders(req.session.activeTenant.tenantId);

// req.session.activeTenant.tenantId is my Demo Company ID that has 8 purhcase orders in varying states

Plucked the purchase order ID's off the response
<img width="460" alt="Screen Shot 2020-09-03 at 2 28 47 PM" src="https://user-images.githubusercontent.com/2935387/92164313-658f9a80-edf2-11ea-94bf-0eb1bbad7e21.png">

<img width="1341" alt="Screen Shot 2020-09-03 at 2 28 54 PM" src="https://user-images.githubusercontent.com/2935387/92164351-76401080-edf2-11ea-816b-fe44912f27a6.png">

Xero Purchase Orders in UI
<img width="844" alt="Screen Shot 2020-09-03 at 2 28 44 PM" src="https://user-images.githubusercontent.com/2935387/92164272-57417e80-edf2-11ea-8317-30885a490c56.png">

**Comment by SerKnight** [comment]
Sorry @moazam996 - my colleague showed me how to reproduce. The core piece was trying to filter by dates via API. Will update asap on fix.

**Comment by SerKnight** [comment]
Actually I was able to validate the `toDate` `fromDate` works.

- first I created a new purchase order
- then I called the function with a date filter from yesterday till December
- I called `getPurchaseOrders` with those date filters and only get back the one that was created in that timeframe.

```javascript
const getPurchaseOrdersResponse = await xero.accountingApi.getPurchaseOrders(req.session.activeTenant.tenantId, undefined, undefined, '2000-09-02', '2020-12-01');
```

<img width="1415" alt="Screen Shot 2020-09-03 at 4 10 56 PM" src="https://user-images.githubusercontent.com/2935387/92178564-0fc1ef00-ee00-11ea-8355-79b79f065a6b.png">

**Comment by moazam996** [comment]
thanks everyone to help actually i was sending null in parameters instead of undefined.
Problem solved.
