### ISSUE TITLE
How to get TokenSet if callback is a lambda function?

### ISSUE THREAD

**Issue by brucem1976** [XeroAPI/xero-node#457]
Hi there - I've happily been using xero-node to do signups to our apps, receiving tokens through xero-node’s _setAccessTokenFromRedirectUri(url)_ call.

However, when making a Lambda to handle this callback (rather than the stateful code sitting permanently on a server), we don’t have access to the original calling URL. Has xero-node implemented a way to get the token in any other way, or specifically a way that is compatible with Lambda?

**Comment by brucem1976** [comment]
Further to the above, the AWS Lambda seems to have this in its event:
 ```
queryStringParameters: {
    code: 'bbc1d6a64ff79399e2dae4xxx20d0d5f4bb0d409c4eb45ef6ddfd8858c41ff4a',
    scope: 'openid profile email accounting.transactions accounting.settings',
    session_state: 'ife6d_2nUOgyuVExyxxxvbqOdga5cBu69avkAFNdvhM.e851c8ec54093d82c736a7ab2120d4fd'
  },
```
So I assume I can actually reconstruct the `originalUrl`? But perhaps this is worth adding another function to `xero-node` that will allow passing of this event object member, instead of the `originalUrl`?

**Comment by RettBehrens** [comment]
@brucem1976 please share which version you're running. That method was renamed / refactored some time ago.

**Comment by RettBehrens** [comment]
Hey @brucem1976 if you build a string using this code and pass the string to the existing it will behave the same as if you had passed the original url.

`
const params = {
   code: 'bbc1d6a64ff79399e2dae4xxx20d0d5f4bb0d409c4eb45ef6ddfd8858c41ff4a',
   scope: 'openid profile email accounting.transactions accounting.settings',
   session_state: 'ife6d_2nUOgyuVExyxxxvbqOdga5cBu69avkAFNdvhM.e851c8ec54093d82c736a7ab2120d4fd'
 };

const paramString = '?' + Object.keys(params).map(key => key + '=' + params[key]).join('&');`

To be clear, this was tested using the latest version of the sdk, using the current method which replaced `setAccessTokenFromRedirectUri(url)`

`async apiCallback(callbackUrl: string): Promise<TokenSet> {
    const params = this.openIdClient.callbackParams(callbackUrl)
    const check = { ...params }
    if (this.config.scopes.includes('openid')) {
      this.tokenSet = await this.openIdClient.callback(this.config.redirectUris[0], params, check);
    } else {
      this.tokenSet = await this.openIdClient.oauthCallback(this.config.redirectUris[0], params, check);
    }
    this.setAccessToken();
    return this.tokenSet
  }`

**Comment by brucem1976** [comment]
Thanks for the reploy @RettBehrens - I updated and tried apiCallback with 2 variations of the constructed url:
`URL:  /signup-callback?code=2d1dd804d05b8887b53734849876df8cbf439dd498e54b47e59589c53ecb5df9&scope=openid%20profile%20email%20accounting.transactions%20accounting.settings&session_state=IPWxluo-WCHuhbmIDSovgxNqCkUm32_FgwqYjtKU5rc.c21f691dccaba3a426ed95c22903a8a1`
and
`URL:  ?code=5abfb58a89f08a1ae68febd31f0160dbc94467832a0b1a141f2be9fdaba86e36&scope=openid%20profile%20email%20accounting.transactions%20accounting.settings&session_state=cfA86DsuVXGSBkGlTwS85FoQplz5arfiAu5yf7MFo2I.4958bb0b29c37b584aca935e5875ad60`

And both of them returned:
`Cannot read property 'callbackParams' of undefined`
from XeroClient

**Comment by RettBehrens** [comment]
Hey @brucem1976 I saw in my email notifications from github that you were getting

`Cannot read property 'callbackParams' of undefined`

but that message has since been deleted.. were you able to resolve the issue?

**Comment by brucem1976** [comment]
> Hey @brucem1976 I saw in my email notifications from github that you were getting
> 
> `Cannot read property 'callbackParams' of undefined`
> 
> but that message has since been deleted.. were you able to resolve the issue?

@RettBehrens I can't find this, but as I remember I needed to call .initialize() before whatever was causing this error.

**Comment by volodymyrrudyi** [comment]
> const paramString = '?' + Object.keys(params).map(key => key + '=' + params[key]).join('&');

@RettBehrens this can potentially cause issues since you are reconstructing query parameters **without URL encoding them**.
