### ISSUE TITLE
Avoid calling Issuer.discover('https://identity.xero.com') multiple times

### ISSUE THREAD

**Issue by ibox4real** [XeroAPI/xero-node#458]
My main issue is with calling `buildConsentUrl()` to get the authorization url. This hits `https://identity.xero.com/.well-known/openid-configuration` every time i ask for the authorization url.  Cant we somehow cache this? 

I actually run into an issue with this when using the client to generate the authorization url multiple times and would get a 403 forbidden.

**Comment by RettBehrens** [comment]
Hey @ibox4real could you elaborate on your use case? What circumstances require generating the auth url multiple times? What conditions caused the 403? Could you share code sample? The openid-client library we're using doesn't include caching for this, we could roll our own solution but want to have a better understanding of the problems we're trying to solve first.
