### ISSUE TITLE
Missing source maps

### ISSUE THREAD

**Issue by CaptainAchilles** [XeroAPI/xero-node#460]
**SDK you're using (please complete the following information):**
 - Version 4.8.1

**Describe the bug**
Running xero-node through the vscode debugger causes it to spam the following error message for each file in the project:

`Could not read source map for file:///project/node_modules/xero-node/dist/gen/model/accounting/invoices.js: ENOENT: no such file or directory, open '/project/node_modules/xero-node/dist/gen/model/accounting/invoices.js.map'`

**To Reproduce**
1. `npm install xero-node`
2. require("xero-node")

**Expected behavior**
Not to be spammed with these error messages

**Screenshots**

**Additional context**
There is a workaround to disable this in vscode with the `resolveSourceMapLocations`, but it doesn't make sense to be pointing the files at a source map if we know it won't exist.

**Comment by CaptainAchilles** [comment]
I've had a little look at this and building it from source doesn't present this issue.

Am I right in saying that it must be something to do with the deployment process?

Is it anything I can help with?

**Comment by RettBehrens** [comment]
Hey @CaptainAchilles you are correct it had to do with the deployment. We were building and including the map files in `dist` but they were being npmignored when publishing. I've included the map files with 4.9.0 release. Closing this for now but please let me know if this doesn't resolve your issue.
