### ISSUE TITLE
getQuoteByNumber

### ISSUE THREAD

**Issue by Arcath** [XeroAPI/xero-node#461]
**SDK you're using (please complete the following information):**
 - Version 4.8.1

**Is your feature request related to a problem? Please describe.**
Purchase Orders have a function of `getPurchaseOrderByNumber` where I can pass the number from Xero e.g. `PO-1234` and get the purchase order record. This is useful so that I can have an input for users to enter the PO number and then do something with it. Quotes don't have this option and users would be force to copy the UUID out of the URL to get the same effect.

**Describe the solution you'd like**
Ideally I'd like the function `getQuoteByNumber` so that I can pass the quotes number e.g. `QU-1234` and get the quote.

**Describe alternatives you've considered**
The only way I can see of doing this at the moment is to get all quotes and loop through the array to find the intended quote. This would be horribly ineffeciant and not to mention data heavy.

**Additional context**
_none_

**Comment by RettBehrens** [comment]
Hey @Arcath with the release of 4.9.0 you can now use `QuoteNumber` as a param to filter by when using `getQuotes()`.

For example:
```
const getAllQuotes = await xero.accountingApi.getQuotes(
    XeroTenantID,
    IfModifiedSince,
    DateFrom,
    DateTo,
    ExpiryDateFrom,
    ExpiryDateTo,
    ContactID,
    Status,
    Page,
    Order,
    QuoteNumber
);
```

**Comment by Arcath** [comment]
Thanks!

That is working as I need it to in our app.
