### ISSUE TITLE
Assign Project id to invoice upon creation

### ISSUE THREAD

**Issue by jim-alexander** [XeroAPI/xero-node#465]
- Version [4.8.1]

I want to assign ACCPAY invoices to a project
[As mentioned here ](https://community.xero.com/developer/discussion/118540025)

When uploading invoices using this method `await xero.accountingApi.createInvoices(tenantId, invoices)` It would be really usefull for a parameter in the invoice object like this` project_id : '12098123-dfhas23d3-...'` to simply assign invoices to projects.

The tracking categories option looked like an okay substitute but you can only have 100 options.. and there is an established project tracker made to do what i want it to do.

For ACCPAY we wont be using line items really anyway so what about just putting the project number in the line item description or something... I just know this will cause problems down the line

**Comment by RettBehrens** [comment]
Hey @jim-alexander unfortunately, like it says in the community discussion, that functionality does not currently exist using the API. Upvoting the request for such functionality on the community discussion and/or in Xero uservoice will elevate the request for the api team. If it's implemented in the API we can definitely update our sdks to make use of it.

Regarding tracking categories, could you link to where you're seeing it's limited to 100 options? I'm not sure what you're referring to there.
