### ISSUE TITLE
more info on 500 errors

### ISSUE THREAD

**Issue by clonq** [XeroAPI/xero-node#466]
Just switched from a trial account to a paid one and the same code that used to create an invoice now gives me this:

{
  "Title": "An error occurred",
  "Detail": "An error occurred in Xero. Check the API Status page http://status.developer.xero.com for current service status.",
  "Status": 500,
  "Instance": "70e430b3-b708-4fd4-80f8-f41669bafd13"
}

Is there a way to get more info about the error?

**Comment by RettBehrens** [comment]
hey @clonq please email api@xero.com if you have not already.
