### ISSUE TITLE
getQuotes() should support fetching by a set of Quote IDs

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#467]
Like `getInvoices()` accepts an array of invoiceIDs, it would be useful if `getQuotes()` could be used in the same way.

**Comment by RettBehrens** [comment]
Hey @sandorvasas this is an issue of what the api does / does not currently support. I would recommend requesting this ability on either or both the Xero UserVoice and/or Xero Community platforms.
