### ISSUE TITLE
Add method to email a quote

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#468]
Analogously to `emailInvoice()`, `emailQuote()` would be handy.

**Comment by RettBehrens** [comment]
Hey @sandorvasas emailing an invoice is supported by the api while emailing a quote is not currently supported by the api. 

I found this recent feature request on the Xero Community forums you could comment on and upvote. https://community.xero.com/business/discussion/118775554

You could also comment on the Xero UserVoice post to request this functionality.
https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/7040008-quotes-via-the-api
