### ISSUE TITLE
Ability to update a singular invoice without requiring the entire invoice object

### ISSUE THREAD

**Issue by leslie-alldridge** [XeroAPI/xero-node#471]
**SDK you're using (please complete the following information):**
 - Version 4.9.1

**Is your feature request related to a problem? Please describe.**
I love to have the ability to update fields for a single invoice without needing to pass through the entire invoice object. For example - mimicking this screenshot here:
![image](https://user-images.githubusercontent.com/11302742/98729116-4d925380-23ff-11eb-9012-35b50225e98a.png)

Currently when using `accountingApi.updateInvoice` I was confused for quite some time as the method name suggests a singular invoice whereas it's designed to batch update multiple. I feel that `updateInvoices` would've been more suitably named. 

Even if a new method is added such as `.updateUniqueInvoice` (I can't think of a good name right now sorry) I'd be happy to use that. 

Referring back to the old sdk this is the functionality currently missing:
```
xeroClient.invoices.update({
     InvoiceID: 123456,
     Status: "AUTHORISED"
})
```

**Describe the solution you'd like**
I've added possible solutions above :)

**Describe alternatives you've considered**
I prefer having my code only needing to know the minimum information required such as InvoiceID and Status. However, I'll change that to be the entire invoice object for now. I've also considered creating an API request from scratch using my token but ended up sticking with the SDK for now.

**Additional context**
Link to SDK example showing update invoice: https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L1156-L1162

**Comment by SerKnight** [comment]
Hey @leslie-alldridge - thanks for opening this up with all details.

The biggest difference from the old SDK and this one, is that it is now generated from Xero's OpenAPI Spec (The spec formerly known as swagger 🕺) https://github.com/XeroAPI/Xero-OpenAPI

Xero's API supports both single and wrapped object creations on almost all endpoints.

That means the following two payloads work for the same endpoint which works well, but is not 100% RESTful.

> POST https://api.xero.com/api.xro/2.0/Invoices
1) Named array of objects
```json
{
  "Invoices": [
    {
      "Type": "ACCREC",
    }
  ]
}
```
2) Single Object
```json
{
  "Type": "ACCREC",
}
```
Your particular example is a completely valid callout considering the function requires the `InvoiceID` as well as the params to update.

Unfortunately it is just a small price to pay for a more maintainable API as a whole. There might be some way to improve these more explicit endpoints in the future though without incurring a breaking change. For the interim though, you will need to pass in the named object as so:

```javascript
// typescript
const invoiceToUpdate: Invoices = {
  invoices: [
    Object.assign(invoice1, newReference)
  ]
}
const updatedInvoices = await xero.accountingApi.updateInvoice(tenantId, invoiceId, invoiceToUpdate)
```


---

### History 
During beta of generating the SDK's via OpenAPI Spec we found the level of maintenance in supporting two methods that hit the same endpoint to be too cumbersome so opted to consolidate to a single function.

You will also find we consolidated a lot of these functions to actually reflect Xero's (not always 100% accurately described) REST endpoints:
Ex:

```javascript
updateInvoices.invoices = [invoice1, invoice2];
await xero.accountingApi.updateOrCreateInvoices(req.session.activeTenant.tenantId, updateInvoices, false)
```

## Full xero-node AccountingAPI docs: 
> https://xeroapi.github.io/xero-node/v4/accounting/index.html#api-Accounting-createInvoices
