### ISSUE TITLE
XeroClient thread safety

### ISSUE THREAD

**Issue by stepanh** [XeroAPI/xero-node#472]
**SDK you're using (please complete the following information):**
 - Version 4.8.1

**Describe the bug**
`xero-node-oauth2-app` initialises a single XeroClient instance `const xero = new XeroClient({` on startup and uses it in most routes. This does not work in multi-user scenario.

**To Reproduce**
1. Launch `xero-node-oauth2-app`
2. In browser-1 connect to Xero as User-1 authorising Org-1
3. In browser-1 click on Accounts. Response is OK
4. In browser-2 connect Xero as User-2 authorising Org-2
5. In browser-1 click again on Accounts. Response is 403, AuthenticationUnsuccessful (User-2's token is now current)

**Expected behavior**
What is the recommended implementation approach in a real-world multi-user multi-org scenario? Initialising a new XeroClient for every request seems wasteful. `setTokenSet` can be used to reset client to current tenant but is that guaranteed to be thread safe for every API?

**Additional context**
Maybe storing a single `tokenSet` within XeroClient and APIs is not the best approach? How about passing `tokenSet` with every API call or storing `tokenSet` per `xeroTenantId`?

**Comment by matthewbloch** [comment]
A XeroClient instance represents a single authenticated user to Xero, that's it. If your app represents multiple Xero users, each one needs their own XeroClient. It's not designed to be multiplexed. I don't know why that would seem wasteful.

[The docs are clear on how to reinitialize it for a new context ](https://github.com/XeroAPI/xero-node#making-offline_access-calls) so you _could_ use one client object for multiple users if you handled the synchronisation yourself - but I don't know why you'd bother. It serializes just fine if you want to avoid reinitializing it, e.g. inside a session object. That might be asking for trouble in future versions though.

**Comment by SerKnight** [comment]
Hi all,

@matthewbloch pretty much covered the gist of what I was going to add. The sample app's intention was more to show all the API usage, and less around production strategy for token management in relation to a users and database.

If you are looking for a code sample that more accurately reflects what a production app might do in regards to creating a new `XeroClient` for each unique user, i've setup a demo that shows full Single Sign on functionality for a user using `xero-node`.

Its got a Postgres DB and should more accurately reflect how you would want to instantiate a new client object from the SDK for each unique user's token_set and API interaction.

### Code Sample:
> https://github.com/SerKnight/xero-sso/blob/master/src/server.ts#L92

### Live Demo
> https://xero-sso.herokuapp.com

Let us know if you still have questions / concerns and we can continue to explore your use case.

**Comment by stepanh** [comment]
Thank you for clarifications @SerKnight @matthewbloch .

What I find potentially wasteful is initialising `XeroClient`s, for each user, yet all of those clients are for the same app, so nearly identical. I did not dig into performance - I only quickly observed that initialising `new XeroClient` on every request for each user seemed slow. Serialisation works. I can totally work with that. I just think that making `XeroClient` user/token independent would be more straightforward.

**Comment by matthewbloch** [comment]
While I think @stepanh's performance angle isn't relevant, I agree that the example app should at least show some representative usage, and it's a bit of a cheat right now.

The main issue is that you can't save its state until you've got a tokenSet, so the XeroClient needs to hang around in memory between requests. This seems a bit fragile. From an API taste point of view, I don't really care about the details, I just want to be able to save and load a XeroClient to my session or database.

There's probably less clumsy ways of fixing this, but in my app, I added two functions to XeroClient which allow you to completely save and restore its state, whether you've authenticated or not:

```js
const xeroNode = require('xero-node')

xeroNode.XeroClient.prototype.saveState = function() {
  return JSON.stringify({
    config: this.config,
    _tenants: this._tenants,
    tokenSet: this.tokenSet,
    openIdClient: this.openIdClient
  })
}

const openIdClient = require('openid-client')
openIdClient.Issuer.discover("https://identity.xero.com/").then((issuer) => {
  xeroNode.XeroClient.prototype.issuerCached = issuer
})
// FIXME: race if first request comes in before above resolves
xeroNode.XeroClient.prototype.loadState = function(stateString) {
  const state = JSON.parse(stateString)
  this.config = state.config
  this.tokenSet = new openIdClient.TokenSet(state.tokenSet)
  this._tenants = state._tenants
  if (state.openIdClient !== undefined) {
    this.openIdClient = new xeroNode.XeroClient.prototype.issuerCached.Client(state.openIdClient)
  }
  if (this.tokenSet.access_token !== undefined) {
    this.setAccessToken()
  }
}
```

And then add this bit of middleware to make _ctx.xero_ saved & restored in the session. (I'm using [express-http-context](https://www.npmjs.com/package/express-http-context) to make the request-local _ctx_ work, and [express-async-errors](https://github.com/davidbanham/express-async-errors) to make exception handling work in async handlers - which is kindof necessary for this example):

```js
require('express-async-errors');
const ctx = require('express-http-context')

app.use(async (req,res,next) => {

  ctx.xero = new xeroNode.XeroClient({
    clientId: process.env.XERO_CLIENT_ID,
    clientSecret: process.env.XERO_CLIENT_SECRET,
    redirectUris: [process.env.XERO_REDIRECT_URI],
    scopes: 'openid profile email accounting.transactions accounting.settings offline_access'.split(" ")
  })

  ctx.req = req
  ctx.res = res

  if (req.session.xeroSerialized) {
    ctx.xero.loadState(req.session.xeroSerialized)
  } else {
    req.session.xeroSerialized = ctx.xero.saveState()
  }

  next()
})
```

You need to make sure you save the state during the authentication flow, so e.g. when redirecting the user out to Xero:

```js
app.get('/connect', async function(req, res, next) {
  const xero = ctx.xero
  const url = await xero.buildConsentUrl()
  req.session.xeroSerialized = xero.saveState()
  res.redirect(url);
})
```

and when they come back again:

```js
app.get('/callback', async function(req, res, next) {
  const xero = ctx.xero;
  const tokenSet = await xero.apiCallback(req.url)
  await xero.updateTenants(true)
  req.session.xeroSerialized = xero.saveState()
  res.redirect('/accounts');
})
```

and whenever you call xero.refreshToken()

```js
  await ctx.xero.refreshToken()
  req.session.xeroSerialized = ctx.xero.saveState()
```

With this implemented the state of the token set, oAuth flow, tenant list and config are all stored in a single state that can be saved & loaded. I think this makes XeroClient easier to use, and the documentation simpler, but I don't know if this would make a useful patch yet.

**Comment by SerKnight** [comment]
Thanks for your details @matthewbloch - if you want to continue on this contribution it might be best to open a pitch in a new issue to clarify discussion.

Also want to callout what seems like similar functionality.. let me know.

This enables you to essentially "Set State" on a Xero client independent of any oauth flow, assuming you have a valid `token_set`.

```javascript
const newXeroClient = new XeroClient()
const refreshedTokenSet = await newXeroClient.refreshWithRefreshToken(client_id, client_secret, tokenSet.refresh_token)
```

**Comment by matthewbloch** [comment]
Sure it's partial duplication - but I didn't see the use of refreshWithRefreshToken unless it could also handle saving OAuth flow state. Without that, you must handle OAuth outside of XeroClient, or ensure you serve requests from the same node process during the OAuth flow. 

The example code skirts round this, which is not quite the same issue @stepanh originally asked about.
