### ISSUE TITLE
Integrate Files API

### ISSUE THREAD

**Issue by SerKnight** [XeroAPI/xero-node#473]
**SDK you're using (please complete the following information):**
- https://developer.xero.com/documentation/files-api/overview-files

**Is your feature request related to a problem? Please describe.**
- Be able to manage Files API

**Comment by RettBehrens** [comment]
implemented with latest release!!!

**Comment by SerKnight** [comment]
https://github.com/XeroAPI/xero-node/releases/tag/4.10.0
