### ISSUE TITLE
Unable to identify correct tenant in tenant list

### ISSUE THREAD

**Issue by FDevman** [XeroAPI/xero-node#474]
Hi, there seems not to be a very good way to identify the "active" tenant/connection immediately after a new connection is made. The README of this project says `be hyper aware of which tenantId you are passing to each function` however in every case I can find in this repo and in the (example app)[https://github.com/XeroAPI/xero-node-oauth2-app] it is assumed that the "active" tenant/connection is the one at `xero.tenants[0]`.

Consider the following code:
``` javascript
const tokenSet = await xero.apiCallback(callbackUrl)
const tenants = await xero.updateTenants()
const activeTenant = tenants[0]
```

Given that there may be more than one tenant in the tenants array and its very important that I know which tenant my user just authorised, relying on the correct tenant to be at array location `0` seems very unreliable. There ought to be an obvious way to relate the tokenSet object I just received to exactly one of the tenants in the tenants array. The only way of doing this I was able to find is as follows:
``` javascript
const tokenSet = await xero.apiCallback(callbackUrl)
const tenants = await xero.updateTenants()
const decodedAccessToken = jwt.decode(tokenSet.access_token)
const activeTenant = tenants.find(tenant = > tenant.authEventId === decodedAccessToken.authentication_event_id)
```
This at least appears to work but is not at all obvious and neither `authEventId` nor `decodedAccessToken.authentication_event_id` appear in the docs.

Am I missing something here? Is array location `0` more reliable than it seems for some reason?

**Comment by SerKnight** [comment]
Hey @FDevman - in the updateTenants helper we filter by the most recently connected tenant. However I do agree there could be a better way to signal this, or perhaps just a helper fn() named `activeTenant` that delivered back the most recent?

Here is that code in the sdk:
https://github.com/XeroAPI/xero-node/blob/master/src/XeroClient.ts#L219

Let us know if you have any ideas on a better way to surface the correct `tenantId` and document for incoming users.

**Comment by SerKnight** [comment]
That being said a `tokenSet` will be relevant for ALL tenants that a user has connected. An `access_token` will have permissions to write to all the `/connections` at any given time. I've found the easiest way is to just surface to the end user a dropdown where they can select which org they want "Active" or by UX let them disconnect any extra they no longer want to write to.

That way your api calls are simply fueled by `currentUser.activeTenantId` etc..

**Comment by RettBehrens** [comment]
Hey @FDevman at the time we wrote the helper method, auth event ID wasn't available on the connection object so we filtered by updatedDateUtc of the returned connection object. This method could be refactored to use auth event id as a better solution now that it's available. Important caveat though is that some apps, those in the app partner program who have opted in / enabled [bulk connections](https://developer.xero.com/documentation/oauth2/partner-benefits#bulkconnections) would have multiple connections associated to a single auth event ID so it's still best practice to implement @SerKnight suggested dropdown ui to give the user the ability to specify which org they want to interact with.

**Comment by RettBehrens** [comment]
Closing this since multiple solutions for identifying activeTenant are identified. Opening an issue to track refactoring of `updateTenants`

https://github.com/XeroAPI/xero-node/issues/475

**Comment by FDevman** [comment]
@SerKnight, @RettBehrens Thanks for the info. There is one situation in particular that taking the most recent tenant fails on and that is the one where a user initiates the connection, finds that there is already at least one organisation they have authorised, and clicks "Continue with 1 organisation". In this situation, I want to be able to treat it the same as if they had clicked "Cancel" as they have not authorised a new org. The most likely reason for this on my side is that someone is using the same Xero credentials to connect two different entities. This is all most important at the moment that someone makes the connection. Subsequently, I will have persisted the (internal) entity <=> Xero org relationship and associated token and so don't need to rely on this SDK for it.

Therefore, in my mind anything that can identify an "active" tenant has more to do with the token acquisition than the `updateTenants` call since, separated in time from an authorization event, "active" is much more subjective. This is basically what the `authentication_event_id` does but its super hidden since I have to decode the access_token to get at it.
