### ISSUE TITLE
Getting AggregateError when making API calls

### ISSUE THREAD

**Issue by opedromiranda** [XeroAPI/xero-node#478]
- Version 4.9.1

**Describe the bug**
Recently we started migrating OAuth1.0a tokens to OAuth2.0. However, some calls end up throwing the following exception:

```
AggregateError: OPError: expected 200 OK, got: 403 Forbidden
at processResponse (/usr/app/node_modules/openid-client/lib/helpers/process_response.js:48:11)
at /usr/app/node_modules/openid-client/lib/issuer.js:249:20 at runMicrotasks ()
at async /usr/app/node_modules/p-some/index.js:53:19
OPError: expected 200 OK, got: 403 Forbidden at processResponse (/usr/app/node_modules/openid-client/lib/helpers/process_response.js:48:11)
at /usr/app/node_modules/openid-client/lib/issuer.js:249:20 at runMicrotasks ()
at async /usr/app/node_modules/p-some/index.js:53:19
```

**To Reproduce**
This appears to be caused when making multiple calls for different organisations at once. 15 organisations at once would lead to this.

We've tried increasing the openid HTTP timeout but it didn't fix this.

**Comment by SerKnight** [comment]
Can you give some more context on the scenario that triggered this?

Is this after you have fully migrated a token, and are setting it on the `XeroClient`?

I've not run into this one before. Some prelim research looks like it might have something to do with the well knowns jwks endpoint - https://github.com/panva/node-openid-client/issues/53

@opedromiranda any code samples to re-create will be helpful.

**Comment by opedromiranda** [comment]
@SerKnight  yes the migrated token would work sometimes, when making multiple requests at once (for multiple orgs, each with their own migrated token) the calls would throw the above error.

Today I rested this and couldn't replicate it either, I will let you know if this happens again.

This call we do is quite simple, essentially retrieves the latest records (contacts first, and then invoices, credit notes and overpayments) since the last time it was called.


```javascript
class XeroOrganisation extends Organisation {
  //....

  async getCustomers({ since = new Date(0), page = 1 } = {}) {
    const result = await this.xeroClient.accountingApi.getContacts(
      this.id,
      since,
      'IsCustomer==true',
      '',
      null,
      page,
      null,
    );
    return result.body.contacts.map((c) => new XeroContact(c, this.tenantID, this.xeroClient));
  }

async getSalesInvoices({ since = new Date(0), page = 1 } = {}) {
    const result = await this.xeroClient.accountingApi.getInvoices(
      this.id,
      since,
      'Type=="ACCREC"',
      '',
      null,
      null,
      null,
      null,
      page,
    );
    return result.body.invoices.map((i) => new XeroInvoice(i, this.tenantID, this.xeroClient));
  }

async getCreditNotes({ since = new Date(0), page = 1 } = {}) {
    const result = await this.xeroClient.accountingApi.getCreditNotes(this.id, since, '', '', page);
    return result.body.creditNotes.map(
      (cn) => new XeroCreditNote(cn, this.tenantID, this.xeroClient),
    );
  }

  async getOverpayments({ since = new Date(0), page = 1 } = {}) {
    const result = await this.xeroClient.accountingApi.getOverpayments(
      this.id,
      since,
      '',
      '',
      page,
    );
    return result.body.overpayments.map(
      (o) => new XeroOverpayment(o, this.tenantID, this.xeroClient),
    );
  }
}
```

**Comment by TheWass** [comment]
> This appears to be caused when making multiple calls for different organisations at once. 15 organisations at once would lead to this.
I had the same issue recorded here: #428

**Comment by oitozero** [comment]
@SerKnight Any update on this?

**Comment by SerKnight** [comment]
@oitozero 

This is a tough one as I wasn't able to clearly reproduce. Its hard to tell without the rest of the code in how the Xero clients are being setup.
```
//....
```

In general though, the XeroClient should only be initialized once. This error is actually from the open id client repo, and looks like it is surfaced when you slam on JWK's endpoint many times. Something that should just be done once.

A solution was provided by @TheWass that might be helpful
https://github.com/XeroAPI/xero-node/issues/428#issuecomment-764915037

----

If you can confirm both how your XeroClient is initialized, and document some steps to reproduce, I can get back on this one and try to see if there is a way to get this solved in the initialize() function.

**Comment by oitozero** [comment]
@SerKnight We have implemented the suggested solution by @TheWass. Working without any issue now. 
Thank you and @TheWass

**Comment by SerKnight** [comment]
Hi @oitozero - glad you got it sorted.

I took another stab at re-creating the issue.. But wasn't able to. Obviously production systems work a lot different than my local sample app so I'm still curious as to how we can get a fix into the SDK.

If anyone else comes along after experiencing this issue and can post some code to re-create it that would be 🌟 

```javascript
 const overload = await Promise.all(
          [
            await xero.initialize(),           
            await xero.initialize(),
            ... + 30 more ;)
          ]
        );
```

**Comment by TheWass** [comment]
@SerKnight, an idea.  Maybe replace your initialize lines with this:
```js
await (new XeroClient(xeroConfig)).initialize()
```
You may need to set the instances to a Map class to keep them in memory.
Once I have some free time, I'll work up a testbed to assist simulating the problem.  I have old code which had this issue in version control... somewhere...

**Comment by SerKnight** [comment]
Cool - I will give that a try @TheWass 
If you get time to recreate ping me @ here when you have a simulation / idea on the fix. We can then start a fresh issue and get a PR going to solve the root issue.

We also have a typescript starter that might be an easier playground to fork and recreate the issue: https://github.com/XeroAPI/xero-node-oauth2-ts-starter
