### ISSUE TITLE
Bank Statement Report

### ISSUE THREAD

**Issue by andrewoons** [XeroAPI/xero-node#481]
Hi,

Is there a specific reason why the Bank Statement report is not implemented? I see Bank Summary has been `getReportBankSummary`, but the Bank Statement is missing. 

If there's no specific reason, do let me know, and we will see if we can get it added and submit a PR. 

Thank you!

**Comment by SidneyAllen** [comment]
@andrewoons - I'm sorry but we won't be accepting PRs to add this endpoint.

please see issue #313 for background.
