### ISSUE TITLE
Readme + sample app examples for filtering and pagination

### ISSUE THREAD

**Issue by SerKnight** [XeroAPI/xero-node#482]
**Is your feature request related to a problem? Please describe.**
* needs examples to show how to paginate, filter, and if-modified-since
* these should be in core readme but also sample app (https://github.com/XeroAPI/xero-node-oauth2-app)

**Describe the solution you'd like**
* clear, manipulable examples showing full XeroAPI functionality

**Describe alternatives you've considered**
Looked in sample app but there are no advanced filtering examples

> https://developer.xero.com/documentation/api/requests-and-responses

**Additional context**

Record filter | You can specify an individual record by appending the BankTransactionID to the endpoint, i.e. GET https://.../BankTransactions/297c2dc5-cc47-4afd-8ec8-74990b8761e9
-- | --
Modified After | The ModifiedAfter filter is actually an HTTP header: ' If-Modified-Since'. A UTC timestamp (yyyy-mm-ddThh:mm:ss) . Only bank transactions created or modified since this timestamp will be returned e.g. 2009-11-12T00:00:00
Where | Filter by an any element ( see Filters )
order | Order by any element returned ( see Order By )
page | Up to 100 bank transactions will be returned per call, with line items shown for each transaction, when the page parameter is used e.g. page=1

**Comment by SerKnight** [comment]
Example in ruby sample project: https://github.com/XeroAPI/xero-ruby-oauth2-app/blob/e91f8c8df2bab20f6467a1eff89c9623933cd33f/app/controllers/accounting_controller.rb#L198

**Comment by RettBehrens** [comment]
```
const xeroTenantId = 'YOUR_XERO_TENANT_ID';
const ifModifiedSince: Date = new Date("2020-02-06T12:17:43.202-08:00");
const where = 'Status=="AUTHORISED" AND Type=="SPEND"';
const order = 'Reference ASC';
const page = 1;
const unitdp = 4;

const response = await xero.accountingApi.getBankTransactions(xeroTenantId, ifModifiedSince, where, order, page, unitdp);
```
