### ISSUE TITLE
Ability to generate receipt to user when applying payment via API

### ISSUE THREAD

**Issue by gparker97** [XeroAPI/xero-node#483]
**SDK you're using (please complete the following information):**
 - Version  4.x

**Is your feature request related to a problem? Please describe.**
In our company we have a button in our internal POS system that creates a Xero invoice and applies a payment to the invoice whenever a payment is collected via cash or bank transfer.  The users in my company often need to issue a receipt for that payment to the user, and the only way we know is through the "Send Receipt" function in the Options menu of the Xero Payment, which is a manual step that can only be performed by those in the company with access to our Xero organization, so it often requires a request to somebody to perform this step.

**Describe the solution you'd like**
I would like the ability to issue a receipt to the addressee (in the To: field) of an invoice when a payment is applied via the API.  Preferably this would be in the form of a parameter of the object sent to the Node SDK, for example:

`const payment: Payment = { invoice: { invoiceID: "00000000-0000-0000-000-000000000000", lineItems: [], contact: {}, type: Invoice.TypeEnum.ACCPAY }, account: { code: "970" }, date: "2019-03-12", amount: 1.0, **sendReceipt: true** }`

**Describe alternatives you've considered**
The only alternative we are aware of is to trigger the send a receipt function manually via the UI.

Thanks very much in advance for your help!  Please let me know if any questions.

Thanks,
Greg

**Comment by SidneyAllen** [comment]
@gparker97 - thanks for your feedback.  Unfortunately, this functionality is not available via Xero's API at this time.

Someone did create a uservoice request, but it's not garnered many votes, so has not be prioritized.
https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/34139746-invoke-receipt-sending-via-api

**Comment by gparker97** [comment]
Thanks for the response Sidney, I've added my vote for the feature request on uservoice.
Greg
