### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by hobochild** [XeroAPI/xero-node#484]
**SDK you're using (please complete the following information):**
 - Version 4.9.1

**Describe the bug**
When requesting attachment by invoice. `xero.accountingApi.getInvoiceAttachments` if the API returns a 429. Then the xero client with fail to parse the response as the body is not JSON. See the stack trace below:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/app/node_modules/xero-node/dist/gen/api/accountingApi.js:8026:41)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:486:12)
    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:486:12)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
```

**To Reproduce**
Call `xero.accountingApi.getInvoiceAttachments` until you exceed the rate limit, and trigger a 429 response.

**Expected behavior**
I'd expect the sdk to parse the body depending on it's type.

**Additional context**
There was similar report of this here: #242, but it's an old closed issue so I thought I'd open a new one.

**Comment by hobochild** [comment]
This is especially problematic as this error appears to be uncatch-able. As it is throwing in the promise resolver but not immediately on function invocation. I have only been able to catch it with `process.on('uncaughtException')`.

A simplified example, replacing `request` with `setTimeout` to show how the error is thrown:
```
new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw new Error("Whoops I couldn't parse the body!");
  }, 1000);
}).catch(alert); // this catch will never be triggered. 
```

**Comment by hobochild** [comment]
I'm not really sure how the sdk generator works, if you can point me to where the change should be made I'd be happy to help.

**Comment by hobochild** [comment]
For those hitting the same issue, I have temporarily resolved it with [patch-package](https://www.npmjs.com/package/patch-package).

Here is the diff for my specific case, but this will be an issue for any of the "Attachments" endpoints.
```
diff --git a/node_modules/xero-node/dist/gen/api/accountingApi.js b/node_modules/xero-node/dist/gen/api/accountingApi.js
index 051bf1a..2bd05d1 100644
--- a/node_modules/xero-node/dist/gen/api/accountingApi.js
+++ b/node_modules/xero-node/dist/gen/api/accountingApi.js
@@ -8023,8 +8023,13 @@ class AccountingApi {
                             reject(error);
                         }
                         else {
-                            body = JSON.parse(body);
-                            body = models_1.ObjectSerializer.deserialize(body, "Attachments");
+                            try {
+                              body = JSON.parse(body);
+                              body = models_1.ObjectSerializer.deserialize(body, "Attachments");
+                              console.log('Modified xero handler')
+                            } catch {
+                              reject({ response: response, body: body });
+                            }
                             if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                                 resolve({ response: response, body: body });
                             }
```

**Comment by SerKnight** [comment]
Hey @hobochild  - thanks for reporting this. You found an interesting case that I believe applies to all endpoints. When a 429 hits it was going down the code path to `JSON.parse` an empty body and fail deserialization without returning the error.

Fixing in next release.
