### ISSUE TITLE
Node-expressjs aggragate error 

### ISSUE THREAD

**Issue by UjjualUSspericorn** [XeroAPI/xero-node#485]
using platform Node expressjs (javascript)

**xero-node   npm:**
 - Version ^4.9.1

**Describe the bug**

I have used the scopes,redirect url and credentials which works fine with postman. below is the code I used.It is throwing aggragate error

const { XeroClient, Invoice } = require("xero-node");

const xero = new XeroClient({
clientId: 'YOUR_CLIENT_ID',
clientSecret: 'YOUR_CLIENT_SECRET',
redirectUris: [`http://localhost:5000/callback`],
scopes: 'accounting.transactions offline_access'.split(" "),
state: '123', // custom params (optional)
httpTimeout: 3000 // ms (optional)
});

// `buildConsentUrl()` will also call `await xero.initialize()`
let consentUrl = await xero.buildConsentUrl();

res.redirect(consentUrl);

--error

**aggregateError: TimeoutError: Timeout awaiting 'request' for 2500ms xero api**
.

**Comment by SerKnight** [comment]
Hi @UjjualUSspericorn  - are you using express or another node framework?

Just from a glance it looks like maybe the `let consentUrl = await xero.buildConsentUrl();` probably needs to be wrapped in an `async` function to properly finish running prior to the res.redirect.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

Also for the posting in the sample app (https://github.com/XeroAPI/node-oauth2-example/issues/4) if you pull that project master branch and run again, are you still receiving this error?
