### ISSUE TITLE
Payment typing not including a BatchPaymentID

### ISSUE THREAD

**Issue by kylethacker05** [XeroAPI/xero-node#489]
**SDK you're using (please complete the following information):**
 - Version 4.9.1

**Describe the bug**
The [docs]( https://developer.xero.com/documentation/api/payments#GET) state there can be a BatchPaymentID on a payment, but currently I cant find a typing for that on the Payment type.

**To Reproduce**
1. Check the Payment type 

**Expected behavior**
The Payment type should include the BatchPaymentID

**Comment by SidneyAllen** [comment]
@RettBehrens - I've got an open PR for the OpenAPI spec to address this
https://github.com/XeroAPI/Xero-OpenAPI/pull/363

**Comment by RettBehrens** [comment]
resolved by latest build from OpenAPI spec
