### ISSUE TITLE
Making a generic request that's not included in OpenAPI

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [XeroAPI/xero-node#493]
Hi all,

I'm having a look through the definitions, and I need to make a request of the equivalent `https://api.xero.com/api.xro/2.0/{Endpoint}/{Guid}/history`, through the SDK but I don't think it's there (correct me if I'm wrong). Is there any way that I can make a generic request via the nodejs SDK so that I could say `xero.call("/{Endpoint}/{Guid}/history")`.

Is this something that I can do at the moment, or look at adding (or just add the initial functionality)?

Thanks.

**Comment by SidneyAllen** [comment]
@NathanBeddoeWebDev - All the history endpoints are defined in this SDK via our OpenAPI spec.

Check out the SDK documentation here for an example of how to get the history on a contact.
https://xeroapi.github.io/xero-node/v4/accounting/index.html#api-Accounting-getContactHistory

**Comment by NathanBeddoeWebDev** [comment]
Hm ok. Thanks. I suppose I'll have to create some method to input an endpoint and a guid, and then it goes off and makes the appropriate SDK call based on the input. Perhaps I misunderstood the point of the `https://api.xero.com/api.xro/2.0/{Endpoint}/{Guid}/history` in the docs.

Closing. Doesn't seem to be appropriate for this repository.
