### ISSUE TITLE
QueryApi doesn't seem to know about tenants

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [XeroAPI/xero-node#494]
Hi,

As per my last issue about getting the History of specific items, I found the queryAPI, which I am under the assumption that it allows me to query any endpoint that's on the xero api, and it'll handle authentication for me.

The issue that I'm coming across, is that when I make this call for history below, I am getting a 403 forbidden error. Which is potentially a tenant issue, or a scope issue.

I have looked across the sample apps that you guys have created, but haven't found any examples to see if I'm doing something wrong.

I'm using this code,
```
const history = await xero.queryApi(
      "GET",
      `https://api.xero.com/api.xro/2.0/${endpoint}/${guid}/history`
    );
```

and I have the scopes of
```
"offline_access openid profile email accounting.transactions accounting.transactions.read accounting.reports.read accounting.journals.read accounting.settings.read accounting.contacts.read accounting.attachments.read"
```
enabled in my authentication. account.transactions should handle the privileges for history searches.

A bearer token is being added to my request, which I examined using the jwt.io decoder, and there was no information about an active tenant, or even a list of tenants. I'm guessing this is what's causing the 403 forbidden, because how is the API supposed to know which tenant to get data from? Should there be away to list the tenant? Or am I completely off base and this isn't an issue at all?

**Comment by NathanBeddoeWebDev** [comment]
As an aside, so when I view the request that's made by say, the ContactAPI, it adds xero-tenant-id as a header to the request. I'm guessing that this should be done for the queryAPI as well.

**Comment by NathanBeddoeWebDev** [comment]
I've just replicated the above xero api request in postman.
Without the xero-tenant-id header, it fails.
With the xero-tenant-id header, it succeeds.

Looks like we need to add the xero-tenant-id as default header and set it as the active tenant id

**Comment by SerKnight** [comment]
Hi @NathanBeddoeWebDev - thanks for the PR https://github.com/XeroAPI/xero-node/pull/495.

However I think there might be another solution in here somewhere that solves for the generic querying for object history.

      `https://api.xero.com/api.xro/2.0/${endpoint}/${guid}/history`

We do generate specific functions to query for object history. Are those not doing it for you?

https://xeroapi.github.io/xero-node/v4/accounting/index.html#api-Accounting-getContactHistory
https://xeroapi.github.io/xero-node/v4/accounting/index.html#api-Accounting-getInvoiceHistory
https://xeroapi.github.io/xero-node/v4/accounting/index.html#api-Accounting-getItemHistory

`queryApi` was originally intended for token related api calls that don't require a tenant id header, however happy to refactor and add some tests around this if it solves for a problem we've not properly understood.

**Comment by NathanBeddoeWebDev** [comment]
Yes I saw those. It's probably just inner lazy me, not wanting to make a switch statement on a req param for each of the get History functions in the SDK.

It seems like it'd be good to have a method that allows us to make direct queries to the API for cases such as this, where it's a lot easier to just use a template string to decide which call to make to the API, and queryAPI is so close to that, it just needs some knowledge of a tenant. Previously, we were using the xero 3rd party package on NPM which was only a direct query to the api, and while xero-node is much nicer, it'd be great to integrate something similar if there aren't any problems such as security.

**Comment by RettBehrens** [comment]
Hey @NathanBeddoeWebDev like @SerKnight said, the `queryApi` method is intended for token related API calls that don't require a tenant id header. That said, we should probably go through XeroClient and mark the methods public or private depending on their intended use. 

The methods for interacting with Xero APIs (accounting, assets, bankfeeds, files, payroll, projects) are all generated from our OpenAPI spec and these methods leverage yaml models and serialize/deserialize payloads. For example:

`getContactHistory` body:
```
HistoryRecords {
  historyRecords: [
    HistoryRecord {
      details: 'Orlena Greenville has been created.',
      changes: 'Created',
      user: 'System Generated',
      dateUTC: 2016-08-10T20:45:36.890Z
    }
  ]
}
```

`queryApi` body:
```
{
  Id: 'a5fe155f-3010-44b6-97b6-36757c4da75a',
  Status: 'OK',
  ProviderName: 'RettBehrensNodeSDKSampleApp',
  DateTimeUTC: '/Date(1614366482371)/',
  HistoryRecords: [
    {
      Changes: 'Created',
      DateUTCString: '2016-08-10T20:45:36',
      DateUTC: '/Date(1470861936890+0000)/',
      User: 'System Generated',
      Details: 'Orlena Greenville has been created.'
    }
  ]
}
```

If you're looking for a generic query method I would suggest rolling your own like you said but I would encourage you to leverage the existing SDK methods for getting history records over that.
