### ISSUE TITLE
 TypeError: client_secret_basic client authentication method requires a client_secret

### ISSUE THREAD

**Issue by outbounder** [XeroAPI/xero-node#499]
Hi there,

I've been testing xero api integration and stumbled upon the following:

**SDK you're using (please complete the following information):**
 - Version 4

**Describe the bug**

I get upon `const tokenSet = await xero.apiCallback(req.url)`

```
TypeError: client_secret_basic client authentication method requires a client_secret
  at Client.authFor (/cells/xero-api/node_modules/openid-client/lib/helpers/client.js:95:15)
  at Client.authenticatedPost (/cells/xero-api/node_modules/openid-client/lib/helpers/client.js:127:30)
  at Client.grant (/cells/xero-api/node_modules/openid-client/lib/client.js:1241:46)
  at Client.callback (/cells/xero-api/node_modules/openid-client/lib/client.js:462:35)
  at XeroClient.<anonymous> (/cells/xero-api/node_modules/xero-node/dist/XeroClient.js:81:58)
```

**To Reproduce**

```
const app = require('expess')
const xero = new XeroClient({ ...  })

app.get('/connect', function (req, res) {
  let consentUrl = await xero.buildConsentUrl()
  res.redirect(consentUrl)
})
app.get('/connect/callback', function (req, res) {
  const tokenSet = await xero.apiCallback(req.url)
  console.log(tokenSet)
})
```

**Expected behavior**

I should be able to see tokenSet printed in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/125437/109966191-a06a8080-7cf8-11eb-9310-3e720b7a08ef.png)

**Additional context**

I'm newbie using xero and following the 'documentation' at https://github.com/XeroAPI/xero-node-oauth2-app but in plain old Javascript ;) 

What I'm missing? 

Thanks for your support and contributions 😊🙏🌱

**Comment by RettBehrens** [comment]
Hi @outbounder could you confirm the full version number? Thanks!

**Comment by RettBehrens** [comment]
Never mind. I think you need to set your client ID and client secret in your .env file. You'll see in the sample app there is a guard against this
```
const xero = new XeroClient({
  clientId: client_id,
  clientSecret: client_secret,
  redirectUris: [redirectUrl],
  scopes: scopes.split(" "),
  state: "imaParam=look-at-me-go",
  httpTimeout: 2000
});

if (!client_id || !client_secret || !redirectUrl) {
  throw Error('Environment Variables not all set - please check your .env file in the project root or create one!')
}
```
If I comment out the check and don't set my client secret in my .env file I replicate your error messge
