### ISSUE TITLE
ContactIDs multiple throws parsing error

### ISSUE THREAD

**Issue by AndrewLugg** [XeroAPI/xero-node#502]
**SDK you're using (please complete the following information):**
 - Version 4.10.2
 - NodeJS 14.16.0

**Describe the bug**
Using getInvoices call, if you send multiple ContactIDs as an array, it returns a "Supplied parameter 'ContactIds' cannot be parsed.". The documentation says to send request with comma, but it comes out of the SDK as URL encoded. One ContactID as an array works fine, it is only when there is more than one.

This was working, and is a regression. 

**Expected behavior**
Accepts both single contactID and multiple.

**Example Error**

Here is an example error, I have redacted some data, and replaced the contact ID's with generic HEX values.
Call that works: 
["12345679-1234-1234-1234-123456789012"]
Doesn't work:
["12345679-1234-1234-1234-123456789012","ABCDEF79-1234-1234-1234-123456789012"]

```
{
  "response": {
    "statusCode": 400,
    "body": "Supplied parameter 'ContactIds' cannot be parsed.",
    "headers": {
      "content-type": "text/html; charset=utf-8",
      "content-length": "49",
      "server": "nginx",
      "xero-correlation-id": "",
      "x-appminlimit-remaining": "9998",
      "x-minlimit-remaining": "47",
      "x-daylimit-remaining": "4813",
      "expires": "Mon, 15 Mar 2021 02:34:05 GMT",
      "cache-control": "max-age=0, no-cache, no-store",
      "pragma": "no-cache",
      "date": "Mon, 15 Mar 2021 02:34:05 GMT",
      "connection": "close",
      "x-client-tls-ver": "tls1.3"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "api.xero.com",
        "port": null,
        "hostname": "api.xero.com",
        "hash": null,
        "search": "?where=&order=date%20DESC&IDs=&InvoiceNumbers=&ContactIDs=12345679-1234-1234-1234-123456789012%2ABCDEF79-1234-1234-1234-123456789012&Statuses=&page=1",
        "query": "where=&order=date%20DESC&IDs=&InvoiceNumbers=&ContactIDs=12345679-1234-1234-1234-123456789012%2ABCDEF79-1234-1234-1234-123456789012&Statuses=&page=1",
        "pathname": "/api.xro/2.0/Invoices",
        "path": "/api.xro/2.0/Invoices?where=&order=date%20DESC&IDs=&InvoiceNumbers=&ContactIDs=12345679-1234-1234-1234-123456789012%2ABCDEF79-1234-1234-1234-123456789012&Statuses=&page=1",
        "href": "https://api.xero.com/api.xro/2.0/Invoices?where=&order=date%20DESC&IDs=&InvoiceNumbers=&ContactIDs=12345679-1234-1234-1234-123456789012%2ABCDEF79-1234-1234-1234-123456789012&Statuses=&page=1"
      },
      "method": "GET",
      "headers": {
        "user-agent": "xero-node-4.10.2",
        "xero-tenant-id": *REDACTED*,
        "If-Modified-Since": null,
        "Authorization": *REDACTED*,
        "accept": "application/json"
      }
    }
  },
  "body": {}
}
```

**Comment by RettBehrens** [comment]
Hey @AndrewLugg I just tested this using the sample app running v4.11.0 and am not able to replicate your error as it worked correctly for me using the following:

`const Invoices = await xero.accountingApi.getInvoices(req.session.activeTenant.tenantId, null, null, null, null, null, ['9ce626d2-14ea-463c-9fff-6785ab5f9bfb', '305ca5cf-497d-4fee-a161-cdb30e6be989']);`

`path: '/api.xro/2.0/Invoices?where=&order=&IDs=&InvoiceNumbers=&ContactIDs=9ce626d2-14ea-463c-9fff-6785ab5f9bfb%2C305ca5cf-497d-4fee-a161-cdb30e6be989',`

Can you test this again using v4.11.0 and reopen if you're still having issues?
