### ISSUE TITLE
AggregateError: Issuer.discover() failed inside buildConsentUrl()

### ISSUE THREAD

**Issue by communig8-public** [XeroAPI/xero-node#511]
**SDK you're using (please complete the following information):**
 - Version 4.11.0

**Describe the bug**
AggregateError: Issuer.discover() failed.
    RequestError: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames
when calling buildConsentUrl()

**To Reproduce**
Call buildConsentUrl() in code

**Expected behavior**
URL to be returned

**Additional context**
This has just started to happen after upgrading to 4.11.0, code was working fine up to then.

Any more information I can provide, just ask. Thanks.

**Comment by communig8-public** [comment]
Just restored the full server back to the 4th of January with a way old xero-node 0.0.13 and it's still doing it!

**Comment by communig8-public** [comment]
Ah no, the system updated xero-node to 4.11.0

**Comment by RettBehrens** [comment]
Unable to replicate using the sample app and v4.11.0 - calling `buildConsentUrl()` works as expected. Could you provide more details? Has something changed with the cert? 

Closing as this does not appear to be SDK related.

**Comment by communig8-public** [comment]
I have this working now. It wasn't the certificate but a full update of the Ubuntu Server it was all running on has fixed it. So yes not the SDK but some other component.
