### ISSUE TITLE
Authentication Error(checks.state argument is missing) 

### ISSUE THREAD

**Issue by bhrigushr** [XeroAPI/xero-node#514]
**SDK you're using (please complete the following information):**
 - Version 4.11.2

**Describe the bug**
Getting following error after successfully authenticating with Xero

```
TypeError: checks.state argument is missing
    at Client.callback (/Users/bhrigusharma/Documents/work/web-backend/node_modules/openid-client/lib/client.js:398:13)
    at XeroClient.<anonymous> (/Users/bhrigusharma/Documents/work/web-backend/node_modules/xero-node/src/XeroClient.ts:118:48)
    at Generator.next (<anonymous>)
    at /Users/bhrigusharma/Documents/work/web-backend/node_modules/xero-node/dist/XeroClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/bhrigusharma/Documents/work/web-backend/node_modules/xero-node/dist/XeroClient.js:4:12)
    at XeroClient.apiCallback (/Users/bhrigusharma/Documents/work/web-backend/node_modules/xero-node/dist/XeroClient.js:77:16)
    at XeroNetworkService.<anonymous> (/Users/bhrigusharma/Documents/work/web-backend/src/modules/xero/xero.network.ts:30:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bhrigusharma/Documents/work/web-backend/src/modules/xero/xero.network.ts:11:58)
```
`apiCallback` is throwing the error the above error

**To Reproduce**
1. Create an auth URL using `buildConsentUrl`
2. Go to the above-generated URL and authenticate successfully 
3. Pass the URL which we get after redirection to `apiCallback`

url passed to `apiCallback` is like `/finishAuth?code=<code>&scope=openid%20profile%20email%20accounting.reports.read%20accounting.settings&state=<state>&session_state=<session_state>`

**Expected behavior**
Should not throw an error instead should generate tokens

**Additional context**
I upgraded my `xero-node` from `4.8.1` to `4.11.2` and my authentication flow stopped working
Everthing was working fine on `4.8.1`

**Comment by bhrigushr** [comment]
Found the issue
In `4.8.1` it is not mandatory to initialize Xero client with `state` even if in auth URL `state` is passed
In `4.11.2` it is required to pass state to initialize Xero client with `state` if in auth URL `state` is passed

```
new XeroClient({
            clientId: <client>,
            clientSecret: <secret>,
            redirectUris: <redirectUris>,
            scopes: <scopes>,
            state:<state>, ---> required in v4.11.2
        })

**Comment by SerKnight** [comment]
Hey @bhrigushr  - have a few more questions if you are able to share.

`xero.config.state` should definitely be an optional parameter to configure the client 🤔 

4.11.2 i've just confirmed the following delivers me back a valid tokenSet.
```
const xero = new XeroClient({
  clientId: client_id,
  clientSecret: client_secret,
  redirectUris: [redirectUrl],
  scopes: scopes.split(" ")
});
```

If you can share any sample on how you replicated with recent release that would be helpful. Thanks for reporting!

**Comment by bhrigushr** [comment]
My code looks like ->

```javascript
import { TokenSet } from 'openid-client';
import { XeroClient } from 'xero-node';
const xero = new XeroClient({
    clientId: <client_id>,
    clientSecret: <client_secret>,
    redirectUris: <redirectUrls>,
    scopes: <scopes>,
});

// STEP 1:-
const consentUrl = await xero.buildConsentUrl();
// Use url to to authenticate with Xero
const url = consentUrl + `&state=someRandomValue`;

// STEP2:-
// Succefully authenticate with Xero

// STEP 3:-
// Pass URL recieved from xero to apiCallback
// it looks like /finishAuth?code=<code>&scope=openid%20profile%20email%20accounting.reports.read%20accounting.settings&state=<state>&session_state=<session_state>
await xero.initialize();
const tokens: TokenSet = await xero.apiCallback(urlFromXero);

```

**Comment by RettBehrens** [comment]
Ah, yep. So we recently made a change that corrected some incorrect CSFR in the SDK

```
public async apiCallback(callbackUrl: string): Promise<TokenSet> {
    const params = this.openIdClient.callbackParams(callbackUrl);
    const check = { ...params };
    if (this.config.scopes.includes('openid')) {
      this._tokenSet = await this.openIdClient.callback(this.config.redirectUris[0], params, check);
    } else {...
```

is now

```
public async apiCallback(callbackUrl: string): Promise<TokenSet> {
    const params = this.openIdClient.callbackParams(callbackUrl);
    const check = { state: this.config.state };
    if (this.config.scopes.includes('openid')) {
      this._tokenSet = await this.openIdClient.callback(this.config.redirectUris[0], params, check);
    } else {...
```

Previously the check object was just a duplicate of the params object so they would always equal each other and effectively was not leveraging openid-client built in CSFR state checking. 

In your code when you tack on state to the consent url, Xero is going to return that state in the callback url and openid-client library is going to check that against your local state from the config - in this case throwing the error.

To resolve - add state to your xeroclient config and remove ```const url = consenturl + `&state=someRandomValue`;```

See more info on `Client.callbackParams()` and `Client.callback()` [here](https://github.com/panva/node-openid-client/blob/main/docs/README.md#client)

**Comment by RettBehrens** [comment]
To clarify, state param is not required but ```const url = consenturl + `&state=someRandomValue`;``` was causing a mismatch between params and check objects

**Comment by adamreisnz** [comment]
This is yet another breaking change that is released as a minor version. Breaking changes should bump the major version of a package. Very frustrating.

**Comment by adamreisnz** [comment]
What's worse, is that this error causes Xero to think it is connected to the app, while the app itself is _not_ connected. This means you have to login to Xero, and disconnect the app before you can try connecting again.

**Comment by SerKnight** [comment]
Hi @adamreisnz yes you are correct & my apologies! What I thought was just cleaning up the API to best practices in passing through the client object initialization rather than tacking onto the string was an oversight that it would be a breaking change.

We do our best to be very diligent about stable releases but feel your pain on getting an unintended break on a patch semver release.. 😢 

To clarify for anyone who comes to this thread in the future.. The readme is accurate now, but the state API change from 1 -> 2
```javascript
1) In 4.8.1 it is not mandatory to initialize Xero client with state even if in auth URL state is passed
2) In 4.11.2+ it is required to pass state to initialize Xero client if in auth URL state is passed 
```

In addition, state is now properly validated against a checksum to enhance a bit of client side security.

**Comment by adamreisnz** [comment]
So should we still pass state in the URL in addition to passing it to the
client? That's what I understood from the quote above.

**Comment by bhrigushr** [comment]
@adamreisnz  you only need to pass `state` in the client if you are passing in URL

**Comment by RettBehrens** [comment]
@bhrigushr @adamreisnz you no longer need to append the state to the url manually. If you include state in the XeroClient config it's appended to the url automatically when calling buildConsentUrl, the same as your specified redirect uri and scopes:
```
url = this.openIdClient.authorizationUrl({
        redirect_uri: this.config.redirectUris[0],
        scope: this.config.scopes.join(' ') || 'openid email profile',
        state: this.config.state
      });
```

**Comment by adamreisnz** [comment]
Ok, other question, _can_ we still append it to the URL manually as well, in _addition_ to passing it to the client?
This is because the Xero library is the _only_ integration that has this method of appending state, and all other OAuth2 integrations we connect with we _manually and explicitly_ pass the state to the URL.

This increases transparency and avoids mistakes, as the Xero Node API is like a black box for us, so we don't really know what happens behind the scene, whether it will append the state or not, etc.

**Comment by SerKnight** [comment]
Hey @adamreisnz - sorry for confusion. Let me close the loop on this issue :)

If you append to the authorize URL string, the callback will fail.
```javascript
const url = await xero.buildConsentUrl()
window.location = url + '&region=Gondor'
```
When you exchange the code in `await xero.apiCallback(req.url);` the response will be an error:
```
TypeError: checks.state argument is missing
```

This improves security of the SDK and prevents any [CSRF attacks](https://auth0.com/docs/protocols/state-parameters). The code is here: [XeroClient.ts](https://github.com/XeroAPI/xero-node/blob/master/src/XeroClient.ts#L116) and depends on state being passed via the `XeroClient` configuration.

```javascript
const xero = new XeroClient({
  ...
  state: 'returnPage=my-sweet-dashboard', // (optional)
});

const check = { state: this.config.state };
```
We then pass `check` to our OA2 certified library of choice [node-openid-cleint](https://github.com/panva/node-openid-client) and [validates](https://auth0.com/docs/tokens/access-tokens/validate-access-tokens) the state as well as both the `access_token` & `id_token`.

**Comment by adamreisnz** [comment]
Hi @SerKnight , thanks yes I understood that, and we now _do_ pass the state to the client upon initialisation, and this is all working again.

However, I wanted to know if it will work if we _also_ add the state to the authorisation URL manually.

Is the Xero client smart enough to _not automatically append it_, if it detects that those parameters are already present, or will it just blindly append it a second time?

**Comment by oitozero** [comment]
@adamreisnz Were you able get a reply on your previous query? cc / @SerKnight

**Comment by adamreisnz** [comment]
@oitozero no, I did not.

**Comment by SerKnight** [comment]
Hey @oitozero and @adamreisnz - apologies this is still unclear. Any ideas to harden the documentation will be well received.

So - If you add add state manually to the authorisation URL the callback will check it against the state configured in the client and [it will fail](https://auth0.com/docs/protocols/state-parameters).

So no, you cannot manually append state to the Xero Auth url. If you want to pass state through the callback flow, you need to add it in the client configuration:

```javascript
const url = await xero.buildConsentUrl()
window.location = url + '&region=Gondor'
// Callback will FAIL

-------------------------------------------
const xero = new XeroClient({
  ....
  state: 'returnPage=my-sweet-dashboard', // custom params (optional)
});

let consentUrl = await xero.buildConsentUrl();
res.redirect(consentUrl);
...
console.log(xero.config.state)
=> 'returnPage=my-sweet-dashboard'
// callback SUCCEEDS
```

**Comment by adamreisnz** [comment]
This still doesn't conclusively answer the question whether doing **both** is possible – e.g. passing it in via the URL **and** the client.

I know that _only_ passing it to the URL will fail, and that we must pass it to the client, but for consistency sake, can we manually attach it _and_ pass it to the client as well? Will the client be smart enough to not append the same parameters twice?

**Comment by SerKnight** [comment]
If you look [at the code](https://github.com/XeroAPI/xero-node/blob/master/src/XeroClient.ts#L116) for the state configuration, you can see that it is passed to the `openid-client`. If the state is manually appended to the URL, then it is not passed through and the evaluation of the passed in state vs the callback's state in the `openid-client` is going to fail.

It not magic, just library code and the reason is for security. Imagine you created your authorize URL and had in on your front end, but some cross site scripting changed the `CLIENT_ID` parameter and sent the user through an unintended authorize flow. The fact that state is now required to be input in the backend client configuration is an added security layer to ensure safe API authorization processes.

I've linked this a few times but please have a read of the following explanation: 
[Prevent Attacks and Redirect Users with OAuth 2.0 State Parameters](https://auth0.com/docs/protocols/state-parameters)

If you have a solution on how the library could support that, we are always open to PR's. Once again, apologies on the in-accurate Semver change. If you have specific questions of why this is still an issue for your application feel free to respond.

**Comment by adamreisnz** [comment]
We would never under any circumstances use this code on the front-end, so that is a moot argument.
But it's alright, we will pass the parameter in the config of the client.

**Comment by talhakhadim** [comment]
@SerKnight  I am new to xero integration,but the thing is I want to identify the user who authorizes the consent url, and in callback, i need an identifier (userId), so if the state is constant variable which we give in xeroclient config then i think we can't use that for this purpose. Which should we pass with the connection URL dynamically so we know the user in the callback?
