### ISSUE TITLE
Tidy up/alias inconsistency in property names with IDs in them

### ISSUE THREAD

**Issue by PeteDuncanson** [XeroAPI/xero-node#522]
**SDK you're using (please complete the following information):**
 - 4.11.2

**Is your feature request related to a problem? Please describe.**

Just got caught out with a mis-match in naming/casing of properties tenantId and contactID. Seems these differ which caught me out. 

```
// updateTenants returns tenants as any[] type so no intellisense
const tenants = await xero.updateTenants(false);
const tenantId = xero.tenants[0].tenantId;


const contactsResponse = await xero.accountingApi.getContacts(tenantId);
const customers = contactsResponse.body.contacts;
const customerId = customers[0].contactID;  // <--- different casing of "id"

// There might be other instances of this, this is just the one I came across

```

Yet when you start interacting with Contacts that uses contactID and not contactId.

**Describe the solution you'd like**

Trouble is this is "out there" now so difficult to actually change without breaking some stuff. For consistency I'd like it to be one or the other (tenantID and contactID or tenantId and contactId). There maybe be other instances of this that need cleaning up too.

The best option that is backwards compat is to add an alias I guess to the newly "corrected" one but keep the old one around?

Adding a type for the tenants would help too as then intellisense could help you pick the "right" one going forward.

Ideally we would mark the older inconsistent version as deprecated ala https://stackoverflow.com/a/62991642 or similar.

**Describe alternatives you've considered**

Rename it and break any existing code, not really what anyone wants though is it? Cuts down on a bit of bloat but for a lot more "hey you broke my thing!" and lets face it no one is going to read the release notes to update.

Just leave it as is, it works but caught me out and lost me enough time that I wanted to create this issue. For a good and welcoming developer experience its always nice to not make us work harder than need be, there is normally a lot going on in our heads as is :)

**Comment by SidneyAllen** [comment]
Hey @PeteDuncanson 

Appreciate you taking the time to share your experience with us.  This is an area where consistency isn't going to be possible across Xero's APIs as we have several large sets of APIs (accounting, payroll, assets, projects, bankfeeds) that have been created by different teams over a 10+ year period.

Our SDKs are now being generated from OpenAPI specs that reflect the data behind our APIs.  

This is what the JSON for a Contact object returned by the API looks like.

    {
        "Id": "5c83b115-a6e8-4f2a-877f-ba63d009235b",
        "Status": "OK",
        "ProviderName": "Xero API Partner",
        "DateTimeUTC": "\/Date(1551462703288)\/",
        "Contacts": [
             {
                 "ContactID": "8138a266-fb42-49b2-a104-014b7045753d",
                 "ContactNumber": "SB2",
                 "AccountNumber": "1234567",
                 "ContactStatus": "ACTIVE",
                 "Name": "Acme Parts Co.",
                 "FirstName": "Blake",
                 "LastName": "Kohler",
                 "EmailAddress": "bk@krave.co",
                            .... truncated ....
            }
        ]
    }

When building our SDKs, I found in languages like Java property casing needs to match exactly otherwise the property data is lost during deserialization.

So, Accounting Contact has ContactID while Projects have contactId

    {
        "pagination":{
        "page":1,
        "pageSize":50,
        "pageCount":1,
        "itemCount":9
        },
        "items":[
            {
                "projectId":"b021e7cb-1903-4292-b48b-5b27b4271e3e",
                "contactId":"216830cb-9a68-487e-928b-c1a7ccc4fc81",
                "name":"FooProject28916",
                "currencyCode":"AUD",
                 "minutesLogged":180,
                 .... truncated ....
            ]
        }

And as you correctly identified tenantId uses this format. 

    [
        {
          "id": "7cb59f93-2964-421d-bb5e-a0f7a4572a44",
          "tenantId": "fe79f7dd-b6d4-4a92-ba7b-538af6289c58",
          "tenantName": "Demo Company (NZ)",
          "tenantType": "ORGANISATION",
          "createdDateUtc": "2019-12-07T18:46:19.5165400",
          "updatedDateUtc": "2019-12-07T18:46:19.5187840"
        }
    ]
    
Generating in 6 different programmings languages with preferences that span PascalCase, camelCase, snake_case has been challenge.

**Comment by RettBehrens** [comment]
Hey @PeteDuncanson I can ask the api team if they're done making changes to the tenant objects returned from the connections endpoint. Previously tenant name was not included. We were trying to be flexible given the changing data and not type it explicitly in case there were further changes to avoid having devs' apps break.

**Comment by RettBehrens** [comment]
Ah, sorry I forgot the other reason we've left it as an any array. The updateTenants method will either return the simple tenants objects in the array or tenants with full org details based on developer's use of the boolean param:

```
public async updateTenants(fullOrgDetails: boolean = true): Promise<any[]> {
    const result = await this.queryApi('GET', 'https://api.xero.com/connections');
    let tenants = result.body.map(connection => connection);

    if (fullOrgDetails) {
      const getOrgsForAll = tenants.map(async tenant => {
        const result = await this.accountingApi.getOrganisations(tenant.tenantId);
        return result.body.organisations[0];
      });
      const orgData = await Promise.all(getOrgsForAll);

      tenants.map((tenant) => { // assign orgData nested under each tenant
        tenant.orgData = orgData.filter((el) => el.organisationID == tenant.tenantId)[0];
      });
    }
    // sorting tenants so the most connection / active tenant is at index 0
    tenants.sort((a: any, b: any) => <number><unknown>new Date(b.updatedDateUtc) - <number><unknown>new Date(a.updatedDateUtc));
    this._tenants = tenants;
    return tenants;
  }
```
For your instance you could define a more strict type for use within your application and for intellisense?

**Comment by PeteDuncanson** [comment]
Hey @RettBehrens thanks for the clarification. Yep I'll go the custom type route to stop myself getting caught out again in the future. Not to worry and thanks for getting back to me and taking the time to look into it, appreciated :)
