### ISSUE TITLE
Contact Groups are always empty?

### ISSUE THREAD

**Issue by PeteDuncanson** [XeroAPI/xero-node#524]
**SDK you're using (please complete the following information):**
v4.11.2

**Describe the bug**

I'm trying to get contactGroup out, its setup in the back office of Xero and I can get it on the Aged Recievable report within Xero itself buy via the API its always an empty array. I'm looking on the Contact object, I'm not sure if it should be looked up elsewhere?

**To Reproduce**

1. Assign a customer to a contact group
2. Check that the group has a value in the existing Aged Receivable report or similar within the back office of Xero
3. Get the contact via a get Contacts api call:

```
      const contactsResponse = await xero.accountingApi.getContacts(
      company.tenantId,
      undefined,
      'ContactStatus=="ACTIVE" AND IsCustomer==true'
    );
    const customers = contactsResponse.body.contacts;
```
4. The contactGroup field on each customer is always an empty array

**Expected behavior**

I'd expect that if a contactGroup is assigned then it is returned within the response. That or I'm looking in completely the wrong place?

**Screenshots**

![image](https://user-images.githubusercontent.com/1674590/115868881-00e28800-a435-11eb-85e4-d17ca6511933.png)

**Comment by SerKnight** [comment]
Hi @PeteDuncanson

Had me scratching my head on this one for a while as well 🤔  Sorry for the delay. You need to specify pagination in order for the API logic to do the more computationally expensive query to fetch nested contact groups.

```javascript
const where = undefined;
const order = undefined
const iDs = undefined
const page = 1
const ifModifiedSince: Date = new Date("2021-05-24T12:17:43.202-08:00");
const contactResponse = await xero.accountingApi.getContacts(tenantId, ifModifiedSince, where, order, iDs, page);
```
> https://developer.xero.com/documentation/api/contacts
![Screen Shot 2021-05-25 at 1 31 30 PM](https://user-images.githubusercontent.com/2935387/119557567-95eede80-bd5d-11eb-9ea6-5bc1180135c5.png)
