### ISSUE TITLE
TypeError: getCurves is not a function

### ISSUE THREAD

**Issue by vinay-iyengar** [XeroAPI/xero-node#525]
`import { XeroClient } from "xero-node";`
After Installed` xero-node` dependency of version 4.11.2, We are getting` getCurvess()` is not a function in reactjs

**Comment by RettBehrens** [comment]
Hey @vinay-iyengar Looks like [this](https://stackoverflow.com/questions/59871686/crypto-getcurves-is-undefined) is related.

Xero-Node is a backend library. Further, Xero API does not support CORS so if you're trying to make calls from a react app you'll need to do so via a server intermediary
