### ISSUE TITLE
new npm dependency issue - openid-client / jose / crypto

### ISSUE THREAD

**Issue by brucem1976** [XeroAPI/xero-node#526]
**SDK you're using (please complete the following information):**
 - Version 4.11.2

**Describe the bug**
Trying to do an npm run build on a package that requires xero-node now breaks with:

```
node_modules/jose/types/index.d.ts:4:10 - error TS2305: Module '"crypto"' has no exported member 'KeyObject'.

4 import { KeyObject, PrivateKeyInput, PublicKeyInput } from 'crypto';
           ~~~~~~~~~

node_modules/jose/types/index.d.ts:4:21 - error TS2305: Module '"crypto"' has no exported member 'PrivateKeyInput'.

4 import { KeyObject, PrivateKeyInput, PublicKeyInput } from 'crypto';
                      ~~~~~~~~~~~~~~~

node_modules/jose/types/index.d.ts:4:38 - error TS2305: Module '"crypto"' has no exported member 'PublicKeyInput'.

4 import { KeyObject, PrivateKeyInput, PublicKeyInput } from 'crypto';
```

xero-node is dependent on openid-client, which is dependent on jose, which reports this.

**To Reproduce**
nodejs 14.16.0
npm 6.14.12
tsc 4.2.4
include xero-node in dependencides in package.json

**Expected behavior**
```
node_modules/jose/types/index.d.ts:4:10 - error TS2305: Module '"crypto"' has no exported member 'KeyObject'.

4 import { KeyObject, PrivateKeyInput, PublicKeyInput } from 'crypto';
           ~~~~~~~~~

node_modules/jose/types/index.d.ts:4:21 - error TS2305: Module '"crypto"' has no exported member 'PrivateKeyInput'.

4 import { KeyObject, PrivateKeyInput, PublicKeyInput } from 'crypto';
                      ~~~~~~~~~~~~~~~

node_modules/jose/types/index.d.ts:4:38 - error TS2305: Module '"crypto"' has no exported member 'PublicKeyInput'.

4 import { KeyObject, PrivateKeyInput, PublicKeyInput } from 'crypto';
```

**Screenshots**

**Additional context**

**Comment by joemaidman** [comment]
@brucem1976 did you solve this? I am facing the same error

**Comment by brucem1976** [comment]
@joemaidman I don't think this was related to xero-node (not 100% sure though) - I fought with npm for ages - deleted node modules, deleted the npm cache, deleted package-lock.json, none of this helped. I ended up removing all my dependencies from package.json and re-adding them one by one, and somehow things started working again.

**Comment by jamesrusso** [comment]
Just throwing a comment on here, that upgrades @types/node to latest resolved this issue for me.
