### ISSUE TITLE
XeroClient#updateTenants throws an exception

### ISSUE THREAD

**Issue by Simon-Campbell** [XeroAPI/xero-node#529]
**SDK you're using (please complete the following information):**
 - Version 4.11.3

**Describe the bug**
The XeroClient#updateTenants function throws an exception with no useful information about how to fix it.

**To Reproduce**
```typescript
const httpConfigureTrigger: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> { 
    const xero = new XeroClient({
        clientId: "CLIENT_ID",
        clientSecret: "CLIENT_SECRET",
        redirectUris: ['CALLBACK_URL'],
        scopes: 'openid profile offline_access accounting.reports.read'.split(' '),
    });
    
    await xero.initialize();

    const tokenSet   = await xero.apiCallback(req.url);
    const tenants = await xero.updateTenants(); // crashes

    // ... snip
}
```

**Expected behavior**
For an exception not to be thrown, and if so, for the exception to be clear.

**Screenshots**
...

**Additional context**
Running in an Azure Type Script function locally --

  Azure Functions Core Tools
  Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
  Function Runtime Version: 3.0.15417.0

These are the logs when the above code sample fails --

```
[2021-05-12T02:12:36.054Z] Executing 'Functions.ConfigureXeroCallback' (Reason='This function was programmatically called via the host APIs.', Id=95afea71-4406-47a3-b173-be625e5a1378)
[2021-05-12T02:12:39.748Z] Executed 'Functions.ConfigureXeroCallback' (Failed, Id=95afea71-4406-47a3-b173-be625e5a1378, Duration=3693ms)
[2021-05-12T02:12:39.752Z] System.Private.CoreLib: Exception while executing function: Functions.ConfigureXeroCallback. System.Private.CoreLib: Result: Failure
Exception: [object Object]
Stack: .
```

These are my dependencies --

```json
{
  "name": "",
  "version": "",
  "scripts": {
    "build": "tsc",
    "build:production": "npm run prestart && npm prune --production",
    "watch": "tsc --w",
    "prestart": "npm run build && func extensions install",
    "start:host": "func start",
    "start": "npm-run-all --parallel start:host watch",
    "test": "echo \"No tests yet...\""
  },
  "description": "",
  "devDependencies": {
    "@azure/functions": "^1.2.3",
    "npm-run-all": "^4.1.5",
    "typescript": "^3.9.9"
  },
  "dependencies": {
    "@azure/identity": "^1.3.0",
    "@azure/keyvault-secrets": "^4.1.0",
    "@types/node": "^15.0.2",
    "xero-node": "^4.11.3"
  }
}
```

**Comment by Simon-Campbell** [comment]
After firing up the debuggering I can observe the following when catching the exception which may be of use --

```    
try {
    await xero.updateTenants();
} catch (e) {
    throw e; // debugger stops here
}
```

![image](https://user-images.githubusercontent.com/7017162/117909643-b7e46c00-b32e-11eb-95ad-e60871ed200a.png)

Digging deeper into `e.response`, I can see there has been a 401 response and these are the headers --

![image](https://user-images.githubusercontent.com/7017162/117909703-d8acc180-b32e-11eb-9dc5-90f49863def0.png)

This is the `body` --

![image](https://user-images.githubusercontent.com/7017162/117909758-f417cc80-b32e-11eb-820a-184af5bc80f4.png)

This is the request that was sent to Xero --

![image](https://user-images.githubusercontent.com/7017162/117909951-33deb400-b32f-11eb-8175-5cdeeee00504.png)

**Comment by Simon-Campbell** [comment]
I have since carried out a test using a sample app. It worked, so I changed the scopes to match in my application... that worked, so then I changed back: *it now works* (the issue has resolved itself)

I still consider the lack of exception information a bug, but the urgency to resolve is now lowered from my point of view and I should be able to continue development.

**Comment by SerKnight** [comment]
Hi @Simon-Campbell 

Thanks for submitting the issue - it looks like you got it sorted.

That helper function calls the organisation endpoint as it populates additional organisation data in relation to the tenant that was authorized. You can still use it without the `fullOrgDetails` option though to get the basics such as orgName, etc.. You just won't have access to the rest of the metadata like short code, or currency, without having that scope.

https://github.com/XeroAPI/Xero-node#step-3-convenience-step

```
Calling await xero.updateTenants() will query the /connections endpoint and store the resulting information on the client. It has an optional parameter named fullOrgDetails that defaults to true. If you do not pass false to this function you will need to have the accounting.settings scope on your token as the /organisation endpoint that is called, requires it.
```
