### ISSUE TITLE
README.md still refers to deprecated function in XeroClient: readIdTokenClaims()

### ISSUE THREAD

**Issue by deplorable** [XeroAPI/xero-node#533]
Just noticed this today after updating from xero-node 4.8.1 to 4.12.0.

In the README.md file, under [Other helper functions](https://github.com/XeroAPI/xero-node/blob/master/README.md#other-helper-functions) it references the deprecated function `readIdTokenClaims()`:

```
await xero.readIdTokenClaims()

await xero.readTokenSet()
```

Something like the following may be preferable:

```
(await xero.readTokenSet()).claims()

await xero.readTokenSet()
```

or 

```
let tokenSet = await xero.readTokenSet()

let idTokenClaims = tokenSet.claims()
```

Thanks!

**Comment by RettBehrens** [comment]
Closing this issue as the readme was reformatted and no longer includes a reference to the deprecated method
