### ISSUE TITLE
refreshToken function fails with error

### ISSUE THREAD

**Issue by malisetti** [XeroAPI/xero-node#534]
**SDK you're using (please complete the following information):**
 - Version 4.12.0

Additional Queries:
1. Why do we receive a new refresh token when the current refresh token is not expired with refreshWithRefreshToken ?
 
refreshToken function fails with below error

```
TypeError: Cannot read property 'refresh' of undefined
    at XeroClient.<anonymous> (/home/sesh/api/node_modules/xero-node/src/XeroClient.ts:147:55)
    at Generator.next (<anonymous>)
    at /home/sesh/api/node_modules/xero-node/dist/XeroClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sesh/api/node_modules/xero-node/dist/XeroClient.js:4:12)
    at XeroClient.refreshToken (/home/sesh/api/node_modules/xero-node/dist/XeroClient.js:107:16)
    at XeroController.<anonymous> (/home/sesh/api/server/api/controllers/xero/xero-controller.ts:213:45)
    at Generator.next (<anonymous>)
    at fulfilled (/home/sesh/api/server/api/controllers/xero/xero-controller.ts:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by SerKnight** [comment]
Hi @malisetti  - can you confirm what you are passing to that function? Looks like you are mixing up the two functions available to refresh a token.

1. `refreshToken()` // requires the XeroClient  to be `initialized()` prior to usage ^This is the function error you posted about
2. `refreshWithRefreshToken(clientId, clientSecret, refreshToken)` this is helpful once you have a stored `token_set` and does not require the `initialize()` func to be called and doesn't setup the `openidclient` dependency that is causing your error:
```
TypeError: Cannot read property 'refresh' of undefined
```

I am pretty sure you either need to `initialize()` the client prior to running `refreshToken()` or use the following function w/ correct parameters:
```javascript
refreshWithRefreshToken(clientId, clientSecret, refreshToken)
```

**Comment by aimensasi** [comment]
Hi, @SerKnight  I am seeing the same error. After the token expires I am not able to refresh the token.

my token set
```
access_token: ""
expires_at: ":
id_token: ""
refresh_token: ""
scope: "openid profile email accounting.transactions accounting.contacts offline_access"
session_state: ""
token_type: ""
```

The code 

```
xero.setTokenSet(credentials.data() as TokenSet);

const tokenSet = xero.readTokenSet();

if (!tokenSet || tokenSet.expired()) {
    const newTokenSet = await xero.refreshToken();
}
```
