### ISSUE TITLE
Add support for using Xero Custom Connections

### ISSUE THREAD

**Issue by anay-kava** [XeroAPI/xero-node#538]
**SDK you're using (please complete the following information):**
 - Version 4.12.0

**Is your feature request related to a problem? Please describe.**
Xero has released a new feature Custom Connections, which supports the 'client-credentials' flow of OAUTH. This is extremely useful for server-to-server apps and APIs.
Currently xero-node SDK does not have support to use the custom connections (like retrieving access-tokens using Custom Connections). Adding this support to xero-node SDK would make it extremely useful for organisations who purchase the Custom Connections support.

**Describe the solution you'd like**
Currently xero-node SDK does not have support to use the custom connections (like retrieving access-tokens using Custom Connections). Adding this support to xero-node SDK would make it extremely useful for organisations who purchase the Custom Connections support.

**Describe alternatives you've considered**
N/A

**Additional context**
Given that 'Custom Connections' is a paid feature, the customers would definitely expect the SDK support for it.

**Comment by SerKnight** [comment]
Hi @anay-kava - we are close to release of the new functionality supporting Custom Connections / `client_credentials` currently in code review and you can expect early next week to see the release at latest.

**Comment by RettBehrens** [comment]
Now supported with Xero-Node v4.13.0
