### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by philals** [XeroAPI/xero-node#54]
I think @dupski (Briggs) has been looking into a CI tool. 

@dupski or @jordanwalsh23  do you have any thoughts? 

Then we could have the tool run against each PR

**Comment by dupski** [comment]
I had a quick hunt round the other day. Two free, hosted options are CircleCI and TravisCI. Out of the two, TravisCI seems the more capable option, but I've not used either so can't really comment further :)

**Comment by jordanwalsh23** [comment]
I got travis CI working with a private app test process.

The only issue was that the attachment tests were failing due to a missing
file system dependency.

If we can figure out a way to kick the file system, then the Travis CI
builds worked a treat.

**Comment by philals** [comment]
Closing to reduce issue no.
