### ISSUE TITLE
tracking and url are not saved in invoice create

### ISSUE THREAD

**Issue by Mars-2030** [XeroAPI/xero-node#542]
Hi,

I am trying to insert the tracking categories and URL during creating an invoice it seems not matter I am doing it is not inserting the tracking or the URL
here is my son
`
{
   "invoices":[
      {
         "type":"ACCREC",
         "contact":{
            "contactID":"0a8bdf2e-c43f-4078-be0a-7f16e579f454"
         },
         "dueDate":"2021-08-01T11:42:34.000Z",
         "lineItems":[
            {
               "description":"product 1",
               "quantity":2,
               "unitAmount":34.5,
               "itemCode":"724323226481",
               "accountCode":200,
               "taxType":"TAX002",
               "taxAmount":9,
               "lineAmount":69,
               "tracking":[
                  {
                     "name":"Locations",
                     "option":"Sulay Warehouse"
                  }
               ]
            }
         ],
         "lineAmountTypes":"Inclusive",
         "invoiceNumber":150,
         "url":"https://xyzinvoice.com/invoices/74",
         "date":"2021-08-01T11:42:34.000Z",
         "reference":"74 ",
         "status":"AUTHORISED"
      }
   ]
}
`

I tried even using  trackingCategoryID and  trackingOptionID but not working
is there a specific configuration I need to do in Xero front end to activate the ability to insert tracking and URL for linking? or what I am doing wrong

Thanks

**Comment by RettBehrens** [comment]
Hi @Mars-2030 is the invoice being created in Xero but not including tracking and url or is the invoice not created at all? Are you receiving a 200 or 400 response code? Any validation error messages? Please provide as much detail as you can and I'll try to replicate. Thanks!

**Comment by RettBehrens** [comment]
Please also specify the SDK version you're using

**Comment by Mars-2030** [comment]
Hi,
No errors I am receiving, I tried to install the same JSON object using postman API, it is inserted successfully .
I am using this version  "xero-node": "^4.11.2"
node version v10.24.1
npm version 6.14.12

**Comment by RettBehrens** [comment]
Ran this code in my local testing app using 4.13.0 and it worked correctly.

```ts
const invoice: Invoice = { // Invoice Type
	type: Invoice.TypeEnum.ACCREC, // Invoice TypeEnum Enum
	contact: {
		contactID: "699f0091-b127-4796-9f15-41a2f42abeb2" // string
	},
	dueDate: "2021-08-15T11:42:34.000Z", // string
	lineItems: [
		{
			description: "description", // string
			quantity: 350, // number
			unitAmount: 10, // number
			accountCode: "200", // string
			taxType: "OUTPUT2", // string
			taxAmount: 9, // number
			lineAmount: 3500, // number
			tracking: [
				{
					name: "Locations", // has to exist in Xero org data first
					option: "Sulay Warehouse" // has to exist in Xero org data first
				}
			]
		}
	],
	lineAmountTypes: LineAmountTypes.Inclusive, // LineAmountTypes Enum
	invoiceNumber: "555", // string
	url: "https://xyzinvoice.com/invoices/74", // string
	date: "2021-08-05T11:42:34.000Z", // string
	reference: "74", // string
	status: Invoice.StatusEnum.AUTHORISED // Invoice StatusEnum Enum
};

const invoices: Invoices = {invoices: [invoice]}; // Invoices Type

const response = await xero.accountingApi.createInvoices(req.session.activeTenant.tenantId, invoices);
```

Received response code 200 and response body with tracking and url.

```json
"Invoices": [
    {
      "Type": "ACCREC",
      "InvoiceID": "eced7afe-83ba-4324-b60e-a3d75b0adbbd",
      "InvoiceNumber": "555",
      "Reference": "74",
      "Prepayments": [],
      "Overpayments": [],
      "AmountDue": 3500.00,
      "AmountPaid": 0.00,
      "Url": "https://xyzinvoice.com/invoices/74",
      "SentToContact": false,
      "CurrencyRate": 1.0000000000,
      "IsDiscounted": false,
      "HasErrors": false,
      "Contact": {
        "ContactID": "699f0091-b127-4796-9f15-41a2f42abeb2",
        "ContactStatus": "ACTIVE",
        "Name": "ABC Furniture",
        "FirstName": "Trish",
        "LastName": "Rawlings",
        "EmailAddress": "info@abfl.com",
        "BankAccountDetails": "",
        "Addresses": [
          {
            "AddressType": "POBOX",
            "City": "",
            "Region": "",
            "PostalCode": "",
            "Country": ""
          },
          {
            "AddressType": "STREET",
            "City": "",
            "Region": "",
            "PostalCode": "",
            "Country": ""
          }
        ],
        "Phones": [
          {
            "PhoneType": "MOBILE",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "DDI",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "FAX",
            "PhoneNumber": "",
            "PhoneAreaCode": "",
            "PhoneCountryCode": ""
          },
          {
            "PhoneType": "DEFAULT",
            "PhoneNumber": "124578",
            "PhoneAreaCode": "800",
            "PhoneCountryCode": ""
          }
        ],
        "UpdatedDateUTC": "\/Date(1627322622093+0000)\/",
        "ContactGroups": [],
        "IsSupplier": true,
        "IsCustomer": true,
        "DefaultCurrency": "GBP",
        "SalesTrackingCategories": [],
        "PurchasesTrackingCategories": [],
        "ContactPersons": [],
        "HasValidationErrors": false
      },
      "DateString": "2021-08-05T00:00:00",
      "Date": "\/Date(1628121600000+0000)\/",
      "DueDateString": "2021-08-15T00:00:00",
      "DueDate": "\/Date(1628985600000+0000)\/",
      "BrandingThemeID": "5d4dd402-c851-497e-aae1-9ff265c0d15a",
      "Status": "AUTHORISED",
      "LineAmountTypes": "Inclusive",
      "LineItems": [
        {
          "Description": "description",
          "UnitAmount": 10.00,
          "TaxType": "OUTPUT2",
          "TaxAmount": 9.00,
          "LineAmount": 3500.00,
          "AccountCode": "200",
          "Tracking": [
            {
              "Name": "Locations",
              "Option": "Sulay Warehouse",
              "TrackingCategoryID": "f217762b-ce28-46c8-9fd1-4dd86301fda1",
              "TrackingOptionID": "b9e423e2-9a23-4860-bf8a-2e0184cf30ef"
            }
          ],
          "Quantity": 350.0000,
          "LineItemID": "de5bd17e-261f-4608-b908-6fc7ef592ab3",
          "ValidationErrors": []
        }
      ],
      "SubTotal": 3491.00,
      "TotalTax": 9.00,
      "Total": 3500.00,
      "UpdatedDateUTC": "\/Date(1628181802003+0000)\/",
      "CurrencyCode": "GBP"
    }
  ]
```

Verified in Xero UI.
<img width="1216" alt="Screen Shot 2021-08-05 at 11 03 48 AM" src="https://user-images.githubusercontent.com/28675148/128391495-964ba9c1-365d-47f5-9b77-cb593c735772.png">

Please update xero-node to 4.13.0 and try again. Please reopen this issue if the problem persists.

**Comment by Mars-2030** [comment]
Hi,
Just to let you know and in case of anyone having this issue in the future .. the problem is related to node js caching, when I restarted the machine everything is working fine now
