### ISSUE TITLE
Question: Is setTokenSet async?

### ISSUE THREAD

**Issue by tyler1314371** [XeroAPI/xero-node#559]
Hi guys,

Looking from the ReadMe it seems like `setTokenSet` is async 
![image](https://user-images.githubusercontent.com/9467678/139092275-1edaee1c-80ba-4758-aa55-5bad07689eb4.png)

However, looking at the underlying code it seems like it doesn't need to be async
![image](https://user-images.githubusercontent.com/9467678/139092412-460d0316-cdb0-42cf-9ea8-bf07597576d1.png)

Do we know if that's the case? Or is there something I am missing here?

Cheers!

**Comment by Eteroa123** [comment]
Talofa @tyler1314371 ,

Thank you for sending through your question to us. I can see that the code that you copied from are from the read me but the in the actual code based in app.ts you will see that it is async. 

The readme  just shows an example of what to look at when you setTokenSet. The main point is that if you remove async the app will break as it is needed to set the session for the token.
