### ISSUE TITLE
Unable to empty the contactPersons array (additional contact persons) when using updateContact

### ISSUE THREAD

**Issue by craigvantonder** [XeroAPI/xero-node#560]
**SDK you're using (please complete the following information):**
 - Version 4.16.1

**Describe the bug**
You can create or update a contactPerson other than the Primary Person within a contact using the updateContact API method but there is no way to completely remove / empty the additional contactPersons that are defined.

**To Reproduce**

Create a contact with a primary person along with an additional contactPerson, you can do this using updateContact:

    const contactID = 'contactID value'
    const additionalContact = { firstName: 'pete', lastName: 'test', emailAddress: 'pete@test.com', includeInEmails: true }
    const contacts = { contacts: [{ contactID, firstName: 'bob', lastName: 'test', emailAddress: 'bob@test.com', contactPersons: [additionalContact] }] }
    await xero.accountingApi.updateContact(xeroTenantId, contactID, contacts)

Try to remove the additional contact person (pete test / pete@test.com):

    const contactID = 'contactID value'
    const contacts = { contacts: [{ contactID, contactPersons: [] }] }
    await xero.accountingApi.updateContact(xeroTenantId, contactID, contacts)

Check the contact in Xero.

**Expected behavior**

The additional contact, "pete test" is still there as the secondary contact witihin the contact in Xero. I would expect at this point that he would have been removed, with only "bob test" / the primary contact remaining.

**Screenshots**
Could provide if required but doesn't seem specific to this problem.

**Additional context**
Tried every which way come Sunday to remove the additional contactPerson using the API but it does not seem to be possible.

**Comment by Eteroa123** [comment]
Talofa @craigvantonder , 
Thank you for your issue and we apologies for the delay to get back to you in regards of your issue. After having a deeper look into the problem we can see that issue lies within the contacts API and we will bring this to the appropriate team.
