### ISSUE TITLE
`xero-node-sso-app` Example App does not contain subscription endpoint examples as described

### ISSUE THREAD

**Issue by daffron** [XeroAPI/xero-node#562]
I was hoping to find more information about when to include the extra scopes etc in this example app, as per its description. 

Currently cannot find anything like that within the app.

```
xero-node-sso-app | App showing Xero Single Sign On - as well as basic setup and usage of the Xero App Store appStoreApi.getSubscription endpoint
-- | --
```

Thanks!

**Comment by RettBehrens** [comment]
You're right... looks like the [PR](https://github.com/XeroAPI/xero-node-sso-app/pull/1) to add that functionality was never merged. I'll confirm it's working before merging - so some time next week assuming it's good to go

**Comment by RettBehrens** [comment]
Closing as this has been added to the xero-node-sso-app
