### ISSUE TITLE
Cannot use refresh token to get a tokenSet

### ISSUE THREAD

**Issue by shash7** [XeroAPI/xero-node#572]
**SDK you're using (please complete the following information):**
 - 4.18.0
Nodejs version:
- 14.17.3

**Describe the bug**
xero.refreshWithRefreshToken() throws a invalid_grant error instead of retrieving a tokenSet.

**To Reproduce**
Setup a app.js test file with nodejs
Install the sdk
Run the following(with a valid refresh token and a CLIENT_ID AND A CLIENT_SECRET)
```
const Xero = require('xero-node');
const XeroClient = Xero.XeroClient;

let CLIENT_ID = '';
let CLIENT_SECRET = '';
let REFRESH_TOKEN = '';

let PORT = '4000';

let scopeList = `openid profile email accounting.settings accounting.reports.read accounting.journals.read accounting.contacts accounting.attachments accounting.transactions offline_access`;

let scopes = scopeList.split(' ');

let xero = new XeroClient({
      clientId: config.xero.CLIENT_ID,
      clientSecret: config.xero.CLIENT_SECRET,
      redirectUris: [`http://localhost:${PORT}`],
      scopes: scopes,
    });


async refreshTheToken(refresh_token) {
    let tokenSet = null;
    try {
      tokenSet = await xero.refreshWithRefreshToken(
        CLIENT_ID,
        CLIENT_SECRET,
        refresh_token
      );
    } catch (err) {
console.log(err);
    }
}

refreshTheToken(REFRESH_TOKEN);
```

**Expected behavior**
This xero.refreshWithRefreshToken function would normally get me a tokenSet. However, since today I'm no longer getting the tokenSet. Instead, I get a 400 invalid_grant error.

**Additional context**
Problem could also exist at xero.apiCallback function but I doubt it.
Let me know if you want my refresh token. Docs say it should last for 60 days so it should work if you pass it in the example.

**Comment by shash7** [comment]
This is a proper working example.

```
const Xero = require('xero-node');
const XeroClient = Xero.XeroClient;

let CLIENT_ID = '37A364FC366C4ABC89B89E34BA3807D3';
let CLIENT_SECRET = 'HGAVy0eoFZOZdeTOiVo4zIDyb7omTFnZgXUH8Ft_UvejCvl9';
let REFRESH_TOKEN =
  'd1c6ba9e988a8c046a7a15b3f0cfc690d474b46921f24a74ad7f07b1d9e57f5b';

let PORT = '4000';

let scopeList = `openid profile email accounting.settings accounting.reports.read accounting.journals.read accounting.contacts accounting.attachments accounting.transactions offline_access`;

let scopes = scopeList.split(' ');

let xero = new XeroClient({
  clientId: CLIENT_ID,
  clientSecret: CLIENT_SECRET,
  redirectUris: [`http://localhost:${PORT}`],
  scopes: scopes,
});

async function refreshTheToken(refresh_token) {
  let tokenSet = null;
  try {
    tokenSet = await xero.refreshWithRefreshToken(
      CLIENT_ID,
      CLIENT_SECRET,
      refresh_token
    );
  } catch (err) {
    console.log(err);
  }
}

refreshTheToken(REFRESH_TOKEN);

```

**Comment by RettBehrens** [comment]
Hi @shash7 From your example above, are you requesting a different set of scopes than you requested on initial auth? It's possible the user disconnected via Xero's "connected apps" screen - can you confirm?

**Comment by shash7** [comment]
Nope, also I checked the dashboard and my app is connected.
<img width="1318" alt="Screen Shot 2022-03-01 at 9 25 04 am" src="https://user-images.githubusercontent.com/3054413/156068598-3611b92a-8b19-4b51-9754-bce0b9037b78.png">


This connection was working fine since Sunday last weekend.

**Comment by RettBehrens** [comment]
I can see in the logs for your app that a token refresh call failed because an invalid refresh token was provided. Can you try re-authenticating and let me know if the issue is resolved or persists. Thanks.

**Comment by shash7** [comment]
Getting a new refresh token worked. Just testing the integration right now.

**Comment by shash7** [comment]
Utterly fascinating. I store the tokenset from the new refresh token. A few minutes later I try to use the refresh token from the tokenset to get a new tokenset and it throws the same error again.

**Comment by RettBehrens** [comment]
Hmmm. We've seen issues in the past where the token was somehow modified in the process of storing it in the db. Are you able to test using [Postman](https://github.com/XeroAPI/xero-postman-oauth2) or [Insomnia](https://github.com/XeroAPI/Xero-Insomnia), using the refresh token before and after it's been stored in your db?

I've tested using the [sample app](https://github.com/XeroAPI/xero-node-oauth2-app) and not been able to replicate the issue.

**Comment by shash7** [comment]
I see. Will give it a try in a few hours.

**Comment by shash7** [comment]
So I did some more testing and I'm using filesystem to store token now on.
However, when I run the xero.updateTenants({fullOrgDetails:false}) that seems to halt the process. As in, if I use nodemon, it will keep restarting at that point and if I directly run my script, it will halt and won't do anything else.
Wrapping the function in a try catch doesn't accomplish anything.

This issue seems to be related:
https://community.xero.com/developer/discussion/127403806

I cannot do a full test until the updateTenants issue is fixed.

**Comment by shash7** [comment]
Update:
I am using the filesystem to save the token and it works. But after a few days when I run the server again, it gives me an invalid_grant error. Is this because I need to constantly reuse the token after a few hours?

**Comment by phil-warner** [comment]
@shash7 did you manage to fix this? The same thing happens for me with (essentially) and identical setup.

**Comment by shash7** [comment]
> @shash7 did you manage to fix this? The same thing happens for me with (essentially) and identical setup.

I started storing the tokenSet stuff inside a json file and I'll periodically update it when I would refresh the token. It did break every now but it works fine since the last few weeks. I reckon Xero fixed something on their end.
