### ISSUE TITLE
AU Payroll missing HasLoanOrStudentDebt in tax declaration

### ISSUE THREAD

**Issue by haydn** [XeroAPI/xero-node#575]
**SDK you're using**

 - Version 4.18.0

**Is your feature request related to a problem? Please describe.**

The `HasLoanOrStudentDebt` field is missing from the employee's `TaxDeclaration` object. The other fields provided (`HasHELPDebt`, `HasSFSSDebt`, `HasTradeSupportLoanDebt` and `HasStudentStartupLoan`) [have all been marked as deprecated in the API](https://developer.xero.com/documentation/api/payrollau/employees/#elements-for-taxdeclaration) in favour of the `HasLoanOrStudentDebt`.

There's also only a single option available to users in the Xero UI:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/27211/157155898-0d6dc8ca-4d22-408a-9d9a-4e428710d441.png">

**Describe the solution you'd like.**

The `HasLoanOrStudentDebt` field added to the `TaxDeclaration` object.

**Describe alternatives you've considered.**

I assume I'd need to bail on using the Node SDK altogether to work around this? Is there an easy way to make raw requests to the underlying API using the SDK? That could work, but it's a real pain.

**Additional context.**

N/A

**Comment by RettBehrens** [comment]
https://github.com/XeroAPI/xero-node/releases/tag/4.23.0
