### ISSUE TITLE
Enum Typed variables coming in as strings

### ISSUE THREAD

**Issue by awasser-omnispear** [XeroAPI/xero-node#581]
I am using TypeScript and the `accountingApi.getReportProfitAndLoss` endpoint.  The response from of this endpoint has some enum types. RowType being one of them, as seen below.
https://github.com/XeroAPI/xero-node/blob/bfcaf1c3426c3387b19b3eee959fd4af17b83d8d/src/gen/model/accounting/reportRow.ts#L5

However, the actual data coming down is not an Enum, it is actually a string.  This causes an error when comparing the value of the data to the enum.
I.E. `row.rowType == RowType.Header` will always be false. 
`row.rowType == 'Header'` will work, but TypeScript indicates this as an error.
I should note, that this only affects the TypeScript typing.  JavaScript works perfectly fine, since it does not enforce any types.

A workaround would be to use `row.rowType.toString() == 'Header'`.  Since rowType comes in as a string anyway, calling `toString()` effectively does nothing, except to satisfy TypeScript.

I would like to see the `row.rowType == RowType.Header` code fragment work correctly for TypeScript users.

**Comment by mbyrne00** [comment]
Hrmmm ... another typescript issue. Just heads up that the dates are also incorrectly typed, format incorrectly documented and plain wrong and the team have simply ignored this blatant bug since Feb 2021. https://github.com/XeroAPI/xero-node/issues/487#issuecomment-1016151415

**Comment by sangeet-joy-tw** [comment]
Hey @awasser-omnispear 

I have tried asserting rowType - `row.rowType == RowType.Header` for `accountingApi.getReportProfitAndLoss()` method in our xero-node sample app and it is working fine for me.

Xero-node version I am using is - **8.0.0**

Here is the sample code on my local - 

![image](https://github.com/XeroAPI/xero-node/assets/157606431/b9bc93c3-b023-4077-bed6-33bb79f790d7)

Could you please try with the latest xero-node version and let us know if you are still facing this issue ?

**Comment by awasser-omnispear** [comment]
Glad to see it working!  Due to technical reasons, we cannot upgrade Xero-node yet in our project, but we're working on it.  I won't be able to test in a reasonable amount of time.

I'm happy to close this issue with your example alone.  It's over 2 years old.
