### ISSUE TITLE
Projects createTask is not typed

### ISSUE THREAD

**Issue by adamburgess** [XeroAPI/xero-node#599]
**SDK you're using (please complete the following information):**
 - Version 4.27.0

**Describe the bug**
`projectApi.createTask`'s returned `body` is not typed.

**To Reproduce**
* Create a task with `projectApi.createTask`.
* A task is returned in the `body` field. It is typed as `any`.

**Expected behavior**
projectApi.createTask's returned `body` should be `Task`

**Comment by RettBehrens** [comment]
This is because the API does not return a Task when creating a Task, it only returns a 201. 

```
    post:
      security:
        - OAuth2: [projects]
      tags:
        - Project
      summary: Allows you to create a task
      operationId: createTask
      description: Allows you to create a specific task
      parameters:
        - name: projectId
          x-snake: project_id
          in: path
          required: true
          description: You can create a task on a specified projectId
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        description: The task object you are creating
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateOrUpdate'
            example:
              '{
                "status": "INPROGRESS"
                }'
      responses:
        '201':
          description: OK/Success - return response 201 no content
          x-isEmpty: true
        '400':
          $ref: '#/components/responses/400Error'
```

Looking at the [Projects API](https://github.com/XeroAPI/Xero-OpenAPI/blob/master/xero-projects.yaml), there are a number of endpoints that return only a status code.

**Comment by adamburgess** [comment]
You can verify it in the API explorer. It returns a 201 _and_ the entity.

I just tested it now...

```
        const response = await xero.projectApi.createTask(tenantId, projectId, {
            name: 'test2',
            chargeType: ChargeType.TIME,
            rate: { currency: CurrencyCode.AUD, value: 0 }
        });
        console.log(response.response.statusCode);
        console.log(response.body);
```
output:
```
201
{
  name: 'test2',
  rate: { currency: 'AUD', value: 0 },
  chargeType: 'TIME',
  status: 'ACTIVE',
  taskId: '[snip]',
  projectId: '[snip]',
  totalMinutes: 0,
  totalAmount: { currency: 'AUD', value: 0 },
  minutesToBeInvoiced: 0,
  minutesInvoiced: 0,
  nonChargeableMinutes: 0,
  fixedMinutes: 0,
  amountToBeInvoiced: { currency: 'AUD', value: 0 },
  amountInvoiced: { currency: 'AUD', value: 0 }
}
```

**Comment by RettBehrens** [comment]
Yeah, no, you're right. I just confirmed it with Insomnia. My apologies for the mix up. 

Looking at the [receipts](https://github.com/XeroAPI/Xero-OpenAPI/pull/493/files), this one is on me.

**Comment by RettBehrens** [comment]
I've reviewed the other methods and it looks like the rest are correct.

Per the [docs](https://developer.xero.com/documentation/api/projects/response-codes) it should be:

- `GET`: 200
- `POST`: 201
- `PUT`, `PATCH`, and `DELETE`: 204

**Comment by RettBehrens** [comment]
https://github.com/XeroAPI/Xero-OpenAPI/pull/513

**Comment by RettBehrens** [comment]
@tnzzz FYI

**Comment by RettBehrens** [comment]
Thanks @tnzzz 🥳
