### ISSUE TITLE
Codestyle PRs

### ISSUE THREAD

**Issue by tinovyatkin** [XeroAPI/xero-node#60]
I just took a look for the library source code and wondering why the code-style is so strange, mixed and outdated. Your `node` version requirement in `package.json` is current LTS (6.0) and that's great, but platform/language features usage seems to be targeting something like node 0.12.

 For example: https://github.com/XeroAPI/xero-node/blob/master/lib/application.js - you have `const` within function declarations, but missing `use strict` anywhere and top level variables declared as `var`.

Question is: will you accept refactoring pull requests? I'm particularly interesting in getting rid of `lodash` as it's huge stone age dependency...

**Comment by philals** [comment]
What about a road map on the README.md? Then contributors can pick up tasks.

Ideas to start with:

- [ ] Add ESLint rules
- [ ] ESLint rule complaint
- [ ] Remove log4js
- [ ] Throw exceptions with messages
- [ ] Remove lodash

I can open a PR with these changes we think it's a good idea.

**Comment by jordanwalsh23** [comment]
Yes.. totally supportive of a roadmap like this.

The code was merged and updated from a project about 3 years ago, so still
lots of cleanup to do.

Also, I'm not a node native. So ES2016/ES2017 vs old JS are still new to
me.

Very keen to learn from the community on what the appropriate standards are
today, so yes totally if you see something you'd like to fix up, submit a
PR and we'll get it merged.

**Comment by philals** [comment]
Here we go @jordanwalsh23  and @tinovyatkin 

https://github.com/XeroAPI/xero-node/pull/61 Adds a quick road map, which hopefully will encourage the community to PR on the old code.

**Comment by tinovyatkin** [comment]
Great! I think ESLint is essential for productive collaboration, so, will start with that small PR.

**Comment by philals** [comment]
Nice @tinovyatkin. I think ESLint will give the greatest benefit.

Thanks.

I guess you get to choose the style to go with.

**Comment by tinovyatkin** [comment]
Well, I have a great experience with `airbnb` rules set + `eslint-prettier`, but whatever you prefer it's more important for me to have it automatically enforced in the project via tooling.

**Comment by philals** [comment]
I agree with you. Does not matter what it is, as long as it's there and automated.

airbnb and eslint-prettier will be great.

**Comment by tinovyatkin** [comment]
Submitted #63

**Comment by jordanwalsh23** [comment]
This has been merged.  Closing the issue.
