### ISSUE TITLE
Issue with API & your support form not working

### ISSUE THREAD

**Issue by tablufc88** [XeroAPI/xero-node#623]
Apologies in advance for spamming here, but your support form is not working (https://developer.xero.com/contact-xero-developer-platform-support)

We use the Xero accounting api to create new notion pages for our renewals. I'm migrating our services & can't get past the first step which is build the consent url when requesting any kind of accounting scopes. There are a few console errors on the white screen I get. 

When I remove the accounting scopes, the auth page loads ok but still with various errors in the console including CSP script-src & I need to be able to connect a tenant.

To check that I'm doing the consent url correctly, I've manually created the consent url & also tried with this SDK... I think this might be an error your end as it was working this way last time I checked a few months ago? Could you point me in the right direction please?

Thanks

**Comment by RettBehrens** [comment]
@tablufc88 I'm unable to replicate using sample app and SDK. I get the expected consent/auth page (not blank). Based on it happening when building the consentUrl manually I've labeled this API not SDK. 

Are using ngrok for development?

Are you requesting any restricted scopes that require approval / activation from Xero prior to use?

If this remains an issue please contact api@xero.com

**Comment by tablufc88** [comment]
It's working now with the same configuration with ngrok. I was also getting the issue when deploying to Vercel so I don't think it was an ngrok thing. Anyway it seems resolved now. Thanks
