### ISSUE TITLE
Authorize url remains blank

### ISSUE THREAD

**Issue by jasperkennis** [XeroAPI/xero-node#624]
**SDK you're using (please complete the following information):**
 - Version 3.32.0

**Describe the bug**
I'm not entirely sure if this is an SDK issue, but here goes. After calling my authorization endpoint created like so (router is an instance of express.Router):

```ts
  router.get('/setup-url', async (
    req: express.Request,
    res: express.Response,
  ) => {
    const consentUrl = await getXeroClient().buildConsentUrl()

    getLogger().debug(consentUrl)

    res.redirect(consentUrl)
  })
  ```
  
my browser happily goes to to that page (at `https://authorize.xero.com/?consentId=a-guid-here&returnUrl=https%3A%2F%2Flogin.xero.com%2Fidentity%2Fidentity%2Fconnect%2Fauthorize%3Fclient_id%3DEFFD5B893D5A4705BF4D9BB603FCE51E%26scope%3Daccounting.attachments.read%2520accounting.attachments%2520accounting.budgets.read%2520accounting.contacts.read%2520accounting.contacts%2520accounting.journals.read%2520accounting.reports.read%2520accounting.reports.tenninetynine.read%2520accounting.settings.read%2520accounting.settings%2520accounting.transactions.read%2520accounting.transactions%2520assets.read%2520assets%2520files.read%2520files%2520offline_access%2520openid%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fmyurl.eu.ngrok.io%252Finternal%252Fxero%252Fcallback`). However, this page is entirely blank, and nothing else happens. No redirect to the callback url is made.

The page remains blank, but a bunch of 403's are being thrown if I check the network tab in the dev tools of Chrome (see screenshot)

![Screenshot 2023-01-05 at 14 55 09](https://user-images.githubusercontent.com/247177/210796531-ee448d10-d15a-46c2-aba3-c70a21497282.png)

It seems as if it is loading some content that I have no access to, but I am logged in to the Xero dashboard, so I wouldn't see why this happens.

**To Reproduce**
Not sure how to instruct for this one...

**Expected behavior**
A redirect to the callback url should happen

**Additional context**
Using Chrome `108.0.5359.124 (Official Build) (arm64)` on OSX 13.0.

**Comment by Sallyhornet** [comment]
As a troubleshooting step, do you get the same issue if you use an alternative to ngrok for the redirect location eg LocalTunnel? (please remember to update the redirect uri in developer.xero.com).

**Comment by tablufc88** [comment]
Similar issue with buildConsentUrl reported a few days ago. Still not had a response https://github.com/XeroAPI/xero-node/issues/623#issue-1515889502

I don't think it's an SDK issue though, you can manually build the consent URL as per their docs & still get this issue

**Comment by RettBehrens** [comment]
@jasperkennis I'm unable to replicate using sample app and SDK. I get the expected consent/auth page (not blank). Based on it happening when building the consentUrl manually per @tablufc88  I've labeled this API not SDK. 

Even using the provided url, I still land on the Xero auth/consent screen. It errors out given `consentId=a-guid-here`

`https://authorize.xero.com/?consentId=a-guid-here&returnUrl=https%3A%2F%2Flogin.xero.com%2Fidentity%2Fidentity%2Fconnect%2Fauthorize%3Fclient_id%3DEFFD5B893D5A4705BF4D9BB603FCE51E%26scope%3Daccounting.attachments.read%2520accounting.attachments%2520accounting.budgets.read%2520accounting.contacts.read%2520accounting.contacts%2520accounting.journals.read%2520accounting.reports.read%2520accounting.reports.tenninetynine.read%2520accounting.settings.read%2520accounting.settings%2520accounting.transactions.read%2520accounting.transactions%2520assets.read%2520assets%2520files.read%2520files%2520offline_access%2520openid%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fmyurl.eu.ngrok.io%252Finternal%252Fxero%252Fcallback`

As @Sallyhornet suggests, please try using ngrok alternative such as LocalTunnel to rule out that as the source of the issue.

If this remains an issue please contact api@xero.com

**Comment by jasperkennis** [comment]
Thanks for having a look at this everyone, sorry for not providing the requested input faster, got distracted. It's working now after I rebased on my dev branch which had some updated packages in it. Can't tell if that was what made it not work or if there was something on the login page not functioning, but at any rate seems like there is no issue now.
