### ISSUE TITLE
Xero CloudQuery Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [XeroAPI/xero-node#626]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Xero plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Xero data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by RettBehrens** [comment]
Hi @yevgenypats thank you for your interest in building a Xero integration. We’d be happy to work with you to become a Xero app partner, however, the integration would have to be fully owned and maintained by CloudQuery not Xero. If you're still interested please check out our [getting started guide](https://developer.xero.com/documentation/getting-started-guide/) and our [steps to becoming an app partner](https://developer.xero.com/documentation/xero-app-store/app-partner-guides/app-partner-steps/)
