### ISSUE TITLE
x-rate-limit-problem: values

### ISSUE THREAD

**Issue by simonhffx** [XeroAPI/xero-node#634]
I'd like to know what the values for `x-rate-limit-problem` are?

I know this is the wrong place to ask, but I was redirected here by the suggestions on https://developer.xero.com/support

I have tried looking on standard sites, but can't find a list of the actual values this header can have. 

I can see one for myself, 'minute' but don't know what the others will be.

Specifically:

'X-MinLimit-Remaining' => 'minute'
'X-AppMinLimit-Remaining' => ?
'X-DayLimit-Remaining' => 'day'?

**Comment by RettBehrens** [comment]
Hi @simonhffx 

There are limits to the number of API calls that your application can make against a particular [tenant](https://developer.xero.com/documentation/guides/oauth2/auth-flow#xero-tenants) (organisation, account or practice):

Concurrent Limit: 5 calls in progress at one time
Minute Limit: 60 calls per minute
Daily Limit: 5000 calls per day

There is also a limit to the number of API calls your app can make per minute across all tenants:

App Minute Limit: 10,000 calls per minute

Each API response you receive will include the X-DayLimit-Remaining, X-MinLimit-Remaining and X-AppMinLimit-Remaining headers telling you the number of remaining against each limit.

Exceeding a rate limit will result in an HTTP 429 (too many requests) response. It will include an X-Rate-Limit-Problem header telling you which limit you have reached.

If you have exceed the minute or daily limit you will also receive a Retry-After http header that tells you how many seconds to wait before making another request. Requests are counted against a fixed window which will reset at different times for each tenant. It is important to use the Retry-After header to know when you can start making calls again.
