### ISSUE TITLE
Hanging when calling initialize

### ISSUE THREAD

**Issue by JakeCoxon** [XeroAPI/xero-node#636]
**SDK you're using (please complete the following information):**
 - Version 4.32.0

**Describe the bug**
`await xero.initialize()` hangs and never recovers. I tracked it down to the call to `got` inside openid-client. I can verify this by manually calling the following code using the same version `openid-client@4.9.1` that xero-node uses
```ts
const openId = await got({
  method: 'GET',
  responseType: 'json',
  url: 'https://identity.xero.com/.well-known/openid-configuration',
});
```
I can see that the request returns status 200 but reading the response from the stream hangs. Fetching the URL using node-fetch returns the expected response.

[got](https://github.com/sindresorhus/got/issues?q=hang) seems to have problems when reading from cache. Presumably this is in combination with something on my machine since I assume many people would be reporting this bug otherwise.

Anyway `openid-client@5.4.0` doesn't use `got` and I can verify that that works fine for me
```ts
await Issuer.discover('https://identity.xero.com');
```

So upgrading to `openid-client@5.4.0` should solve this issue

**Comment by sangeet-joy-tw** [comment]
Hey @JakeCoxon i have tried calling **await xero.initialize()** and it is printing the response and not hanging on my end.

i have on the latest version of xero node @5.0.1.

could you please be on the latest xero-node version and let us know if the xero.initialize() call is still failing?

**Comment by STEVEOO6** [comment]
I have the same hanging issue, but am attempting to run via bun.

It looks like there's an issue with the version of openid-client being used in xero-node.

Are there any plans on the roadmap to upgrade openid-client in xero-node to the latest (currently 5.6.5)?

**Comment by sangeet-joy-tw** [comment]
Hey @STEVEOO6 @JakeCoxon 

We have upgraded the openid-client to its latest version in our new xero-node v7.0.0.

Could you please be on the latest xero-node version and let us know incase of any issues?
