### ISSUE TITLE
The LeaveApplicationV2 endpoint doesn't include LeaveTypeID

### ISSUE THREAD

**Issue by haydn** [XeroAPI/xero-node#645]
**SDK:**

- Version 4.35.0

**Describe the bug**

Using the new `/payroll.xro/1.0/LeaveApplications/v2` endpoint for AU Payroll doesn't include `LeaveTypeID` properties for leave applications that have `REQUESTED` or `REJECTED` statuses.

**To Reproduce**

1. Connect [the Xero API Explorer](https://api-explorer.xero.com/payrollau/leaveapplications/getleaveapplicationsv2) to an organisation that includes requested and/or rejected leave applications.
2. Get all the leave applications using [the v2 endpoint](https://api-explorer.xero.com/payrollau/leaveapplications/getleaveapplicationsv2).

**Expected behavior**

All leave applications returned should include a `LeaveTypeID` property.

Note: Loading any of the leave applications that are missing the `LeaveTypeID` individually with the `/payroll.xro/1.0/LeaveApplications/{LeaveApplicationID}` endpoint correctly includes in the `LeaveTypeID`.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by rdemarco-xero** [comment]
Fixed with a recent release to the API
