### ISSUE TITLE
The request package used by Node 4.3.0 is depreciated 

### ISSUE THREAD

**Issue by aakashbhatiaaccenture** [XeroAPI/xero-node#659]
**SDK you're using (please complete the following information):**
 - Version [e.g. 4.37.0]

**Describe the bug**
xero-node  >=4.0.0-alpha.1 depends on vulnerable versions of request. The request package itself is depreciated.

**To Reproduce**
1. Install xero-node >= 4.0.0 using npm
2. Run 'npm audit'
3. See the vulnerability listed

**Expected behavior**
It should not make use of the depreciated package. Instead it could one the following listed packages: https://github.com/request/request/issues/3143

**Comment by AndrewLugg** [comment]
They have known about this for over a year, and not seeming to care. I feel this package is unmaintained. They are updating the xero api endpoints, but not maintaining any security updates.

**Comment by manishT72** [comment]
Apologies for the delay. We have removed direct dependencies on request module in version 5.0.0. We will soon remove it from other nested package dependencies.

**Comment by aakashbhatiaaccenture** [comment]
> Apologies for the delay. We have removed direct dependencies on request module in version 5.0.0. We will soon remove it from other nested package dependencies.

Thanks very much, really appreciate it

**Comment by sangeet-joy-tw** [comment]
this issue is fixed in latest version of xero-node.
