### ISSUE TITLE
CORS ERROR

### ISSUE THREAD

**Issue by utkarsh3020** [XeroAPI/xero-node#681]
Hi,
I am getting cors error while hitting the API's from the frontend react app, while its working fine when hits on backend live sever port.

**Comment by utkarsh3020** [comment]
Hi, is there anybody who can help me regarding this issue?

**Comment by RettBehrens** [comment]
Hi @utkarsh3020 Xero-Node is a backend library. Further, Xero API does not support CORS so if you're trying to make calls from a react app you'll need to do so via a server intermediary

**Comment by sangeet-joy-tw** [comment]
Hey @utkarsh3020 ,

It seems like this issue is not with SDK and it is more on the API side.

I kindly request you to raise the concern in [Xero developer support forum](https://developer.xero.com/support) if your issue is not yet resolved.
