### ISSUE TITLE
Can you please upgrade openid-client to the latest (currently 5.6.5)

### ISSUE THREAD

**Issue by STEVEOO6** [XeroAPI/xero-node#684]
**Is your feature request related to a problem? Please describe.**
Hangs on initialize invocation (see https://github.com/XeroAPI/xero-node/issues/636)

**Comment by sangeet-joy-tw** [comment]
Hey @STEVEOO6 

Openid-client has been upgraded to 5.6.5 in latest xero-node v7.0.0. 

Closing this issue while #636 is kept open for tracking.
