### ISSUE TITLE
Attempt to parse object as JSON results in "JSON parse body failed" written to console

### ISSUE THREAD

**Issue by drew-r** [XeroAPI/xero-node#686]
**SDK you're using (please complete the following information):**
Version 5.1.0 but looks present in 6.0.0

**Describe the bug**
There is an attempt to parse what is already an object as JSON, which throws an error causing 'JSON parse body failed' to be written to the console.

**To Reproduce**
Call `getBankTransactionAttachments` etc.

**Expected behavior**
There is no attempt to JSON.parse & nothing is written to the console

It's not ideal for libraries to be writing to the console at all unless some verbosity/tracing is explicitly requested for example through a DEBUG env var

**Comment by sangeet-joy-tw** [comment]
Hey @drew-r

We have removed the unnecessary json parsing code in our latest xero-node v9.0.0.

Please try our new version and let us know with any further issues.
