### ISSUE TITLE
Unable to upload documents from Readable stream

### ISSUE THREAD

**Issue by csharpsi** [XeroAPI/xero-node#690]
When I perform an export, the file is not attached to the invoice. I have a unit test that proves that the document stream passed into the `updateInvoiceAttachmentByFileName` function matches the byte array of the test file and that is passing, so I am confident that the issue is with the SDK.  

Example effected invoices:
* `22e3d6d4-3442-444b-b109-fa359bcacef6`
* `3c425103-1d67-4189-9b1f-3ef1baf286e1`

The below examples were imported into Xero, the first using the latest version of the xero-node SDK and the second using version 4.17.0 

![Latest Version](https://github.com/XeroAPI/xero-node/assets/1210114/73863216-ae87-4685-a232-7ef4fb27e249)

![Version 4.17.0](https://github.com/XeroAPI/xero-node/assets/1210114/64c1af5a-4bf4-47ac-8f78-83bfb2e6c08c)

Additionally, I am seeing a console.log message `JSON parse body failed` which looks to be coming from the SDK [here](https://github.com/XeroAPI/xero-node/blob/master/src/gen/api/accountingApi.ts#L17719)

![image](https://github.com/XeroAPI/xero-node/assets/1210114/cd4f924c-fc53-4c94-bd96-1f8c0f64c3bb)

If I can help any further please let me know

_Originally posted by @csharpsi in https://github.com/XeroAPI/xero-node/issues/631#issuecomment-2163016589_

**Comment by elena-dev-thought** [comment]
we experince the same issue, when do you estimate to fix the issue?

**Comment by MiscellaneousStuff** [comment]
Same here

**Comment by sangeet-joy-tw** [comment]
Hey @csharpsi @elena-dev-thought @MiscellaneousStuff 

The issue has been addressed in our latest xero-node **v9.0.0**.

Please try using the latest version and let us know if the issue still persists.

**Comment by csharpsi** [comment]
Hi @sangeet-joy-tw 
Thanks for the update. Looks like it's working nicely with v9
