### ISSUE TITLE
TaxNumberType field missing in response for Contacts

### ISSUE THREAD

**Issue by xenvish** [XeroAPI/xero-node#698]
**SDK you're using (please complete the following information):**
 - Version [e.g. 9.0.0]

**Describe the bug**
When we call getContacts, it does not return "TaxNumberType" field in response but when checked in the API Explorer it does return the field in response. "TaxNumberType"

**Expected behavior**
The getContacts function should return the field "TaxNumberType" as well.

**Comment by sangeet-joy-tw** [comment]
Hey @xenvish,

I have checked the [API Explorer](https://api-explorer.xero.com/accounting/contacts/getcontacts) for `getContacts` however I do not see the `TaxNumberType` field in the response.

I have also called `getContacts` using our Node SDK latest version but I do not see `TaxNumberType ` field in the response.

There is also no field present called `TaxNumberType` in open API [accounting schema](https://github.com/XeroAPI/Xero-OpenAPI/blob/27dcb2ee7df83b0b8877d40eec3f980d86f73279/xero_accounting.yaml#L3755)

Could you please share some more details on how did you see `TaxNumberType` in API explorer ? Please share the explorer link or screenshots ?

![image](https://github.com/user-attachments/assets/08fd0226-acc6-4ed2-887c-fa14b752b4e1)

<img width="1728" alt="Pasted Graphic 11" src="https://github.com/user-attachments/assets/704edad8-d6c3-4f73-aebf-5025cb5e831e">
