### ISSUE TITLE
Custom Connections premium link only works if already on premium 

### ISSUE THREAD

**Issue by seanwarmanshine** [XeroAPI/xero-node#727]
**SDK you're using (please complete the following information):**
 - Version 9.3.0

**Is your feature request related to a problem? Please describe.**
Xero are introducing new subscription levels ("Ignite", "Grow", "Comprehensive" etc). I'm having trouble finding anywhere that tells me which of these levels allows the API to use OAuth.2.0's client_credentials for custom connections. Currently the docs just says "premium" accounts can use custom connections (which links to a page you can only see if you already have a premium account).

**Describe the solution you'd like**
I like to see some detail on which subscriptions allow for custom connections in the [Custom Connections](https://github.com/XeroAPI/xero-node?tab=readme-ov-file#custom-connections) section of the README. Could be a link that goes to a relevant page in Xero's API docs, [this one](https://developer.xero.com/documentation/guides/oauth2/custom-connections/) for example.

**Comment by Sallyhornet** [comment]
This is not SDK-related.

Custom connections are available for all plans in the UK, AU and NZ but you need to take out a custom connection subscription in addition to your Xero plan subscription.

https://central.xero.com/s/article/Create-custom-integrations-and-apps-with-Xero

**Comment by seanwarmanshine** [comment]
It's related to the SDK's documentation. Let me better explain the issue:

If you visit [this link](https://developer.xero.com/documentation/oauth2/custom-connections) (which is the one in the README) it responds with "Not Authorized" unless you already have a custom connection subscription.

![image](https://github.com/user-attachments/assets/45e04640-2d39-46cf-b030-33068b41a3ce)

It's not very likely you'd click that link if you already had a custom connection subscription.

My suggestion is to replace the link with one to [Xero's custom connections documentation](https://developer.xero.com/documentation/guides/oauth2/custom-connections/).
