### ISSUE TITLE
AddressSchema / AddressDetailsSchema issue

### ISSUE THREAD

**Issue by bcsan** [XeroAPI/xero-node#77]
on xero-node/lib/entities/shared.js you have:

`module.exports.AddressSchema = Entity.SchemaObject({
    Address: { type: AddressDetailsSchema, toObject: 'always' }
});`

However this additional object "Address" breaks the GET/POST with Xero. To get it to work I did:

`module.exports.AddressSchema = AddressDetailsSchema;`

Bypassing this extra Address object. I didn't sent a PR as I don't know if this breaks other components such as "employees" in the payroll. But definitely to create/update/retrieve Contacts, this was the way to make it work. Hope this helps.

**Comment by philals** [comment]
Hi @bcsan .

I did some tests and your right. I have fixed this in the mentioned pr.

I'll push to npm tomorrow and close issue.

Thanks for your time.

**Comment by jordanwalsh23** [comment]
Hi @bcsan, this has been resolved in xero-node@2.6.0. 

Please retest and comment if it's not working for you.
