### ISSUE TITLE
Tracking on LineItems not working

### ISSUE THREAD

**Issue by Scoutski** [XeroAPI/xero-node#86]
Have been trying to structure the JSON correctly to submit a TrackingCategory option on a LineItem as part of a `.newInvoice()` call, but can not seem to make anything work. Adhering to the Schemas makes it look like it expects a format like:

```
{
     ...
     LineItems: [{
        ...
        Tracking: [{
              TrackingCategory: {
                   Name: 'Region',
                   Option: 'Eastside',
                   TrackingCategoryID: (UUID),
              }
         }]
     }]
}
```

The request is being accepted and the invoice appears in Xero, but the Tracking information is missing, there are no errors or status messages being returned.

Not sure if the issue is just on my end with this problem, but I'd be happy to submit a PR adding to the documentation if I could get some help on this one.

I'm wondering if this is possibly linked to https://github.com/XeroAPI/xero-node/issues/22 ? Is it a limitation to be able to send Tracking?

**Comment by jordanwalsh23** [comment]
I've just pushed PR #89 for review.  Once @philals has some time to review we'll get this merged which should resolve your issue.

**Comment by warp** [comment]
I would also appreciate getting this merged as we rely on Tracking Categories for our integration. Our testing confirms the fix in #89

**Comment by Scoutski** [comment]
Just wanted to confirm that I've forked and tested your changes successfully for Tracking Categories :+1: Appreciate the help @jordanwalsh23

**Comment by jordanwalsh23** [comment]
Change has been merged.  Awaiting the next release to NPM prior to closing.

**Comment by philals** [comment]
Hi @Scoutski and @warp. Thanks for the original issue. I have merged the changes and they it is deployed as 2.7.0.

Please let us know if you have any problems.

Thanks

**Comment by warp** [comment]
@philals Somehow the release published to npm as version 2.7.0 does not appear to contain the latest changes is it possible there was a mistake with the release? The release tag in github and associated archive appears to be correct.

**Comment by philals** [comment]
Hi @warp Sorry about this. I'll fix it up once at my computer.

**Comment by philals** [comment]
@warp Thanks for picking that up. I have pushed 2.8.0. This should have them. Cheers
