### ISSUE TITLE
add contact api

### ISSUE THREAD

**Issue by monukanyal** [XeroAPI/xero-node#95]
Hello,
Please help , how to add address in xero add contact api.

**Comment by monukanyal** [comment]
"Addresses": {
				"Address": {
					"AddressType": "POBOX",
					"AttentionTo": "Simon G.",
					"AddressLine1": "PO Box 10112",
					"AddressLine2": "",
					"AddressLine3": "",
					"AddressLine4": "",
					"City": "New York",
					"Region": "New York State",
					"PostalCode": "10112",
					"Country": "USA"
				}
			},

it is giving error like 'error:TypeError: Converting circular structure to JSON'

**Comment by jordanwalsh23** [comment]
Check out the examples here and you should be able to figure it out: 

https://github.com/XeroAPI/xero-node/blob/master/test/core/contacts_tests.js

Cheers

**Comment by monukanyal** [comment]
Thankyou @jordanwalsh23  :)

**Comment by monukanyal** [comment]
Hello, 
I wrote addresses according to the document you provided me. but I am getting error like 'error:TypeError: Converting circular structure to JSON'. please provide me the solution.
