### ISSUE TITLE
add contact api response

### ISSUE THREAD

**Issue by monukanyal** [XeroAPI/xero-node#97]
Hello,

I wrote addresses according to the url you provided me. 
https://github.com/XeroAPI/xero-node/blob/master/test/core/contacts_tests.js
but I am getting error like 'error:TypeError: Converting circular structure to JSON'. please provide me the solution.

**Comment by jordanwalsh23** [comment]
I've just copied the code from the sample I gave you and ran it.  This is using the latest version of xero-node (2.7.0)

**createContact.js**
```
'use strict';

const xero = require('xero-node');
const fs = require('fs');

const config = JSON.parse(fs.readFileSync('/Users/jordan.walsh/.xero/private_app_config.json'));

if (!config.privateKey && config.privateKeyPath) {
  config.privateKey = fs.readFileSync(config.privateKeyPath);
}

const currentApp = new xero.PrivateApplication(config);

let sampleContact = {
  Name: `Johnnies Coffee ${Math.random()}`,
  FirstName: 'John',
  LastName: 'Smith',
  Addresses: [
    {
      AddressType: 'POBOX',
      AddressLine1: 'P O Box 123',
      City: 'Wellington',
      PostalCode: '6011',
      AttentionTo: 'Andrea',
    },
  ],
  SalesTrackingCategories: [
    {
      TrackingCategoryName: 'Region',
      TrackingOptionName: 'South',
    },
  ],
  PurchasesTrackingCategories: [
    {
      TrackingCategoryName: 'Region',
      TrackingOptionName: 'North',
    },
  ],
};

const contactObj = currentApp.core.contacts.newContact(sampleContact);

contactObj.save()
    .then(function(contacts) {
        //Contact has been created 
        const addresses = contacts.entities[0].Addresses;
        console.log(addresses[1].toJSON());
    })
    .catch(function(err) {
        //Some error occurred
    });
```

Just ran that code and got this output:

```
> node createContact.js
{ AddressLine1: 'P O Box 123',
  City: 'Wellington',
  Region: '',
  PostalCode: '6011',
  Country: '',
  AttentionTo: 'Andrea',
  AddressType: 'POBOX' }
>
```

This is working as expected.

**Comment by monukanyal** [comment]
Hello,

can you please check my code from your end.
  var sampleContact = {
                         
                          Name:'pradhe'+Math.random(),
                          FirstName:'pradhe',
                          LastName:'singh',
                          ContactNumber:'87676747575',
                          ContactStatus: 'ACTIVE',
                          EmailAddress:'pradhe@gmail.com',
                          TaxNumber:'',
                          Addresses: [
                                {
                                        AddressType:'POBOX',
                                        AddressLine1:'pradhe road',
                                        AddressLine2:'wing 1',
                                        City:'ddn',
                                        Region:'uttarakhand',
                                        PostalCode:'223344',
                                        Country:'india',
                                    }
                                ],
                            DefaultCurrency:'AUD'
                          };

                        console.log(sampleContact);
                var contactObj = xeroClient.core.contacts.newContact(sampleContact);

                contactObj.save()
                .then(function(contacts) {
                    //Contact has been created 
                    var contacts=JSON.stringify(contacts);
                    var myContact = contacts.entities[0];
                    console.log('added contact to xero:'+myContact);
                })
                .catch(function(err) {
                    //Some error occurred
                     console.log('addcontact error:'+err);
                });

**Comment by jordanwalsh23** [comment]
What edition/Region of Xero are you using? Also, which version of Node.js/NPM & xero-node?

**Comment by monukanyal** [comment]
I am using  node v6.10.2, xero-node@2.7.0 and npm 3.10.10

**Comment by monukanyal** [comment]
I think i got solution.the problem was inside this:
contactObj.save()
            .then(function(contacts) {
                //Contact has been created 
         var contacts=JSON.stringify(contacts);  //<----circulating error was coming because of this
                var myContact = contacts.entities[0];
                console.log('added contact to xero:'+myContact);
            })
  but please let me know how can i get contactid in response.

**Comment by monukanyal** [comment]
ok got it after some research var myContact = contacts.entities[0].ContactID;
thankyou

**Comment by jordanwalsh23** [comment]
Glad to hear it. Closing the issue. Thanks.
